### ISSUE TITLE
Recommendations for CSV editing tools

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1014]
In the past we've discussed alternatives to the Prose.io CSV editing functionality (since Prose.io has a few quirks that can prevent it from being used in some cases). Some countries may be using Excel to edit CSV files, or automatically generating CSV files from some other maintenance tool.

I'm interested in hearing any recommendations for approaches to CSV file edits. Is anyone using anything else? Does anyone know of any web-service and/or open-source library for CSV file editing?

One feature I'm particularly interested in is integration with some sort of data schema (like an SDMX DSD for example) which could convert cells into dropdowns, to require particular values. For example, instead of a free-form cell, a dropdown with "Rural" and "Urban" as the only options.

**Comment by brockfanning** [comment]
@jwestw Just wondering if you know of any popular CSV editors in the CSV-W world, which might allow for cells to become dropdowns as described above.

**Comment by brockfanning** [comment]
Since Excel is universally available, maybe it would be a good choice? The one problem with Excel files is that they will not display differences in Github (it will just say "binary file changed" or similar). I suppose one way around this problem would be for the country to export to CSV before uploading, and for sdg-build to automatically generate Excel files per indicator (with the appropriate cells converted into dropdowns). So, from the platform's perspective nothing would change - it would still be CSV files. But the data manager would have the option of maintaining the data with .XLSX files with dropdowns.

**Comment by LucyGwilliamAdmin** [comment]
I think Excel could work. However re. it being universally available, is there a web-based version that could be used? Otherwise another issue I see is that a Microsoft license would be required

**Comment by brockfanning** [comment]
I was thinking that sdg-build could automatically produce the .xlsx files. Any countries that prefer not to use Excel could then upload them to Google Docs as an alternative.

But that is a bit of manual work, and it would still be nice to know of any Prose-like services out there, which might support dropdowns for cells.

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin I might be misinterpretating this, but we would also need to check around what formats are acceptable. For example I think our government promotes the use of Open Document Formats (ODF), therefore tieing into .xls may not be acceptable in regards to assessment etc.

**Comment by jwestw** [comment]
RE: the above conversation I think ODF is the way to go as it's non-proprietary. 

These are not recommendations but I looked around on Github and saw a number of CSV editors that (I think) can be used online:

- https://github.com/LemonUnit/csv-editor-online  - this repo is archived now, but it was under development less than a year ago. 
- https://github.com/itsalb3rt/cloudcsv - looks like it might be overkill, but I wonder if a scaled down version might be possible. 
- https://github.com/frictionlessdata/delimiter - last developed 2 years ago. Possibly part of the Frictionless Data tools. Unfortunately I can't see their webpage [delimiter.netlify.com](delimiter.netlify.com) on an ONS machine

**Comment by phillipgardiner** [comment]
Its an old blog but.....https://technology.blog.gov.uk/2018/04/27/open-document-format-in-government-an-update/

**Comment by jwestw** [comment]
After looking up the [UK Gov guidance on ODF](https://www.gov.uk/guidance/using-open-document-formats-odf-in-your-organisation), I found [Collabora Office Online](https://www.collaboraoffice.com/). 

Collabora is based on Libre Office, so can certainly handle CSV editing. 

On their FAQ they state:
 "Collabora Online is a software component which can be integrated into your web application"

I am not sure what that integration would look like. 

Again, this might be overkill, but if not too hard to implement  it is a well developed option. 

Also note that [Collabora handles file conversion](https://www.collaboraoffice.com/document-conversion/) via an API so it could do XLS to ODF conversion for example.

**Comment by brockfanning** [comment]
An update here - during recent Open SDG trainings we have been trying out the use of the indicator/site/metadata config forms, and from what I've seen the reactions have been positive. That makes me lean more towards implementing this in-browser, rather than the Excel-based approach that I was suggesting above. An after a bit of investigation I've found a couple of open-source libraries that look pretty good: [Handsontable](https://handsontable.com/) and [Jspreadsheet](https://bossanova.uk/jspreadsheet/v4/).

In fact it looks like it will be relatively trivial to have an "Edit data" page for each indicator, with a spreadsheet-like interface. I think the main challenge will be accessibility, as neither of those libraries seem to have devoted much effort towards making them accessible. There are workarounds available (such as in [this issue about keyboard accessibility](https://github.com/handsontable/handsontable/issues/2519).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning anything additional to do here are ready to close?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'll go ahead and close, since we merged in the data form. We may need a future ticket about accessibility on the data forms, but I don't think we need to continue looking for other approaches necessarily, so I'm closing this now.
