### ISSUE TITLE
Show target without indicators

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1018]
Since the 2020 revision of the SDG indicators there is no Indicator 11.c.1 anymore. Anyway the target 11.c is still part of the indicator framework since it is searched for a suitable replacement of 11.c.1. 

Right now 11.c is not shown on the target page. Is it possible to show the target even if there is no indicator?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse looking at Germany platform, it looks like you achieved this?

Could you outline the process you carried out for this please?

**Comment by MoBosse** [comment]
@LucyGwilliamAdmin I have integrated [this part](https://github.com/G205SDGs/sdg-indicators/commit/0699ae20bae99a398fd22c67525766fd90d803f3) into the Goal-by -target layout as a temporary solution for Goal 11.
I don't think this is a general solution, but since the problem only occurs at this point, it's good enough for me for now.

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse we are considering putting something for this into next release (see #1275).

We are looking to get some thoughts on a related question - should the placeholder indicator(s) affect the reporting status total counts or not?

**Comment by MoBosse** [comment]
Hi @LucyGwilliamAdmin. A good question. 
Since the placeholder indicator can not be "completed" or anything else I would say it should not effect the reporting status.

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse thanks for feeding back

**Comment by MoBosse** [comment]
Sorry, @LucyGwilliamAdmin , I closed this one too early. I just realized that the placeholder Indicator 11.c.1 is not ignored in the calculation of the reporting status as it should be (as I understand it).
See Target page with 12 indicators "reported" plus one placeholder [here](https://sdgtestenvironment.github.io/sdg-indicators/en/11/)
and the reporting status with 13 indicators [here](https://sdgtestenvironment.github.io/sdg-indicators/reporting-status/)

[data repo](https://github.com/SdgTestEnvironment/sdg-data/blob/develop/meta/en/11-c-1.md)

**Comment by LucyGwilliamAdmin** [comment]
Hi @MoBosse I think you need to upgrade to 1.5.0 as it was part of that release

**Comment by MoBosse** [comment]
On the site where I tested this I actually use [1.5.2](https://github.com/SdgTestEnvironment/sdg-indicators/blob/develop/_config.yml#L178)

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse there are also changes needed from sdg-build and jekyll-open-sdg-plugins 1.5.0 versions

**Comment by MoBosse** [comment]
Ah sorry, I missed that. Now it works as expected. Thanks!
