### ISSUE TITLE
Remove disaggregation percentage bars from filters

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1050]
Within usability testing conducted October 2020, no participants naturally noticed the disaggregation percentage bars displayed in the filters. When shown their function none said it was of any use to them.

Recommendation: Remove the disaggregation percentage bars from the filter options.

![Screenshot (96)_LI](https://user-images.githubusercontent.com/60919820/104299104-b3ad5c80-54bc-11eb-861c-4fa4acbc314e.jpg)

**Comment by brockfanning** [comment]
Review after looking at disaggregation controls user research.
