### ISSUE TITLE
Convert enable high contrast 'A' to a single toggle icon

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1059]
On desktop we currently have two 'A' icons. One to 'Enable high contrast' and one to 'Disable high contrast'. We do not require a  'disable high contrast' option on desktop view when you are not on the high contrast version (and visa versa).

Recommendation is to only have a single 'A' icon that works like a toggle between the two states, working the same way as when in mobile view (and copying the visual style too).

Additionally I have also noticed that when viewed on desktop the 'A' on the icons is perfectly centred in the circle. However when viewed on mobile the 'A' seems to increase in size and therefore no longer sits in the centre - could this be looked at please.

We have put the above to DAC who had the following feedback which I believe we will have addressed with this implementation.

Here’s DAC’s response:

_I understand what you are saying about the buttons where there are only two different style sheets. From an accessibility POV I don’t see there being any problems with only having the button available which switches to the state that is not already selected. However, it would very much depend on the implementation and there are a few accessibility points to consider – for example, if you are going to switch buttons as soon as a button is activated, will this be a different button? If so, where will focus go? If it is the same button but with a different purpose, how will it be labelled? Also, what would you do if you wanted to add additional style sheets to the page? 

The best option would be to have a toggle button, but toggles are not enormously different to what you already have really. I would say that a toggle implementation may be clearer for users reliant on audio feedback where the options are mutually exclusive, but that the current implementation works ok too._

**Comment by brockfanning** [comment]
Let's fix https://github.com/open-sdg/open-sdg/issues/755 at the same time as this.
