### ISSUE TITLE
Intro for tutorials

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1062]
We need a intro which we'll use for all our tutorials - let's discuss this here...

## Video
I've quickly put something together using an out-of-the-box template but with SDG colours - though it would be good to have somewhere to start from.

First colour: goal 10 (`#DD1357`)
Second colour: goal 9 (`#FD6925`)
Third colour: goal 5 (`#FF3A21`)

https://user-images.githubusercontent.com/43404358/104916536-1f466c80-598a-11eb-86c9-df38b096df2c.mp4

## Audio
There are audios on Camtasia but they're slightly more tricky and need to find out if ok to use (imagine they are, otherwise probs wouldn't be on there

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning @jwestw @phillipgardiner 

I've put the above together - what are your thoughts/suggestions? want to change completely? want to change colours? or anything else?

**Comment by brockfanning** [comment]
Cool! Great idea. I'm interested to hear others' thoughts, but here are my 2 cents:
1. I liked the logo-pop-up animation.
2. I might like to see a version without the logo-collapse animation. Maybe just the quick fade at the end?
3. I thought the intro colors were cool but I'm wondering if we might want the whole thing to be quicker. Like just the logo-pop-up, and then quick-fade, or something like that. If it's quick enough it might not need any audio either - just a simple sound.

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Nice work. I love the idea of having something consistent at the start of each video to let users know they all relate to the SGD's. I would probably agree with brocks comments above in that I'm not sure all the colour intros are necessary (or maybe we only need one or something?). Other than that I think its looking good.

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning @phillipgardiner @jwestw 

Have made some changes following feedback so far (thanks!):
Without any colours at all:
https://user-images.githubusercontent.com/43404358/105043010-dd3a2b00-5a5c-11eb-9d66-44fbaff52c43.mp4

With one colour:
https://user-images.githubusercontent.com/43404358/105042952-cb588800-5a5c-11eb-9740-c751b79b305c.mp4

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Look great Lucy. To be honest they both work for me. Can you select the colour to use? Just wondering if there is a more generic SDG colour that could be used (for example the aqua blue from the SDG logo? But I'd vote for either of these :)

**Comment by LucyGwilliamAdmin** [comment]
Yeah, colour is very easy to change so happy for any suggestions re. sdg colours.. What are others thoughts on 1 vs the others? or any other opinions?

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin really great idea to have common intro. 
I think my vote goes for the no colours but having the Open SDG bit there for longer - 3 secs seems too quick. so maybe another second or two before fades out?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp slightly longer version:
https://user-images.githubusercontent.com/43404358/105483009-1bc02780-5ca1-11eb-9b52-ceff34228507.mp4

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin looks good to me!
