### ISSUE TITLE
Transparent chart tooltip background

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1063]
Adjust the transparency of the tool tip to enable easier viewing of the graph underneath (particularly important when long unit names and dissagregation names are present. 

The background color is currently set at 0.8 opacity. 

@brockfanning and @phillipgardiner to 'turn the dials' to decide on optimum opacity.  

Suggest 0.6 opacity as a starting point.

**Comment by brockfanning** [comment]
@phillipgardiner Does anything else need to be done here?

**Comment by phillipgardiner** [comment]
@brockfanning Yes. I don't think this has been done. We split it out as a separate ticket and said we would turn the dials and assess using screen shots. I guess would be good to still see what it looks like at 0.6 opacity.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning this is what it looks like at 0.6: 
![image](https://user-images.githubusercontent.com/43404358/126181636-7186e5bf-46a4-40e7-a21e-a298933eb3aa.png)

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin That looks good to me. Do you know what the grey colour is as a hex. Want to check that the contrasts still pass accessibility etc.

**Comment by LucyGwilliamAdmin** [comment]
So the colour is just rgb(0, 0, 0) with 60% opacity, so think hex is either #000000 with 60% opacity or #99000000 (according to this: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4)

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Um, I can't figure this out. When entering a hex value only six numbers are allowed? I think we need to figure this out as I have a sneaky feeling it may fail contrast ratios.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner do you mean the white against the grey?

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner So I've just used the colour picker on powerpoint to get the colour of the tooltip and it came out with `#737373`
