### ISSUE TITLE
Change 'Units type' to 'Unit of measurement'

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1064]
Usability testing showed that there was some misinterpretation of the term 'Units type'. 

In order to help address this and create consistency with the terms used in the graph footnote, The term 'Units type' used in the graph filtering is to be changed to 'Unit of measurement'. 

'Unit of measurement' is to be the default for OpenSDG

![Screenshot (106)_LI](https://user-images.githubusercontent.com/60919820/105186662-da593c00-5b29-11eb-8186-ced2588025b9.jpg)

**Comment by brockfanning** [comment]
Related to #1038
