### ISSUE TITLE
Move position of graph download buttons

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1066]
Several rounds of usability testing have now shown that the placement of the graph download buttons could be optimised for users. By placing the buttons above the graph their visibility is increased when first landing on the indicator page, and those users who are only interested in the data are able to quickly and efficiently complete their download task.  

All graph download buttons are to be placed above the graph as shown in the attached mock-up: [Download_button_position.pdf](https://github.com/open-sdg/open-sdg/files/5843217/Download_button_position.pdf)

As of 20/01/2021 a decision is yet to be taken if this new button position should be the default for all of OpenSDG or not. A piece of development work is required in order to identify how easy it would be for countries to change the positions should they so desire.

**Comment by phillipgardiner** [comment]
Out of interest is there likely to be new download buttons required in the future (e.g. SDMX)?

**Comment by LucyGwilliamAdmin** [comment]
Something that is already in place is the option to add additional download buttons e.g. a country could have a folder which contains any type of file they wish to make available for downloads.

Kyrgyzstan already do this with their SDMX files:
https://sustainabledevelopment-kyrgyzstan.github.io/en/1-1-1/
and they're planning on doing same with Excel files.

I'm not too sure what the long-term plan is? @brockfanning

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin That's interesting, good to know. I think myself and @AnnCorp were hoping this would be a simple change. If additional buttons are going to be added this is still fine but might mean this is a little bit more effort. For example in an ideal world we would probably move the word 'download' from the buttons and put it as a fieldset (is that the right word) outside the buttons (see example: [Download_Buttons_2.pdf](https://github.com/open-sdg/open-sdg/files/5866926/Download_Buttons_2.pdf)
Would need checking from accessibility perspective though and id imagone would def mean some translation work too. Just putting all this down a reminder when picking up the card.

**Comment by brockfanning** [comment]
Yes I think there is the definite possibility of additional buttons. For example I assume the plan is for the UK to eventually have both CSVW and SDMX downloads. But these are **not** required by Open SDG - they're optional features.

Side note: SDMX and CSVW are both interesting because they kind of involve 2 files each. CSVW involves a CSV file plus a JSON file. And SDMX involves the SDMX file plus the DSD file. It kind of seems like they would need to be drop-downs maybe? Or maybe something else better.

**Comment by AnnCorp** [comment]
@brockfanning @LucyGwilliamAdmin @phillipgardiner think would be good to talk through this one at Tech call 27 Jan.

**Comment by phillipgardiner** [comment]
It was decided at the tech call 27/01/21 to look at this again at a later date. There are a couple of new requirements to include both a SDMX and a CSVW download buttons into any design. This also raised a point in that these new buttons have a different remit so potentially would be alternatively placed e.g. Source, SDMX and CSVW = Download everything, Chart, image, download what you have selected.

**Comment by phillipgardiner** [comment]
Research undertaken recently highlighted that users expected download buttons to sit inside or outside the chart area depending on their purpose.

**Comment by phillipgardiner** [comment]
Might also need to look at adding file type and file size information alongside these?

**Comment by brockfanning** [comment]
@phillipgardiner To discuss more.

**Comment by phillipgardiner** [comment]
Additional research has been undertaken since this ticket was originally created. New needs in regard to additional download buttons (e.g. CSVW) and their placement have arisen. The original design proposal is therefore no longer applicable. This ticket will have to be moved back into the SDG team sprints so that a new design proposal taking into account the changes can be created.

**Comment by phillipgardiner** [comment]
Additional research has been undertaken since this ticket was originally created. New needs in regard to additional download buttons (e.g. CSVW) and their placement have arisen. The original design proposal is therefore no longer applicable. This ticket has been moved back into the SDG team sprints so that a new design proposal taking into account the changes can be created.
