### ISSUE TITLE
Mapping: Non-standard/mixed year types

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/open-sdg#108]
The map currently recognises when the year is in the format '2014'. However, for mixed years ('2014-15' or '2014/15') it becomes confused. Is there a way to have these mixed-year formats display on the site?

https://sustainabledevelopment-rwanda.github.io/1-2-1/

**Comment by brockfanning** [comment]
This one may be tricky, since the [Leaflet TimeDimension plugin](https://github.com/socib/Leaflet.TimeDimension) seems like it's a pretty dependent on actual times. But maybe there is a way to do time ranges in some way to allow for this.

**Comment by brockfanning** [comment]
Closing this because this is fixed by #993 and will be in release 1.3.0.
