### ISSUE TITLE
Mapping: Ignore 'Units' and disaggregation columns

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/open-sdg#109]
Having a 'Units' column in the CSV prevents the map from displaying data. Can we hide the 'Units' column from the mapping script as a short-term solution, and display the first Units option by default?

Alternatively, we could include a 'Units' option in the map, but this implies to users that the disaggregations are available to be used on the map, which they aren't (yet).

**Note**: This issue is a problem with disaggregation in general, as the presence of Geographical data overlapping with another category in the CSV prevents data from displaying on the map. We would like to have disaggregations working on the map in future, but this is likely to be complex.

**Comment by brockfanning** [comment]
I'm updating the title here for the first task, which is to make sure that the map doesn't look at 'Units' or other disaggregation columns. Later, when we figure out how to incorporate the disaggregation in the map, then we can revisit.

A temporary fix for countries having trouble here might be to remove the GeoCode values from any rows with disaggregation. As for 'Units', I think they'll need to pick one unit for map display, and remove the GeoCodes from all rows with any other units.

**Comment by Norric1Admin** [comment]
Thanks - I tried this on the Rwanda site but it didn't work unfortunately; https://sustainabledevelopment-rwanda.github.io/sdg-indicators/1-2-1/

**Comment by Norric1Admin** [comment]
@SavvasStephanides is working on a related issue, to remove categories from view in 'Map' or 'Embed' tab: https://github.com/ONSdigital/sdg-indicators/issues/2985.
