### ISSUE TITLE
Template for case studies in documentation

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#110]
We discussed adding case studies to the documentation, and deciding on a common template to use. Let's brainstorm that template.

**Comment by brockfanning** [comment]
Here is a draft for discussion (thanks @calebdow!)

## Key information

1. Link to platform
1. Why was Open SDG chosen as an approach to SDG reporting?
1. Which organisation (e.g. government ministry, office) was responsible for implementing the Open SDG platform?
1. What process did the organisation follow to fork the platform?
1. What kinds of technical and other capacities were most helpful for your organisation?
1. How is the platform hosted? (GitHub, local server, other platform)
1. How are support and maintenance managed for the platform?

## Platform content and features

1. What languages is your platform available in?
1. What customisations were added to the Open SDG platform to align with your specific context and needs?
1. What additional information has been included on the platform, in addition to statistics and metadata (e.g. guidance, policy materials, and publications)?

## Platform data

1. What is the process for managing and uploading data to the Open SDGs platform?
1. Does your platform expose data in formats that enable the automation of data exchanges? (API, SDMX, etc.)?
1. Are global, national, and/or domestic indicators included on your platform? (include how identified)
1. Are national proxies of global indicators used? (Include how identified)  
1. Are non-NSO or non-official data included? (include how identified)
1. Are non-statistical indicators reported on? (include how identified)

## Open SDG collaboration

1. What are important considerations and lessons learned from the process of setting up the platform?
1. How does your country plan to contribute or collaborate on the Open SDG code base?
1. What, if any, additions you would you like to make to the platform in the future?

**Comment by brockfanning** [comment]
@AnnCorp @philipashlock Calling your attention to this draft for review.

**Comment by AnnCorp** [comment]
Huge thanks for starting this off @brockfanning and @calebdow. 
I think we try and keep as plain English as possible and trim some of the content so overall the text is shorter and all directly relevant to countries also considering Open SDG. In Key info, I'd make some stuff simpler language and add something re how long it took to set up platform, In Platform data quite a bit of this flows from the UNECE template but less relevant in our context so I'd drop at least (4) to (6).  In the last section I'd definitely keep point 1 but would prune out the other points (they are relevant to us so but less so other countries).
I suggest best way to test it would be for Brock to complete a version for Armenia and us to do a version for Rwanda and see what kind of info we include and what would need to add questions for and then compare our content and refine/prune further from there? I think its really important to get this up and running so Chris and I could start to look at this early next week if not today.

**Comment by AnnCorp** [comment]
My suggestion for shortened/simplifield version below (haven't put any sub-headings yet). Wonder if there's also some kind of question around resources used by a country to set things up - implied in other questions though.
1.	Link to platform
2.	Why was Open SDG chosen?
3.	Which organisation was responsible for choosing and implementing the platform?
4.	How did you set up your country platform based on Open SDG?
5.	How long did it take to set up the platform?
6.	How do you upload data and metadata into the platform?
7.	How is the platform hosted? (GitHub, local server, other platform)
8.	How are support and maintenance managed for the platform?
9.	What languages is your platform available in?
10.	What customisations were added to the Open SDG platform?
11.	What advice and lessons learned could you give to other countries considering using Open SDG?

**Comment by calebdow** [comment]
Thanks for the edits and feedback @AnnCorp! 

I've discussed the edits with @brockfanning and Katarina and we've agreed that the new draft is much simpler and easier to fill out. I also don't think there is a need for a question on resources. 

Here is a link to the [new template](https://docs.google.com/document/d/1HolhYxND74H8KQQTH9T3c-1qJcxOvhBcP4j9vTgq7cI/edit?usp=sharing) for you and Chris to fill out.

**Comment by brockfanning** [comment]
Closing this now that there is a case study up.
