### ISSUE TITLE
Change colour of download buttons in high contrast mode

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1114]
Currently the download buttons within the high contrast mode are white: #FFFFFF.

In order to align these with the rest of the page, could these buttons please be changed to: #EEEEEE in normal state. Then when a mouse hovers over it: #DBDAD9.

**Comment by brockfanning** [comment]
As part of this ticket let's also make other buttons more consistent. Another example if the magnifying glass button for the search box.
