### ISSUE TITLE
Search button not correct colour in high contrast

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1123]
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-dev:

![image](https://user-images.githubusercontent.com/43404358/109189527-0486c500-778c-11eb-82d7-8531d4f9afc5.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It looks like that grey was introduced in #1002 but I don't see it being specifically requested. So it may have just been a developer-added kind of thing. Should we have it stick with the normal green color? Posting a PR now.

**Comment by jwestw** [comment]
This looks like it's fixed.

How it looks on the [feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/high-contrast-search-button/). 

![image](https://user-images.githubusercontent.com/67740306/109520663-63a64b80-7aa4-11eb-989c-81dee2bb625f.png)

How it looks on the UK site currently 

![image](https://user-images.githubusercontent.com/67740306/109520884-96e8da80-7aa4-11eb-904a-497971175a72.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @jwestw I think this can be closed right? since PR has been merged

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I actually closed the PR without merging. We have #1114 which is about making high-contrast buttons more consistent, so thought we'd do the search button there too. If you agree I think we could close this one, right?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ah right - yeah, that makes sense to me
