### ISSUE TITLE
Footer text is not white in high contrast

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1124]
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/1.3.0-dev/1-2-1/

![image](https://user-images.githubusercontent.com/43404358/109189797-50d20500-778c-11eb-8fb1-24bb53efb966.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'm not able to recreate this - is this happening in a particular browser?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just checked in Chrome and Edge and it happens in both
