### ISSUE TITLE
Data gaps not shown in chart and table

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1154]
**Please complete the following information** 
Site repository URL: https://github.com/SdgTestEnvironment
Open SDG version: 1.3.0

**Describe the bug**
Gaps in time series are not shown (neither in the chart nor in the table), although there is a row with empty value column for these years in the csv file.

**To Reproduce**
1. Go to [https://sdgtestenvironment.github.io/sdg-indicators/3-d-1/](https://sdgtestenvironment.github.io/sdg-indicators/3-d-1/)
2. See missing years 2013, 2015 & 2016

**Expected behavior**
I would expect the chart and table to show all years listed in the csv file (including years with no values before the first or after the last value in the series - we are thinking of having all charts start at 2010, whether there are values or not).

Appearence of No-Value-Years:
For a line chart I would expect to show no Marker but a line spaned from previous to next value.
For a bar chart I would expect to show a gap in between the other bars
For the table I would expect to show a "-"

**Screenshots**

![grafik](https://user-images.githubusercontent.com/50657629/111428877-6b96fa00-86f8-11eb-8932-570f0206127f.png)

**Additional context**
After pointing to 1.3.0 it took me some time to notice this. I hope it is not caused by any overwrite I did untill then.

**Comment by brockfanning** [comment]
Good catch @MoBosse I'm working on a fix now for this regression bug.

**Comment by brockfanning** [comment]
This is fixed in 1.3.1.
