### ISSUE TITLE
Tooltips show year instead of label

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1155]
**Please complete the following information** 
Site repository URL: https://github.com/SdgTestEnvironment/sdg-indicators
Open SDG version: 1.3.0

**Describe the bug**
Not sure if this is intended to be like that but it seems like a bug to me: The chart tooltips show the years instead of the labels. Only the year is allready shown at the top of the tooltip...

**To Reproduce**
1. Go to any indicator at [https://sdgdata.gov.uk/](https://sdgdata.gov.uk/)
2. See the chart and hover over it

**Expected behavior**
Instead of displaying the (same) year for each selected time series the labels should be displayed (as in th legend).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50657629/111438688-d5b59c00-8704-11eb-8865-866e508208e3.png)

**Additional context**
Not sure but I think it has something to do with these lines: [https://github.com/open-sdg/open-sdg/blob/1.3.0/_includes/assets/js/indicatorView.js#L480-L482](https://github.com/open-sdg/open-sdg/blob/1.3.0/_includes/assets/js/indicatorView.js#L480-L482)

**Comment by brockfanning** [comment]
@MoBosse You're right, we broke this in the latest release. I've got a PR up to fix this (#1156) and if it works we'll try to get it into a 1.3.1 hotfix release.

**Comment by jwestw** [comment]
@MoBosse Thanks. I also spotted this. We are testing a fix now.

**Comment by brockfanning** [comment]
This is fixed in 1.3.1.
