### ISSUE TITLE
Inconsistent sorting of legend entries

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1158]
**Please complete the following information** 
Site repository URL: https://github.com/SdgTestEnvironment/sdg-indicators
Open SDG version: 1.3.0

**Describe the bug**
The` .sort()` here [https://github.com/open-sdg/open-sdg/blob/1.4.0-dev/_includes/assets/js/model/chartHelpers.js#L315](https://github.com/open-sdg/open-sdg/blob/1.4.0-dev/_includes/assets/js/model/chartHelpers.js#L315) makes the structure of the lengend entries inconsistent as somtimes it is "parent","child" and sometimes "child","parent" depending on the alphabetic order of the keys.

**To Reproduce**
1. Go to https://sdgtestenvironment.github.io/sdg-indicators/
2. Click on indicator 4.6.1 (here it ist "parent","child")
3. Click on indicator 6.3.1 (here it ist "child","parent")

**Expected behavior**
I would expect the legend entries to allways be of the structure "parent","child"

**Screenshots**
4.6.1 ("parent","child"):

![Correct_Sorting](https://user-images.githubusercontent.com/50657629/111609761-e9cbcd00-87da-11eb-9da8-351402543f18.PNG)

6.3.1 ("child","parent")
![Wrong_Sorting](https://user-images.githubusercontent.com/50657629/111609775-ed5f5400-87da-11eb-81f2-5607247c1866.PNG)

**Additional context**
Deleting the `.sort()` in chartHelpers.js seems to fix this but I don`t know if this is needed for anything else.

**Comment by MoBosse** [comment]
Here is an even better example on the [UK site for 3.2.2](https://sdgdata.gov.uk/3-2-2/):

 ![grafik](https://user-images.githubusercontent.com/50657629/111610851-13d1bf00-87dc-11eb-8715-1ffe2c6669ae.png)

Here it is "country, region" for "England, East of England" but "age, country" for "19 and under, England and Wales"

**Comment by brockfanning** [comment]
@MoBosse I might be missing something but I'm not aware of any other purpose for the `sort` there. It sounds promising if just removing that helps. My suspicion would have been that without the sort it would be random, but from your experience it sounds like there is some sorting happening before that point which keeps the parent/child order.

**Comment by MoBosse** [comment]
@brockfanning  a closer look showed that your suspicions were correct. Deleting the `sort` fixes it for a simple parent child relationship as in indicator 6.3.1 shown above but messes things up when there are multiple childs:

![grafik](https://user-images.githubusercontent.com/50657629/112010720-d9dc2200-8b27-11eb-93cb-f202546acfef.png)

**Comment by MoBosse** [comment]
@brockfanning Could you please take a look at [this approach](https://github.com/SdgTestEnvironment/sdg-indicators/blob/develop/_includes/assets/js/model/fieldHelpers.js#L260-L279)? At first glance it seems to solve the problem.

![grafik](https://user-images.githubusercontent.com/50657629/112790613-0cbe7280-9060-11eb-85b7-04aaeee772ed.png)

**Comment by brockfanning** [comment]
@MoBosse Sorry for the delay. I am working related functionality and will see if there will be any overlap. More soon.

**Comment by brockfanning** [comment]
@MoBosse Actually I don't think my other work overlaps with this. Your approach seems great to me. I admit that the code is a bit of a mind-bender, but I believe I roughly understand what is going on. Do you mind submitting a PR? I'd just ask that you tweak a few things, like capitalize the "f" in "unsortedfieldValuePairCombinations", and maybe rename "combinationArray", since it is not actually an array. Thank you!

**Comment by MoBosse** [comment]
@brockfanning Tanks for taking a look at it. Where do adress the PR to? Master or 1.4.0-dev?

**Comment by brockfanning** [comment]
Thanks @MoBosse , 1.4.0-dev please.

**Comment by brockfanning** [comment]
@MoBosse We've noticed a pretty major bug that happens when there are multiple multi-level disaggregations, and I have a potential fix ready for testing. I am hoping that it might also resolve this issue. Is there any chance you could try it out? The PR is #1205. FYI, it is basically a refactor of that getCombinationData function, so if it is easier you could grab the new code and replace it in your override. In that PR I also used your approach of removing that sort() in getCombinationDescription.

**Comment by MoBosse** [comment]
@brockfanning Sorry for the late reply. PR [#1205](https://github.com/open-sdg/open-sdg/pull/1205) works perfectly for this issue. I tested on [this](https://mobosse.github.io/testSite/1-3-1/) site. 
Here is the result when pointing to remote theme open-sdg@1.3.0
![grafik](https://user-images.githubusercontent.com/50657629/119148968-536f8e00-ba4d-11eb-845e-04c0abd1e372.png)
and here when pointing to `brockfanning/open-sdg@fix-for-get-combination-data`:
![grafik](https://user-images.githubusercontent.com/50657629/119149187-929ddf00-ba4d-11eb-968b-61f81019afb9.png)
