### ISSUE TITLE
Remove yellow horizontal lines on indicator pages

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1159]
The yellow horizontal lines on the indicator page do not offer any additional use. Please remove. 

![Screenshot (188)_LI](https://user-images.githubusercontent.com/60919820/111612697-a15de080-87d5-11eb-92e5-584246677f1a.jpg)

**Comment by brockfanning** [comment]
@phillipgardiner These can be removed by admins by overriding a CSS variable and setting the color to "transparent". Just wanted to make sure we discuss whether it is important enough to introduce a breaking (albeit very minor) change.

**Comment by phillipgardiner** [comment]
@brockfanning Probably not then as we wold still want the white space to reside so prob easier to set to transparent, but lets double check with @AnnCorp on the tech call this week.

Out of interest what was the approach we took to this on the goals pages? Did we remove the lines that existed there or just set them transparent?

**Comment by brockfanning** [comment]
@phillipgardiner I'm having trouble finding the PR for a goal pages change related to horizontal lines. But looking at the code now I don't see any horizontal rules or borders. So in that case I guess we just removed them? If you happen to know the PR I could maybe give some more insights.

**Comment by phillipgardiner** [comment]
@brockfanning Um. Perhaps I'm making that up then! I can't find anything either. Oh well not a problem really.

**Comment by AnnCorp** [comment]
@brockfanning definitely don't want to into a breaking change for this. Can we set the CSS for starter repos so appear transparent rather than yellow?

**Comment by brockfanning** [comment]
@AnnCorp Yes we could take that approach. I've just put up a PR for that: https://github.com/open-sdg/open-sdg-site-starter/pull/72

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @jwestw @phillipgardiner I'll go ahead and close this. To implement this on the UK platform, it would be something like this: https://github.com/open-sdg/open-sdg-site-starter/pull/72/files
