### ISSUE TITLE
graph_limits not working in open-sdg>1.2

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1182]
**Please complete the following information** 
Site repository URL: [https://github.com/MoBosse/testSite](https://github.com/MoBosse/testSite)
Open SDG version: 1.3.0

**Describe the bug**
Setting the "graph_limits" has no effect on the chart.

**To Reproduce**
1. See the metadata for indicator 1.2.1 [here](https://raw.githubusercontent.com/MoBosse/testData/develop/meta/1-2-1.md)
2. See the chart [here](https://mobosse.github.io/testSite/1-2-1/)
3. Notice that the y-axis is not responding to the graph_limits

**Expected behavior**
The y-axis should be limited to the minimum and maximum defined in the metadata.

**Additional context**
When I point to open-sdg 1.2.0 it works as expected. The issue only occures when pointing to 1.3.0 or higher

**Comment by LucyGwilliamAdmin** [comment]
Hi @MoBosse 

I'm not sure if this is what's causing the issue but would be good to see if the issue still persists after changing:

```
graph_limits:
  - unit: "%"
    minimum: 1
    maximimum: 20
  - unit: Number
    minimum: 15
    maximum: 55
```

It looks like the unit name is actually `Percentage` rather than `%` and also you have a typo in the first instance of maximum

Let me know if this works

**Comment by MoBosse** [comment]
Hi @LucyGwilliamAdmin 
thanks for taking a look at it. I made the changes you suggested but it seems not to work. (Funny it worked in open-sdg 1.2.0 even with the typo...)
Anyway, in my csv file in the Units column it says % (not "Percentage"). Doesn't that need to be here as well?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse thanks for the further info - could you try just one more thing please. Can you try rebuilding the site repo as looks like it hasn't been rebuild since last changes?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse actually please ignore my previous comment - I see now that you did rerun the workflow - it just wasn't obvious at first. 

I think you may be right and this is a bug then

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse I didn't realise that Percentage was a translations but I see what you mean now - I think that it should actually be changed back to % - apologies

**Comment by LucyGwilliamAdmin** [comment]
Canada have also experienced this issue and I can recreate (tried multiple different ways - no series or units, just units, series and units)

**Comment by LucyGwilliamAdmin** [comment]
Wonder if Canary Islands' override fixes this: https://github.com/eDatos/opensdg/blob/develop/opensdg-web/src/_includes/components/charts/graph_limits.html

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just noticed there's a typo in the docs, which it seems we have all carried through to our metadata files - retesting this quickly now

**Comment by LucyGwilliamAdmin** [comment]
Ok, doesn't seem to work still: 
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-graph-limits/1-1-1/

md file:
https://github.com/ONSdigital/sdg-data/blob/feature-graph-limits/meta/1-1-1.md

**Comment by brockfanning** [comment]
@MoBosse @LucyGwilliamAdmin This should be fixed now. The latest tag 1.4.0-beta3 has the fix in it.

**Comment by LucyGwilliamAdmin** [comment]
Just tested this with

```
graph_limits:
  unit: Percentage (%)
  minimum: 0
  maximum: 100
```

and

```
graph_limits:
  minimum: 0
  maximum: 100
```

and both look like this: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-graph-limits-test/1-1-1/

**Comment by LucyGwilliamAdmin** [comment]
I also can't seem to get it work on 1.2.0 so not sure if maybe not doing something right

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes it needs to be a list of objects, like this example:
```
graph_limits:
  - unit: total
    minimum: 100
    maximum: 1000
  - unit: percent
    minimum: 0
    maximum: 100
```

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning ah yes, that's working for me now - thank you. Closing issue
