### ISSUE TITLE
Table and graph do not appear

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1183]
**Please complete the following information** 

Site: https://wohnungnds.github.io/IM_Site/

Site repository URL: [https://github.com/WohnungNDS/IM_Site]
Data repository URL: [https://github.com/WohnungNDS/IM_Data]
Open SDG version: [e.g. 1.3.1]

**Describe the bug**
Table, graph an map do not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/67795376/115876766-01841a00-a447-11eb-82ed-afa82b9f7881.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [chrome]
 
 my Site [_config.yml](https://github.com/WohnungNDS/IM_Site/blob/develop/_config.yml) 
my Data [config_data.yml](https://github.com/WohnungNDS/IM_Data/blob/develop/config_data.yml) 

Any Ideas?
Thank You!

**Comment by MoBosse** [comment]
Hi @WohnungNDS 
not sure but could you try to add `https` rather than `http` [here](https://github.com/WohnungNDS/IM_Site/blob/develop/_config.yml#L12)?

**Comment by WohnungNDS** [comment]
@MoBosse Great! It works! Thank you so much!
I'll get back to you because of the privacy statement and cookies via email next week!
I got two month to explore if I can use the platform for my work on the migration report for lower saxony. To my mind would be great to use it. But there are some privacy things to to figure out... this might be more worse then the technical things ;-)
