### ISSUE TITLE
formatting translations

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1185]
Hello, 

how can I do linebreaks or use bold or italic in translations?

I want to do something like this:

---
Some long sentences. Some long sentences. Some long sentences. <br>
Some long sentences. Some long sentences. <br>
**one or more important words**
_some italic formatted text_

---
[my translations repository ](https://github.com/WohnungNDS/IM_translations)

[my site repository](https://github.com/WohnungNDS/IM_Site)

[my data repostitory](https://github.com/WohnungNDS/IM_Site)

**Comment by MoBosse** [comment]
If I am not mistaken you can use the normal html tags. See e.g. the `<small>` tag used [here](https://github.com/G205SDGs/sdg-translations/blob/master/translations/de/metadata_fields.yml#L27) and the result here: 
![grafik](https://user-images.githubusercontent.com/50657629/116354852-4ae2b980-a7f9-11eb-9a73-c7b10b2525a7.png)

To get a line break it would be `<br>`
For italic text it would be `<i> some italic formatted text </i>`
For bolt text it would be `<b> one or more important words </b>`

**Comment by WohnungNDS** [comment]
Great it works!

But something seems to be wrong with my translations repository. 
i do not now when the translations will be filled in.

I have changed this line but it won't show..

https://github.com/WohnungNDS/IM_translations/blob/0c300dca77ce5aaa51e664b98200ab1f4150a6e4/translations/de/global_targets.yml#L289

changed some data, and something in the site config to start the dployment process...

[Indicator 2](https://wohnungnds.github.io/IM_Site/2/)


[my config_data](https://github.com/WohnungNDS/IM_Data/blob/develop/config_data.yml)

[my site config](https://github.com/WohnungNDS/IM_Site/blob/develop/_config.yml)

Any Ideas?

**Comment by MoBosse** [comment]
I think it does show:
![grafik](https://user-images.githubusercontent.com/50657629/116656044-50243d80-a98c-11eb-8d67-6da8ea9fe98c.png)
That is what you wanted to achief, isn`t it?

**Comment by WohnungNDS** [comment]
Yes.... but it took severeal hours before it has been showed.
I think, i will try to have the translations in the data repo... may be this will be quicker.

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS has your issue been resolved?

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin yes I think so.
