### ISSUE TITLE
Docs for new indicator config/metadata structure

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1201]
Split [Metadata format](https://open-sdg.readthedocs.io/en/latest/metadata-format/) into metadata and indicator config

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I don't think we've actually discussed this but thinking we could move what is currently in [metadata format](https://open-sdg.readthedocs.io/en/latest/metadata-format/) to something called "Indicator configuration", and then in metadata format we could have definitions of the SDMX metadata concepts (see #1202) where I made a start.

Let me know your thoughts? I'm happy to continue making the changes if you think that's the route we should go down?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes that sounds great!
