### ISSUE TITLE
Single unit of measurement

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1204]
**Finding**: 'Unit of measurement' is displayed as an option in the dis-aggregation filters filters even if there is only one measure available (for example see: https://sdgdata.gov.uk/15-4-2/)

**Recommendation:**
If there is only one 'Unit of measurement', do not display it in the disaggregation controls. The unit of measurement is able to be interpreted by the users from the graph axis, footnote and graph title.

**Comment by brockfanning** [comment]
As discussed, a config setting is unnecessary here.
