### ISSUE TITLE
Map Tile image won't show

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1208]
**Please complete the following information**
[Data repository URL](https://github.com/WohnungNDS/IM_Data/): [https://github.com/WohnungNDS/IM_Data/]
[Site repository URL](https://github.com/WohnungNDS/IM_Site/): [https://github.com/WohnungNDS/IM_Site/]
Data or metadata issue: Map

**Describe the bug**
The tile image is not shown on the map
![image](https://user-images.githubusercontent.com/67795376/118949876-f21ac280-b959-11eb-8466-734c30c5c8f3.png)

I put the PNG adresse in my  my site [_config file](https://github.com/WohnungNDS/IM_Site/blob/develop/_config.yml) line 169

`
map_options:  minZoom: 5  maxZoom: 10  tileURL: https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}  tileOptions:    id: mapbox.light    accessToken: pk.eyJ1IjoiY2hyaXN0b3BoNDcxMSIsImEiOiJjanp1cjdpbzQwMTFwM29tdzJ2ZTh3Ymo4In0.C7_7e3AFcMaF_QBg6MaT0Q    attribution: &lt;a href="https://www.mapbox.com"&gt;Mapbox&lt;/a&gt; | &lt;a href="http://www.bkg.bund.de"&gt;© GeoBasis-DE / BKG&lt;/a&gt;
`
I have also tried openstreetmap like sdg-indikatoren.de 
https://github.com/G205SDGs/sdg-indicators/blob/e62d0bb00ef2710c447ac52a67bd47b59a4c80a2/_config.yml#L181
but no tile image appears.

**Comment by brockfanning** [comment]
@WohnungNDS Here is what I'm seeing in the console:

![Screenshot 2021-05-20 075426](https://user-images.githubusercontent.com/1319083/118974330-b1fb1600-b940-11eb-95f4-f86769733ac9.png)

I'm not sure why the openstreetmap didn't work, though. If you switch back to that, I'd be happy to take a look for any clues in the console. Usually if the tile images are not displaying there will be a lot of errors in the console with some clues.

**Comment by WohnungNDS** [comment]
Now the openstreetmap tile works...
Thank You!
