### ISSUE TITLE
sdgbg.png

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1210]
**Please complete the following information**
[Data repository URL](https://github.com/WohnungNDS/IM_Data/): [https://github.com/WohnungNDS/IM_Data/]
[Site repository URL](https://github.com/WohnungNDS/IM_Site/): [https://github.com/WohnungNDS/IM_Site/]
Data or metadata issue: sdgbg.png image

I try to get rid of this multi color line on the top of the site.

![image](https://user-images.githubusercontent.com/67795376/119000285-4722fc80-b98b-11eb-8993-0468d5857e0d.png)

Looking at the console it schould be in my 
[Site repository](https://github.com/WohnungNDS/IM_Site/tree/develop/assets/img)

I can call it directly [here](https://wohnungnds.github.io/IM_Site/assets/img/sdgbg.png) 

But I can't find it in my repisitory.

Any Ideas?

**Comment by brockfanning** [comment]
@WohnungNDS I think the easiest way to get rid of it would be to add something like this in your _sass/custom.scss file:

```
body {
  background: white;
  padding-top: 0;
}
```

**Comment by WohnungNDS** [comment]
Thank you! Adding 

'
body {
  background: white;
  padding-top: 0;
}
'
in the custom.scss works.....
