### ISSUE TITLE
expand metatdata tab

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1211]
[Data repository URL](https://github.com/WohnungNDS/IM_Data/): [https://github.com/WohnungNDS/IM_Data/]
[Site repository URL](https://github.com/WohnungNDS/IM_Site/): [https://github.com/WohnungNDS/IM_Site/]
Data or metadata issue: metadata

my metadata tab seems to be not as wide as it schould be:

![image](https://user-images.githubusercontent.com/67795376/119129389-20ba9b00-ba37-11eb-80c2-e7703d0de9e5.png)

my[ _prose.yml ](https://github.com/WohnungNDS/IM_Data/blob/develop/_prose.yml)says the field has to be a Textarea

'
      - name: "source_other_info_1"
        field:
            element: textarea
            label: "Other information"
            translation_key: metadata_fields.source_other_info_1
            scope: source_1
'

For my indicator description  "textarea" works fine:

![image](https://user-images.githubusercontent.com/67795376/119129674-81e26e80-ba37-11eb-98cc-bd2770699b93.png)

**Comment by LucyGwilliamAdmin** [comment]
Hi @WohnungNDS 

That is actually the way that the source tab is designed as it's possible to have multiple sources e.g. see here:
https://sdgdata.gov.uk/1-a-2/

Are you planning on always just having the one source?

**Comment by WohnungNDS** [comment]
Ah I understand!

I haven't thought about the number of sources. At the moment I think one source is enough.....

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS no probs, if you do still want to expand the column size within the sources tab there are options depending on what you want e.g. something like 

1. You could overwrite the width so it would look something like this (but would also want to sort the alignment if having more than one source per indicator):
![image](https://user-images.githubusercontent.com/43404358/119137643-ec47de80-ba38-11eb-8276-0755ccb2909c.png)

2. You could make use of [metadata_tabs configuration option](https://open-sdg.readthedocs.io/en/latest/configuration/#metadata_tabs) to create a new tab and have that contain your source fields, and then this would be styled the same as the national and global metadata tabs.

I think if there is a chance of you wanting more than one source in the future then it maybe be better to go with option 1 as you would still be able to make use of the splitting of sources.

If either of these are of particular interest, I'm happy to go into more detail

**Comment by WohnungNDS** [comment]
Thank you! I choose the first option. Where do I overwrite the width?

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS to overwrite the width, you need to overwrite [_includes/components/indicator/sources.html](https://github.com/open-sdg/open-sdg/blob/1.4.0-dev/_includes/components/indicator/sources.html) and remove `class="col-md-6"` from line 15 - this will increase the width to the full width of the tap.

From looking at some work Brock previously done on this when we were thinking of implementing this as default, you will also need to add some custom css - this will deal with row-name:row-value split:

```
metadata-tabs {
  #sources {
    td {
      min-width: 60%;
    }
  }
}
```

Finally, you will need to call that class somewhere, but I'm not too sure where - @brockfanning can you clarify please? Is it [_includes/components/indicator/metadata-panes](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/indicator/metadata-panes.html)?
