### ISSUE TITLE
Remove support for ShareThis

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1242]
Right now there is an optional setting for turning on ShareThis. As we're starting to think about a better cookie-consent system, it is clear that we would need to have special documentation of this feature as it relates to cookies and privacy. This adds the additional complication of requiring that documentation to be translated in SDG Translations, since it would be displayed on the site in a cookie-consent form.

Since that feature was added, we've also added a "head-custom.html" include file, which can be easily used to add ShareThis without the help of that setting.

Are there any objections to removing the setting in the next minor release, and providing help on how to use head-custom.html to maintain that functionality?

**Comment by LucyGwilliamAdmin** [comment]
No objection from me
