### ISSUE TITLE
Easier control of fonts and sizes

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1257]
**Is your feature request related to a problem? Please describe.**

The font-family is hardcoded in the platform's CSS, and so can't be changed without adding custom CSS. There are also font sizes scattered throughout our code, applying specific sizes (in pixels) to various elements. Sometimes after changing a font, the sizes need to be tweaked also. So, changing the font is difficult right now.

**Describe the solution that you need**

Just like we use for colors, we need to have variables for the font-family, as well as for different categories of font-sizes. This would allow fonts to be changed and tweaked only by overriding a few variables.

**Why do you need this feature?**

To allow more flexibility to the typography.

**Comment by brockfanning** [comment]
Here is an audit of the places where we use font-size:

* Overall font size: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L3
* H1: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L10
* H2: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L11
* H3: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L12
* Lead copy: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L13
* Small text: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_typography.scss#L14
* Back to top: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_back_to_top.scss#L9
* Disclaimer: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_disclaimer.scss#L15
* Goal-by-target vertical: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_goal-by-target-vertical.scss#L5
* Reporting status:
    * Status tags: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_reporting_status.scss#L43
    * Goal total: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_reporting_status.scss#L107
* News page post title: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_news.scss#L15
* Search results:
    * Title: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_search.scss#L36
    * URL: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_search.scss#L55
* Goal page status tags: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_mixins.scss#L14
* Search bar: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_mixins.scss#L176
* Language toggle:
    * https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/base/_mixins.scss#L236
    * https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_language_toggle.scss#L7
    * https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_language_toggle.scss#L16
    * (mobile) https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_language_toggle.scss#L38
    * (links) https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/components/_language_toggle.scss#L141
* Main menu items: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_header.scss#L92
* Mobile menu toggles: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_header.scss#L199
* Mobile menu items: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_header.scss#L247
* Disaggregation controls:
    * Buttons: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L38
    * Fields: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L76
    * H5, H6: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L109
    * Disaggregation buttons: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L164
    * Disaggregation labels: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L185
    * Max disaggregation warning: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L273
* Chart legend items: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L299
* Chart footer items:
    * https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L403
    * https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_indicator.scss#L472
* Homepage intro:
    * Description: https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_sass/layouts/_homeintro.scss#L5

**Comment by LucyGwilliamAdmin** [comment]
Discussed and think can move to later release

**Comment by phillipgardiner** [comment]
@brockfanning @LucyGwilliamAdmin  I was just trying to make some progress with this. What I have done is gone through the site and noted down from a visual perspective the font size of different elements. On this basis I believe most things (I may have missed some) would fit into six categories, these are (I'm guessing we could call them what we like?):

36px | x-large (currently H1)
27px | large (currently H2)
24px | medium (currently H3)
22px | lead-body (currently lead-copy)
16px | body
14px | small (currently small-text)

There are then a couple of specific ones where even though they share the same font sizes as copy we would not want them updated alongside if we were to change the overall variable size, these are:

16px | navigation-menu
16px | breadcrumb
14px | button-text
12px | tag-text
18px | search-result-link
20px | chart-title

I've tried to map these onto the links you provided above (see attachment) [Fonts and sizes.xlsx](https://github.com/open-sdg/open-sdg/files/7604124/Fonts.and.sizes.xlsx), but may have mis interpreted the task? Perhaps we could pick this up as part of tech call if time seeing as going to be less of us attending next week. Thanks.

**Comment by brockfanning** [comment]
@phillipgardiner That's very helpful. I've submitted a pull-request with these. #1496

**Comment by LucyGwilliamAdmin** [comment]
Closing as was in 1.7.0
