### ISSUE TITLE
Add support for Google Analytics 4 (latest version)

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1258]
The Google Analytics code we currently have is compatible with Google Analytics - Universal Analytics. However it is not compatible with the new version (GA4).

More information about GA4 is here:
https://support.google.com/analytics/answer/10089681?hl=en

The code Canada are having to use instead is here:
https://github.com/sdg-data-canada-odd-donnees/cif-cic_dev/blob/develop/_includes/footer.html#L42-L52

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner I think this is actually quite complex as there's a few different scenarios:

1. An existing Open SDG user who has Universal Analytics set up and is going to continue using Universal Analytics (currently what's supported)
2. An existing Open SDG user who has Universal Analytics set up but want to start using GA4 alongside Universal Analytics ([Google Analytics article](https://support.google.com/analytics/answer/9744165?hl=en&ref_topic=9303319)
3. An Open SDG user who wants to use Google Tag Manager (possibly in order to link GA4 and UA)
4. An Open SDG user who is setting up Google Analytics for the first time and will be using just GA4 ([Google Analytics article](https://support.google.com/analytics/answer/9304153))

@brockfanning what is the approach for adding google analytics at the moment? I can see this file but how does it relate to the data collection approaches mentioned in this [Google Analytics article](https://support.google.com/analytics/answer/10269537)

**Comment by brockfanning** [comment]
We'll try to get all the GA code into one include file for easy overriding.
