### ISSUE TITLE
Add a label to graph x-axis

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1259]
Currently graphs on the SDG website do not contain a label on the x-axis (a label only exists on the y a-xis). Ticket to add a label to the x-axis. More details to follow after conversation with the ONS 'style council'.

Configuration settings:
- Site config: blank by default (for side wide default)
- Indicator config (for indicator-specific control)

Mock up:
![image](https://user-images.githubusercontent.com/43404358/126778372-5d8d63a9-8de8-4083-8f3c-5988e237612d.png)

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner does this require more research?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin Not really I think you were just contacting the ONS 'style council' to see what they said. Otherwise I think its just a case of adding the label and following best practices for positioning - which i'm happy to propose.

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin a candidate for 1.5.0?

**Comment by brockfanning** [comment]
As discussed, this can default to being blank, and more feedback is coming on where the label will appear when it is selected.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner we had discussion in UK this morning about settings and defaults - I've added to the description, what we thinking would work: 2 settings - one site-wide which defaults to blank, and one indicator configuration/

**Comment by brockfanning** [comment]
@phillipgardiner Just to set expectations - this is supported in Chart.js but only centered - not on the right. Here is how it will look:

![screenshot-127 0 0 1_4000-2021 08 16-23_17_07](https://user-images.githubusercontent.com/1319083/129658290-ab8ae866-0aaf-44bf-bc43-3d81b4d7b764.png)

**Comment by brockfanning** [comment]
@phillipgardiner Here are the options available for configuring these labels: https://www.chartjs.org/docs/2.9.4/axes/labelling.html

**Comment by phillipgardiner** [comment]
@brockfanning Hi, I can't seem to work out what the current font size is for the axis labels. I think if anything I'd like to see what they look like if they were increase by say 4px so if currently 8px change to 12px. If this doesn't actually help in anyway, then we may be best to leave as is until we upgrade chart.js and then make it exactly how we want it. 

Would you be able to do a screen shot or something with the axis labels px increased please?

**Comment by brockfanning** [comment]
@phillipgardiner Yes, the default is 12px. Here is a screenshot with both axis labels increased to 16px:

![screenshot-127 0 0 1_4000-2021 08 17-10_18_48](https://user-images.githubusercontent.com/1319083/129743048-97db53f4-e129-46e4-8d18-942748198682.png)

**Comment by brockfanning** [comment]
@phillipgardiner Also here is a version with the fontFamily set to match the rest of the page (just a slight difference):

![screenshot-127 0 0 1_4000-2021 08 17-10_23_17](https://user-images.githubusercontent.com/1319083/129743915-373ec6f9-e8ca-4292-806d-64e3f0c2c9ab.png)

**Comment by brockfanning** [comment]
@phillipgardiner Lastly here's a version with the Y axis left at 12px:

![screenshot-127 0 0 1_4000-2021 08 17-10_26_41](https://user-images.githubusercontent.com/1319083/129744499-5f9051a2-f2fd-4352-abb4-2ceb1ff9cfcb.png)

**Comment by phillipgardiner** [comment]
@brockfanning sorry is the last example with the font changed also? I def think 16px is too big. Sorry to be a pain could we try with 14px?

**Comment by brockfanning** [comment]
No problem. Yes the last example had the changed (Open Sans) font. Here's a version with both axes at 14px and the Open Sans font (the only reason we weren't already using the Open Sans font for the unit label is that we hadn't specified it, so Chart.js was just using its own default):

![screenshot-127 0 0 1_4000-2021 08 17-10_45_43](https://user-images.githubusercontent.com/1319083/129748038-cfff571b-476f-4076-9641-f51c71fa4e51.png)

**Comment by phillipgardiner** [comment]
@brockfanning Thank you. I think i'll need to double check it on a feature branch when we have one, but I think that works - do you?

**Comment by brockfanning** [comment]
@phillipgardiner Sounds good - keep an eye on #1293 for an updated feature branch.
