### ISSUE TITLE
Combination of "Series" column and "data_start_values" not working

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1266]
**Please complete the following information**
Data repository URL: [https://github.com/MoBosse/testData/](https://github.com/MoBosse/testData/)
Input format: csv

**Describe the bug**
A combination of using a "Series" column in the csv and "data_start_values" is breaking the chart (saying "helpers.getSeriesFromStartValues is not a function")

See example here: 
Site: [https://mobosse.github.io/testSite/9-2-2/](https://mobosse.github.io/testSite/9-2-2/)
Data repo: [https://github.com/MoBosse/testData/blob/develop/meta/9-2-2.md](https://github.com/MoBosse/testData/blob/develop/meta/9-2-2.md)
Site repo: [https://github.com/MoBosse/testSite](https://github.com/MoBosse/testSite)

**Comment by MoBosse** [comment]
@brockfanning I tested the pr #1265 and it solves the issue discribed above but there is still a little problem remaining: [Here](https://mobosse.github.io/testSite/8-4-1/) is an indicator with two series, one of which (a) has two units and the other (b) has one unit. I set start_values to series (a) with one of its units. This worked perfectly. The problem is that I can`t preset the unit of (b) so the chart doesn't show any values when I change the series until I select the unit as well.

To reproduce: 

1. Go to [this page](https://mobosse.github.io/testSite/8-4-1/)
2. Select the series "Inländische Rohstoffverwendung pro realem BIP"
3. See how you need to select the Unit "2015 = 100" as well.

meta repo: [https://github.com/MoBosse/testData/blob/develop/meta/8-4-1.md](https://github.com/MoBosse/testData/blob/develop/meta/8-4-1.md)

**Comment by brockfanning** [comment]
@MoBosse Thanks for reporting that. I've pushed a potential fix to the same branch/PR.

By the way, I don't believe you need the third item in the data_start_values in this file. That third item will never be reached because "Units" will always be found in the first item.

**Comment by MoBosse** [comment]
@brockfanning Thanks! Works perfectly now.
