### ISSUE TITLE
Handle large number of disaggregations

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1267]
When a user attempts to add too many disaggregations the page freezes and becomes unresponsive

For example, see:

Go to http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-1.4.0-beta2/11-6-2/
Click "Select all" from Local authority dropdown

And:

Go to: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-1.4.0-beta2/5-2-1
Click "Select all" from dropdowns Age, Country of birth, Disability status, Ethnicity,  Highest Qualification, Type of partner abuse and Abuse sub-category

**Comment by brockfanning** [comment]
Fixed by #1269
