### ISSUE TITLE
Problems with generate maps 

### ISSUE THREAD

**Issue by emiliopardo** [open-sdg/open-sdg#1271]
Hello 

First sorry for my bad Engilsh

My name is Emilio Pardo. I am working to deploy open-sdg-simple-starter. I can deploy and show table and graphs. My problems is with de maps options.

I have one indicator with GeoCode field and a geojson with the name and field_id. GeoCode field and  field_id have the correct values.

When I update the github repository the bulid script not show errors but when I see the geojson indicator is equal than de original geojson. There is not dissagregations or values fields.

My geojson is valid because github page show de map over mapboox base layer.

I can create a geojson file with GIS software and upload  to gh-pages. The file is correct and can view the Map tab in indicator page.

Here is the results when i create the geojson in qgis 
https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-a/

I installed sdg-build and run test geojson.py and I have the same results.

**geojson file** 

[https://raw.githubusercontent.com/emiliopardo/terminos_municipales/main/terminos_municipales.geojson](https://raw.githubusercontent.com/emiliopardo/terminos_municipales/main/terminos_municipales.geojson)

**csv file**
[https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/data/indicator_7-1-2-a.csv](https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/data/indicator_7-1-2-a.csv)

**metadata file**
[https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/meta/7-1-2-a.md](https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/meta/7-1-2-a.md)

The build script not show information about any errors 

Any idea?

thanks

**Comment by emiliopardo** [comment]
the metada file have some fields than i create a put in _prose.yml Thats new fields are displayed correctly in the indicator page

**Comment by LucyGwilliamAdmin** [comment]
Hi @emiliopardo - is the issue that no disaggregation options are showing for the map?

**Comment by emiliopardo** [comment]
it basically does not join between the csv and the geojson

the two objects fields in result geojson is not generate when run build script

there is not dissagregations  and values fields

**Comment by emiliopardo** [comment]
Is not show, because is not join csv and geojson. but name_property and id_property is defined in config_data.yml with the corrects values name and geocode

**Comment by LucyGwilliamAdmin** [comment]
@emiliopardo from what I can see here, this is how I would expect the map to look:
https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-a/

It currently isn't possible to view disaggregations on maps.

However, there is a pull request open for the feature: https://github.com/open-sdg/open-sdg/pull/663 - it is still being discussed

**Comment by emiliopardo** [comment]
yes, that's the expected result (https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-a/)

I create that geojson in qgis desktop and upload to gh-pages

If is not possible  why is the map correctly?. 

the problem is in sdg-bulid?

Thank you for answering so quickly

**Comment by emiliopardo** [comment]
so, if my csv file did not have the column "degree urbanization"

the geojson generation would work correctly?

thanks

**Comment by LucyGwilliamAdmin** [comment]
@emiliopardo apologies, I didn't realise at first the structure of the disaggregation.

I'm not sure we've actually come across this before i.e. where the geographical disaggregation is a child of a non-geographical disaggregation.

I think one way of fixing it would be to remove the degree of urbanization column but then that takes away some of the filtering aspect

@brockfanning what are your thoughts? Do you think that could be why the geojson isn't generating like it should?

**Comment by brockfanning** [comment]
@emiliopardo @LucyGwilliamAdmin I believe we may have had some map-related fixes in the latest release, so it might be a good idea to first upgrade to version 1.4.0. Here are instructions on doing that: https://open-sdg.readthedocs.io/en/latest/upgrades/upgrading-1-4-0/

@emiliopardo Can you try doing that and see if the problem still happens?

**Comment by emiliopardo** [comment]
We can start with a clean install with the last stable version. Actually we are under development state so I think is better.

We only have seven indicator, actually only three have active maps tabs.

7.1.2.a -> [https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-a/](https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-a/)
7.1.2.b ->  [https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-b/](https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/7-1-2-b/)
8.3.1-> [https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/8-3-1/](https://ods-municipios-andalucia.github.io/ods-municipios-andalucia/8-3-1/)

7.1.2.a and 7.1.2.b have disaggregation with "degree urbanization"

8.3.1 unemployed rate have not disaggregation 


thanks for your help

**Comment by emiliopardo** [comment]
I created a clean install
[https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/)(https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/)

I removed all the demo indicators and loaded our seven indicators and the geojson

I commit all changes to the remote repository and gh-pages was created successfully

![deploy_gh-pages](https://user-images.githubusercontent.com/16943695/126282854-37d69f0a-c4f7-4172-a56f-a9c8d2fd847f.png)


When I check maps in flags 7.1.2.a 7.1.2.b and 8.3.1, the maps tab is displayed, but the geojson layer does not load correctly.

The map should be centered on the Andalusia, Spain region.

If I look at the browser debugger
```
Uncaught Error: Bounds are not valid.
    fitBounds https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    init https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720073628:543

```
![browser_debugger](https://user-images.githubusercontent.com/16943695/126282986-0b38acf2-1204-4bbf-9b4b-ba673fe6a3ac.png)

In branch gh-pages are geojson files 
[https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/tree/gh-pages/es/geojson/regions](https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/tree/gh-pages/es/geojson/regions)

I don't Know why  there are seven geojson when only three indicators have data_show_map: true

If i watch geojson on github are ok,  the geojson is loaded over mapbox base map and is centered over Andalusia 

When I check geojson in raw mode I saw that all indicators have the same content of the original geojson file [https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/blob/develop/geojson/terminos_municipales_simplify.geojson](https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/blob/develop/geojson/terminos_municipales_simplify.geojson)

So, there is not join between csv and geojson but csv have GeoCode field and geojson if defined correctly in config_data.yml whith name_property and id_porperty

Disaggregations are not the problems because indicator 8.3.1 has not disaggregations


If I create the geojson with  QGis (GIS Desktop aplicattion ) with the logical structure copied of the map tab from [https://mobosse.github.io/testSite/en/1-4-2/](https://mobosse.github.io/testSite/en/1-4-2/)

here is the geojson of  @mobosse

[https://mobosse.github.io/testData/en/geojson/regions/indicator_1-4-2.geojson](https://mobosse.github.io/testData/en/geojson/regions/indicator_1-4-2.geojson)

My maps are showed correctly in my maps tab

here my geojson created in QGis Desketop app 

[https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_7-1-2-a.geojson](https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_7-1-2-a.geojson)
[https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_7-1-2-b.geojson](https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_7-1-2-b.geojson)
[https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_8-3-1-.geojson](https://raw.githubusercontent.com/ods-municipios-andalucia/ods-municipios-andalucia/develop/geojson/indicator_8-3-1-.geojson)

the third does not have disaggregation

**Comment by LucyGwilliamAdmin** [comment]
I'm not sure what's going on - one thing I've noticed is that terminos_municipales_simplify.geojson has a few instances where the same name/geocode is used in multiple features e.g. "Borge, El". @brockfanning do you think that could be causing an issue?

**Comment by emiliopardo** [comment]
tomorrow I will check the geojson and remove duplicates.

 Another thing I'm going to try is sdg-build the geojson example to see if it gives more information.

Thanks

**Comment by emiliopardo** [comment]
That geojson simplify is a generalized geometry of the local administration units of Andalusia región. 

Downloaded from eurostats

**Comment by emiliopardo** [comment]
I have reviewed the geojson and I have verified that in some cases the municipalities have separate areas, that is, it is formed by two or more independent polygons.

![Captura de pantalla_2021-07-20_22-30-41](https://user-images.githubusercontent.com/16943695/126391574-788af90a-2e00-4652-a0aa-2698d32f397a.png)


I have unified the geometries to multipolygon, there is only one record for each municipality

[https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/blob/develop/geojson/terminos_municipales_multipolygon_simplify.geojson](https://github.com/ods-municipios-andalucia/open-sdg-simple-starter/blob/develop/geojson/terminos_municipales_multipolygon_simplify.geojson)

i have configured this new geojson in config file 

```
map_layers:
 - geojson_file: ./geojson/terminos_municipales_multipolygon_simplify.geojson
   name_property: name
   id_property: geocode
   output_subfolder: regions
   filename_prefix: indicator_
```
gh-pages creation has been executed but the result is still the same

browser debugger show one error

```
Uncaught Error: Bounds are not valid.
    fitBounds https://unpkg.com/leaflet@1.3.4/dist/leaflet.js:5
    init https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720202704:543
    setTimeout handler*init/< https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720202704:537
    jQuery 9
    <anonymous> https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720202704:3840
    jQuery 2
    <anonymous> https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720202704:3824
    jQuery 2
    <anonymous> https://ods-municipios-andalucia.github.io/open-sdg-simple-starter/assets/js/sdg.js?v=20210720202704:3808
    jQuery 13
```

generated geojson haven't data values, join between the csv and the source geojson does not make

**Comment by brockfanning** [comment]
@emiliopardo I think you have found two bugs:
1. Using an id_column of `geocode` and a name_column of `name` causes problems.
2. Using purely numeric geocodes causes problems.

I've opened a couple of pull-requests in sdg-build to try and help with these bugs, but in the meantime I think the quickest fix for you is to:
1. Add a non-numeric prefix to all your geocodes. Eg: `A04001` instead of `04001`.
2. Use different id_column and name_column. Eg, instead of `geocode` and `name`, use `geocode1` and `name1`.

**Comment by emiliopardo** [comment]
hello 
I'll change de names of columns and modify number codes, that code is the oficial code for Local Administrative Unitsdefined by Eurostats

[https://ec.europa.eu/eurostat/documents/345175/501971/EU-27-LAU-2020-NUTS-2021-NUTS-2016.xlsx](https://ec.europa.eu/eurostat/documents/345175/501971/EU-27-LAU-2020-NUTS-2021-NUTS-2016.xlsx)

I'll change my geocode with a prefix 

thanks

**Comment by emiliopardo** [comment]
Eureka !!!

the maps are already generated correctly

The problem of codes of provinces or regions is something that we drag in all our works.

Officially it's five numeric characters

The province of Almería is the code 04 and the first municipality of the province is Abla 04001

When we work with csv or excel it always changes us from text type to numeric type and eliminates the 0 in front

Almeria 4
Abla 4001

Thanks for your effort

![7f9b6b421ccfb0ba55a0e2a5b20334dd](https://user-images.githubusercontent.com/16943695/126444482-6e0cd1ed-fd1a-40d8-bb67-4626c4d38f60.gif)

**Comment by brockfanning** [comment]
Great to hear! Leave leave this issue open until those 2 bugs are fixed. Thanks for bringing those to our attention.
