### ISSUE TITLE
Add placeholder indicator e.g. for 11.2.1 (undefined indicator)

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1275]
Discussed so far:
- could possibly use a new "placeholder" indicator configuration setting, which serves to prevent an indicator page from being generated, and on the goal pages display the contents of that setting rather than a link to an indicator page.
- can countries somehow control exclusion from reporting status counts?

Expected:
![image](https://user-images.githubusercontent.com/43404358/126364342-32c5e157-4809-4c80-8694-1fb29b526f5b.png)

**Comment by brockfanning** [comment]
We may have the "placeholder" setting automatically exclude the indicator from reporting status. We'll check with the data teams for their opinion on this.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you have a time estimate on this?

**Comment by brockfanning** [comment]
I'd estimate about 5 hours.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've had a response from UK data team - looking at it from the 11.c.1 POV they said it shouldn't affect reporting status as UN Stats states that there are 247 indicators (adding 11.c.1 would make it 248).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Moritz has also said that the total count should not be affected
