### ISSUE TITLE
Deploy to Production Failure

### ISSUE THREAD

**Issue by jjzajdel** [open-sdg/open-sdg#1279]
**Please complete the following information** 
Site repository URL: https://github.com/jjzajdel/site
Open SDG version: 1.4.0

**Describe the bug**
When I go to preform the initial site deployment, I get the following error message;

Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Unable to read data from: https://my-github-org.github.io/open-sdg-data-starter/en/meta/all.json
404 Not Found
Error: Process completed with exit code 1.

**To Reproduce**
The bug can be reproduced by either creating a new Master branch or by merging the master and develop branches.

**Expected behavior**
I would expect the site to be pushed to the production site after the creation or merging of the master and development branches. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by LucyGwilliamAdmin** [comment]
@jjzajdel you need to update the value in [_data/site_config_prod.yml](https://github.com/jjzajdel/site/blob/develop/_data/site_config_prod.yml#L19) to: `https://sandag-sdg.github.io/SANDAG-SDG-Data`

**Comment by jjzajdel** [comment]
@LucyGwilliamAdmin Thank you it runs smoothly now. This is off topic but are there plans to most a tutorial on map creation? Thanks for your help!
