### ISSUE TITLE
Set Default  Map Tab actived

### ISSUE THREAD

**Issue by emiliopardo** [open-sdg/open-sdg#1280]
I 'm changing default order of indicator tabs. 

**From:**  Chart | Table | Map
**to:** Map |Chart |table

I added in my deploy:
 _includes/components/indicator/indicator-main.html
 _includes/components/indicator/data-tabs.html
 _includes/components/indicator/data-panes.html

in the first file (indicator-main)  I changed default css to hidden sidebar added class (indicator-sidebar-hidden) and get indicator-main full adding class indicator-main-full

in the second file (data-tabs) I chaged the order of <li> and created if else sentence to take in considerations the indcators with out maps

in the third file (data-panes) I changed class actived to map when exists with if else sentence.

the html page is correct the tabs are displayed like I want. I can active or desactive tabs and view chart tab or map.

The problem is in the map. When load indicator page, maps is not center in the extent of geojson. But when you active other tab and return to map tab. Map is center in the correct position.

I think there is not inicialized map correct, like center or zoom or extent.

The map is not center over my geojson but when you move the map my  geojson is correctly 

How I can trigger the inizialization of the map with out click on the Map Tab

Thanks

**Comment by brockfanning** [comment]
@emiliopardo I think this would be a useful feature for Open SDG - to be able to set an indicator to start out in the map tab. Unfortunately one issue is that there is some code that only runs when the map tab is clicked on. That code is [here](https://github.com/open-sdg/open-sdg/blob/1.5.0-dev/_includes/assets/js/plugins/jquery.sdgMap.js#L504-L533).

A low-tech way to do this, without overrides, would be to use jQuery to click the tab by adding this to a custom JS file:

```
function showMap() {
  $('#tab-mapview').click(); 
}
setTimeout(showMap, 300);
```

(The setTimeout would probably be needed to allow other stuff to ready.)

But in the long term I feel like this would be a good feature to add to the platform.

**Comment by emiliopardo** [comment]
Ok i add the Code on custom.js and  i'll test

Thanks

**Comment by emiliopardo** [comment]
Perfect, it worked

I close the issue

Thanks

**Comment by brockfanning** [comment]
@emiliopardo Glad to hear it. Just to mention, you can also remove those three _includes files, if using that jQuery approach.

I'm also happy to keep this issue open because I know that other users have had this need, and this might be a good candidate for a new feature.

**Comment by emiliopardo** [comment]
Ok, reopen and i delete  my includes

**Comment by emiliopardo** [comment]
For new feature when config_data has geojson layer when sdg-build create gh-pages can read geojson extent and create a variable in JavaScript files than leaflet can take.

If in the future hace two or more geojson for create diferents Maps view that variable can be an array

**Comment by LucyGwilliamAdmin** [comment]
Closing this one as more generally covered in #1435
