### ISSUE TITLE
Map tab to react to series being changed

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1282]
**Is your feature request related to a problem? Please describe.**
If an indicator has a map and more than one series, the map tab doesn't react to the series being changed. However, the title changes.

This can be misleading as users could think that the map is showing data for the series but it's not (unless it's the first series)

**Describe the solution that you need**
When the series is changed, the map should change to reflect the changes in data

**Why do you need this feature?**
So that users aren't misled in thinking that the map is showing something it isn't

**Describe alternatives you've considered**
Depending on how long this may take and difficulty, maybe something quicker/easier could be implemented in short term e.g. that makes it clear that the map is showing the first series.

**Comment by LucyGwilliamAdmin** [comment]
@EmmaWoodONS I've just added this issue based on what you were saying about maps and series but feel free to make some changes to the description if I've missed anything

**Comment by EmmaWoodONS** [comment]
Thanks Lucy - I think that covers it. I just have one slight addition:

Even if the start_value is set to a series that is not the default, the title of the map changes to that for the start_value, but the map itself stays on the default first series.
