### ISSUE TITLE
Video: Turn on automated tests

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1301]
Tasks:
- [x] Script written
- [x] Script approved (if required)
- [x] Screen recording complete
- [x] Video edited
- [x] Uploaded to YouTube as private
- [x] Video reviewed and approved
- [x] Video made public
- [x] Embedded on open-sdg.org/readthedocs

**Comment by WohnungNDS** [comment]
Great!

**Comment by LucyGwilliamAdmin** [comment]
Video is on YouTube and embedded in docs so closing issue
