### ISSUE TITLE
Hide units widget if there is only one choice

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#132]
The "Units" radio button displays even when there is only one option. Ideally it would not display in this case. In fact, the entire sidebar should be hidden.

**Comment by dougmet** [comment]
Just to voice one opinion against this. 

* A radio with a single option, to me, is obviously not interactive
* It might be confusing if people are used it seeing it there for it not to be there sometimes
* Adds a lot of extra logic for a low pay off (IMO)

Happy to go with group decision though.

**Comment by AnnCorp** [comment]
We at ONS raised this initially but I think we've now agreed to live with it as-is unless we get external complaints, given all the other work we have. So am now thinking we could close this or at least put it on the back burner? Could be something we cover in usability testing which am aiming for our user researcher to take forward.

**Comment by brockfanning** [comment]
Sounds good to me, I'm happy to close this for now, and re-open if it becomes a common request.
