### ISSUE TITLE
units options disappearing

### ISSUE THREAD

**Issue by EmmaWoodONS** [open-sdg/open-sdg#1371]
**Please complete the following information**
Data repository URL:  github.com/ONSdigital/sdg-data
Data or metadata issue: Data
Input format: CSV

**Describe the bug**
When I first go to [15.2.1](https://sdgdata.gov.uk/15-2-1/), the first series (woodland area net change) has two available units. If I change the series to one with only a single units option (e.g. series 2), but then go back to woodland area net change, I don't get any units options.

However, if the second series I select also has two units options (e.g. series 5), then go back to the first series, my units options display correctly.

**Additional context**

**Comment by brockfanning** [comment]
This was fixed by #1373 so I'll go ahead and close it.
