### ISSUE TITLE
Translating Year in the table

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1372]
@MoBosse 
I saw you have translated Year into Jahr in your sdg-indikatoren.de
I found the data.yml in your translation repo and also created a data.yml im my translations folder [here](https://github.com/WohnungNDS/IM_Data/tree/develop/translations/de)

Do I have to change anything else to have Jahr instead of Year in my tabels?

[data repo](https://github.com/WohnungNDS/IM_Data)
[site repo](https://github.com/WohnungNDS/IM_Site)

[https://wohnungnds.github.io/IM_Site/](https://wohnungnds.github.io/IM_Site/)

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin 

I added a [custom.js](https://github.com/WohnungNDS/IM_Site/blob/develop/assets/js/custom.js) in my site repo with the code you mentioned above but is ha obviosly no effect on the table.... the yars are still in ascending order

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS apologies, you will need to uncomment these lines in your site config:

https://github.com/WohnungNDS/IM_Site/blob/develop/_config.yml#L247-L248

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin Thank you! It works fine....
@brockfanning @MoBosse 

may be it could be worth to think about to adjust he ordering site-wide?

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS great!

I'll open a separate issue for it

**Comment by LucyGwilliamAdmin** [comment]
Closing as resolved
