### ISSUE TITLE
National indicators list

### ISSUE THREAD

**Issue by ukraine-sdg** [open-sdg/open-sdg#1374]
Hi,

In case the SDG system was nationalised and the list of indicators is not the same as the global one:
is it possible 
(1) to delete the indicators from the site
(2) to change the names of targets?

if yes, could you, please, help how to do this

**Comment by LucyGwilliamAdmin** [comment]
Hi @ukraine-sdg. Yes, both of these things are possible.

For 1) delete the corresponding indicators from the indicator-config folder in the data repository.
For 2) use the translations folder in your data repository: create a folder for each language and then within each of those folders create a file called global_targets.yml. That file should then look like this: https://github.com/open-sdg/sdg-translations/blob/1.6.0-dev/translations/en/global_targets.yml (but with your targets and target names)

Hope this helps!

**Comment by ukraine-sdg** [comment]
I also have an issue with meta data. I could add the indicator, but it adds some text on australia and also does not show my meta data. How can I change the text here https://ukraine-sdg.github.io/site/1/  ?

**Comment by ukraine-sdg** [comment]
how to save the metadata after I have filled then in the indicator page?

**Comment by ukraine-sdg** [comment]
Hi Lucy,

could you, please, give an example how to change the name of an indicator 1.1.1 in the config form? Which text chould I write in the site_config.yml file to change the name of 1.1.1 and the name of the chart for 1.1.1?

or, alternatively, 
where is the yml file for the name of the indicator 1.1.1 located? and which text should I change in the file?

**Comment by ukraine-sdg** [comment]
Dear Lucy,

I tries tp change the names of the indicators and charts in 2 ways. 

(1) I wrote in the file "1-1-1.yml" in  the indicator-config folder:
  graph_title: my graph_title
  indicator_name: my indicator name 
  indicator_number: '1.1.1'

(2) I created the list of the nationalised indicators in the file  "translations/en/global_indicators.yml" 
and wrote in the file "1-1-1.yml" in  the indicator-config folder:
  graph_title: global_indicators.1-1-1-title
  indicator_name: global_indicators.1-1-1-title
  indicator_number: '1.1.1'

In both cases I got my names of the indicators of the site correctly, but both data and graph dissapeared from the site
(see example: here I created 1-1-1.yml and 1-1-2.yml in the config folder  - https://ukraine-sdg.github.io/site/1/)

Could you, please, help to fix it

**Comment by WohnungNDS** [comment]
Hi @ukraine-sdg 
I think you have to change this line: 
https://github.com/ukraine-sdg/data/blob/cb0c78e40870b1aa24dbeeee228637f1a6f06ea5/indicator-config/1-1-1.yml#L29
reporting_status: notstarted
to 
reporting_status: complete

**Comment by ukraine-sdg** [comment]
Thanks a lot! 
It worked for 1.1.1, which is available in global indicators list, 
But, unfortunately, it did not work for 1.1.2, which is not available in the list of global indicators.
could you also, please, take a look at 1.1.2?

**Comment by WohnungNDS** [comment]
https://github.com/ukraine-sdg/data/blob/cb0c78e40870b1aa24dbeeee228637f1a6f06ea5/indicator-config/1-1-2.yml#L29

also change this line tofrom nitstarted to complete

**Comment by ukraine-sdg** [comment]
ah, yes! it works!

**Comment by ukraine-sdg** [comment]
Lucy, could you, please, help to add Ukrainian.
I have already adited all the translations on Weblate.

Then I tried to add Ukrainian in config_data.yml in the way which is written in the tutorial. I tried to add "uk" then "ua", but both times it failed (All checks have failed).

Could you, please write how can I add Ukrainian, which steps should I do

**Comment by LucyGwilliamAdmin** [comment]
@ukraine-sdg I'm closing this one as I've answered latest question here@ https://github.com/open-sdg/open-sdg/discussions/1437 and your original query has been resolved.
