### ISSUE TITLE
Using superscript in the disaggregrations

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1392]
**Why do you need this feature?**

In my data often footnotes describe something that's important for the understanding of the data. Accidentliy I have noticed (copy and paste from my old excel files) superscript characters are correctly shown e.g. in the graph title as you can see [here](https://wohnungnds.github.io/IM_Site/7-1-1/):

![image](https://user-images.githubusercontent.com/67795376/139065692-a4081688-9728-4075-bf3e-85b4d1331b29.png)

I wonder if I can use this in the disaggregation (which means also in the CSV-file) as well? Till today I thought this won't work but adding as superscript "2" (copied from the site) works fine in the github-data-view:

in Atom demo_indicator.csv
![image](https://user-images.githubusercontent.com/67795376/139066244-c57020a8-9d76-4a46-8bf8-7cf33bfde0a9.png)

in github
![image](https://user-images.githubusercontent.com/67795376/139066409-3e9af6df-7907-454b-bf80-162cfac37d26.png)

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS closing this but have added your final question about unintended consequences as a discussion: https://github.com/open-sdg/open-sdg/discussions/1438
