### ISSUE TITLE
Dynamically change footer fields per series

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1395]
User story:
I need the footnote area to reflect the source, units, and geographical area, of the data selected on the 'disaggregation controls', only
So that references are not made to data not displayed

There are currently four footer fields on Open SDG:

- Source
- Geographical Area
- Unit of measurement
- Footnote

None of this fields change dynamically when the series shown is changed but often there is a difference, which can lead to issues such as:
- countries will put info for all series in the fields which can lead to users not knowing which series they belong to.
- important information wont be shown

Unit of Measurement and Footnote map to SDMX series level attributes. Units is also changed dynamically else where: y-axis and chart tooltips. However footnote is also static.

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin https://trello.com/c/HmPPja66/189-dynamic-footnote-area

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner despite this being part of a larger user story I think this particular issue could focus on the Units aspect as think would need two diff methods i.e. for Units can change footer to match name of toggle item chosen, but I think for the other two will need to use the same approach as we do for other units/series-specific fields (as described [here](https://open-sdg.readthedocs.io/en/latest/indicator-configuration/#note-about-unit-specific-and-series-specific-settings) i.e.:

```
sources:
  - unit: Percent
    source: ONS
  - unit: Number
    source: World Bank
```

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin makes sense to me. Upto you / Ann if we deal with all of it now or deal with units in this ticket and then the rest at a later date.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin In terms of an estimate, I would assign this one about 10 hours.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I overestimated this - it was simpler than expected.
