### ISSUE TITLE
jekyll 3.8.4 | Error:  undefined method `keys' for nil:NilClass

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#1422]
**Please complete the following information**
[Site repository URL](https://github.com/WohnungNDS/IM_Site)
[Data repository URL](https://github.com/WohnungNDS/IM_Data)
**Describe the bug**

Remote Theme: Using theme brockfanning/open-sdg
jekyll 3.8.4 | Error:  undefined method `keys' for nil:NilClass
Error: Process completed with exit code 1.

 I have changed this [file](https://github.com/WohnungNDS/IM_Site/blob/develop/_pages/notes.md): 
I only added some lines. An since Yesterday eneving i get this Error message 

Remote Theme: Using theme brockfanning/open-sdg
jekyll 3.8.4 | Error:  undefined method `keys' for nil:NilClass
Error: Process completed with exit code 1.

I tried to use the files from before making this changes with the same result
i tried to change my remote_theme from 

`remote_theme: brockfanning/open-sdg@map-disaggregation-select`

to

`remote_theme: open-sdg/open-sdg@1.5.0`

But I still get this Error message.....

Any ideas @brockfanning @MoBosse @LucyGwilliamAdmin

**Comment by LucyGwilliamAdmin** [comment]
@WohnungNDS I'm not too sure what's going on here - what happens if you return everything to like how it was before you started getting the error?

**Comment by WohnungNDS** [comment]
This is what ihave tried first.... but the error stays the same....

In my despair I downloaded the latest running version [(6b22952cd5)](https://github.com/WohnungNDS/IM_Site/tree/6b22952cd5f461f8f062880fac8870bd20976687) as a zip file and repalced my local files.... but still getting this error message...

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin the [data repo](https://github.com/WohnungNDS/IM_Data) works fine....

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning any ideas on this?

**Comment by WohnungNDS** [comment]
I am not sure, but may be the only way to get it running again is forking the open-sdg-site-starter repo into a new repo.....
an add file per file from the old one to see where the error comes from....

What do you think @LucyGwilliamAdmin @brockfanning Is it worth a try?

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin @brockfanning @MoBosse 
It works....

The short story:
I created a new repo from the site-starter and point to my old data repo. 
I got the same Error message, so I looked into my data rep what always deplyed wothout errors.
After a couple of hours I found that a ":" in one of my translations causes the error....
Or just using try an error I deleteted the : in this [line 24](https://github.com/WohnungNDS/IM_Data/commit/28ef2c8cd25074319710d1be88e03ee894dbb7f1)
And now it works again....

But I think it will take two days to revover all the try an error changes I made on my site repo :-(

**Comment by brockfanning** [comment]
@WohnungNDS You can put ":" into yaml files, but the value has to be in quotes. For example this is valid:

```
foo: "hello: world"
```

But this is not valid:

```
foo: hello: world
```

**Comment by LucyGwilliamAdmin** [comment]
Closing as issue has been resolved
