### ISSUE TITLE
Make order of data tabs configurable

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1435]
### Discussed in https://github.com/open-sdg/open-sdg/discussions/1433

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** November  9, 2021</sup>
Some countries want to change the order of data tabs (e.g. chart, table, map). This could be configurable just side-wide or both site-wide and per indicator</div>

**Comment by LucyGwilliamAdmin** [comment]
Relates back to this request: https://github.com/open-sdg/open-sdg/issues/1280

**Comment by WohnungNDS** [comment]
@LucyGwilliamAdmin I would prefer to have it per indicator because in some indicators I have no map . If it is configured side-wide yoyu hafe to check before if chart, map or table exit....

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin The associated PR is ready for review. It was a bit involved, about 7 hours.
