### ISSUE TITLE
data_start_values causing error when used on "Series"

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1477]
**Please complete the following information**
Data repository URL: [https://github.com/MoBosse/testData](https://github.com/MoBosse/testData)
Data or metadata issue: data
Input format: csv

**Describe the bug**
data_start_values seem not to work in combination with Series_toggle and a combination of series with and without disaggregation.

I have the following situation: 

- Two Series (A and B). 
- A has no disaggregation but only a total series
- B has no total series but two disaggregations (x & y)
- A has the unit %
- B has the unit number
See data [here](https://github.com/MoBosse/testData/blob/develop/data/indicator_1-5-2.csv)

If I do not add any start values, A is selected by default. When I switch to B, the row "x" is selected. 
Now I want "y" to also be selected when I switch to B, so I added the following

```
 data_start_values: 
  - series: B
    field: disagg
    value: x
  - series: B
    field: disagg
    value: y
```

See meta [here](https://github.com/MoBosse/testData/blob/develop/meta/1-5-2.md)

With the start values the chart fails to load. See result [here](https://mobosse.github.io/testSite/1-5-2/)

I have tried many variations of the start values, but nothing seems to work.
I also tried with the same unit for all series but the result is more or less the same. See [here](https://mobosse.github.io/testSite/1-5-3/)

**Comment by brockfanning** [comment]
@MoBosse Can you give #1479 a try and see if fixes the bug?

**Comment by MoBosse** [comment]
@brockfanning Tested on the indicators metioned above and on [this one](https://sdgtestenvironment.github.io/sdg-indicators/11-1-1/). Everything is working as expected!

**Comment by MoBosse** [comment]
@brockfanning I just came across another bug that might be related to this one and could be fixed as well:

When I try to set min/max values for only one of the Series [here](https://mobosse.github.io/testSite/1-5-3/), they appear for both series.

This is in the [meta document](https://github.com/MoBosse/testData/blob/develop/meta/1-5-3.md):

> graph_limits:
  - series: A
    minimum: 0
    maximum: 10

**Comment by MoBosse** [comment]
...works for titles amd precision though.

**Comment by brockfanning** [comment]
Ok, makes sense. I'm guessing that the code that runs when the series changes does not reset the chart min/max. Do you mind creating an issue for that one too?
