### ISSUE TITLE
reporting status addidtional goal is shown

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1482]
To avoid confusion: I have to move my migration report from WohnungNDS (private account) to another official account christoph-lsn.... So It's me ;-)

[Site repo](https://github.com/christoph-LSN/MT_Site)
[Data repo](https://github.com/christoph-LSN/IM_Data)

**Describe the bug**

I have 8 goals. As you can see here in the [reorting status](https://christoph-lsn.github.io/MT_Site/reporting-status/) under 8 is another goal shown with a broken image which is liked to the reporting status again

![image](https://user-images.githubusercontent.com/94443931/142631057-e862c96e-777f-4e51-94dc-dc6a63ba7f64.png)

any ideas?

**Comment by brockfanning** [comment]
@christoph-LSN The first thing to I would check is if any indicators have a different goal in their metadata. For example it looks like indicator 2.1.3 has a metadata field of "sdg_goal" which is set to 11. I'm not sure if that's the cause but I would try fixing that first.

**Comment by christoph-LSN** [comment]
@brockfanning Great! Now it works right! How do you find this?

**Comment by brockfanning** [comment]
@christoph-LSN I cloned your repo locally so that I could search using a code editor (I used Visual Studio Code). I searched the meta folder for "sdg_goal" and scanned through the results.

**Comment by christoph-LSN** [comment]
@brockfanning great idea! searching a complete folder is an approach i haven't thought about until now ;-)  I am sure atom will have this option...
