### ISSUE TITLE
graph_limits not working in combination with series_toggle

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1483]
**Please complete the following information**
Data repository URL:  [https://github.com/MoBosse/testData](https://github.com/MoBosse/testData)
Data or metadata issue: meta
Input format: csv

**Describe the bug**
For indicators with multiple Series (and the config setting series_toggle = true) it is not possible to set graph_limits specified to the Series.

Assuming there are series A and B, the following configuration would set the limits for both A and B, although it should be valid for A only. 

> graph_limits:
>       - series: A
>         minimum: 0
>         maximum: 10

Adding limits for B has no effect.

**Comment by brockfanning** [comment]
@MoBosse #1485 should hopefully fix this, if you are able to try it out.

**Comment by MoBosse** [comment]
@brockfanning Perfect! Works as expected.
