### ISSUE TITLE
Update data starter to use global metadata

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1488]
### Discussed in https://github.com/open-sdg/open-sdg/discussions/1442

<div type='discussions-op-text'>

<sup>Originally posted by **brockfanning** June 17, 2019</sup>
Right now the contents of the "Global metadata" tab are fields that must be in the data repository's "meta" files. But this is all official UN metadata and does not need to be custom or controlled. Is there some way that we can leverage UN (and/or other) sources to populate the "Global metadata" tab?</div>

**Comment by brockfanning** [comment]
Once the UN metadata database is complete, we can update the data starter so that it pulls metadata from there for the "Global" tab.

**Comment by LucyGwilliamAdmin** [comment]
We will only pull in existing fields plus related indicators but will comment out others so countries can choose if they want to pull in others
