### ISSUE TITLE
Search symbol not showing in IE

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#152]
![image](https://user-images.githubusercontent.com/43404358/56033209-eb9dd380-5d1b-11e9-90c2-5a2f4082b908.png)

**Comment by Norric1Admin** [comment]
It would also be good to get the 'Goals' option back in the menu bar (see [UK site](https://sustainabledevelopment-uk.github.io/)) for accessibility reasons.

**Comment by brockfanning** [comment]
@Norric1Admin @LucyGwilliamAdmin I'm not able to recreate the problem with 'Goals' not showing. It appears to be there for both the staging and production UK sites, as far as I can tell. Though it's clearly missing in the screenshot above. Maybe you already fixed it?

I can, however, recreate the issue with the search symbol being missing in IE. Unless you object I'd propose we rename this issue to just be about the search symbol.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning the screenshot above is from the Kyrgyzstan platform - we just think it might be better for the starter sites to have the 'Goals' page.

Happy to have two separate issues

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Gotcha. Adding it to the starter sites sounds like a good idea to me, and that change can be made as a pull-request in [this repository](https://github.com/open-sdg/open-sdg-site-starter). I've created an [issue](https://github.com/open-sdg/open-sdg-site-starter/issues/29) for it over there. I'll go ahead and rename this issue to focus on the IE problem.

**Comment by brockfanning** [comment]
This also affects the global icon by the language switcher. I get the impression that FontAwesome doesn't really support IE anymore: https://github.com/FortAwesome/Font-Awesome/issues/8825

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning on that issue they managed to fix the problem:

> I tried the solutions here ... and now I found out why it doesn't show because
you didn't include fontawesome-webfont.eot in your /fonts which it was recommended font for IE11

**Comment by LucyGwilliamAdmin** [comment]
^ that might not be the solution, might just be that we need a newer version of font-awesome.

That being said, I've just been on IE11 on my personal laptop and the search icon was displaying on that so will check on my work laptop when I can to see if it's also fixed on that

**Comment by LucyGwilliamAdmin** [comment]
I have checked on my work laptop (which also uses IE11) and there is still an issue. I have come across [this post](https://stackoverflow.com/questions/26894319/icon-fonts-not-loading-in-ie11) which says: 

'Font downloads are disabled in IE, under Internet Options / Security / Custom Level / Font Downloads enable /disable. They might be disabled by your network admin, in which case you would not be able to see nor change this setting.'

Unfortunately, these security settings are disabled for us so I cannot try this.

@brockfanning you said you were also having the problem with the search icon not showing - could you check if you have font downloads enabled please?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning after you tested, looks like this is only an issue on locked down computers so looks like we can close this issue.
