### ISSUE TITLE
Disaggregations not displaying in IE

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/open-sdg#153]
Since moving to open-sdg@0.5.0, chart disaggregations do not display in Internet Explorer. I thought this was a problem specific to the UK, but it seems that the [open-sdg-site-starter](https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-site-starter/) has a similar bug.

The console shows that `includes` is not recognised in IE (`IndexOf` is recommended) but the problem goes deeper as errors such as `i not recognised` and various references to JavaScript files also occur. I did try to [polyfill](https://github.com/ONSdigital/sdg-indicators/commit/f576fffa6696337dafae88884bfbb3758ea996f1) the code and Savvas added a [‘For’ loop](https://github.com/ONSdigital/sdg-indicators/commit/84992a327a0618078003c81f15cf44c622854449) in `indicator.html`. We are still having problems however.

**Comment by brockfanning** [comment]
@SavvasStephanides @Norric1Admin I just put up a PR that fixes this problem with the disaggregation filters not displaying in IE: #154

**Comment by SavvasStephanides** [comment]
Is it safe to close this issue since #154 has been approved and merged?

**Comment by Norric1Admin** [comment]
Testing this out - will close shortly.
