### ISSUE TITLE
Text overflowing boxes in metadata

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1532]
Currently on the live site the text for some metadata is not wrapping properly and as such is overflowing out of the text box. This can be seen on 4.4.1 (https://sdgdata.gov.uk/4-4-1/) and the sources tab of 4.1.1 (https://sdgdata.gov.uk/4-1-1/)

For more info, the issue occurs when an email address is longer than the source column allows. Unlike urls, it's not possible to shorten this text by using a hyperlink

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath did you resolve this? Often when that happens it's due to text that can't be broken across two lines e.g. links

**Comment by otis-bath** [comment]
@LucyGwilliamAdmin yes all sorted now, was exactly that - the link wasn't set up properly

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath I just had a quick look at 4.1.1 on the feature branch - is the fix to add spaces to the email address?

If so not sure, if that's the best way as causing unnecessary splits in email address - so may actually be worth raising here?

**Comment by otis-bath** [comment]
@LucyGwilliamAdmin for tomorrow's push to live 4.4.1 is fixed and 4.1.1 is now just a single space (as opposed to all the spaces or a new line break) - I will however reopen this as now 4.1.1 is a tad bunched http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-4-4-1/4-1-1/

**Comment by LucyGwilliamAdmin** [comment]
Short-term options include:

- give class to contact details row and make that field wrap anywhere
- give class to contact details row and make that field wrap on '@' - don't know if possible yet

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @otis-bath I haven't found any indication that wrapping on '@' will be possible. However this is an interesting solution: https://stackoverflow.com/a/23777535

That approach would not be an Open SDG solution - but instead would be something countries would need to do: add `&#8203;` where you would like it to wrap. You'd just need to confirm that the email could still be correctly copy/pasted into an email client.

**Comment by otis-bath** [comment]
@brockfanning have tried this on the feature branch http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-text-wrap-test/4-1-1/ and it does work well, the email address can be copied properly unlike as with the space

**Comment by LucyGwilliamAdmin** [comment]
Removed from 1.8.0 as workaround mentioned above is suffice for now

**Comment by phillipgardiner** [comment]
Also see discussion https://github.com/open-sdg/open-sdg/discussions/1551 for background info
