### ISSUE TITLE
The initialize master action for both site and data (use the template step) has issues

### ISSUE THREAD

**Issue by MeghaStha** [open-sdg/open-sdg#1533]
**Please complete the following information** 
Site repository URL: (https://github.com/MeghaStha/AuburnAldataRepo); https://github.com/MeghaStha/AuburnSite
Open SDG version: [e.g. 1.0.0]

**Describe the bug**
I used the template for open-sdg-data-starter and open-sdg-site-starter to create my own repositories for site and data. There have been issues while doing so. The initializer master actions is showing issues and the page links is up but has issues. 

**To Reproduce**
1. Go to open-sdg/open-sdg-data-starter
2. Click on Use this template
3. Click on Actions

**Expected behavior**
The initialize masters branch

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, safari

**Comment by brockfanning** [comment]
@MeghaStha Let's try something to see if we can get it working. Can you edit this line? https://github.com/MeghaStha/AuburnSite/blob/develop/_data/site_config.yml#L209

Instead of...

```
remote_data_prefix: 'https://open-sdg.org/open-sdg-data-starter'
```

Try changing it to:

```
remote_data_prefix: https://meghastha.github.io/AuburnAldataRepo/
```

You can safely ignore the errors related to the "master" branch for now.

**Comment by MeghaStha** [comment]
It fixed the issue. Thank you.
