### ISSUE TITLE
Tab ordering bug

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1547]
The feature introduced in 1.7.0 allowed the configuration of the chart, map and table tabs. When testing I found that dropping a tab would result in this appearance of a blank tab with no functionality however as the feature branch below shows, any rearrangement of the tab ordering causes this extra tab with unusual functionality to appear. It will maintain the settings of the previous tab when clicked on leading to unwanted behaviour i.e. map with sidebar if configured 

http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-indicator-tab-order/3-a-1/

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath did you find solution for this after?

**Comment by otis-bath** [comment]
@LucyGwilliamAdmin yes all sorted, the default is 4 tabs when overriding so just needed to hide the final one
