### ISSUE TITLE
Map needs build failure if data is not correct (as opposed to loading wheel)

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1566]
https://sdgdata.gov.uk/10-3-1/

Currently on the live site and all feature branches on all browsers the map on 10-3-1 is not loading. Instead a loading screen is presented that never ends. @brockfanning @LucyGwilliamAdmin do you know why this might be occuring?
![image](https://user-images.githubusercontent.com/90769108/157912989-ec26867f-5e88-4587-b98d-eeceec10dd55.png)

**Comment by brockfanning** [comment]
@otis-bath I'm not sure if it's supposed to be added dynamically by some code elsewhere, but I don't believe the GeoCode column is populated in the [data for 10.3.1](https://github.com/ONSdigital/sdg-data/blob/develop/data/indicator_10-3-1.csv).

If that's the reason, we probably need better behavior than the spinning wheel - like a message that says "no data is available" or something like that.

**Comment by otis-bath** [comment]
Okay great, our data team are going to look at populating this. I will check there are no other instances of this occuring on the platform and we can discuss how we want it to look tomorrow

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @otis-bath I think actually instead of displaying something different on the platform, it should be prevented earlier on - maybe a fail in the data build?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning did we end up adding something into 1.8.0 that would make the build fail in this scenario
