### ISSUE TITLE
Data repo no longer updating

### ISSUE THREAD

**Issue by JulienSTC** [open-sdg/open-sdg#1587]
**Please complete the following information**
Data repository URL: https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic
Data or metadata issue: Issue with the build
Input format: N/A

**Describe the bug**
As of 2 weeks ago we are no longer able to update the data repo. We have followed the instructions provided in this document: https://open-sdg.org/blog/2022-01-11-fix-for-github-data-builds/ but the update failed as some of the checks fail (see: https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/pull/66). Any help would be appreciated, thanks! 

**Additional context**
This occurs in our national framework data hub which is from an older build but also occur with our platform for the GIF currently in development (https://github.com/sdg-data-canada-odd-donnees/sdg-data-donnees-odd/actions/runs/2059609570).

**Comment by brockfanning** [comment]
@JulienSTC It appears that down the chain of dependencies there is a new problem of the "typer" package being incompatible with the latest version of "click". The open source community tends to solve these kinds of issues pretty quickly, but there is a quick-fix of adding "click==8.0" to your requirements.txt file.

If you'd like to follow the dependency issue, there's some discussion of it here: https://github.com/tiangolo/typer/issues/377

**Comment by JulienSTC** [comment]
> @JulienSTC It appears that down the chain of dependencies there is a new problem of the "typer" package being incompatible with the latest version of "click". The open source community tends to solve these kinds of issues pretty quickly, but there is a quick-fix of adding "click==8.0" to your requirements.txt file.
> 
> If you'd like to follow the dependency issue, there's some discussion of it here: [tiangolo/typer#377](https://github.com/tiangolo/typer/issues/377)

Thank you, Brock. The recommended fix seems to be working perfectly for now. We will follow the discussion on the dependency issue.

**Comment by brockfanning** [comment]
No problem, glad it's working. I think we should leave this open until the root issue is resolved.

**Comment by tiangolo** [comment]
I just released Typer `0.4.1` that should handle it. :rocket: :nerd_face:

**Comment by brockfanning** [comment]
Thanks for letting us know @tiangolo!

@JulienSTC You should be able to remove that "click==8.0" now.

**Comment by LucyGwilliamAdmin** [comment]
@JulienSTC is the data updating without "click==8.0"?

Just checking so know if we can close

**Comment by JulienSTC** [comment]
> @JulienSTC is the data updating without "click==8.0"?
> 
> Just checking so know if we can close

Everything is working still after removing the "click==8.0". Thanks everyone!
