### ISSUE TITLE
Map tab not using correct series title

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1600]
**Describe the bug**
When on a page with a map e.g. [3.3.3](https://sdgdata.gov.uk/3-3-3/) if you change the series on the chart tab and then click to the map tab the title will stay as whatever series is selected as opposed to changing back to the correct default based on what data is available. 

See the image below, I selected Percentage of total cases as the series and then navigated to the map tab, as you can see the data for England reads 1480. 
![image](https://user-images.githubusercontent.com/90769108/165317840-e0a14eb3-fcb1-4061-b01b-cc37439e29ce.png)

**Comment by brockfanning** [comment]
This should be a relatively simple fix to remove the "chart-title" class, which is how that element is being updated, and then a small style adjustment to make sure it looks the same. 1-2 hours at the most.
