### ISSUE TITLE
7-1-1 Not showing full graph

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1613]
7-1-1 https://sdgdata.gov.uk/7-1-1/

Since the value is either 100% or so close it makes no difference and we have the y-axis limits set to 0-100 the graph is not showing completely with each data point cut off at the top. 

If we add it to the y-axis percentage exception list it shows the full point as you can see [here](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-7-1-1-exclusion/7-1-1/) - is there a way we can build this into Open SDG

**Comment by brockfanning** [comment]
@otis-bath Can you describe what your y-axis percentage exception list is, and how it works?

**Comment by otis-bath** [comment]
> @otis-bath Can you describe what your y-axis percentage exception list is, and how it works?

Sure, in the [data build](https://github.com/ONSdigital/sdg-data/blob/develop/scripts/build_data.py) it is a list of indicators with 'Percentage (%)' as their units that can be excluded from having their y-axis limits set to 0-100. It is based upon [this code](https://github.com/ONSdigital/sdg-data/blob/2b40606a2df74fb2a73d6d5345144f15692797de/scripts/build_data.py#L50)

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath when you have chance, could you create feature branch with 7.1.1 in the exception list so we can demo the difference please?
