### ISSUE TITLE
Hide search when JS is off

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1615]
We need to hide search when JS is off since it's impossible to get it to work. However, we need to adjust the interface (particularly on mobile) so you are not just left with a big white gap where the search bar would have been.

### Discussed in https://github.com/open-sdg/open-sdg/discussions/1611

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** May 16, 2022</sup>
When JS if off, searching for any terms results in continuous loading wheel.

**To discuss: can we/should we display an error message instead in this instance? or should we completely hide the search?**

Search results when JS is off:
![image](https://user-images.githubusercontent.com/43404358/168619676-8d184f29-76ac-4956-bba1-47e4674453d8.png)
</div>

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @otis-bath @phillipgardiner I've got a PR that addresses this and also #1617. I did not devote any time to adjusting the design of the no-javascript platform -- I only hid the search bar and contrast toggle. I think that adjusting the design of the no-javascript platform will be significantly harder, and may also raise some design questions. Let's take a look at a feature-branch and see how we like it. The PR is: #1618
