### ISSUE TITLE
Let users know more data is available in download when JS is off

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1616]
When JS is off, only headline data shows. We should let users know that more data is available in download.

Need to agree exact text

### Discussed in https://github.com/open-sdg/open-sdg/discussions/1609

<div type='discussions-op-text'>

<sup>Originally posted by **LucyGwilliamAdmin** May 16, 2022</sup>
When JS is off, users have no control over viewing disaggregated data online - instead they need to download the source CSV.

**To discuss: should we/is it possible to display all data when JS is off? Is MVP to let users know there is disaggregated data available in data download?**

Indicator page when JS is on:
<img src="https://user-images.githubusercontent.com/43404358/168613270-9221ef74-c5a4-4422-94b4-07f68ee5ceb3.png" height="75%" width="75%">

Indicator page when JS is off:
<img src="https://user-images.githubusercontent.com/43404358/168613516-dfee8762-d244-4d3a-bdbe-6606d1ad0313.png" height="75%" width="75%">
</div>

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @brockfanning @otis-bath this text was suggested in discussion: 

'Additional disaggregations are available in data download'

Any further thoughts on this?

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner @otis-bath @brockfanning this is how pages without headline data look with js off:

![image](https://user-images.githubusercontent.com/43404358/170043341-bf498729-f60f-48d8-a0b6-802f6819c70d.png)

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning @otis-bath Lucys suggestions above seem sensible and I would agree that. (e.g. Do we hide 'Download headline data' button, change 'Headline data' to 'No headline data available'. And add below 'Download source data for disaggregations)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @otis-bath @phillipgardiner Do I have this all correct?

When javascript is off:

1. For all indicators with data, add "Download source CSV for disaggregations"
2. Only for indicators without headline data:
    1. Hide "Download headline data"
    2. Change "Headline data" to "No headline data available"
