### ISSUE TITLE
Add breadcrumb navigation to all non goal and indicator pages

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1625]
Breadcrumb navigation is missing from all non goal and indicator pages. Add breadcrumbs following the GDS standard to the following pages:

- Goals (https://sdgdata.gov.uk/goals/)
- Reporting status (https://sdgdata.gov.uk/reporting-status/
- About (https://sdgdata.gov.uk/about/
- Publications (https://sdgdata.gov.uk/publications/
- FAQ (https://sdgdata.gov.uk/faq/
- Updates (https://sdgdata.gov.uk/updates/)

GDS standard: https://design-system.service.gov.uk/components/breadcrumbs/

**Comment by brockfanning** [comment]
@phillipgardiner All of these pages would just have "Home" as the sole breadcrumb. Just confirming that that is what you're expecting.

**Comment by phillipgardiner** [comment]
@brockfanning I was of the understanding as with our other pages the breadcrumb would be (Home > current page), see example: https://sdgdata.gov.uk/1/

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @brockfanning Is this a UK only issue? or would this be done as part of Open SDG?

**Comment by brockfanning** [comment]
@phillipgardiner Sorry, I lost track of this one. Yes I think this would make sense to be done in Open SDG, to make pages consistent with goals, like you point out. @LucyGwilliamAdmin Is this something to try to get into 2.0.0?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning it would be pretty straight foward to add, right?
