### ISSUE TITLE
Add colons (:) between the goals number and title 

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1630]
![image](https://user-images.githubusercontent.com/60919820/169795555-0aad8ec9-4edf-4e64-9d4b-51affb6842aa.png)

Recommendation: Add a colon between the goal number and the goal title on the publications page (https://sdgdata.gov.uk/publications/)

**Comment by brockfanning** [comment]
@phillipgardiner This is another UK-specific content issue.

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin @otis-bath @brockfanning Another to potentially be moved to UK only board?

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin as this is a UK only issue, I have captured this on the UK backlog and am closing this ticket
