### ISSUE TITLE
Remove indent on paragraphs (Mobile)

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1632]
![image](https://user-images.githubusercontent.com/60919820/169797304-ce8849fa-0b95-4517-8454-c032e632c4a4.png)

Recommendation: On mobile on the privacy notice page (https://sdgdata.gov.uk/privacy-notice/). Each new paragraph appears slightly indented. Please remove this indent so the paragraph begins align at the left hand side of the page.

**Comment by phillipgardiner** [comment]
@brockfanning the screenshot was taken on an iphone 11.

**Comment by brockfanning** [comment]
@phillipgardiner Thanks - I don't have an iPhone to test, but I've put up a PR that explicitly turns off the "text-indent" CSS property on paragraphs. It's just a shot in the dark that maybe the iPhone is applying some text-indent to those paragraphs for some reason.
