### ISSUE TITLE
Pie chart

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#164]
Is it possible to include pie chart and/or stacked bar visualizations? These would need to fundamentally involve disaggregation, and would only work with percentage-based datasets. But it should be possible, right?

**Comment by LucyGwilliamAdmin** [comment]
So could these only be used for indicators that have one disaggregation?

**Comment by LucyGwilliamAdmin** [comment]
Maybe something like this:
![Uploading piechart1.png…]()
![Uploading piechart2.png…]()

Not only does the dataset have to be percentage-based but it has to be the case where the disaggregation is split e.g. not like [1.2.1](https://sustainabledevelopment-uk.github.io/1-2-1/)

**Comment by brockfanning** [comment]
Linking to similar discussion: https://github.com/dawncomer/open-sdg-site-starter/issues/16

**Comment by brockfanning** [comment]
To carry over an idea from the other thread: there could be a metadata field `stacked_disaggregation` which could be used like:
```
stacked_disaggregation: Gender
```
The idea is that this would communicate to the platform that this disaggregation should get "stacked" whereas all other disaggregations are displayed separately. So for a bar chart using the example above, all "Gender" disaggregations would be stacked in one bar, whereas all other disaggregations ("Age", "Region", etc.) would be in their own bars. I guess it would make sense to start with all of the "Gender" disaggregations pre-selected (which can already be done with `data_start_values`).

It's kind of a mind-bender to think about how it would all fit together. But that might be a simple place to start.

**Comment by brockfanning** [comment]
It would be nice to get this into 1.0.0, since it may carry with it some structural changes.

**Comment by brockfanning** [comment]
Stacked bars can be tested in #497, though it depends on another PR in sdg-build.

**Comment by brockfanning** [comment]
We have implemented an approach to stack bar charts, so I'm going to change this issue to just pie charts.
