### ISSUE TITLE
Unable to change graph color set 

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1645]
I am currently unable to change the chart color set using the configuration options outlined in the docs? Are these now redundant with the updgrade to 2.0.0 as currently I cannot change the colours from the default. I have attempted using different options from the 'graph_color_set' options including using custom hexidecimal colourset (currently active on FB below). 
On [this FB](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-open-sdg-functionality/1-2-1/) I have set four hexidecimal codes in the site configuration (pinks and oranges) that currently do not show. 
The [site configuration](https://github.com/ONSdigital/sdg-indicators/blob/573f9c95c00b5b503d692aa2ac581e3b92a3c101/_config.yml#L181)

**Comment by brockfanning** [comment]
@otis-bath I'm able to get this to work locally. Since your FB is on 1.8.0, I'm wondering if maybe this was broken in 1.8.0 but somehow fixed in 2.0.0-dev? Any chance you could try a new 2.0.0-dev FB to test that theory?

**Comment by brockfanning** [comment]
@otis-bath Actually scratch that - I think I see the issue - there is an errant quote after "graph_color_list" here: https://github.com/ONSdigital/sdg-indicators/blob/573f9c95c00b5b503d692aa2ac581e3b92a3c101/_config.yml#L182
