### ISSUE TITLE
Issue with the footer_fields functionality - fields not showing

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1651]
**Please complete the following information** 
Open SDG version: 1.8.0

**Describe the bug**
Issue with the footer_fields functionality - display: none seems to be being applied to field label and field value

**To Reproduce**
1. Go to 'http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-footer-fields-test/1-1-1/'
2. Scroll down to chart footer
4. See that extra footer field 'Next indicator update' and corresponding value is not showing
5. View area in inspect console and see that elements are there but 'display: none' is being applied

**Expected behavior**
Extra footer field should be visible in footer section

**Screenshots**
![image](https://user-images.githubusercontent.com/43404358/172630432-aa295bf7-bcdc-445d-a227-702d17b270c0.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @otis-bath  I've just identified this bug - occurs with 1.8.0 and 2.0.0-dev

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Can you link me to the indicator configuration for this indicator?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 
> @LucyGwilliamAdmin Can you link me to the indicator configuration for this indicator?

https://raw.githubusercontent.com/ONSdigital/sdg-data/feature-footer-fields-test/meta/1-1-1.md

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning great, I've added to 2.0.0 project board
