### ISSUE TITLE
decimal seperator and precision do not affect tableTargetLines

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1671]
**Please complete the following information**
Data repository URL: [https://github.com/DnsUpgradeEnvironment/dns-data](https://github.com/DnsUpgradeEnvironment/dns-data)
Data or metadata issue: meta
Input format: csv

**Describe the bug**
The values of target_lines displayed in the table are not affected by the decimal separator and decimal precision.

For me, some [minor overrides](https://github.com/SdgTestEnvironment/sdg-indicators/commit/5896cfd280e30dd561a22767db1cac3feab12d90) worked perfectly to solve this problem, but I'm not sure how to implement it in 2.0.0

**Comment by brockfanning** [comment]
@MoBosse I believe that for 2.0.0 this is the way that would be fixed: https://github.com/open-sdg/open-sdg/pull/1675

Is that something you'd be able to give a try?

**Comment by MoBosse** [comment]
@brockfanning  Saw that @otis-bath has already tested. Thanks for that and sorry for being late. Have now also tested and everything looks good to me.
