### ISSUE TITLE
Unable to download site configuration from Open SDG starter

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1673]
As can be seen here: https://sarah-beasley.github.io/site/config/

Open SDG platform set up using guidance instructions and upon setting the remote data prefix and repository URL in the configuration options on the site, are unable to download the configuration options to become the _site_config.yml file. The button appears however does not prompt a download when clicked.

**Comment by brockfanning** [comment]
Actually I'll leave this open in case anyone else runs into this problem.

This has been fixed in tags 1.8.1 and 2.0.0-beta1.
