### ISSUE TITLE
Target line appearing behind graph elements

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1683]
**Describe the bug**
On a graph when a target line is present the target line appears hidden behind the data points. This makes it hard to see the target line in question.

**Expected behavior**
The target line should appear in front of the data points so as not to be hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/60919820/174039764-7fa6eb0c-5641-431b-a2a3-f56f854bb835.png)

**Additional context**
Note: This may be relevant for the 'series break' line also

**Comment by brockfanning** [comment]
Closing as fixed.
