### ISSUE TITLE
Archived indicators formatting missing elements (2.0.0 upgrade)

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1700]
@brockfanning 
As you can see: http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.0.0-beta1/archived-indicators/

The archived indicators formatting has become distorted with the new release and is missing the labels of what indicator it corresponds to. Do you know why this would be?

**Comment by brockfanning** [comment]
Fixed by https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/137
