### ISSUE TITLE
Site configuration form contrast mode

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1701]
http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.0.0-beta1/config/
@brockfanning 
As you can see on the beta1 FB when you switch the high contrast mode, the text for (Opens in a new tab) on the Go to repository button doesn't show correctly.

**Comment by LucyGwilliamAdmin** [comment]
@otis-bath @brockfanning I was just about to question if this one went in to 2.1.0 after as I vaguely remember something but then looking at the 2.1.0-beta1 feature branch, it hasn't?

http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-2.1.0-beta1/config/

**Comment by LucyGwilliamAdmin** [comment]
If not, any chance we could get it into beta3 tag since so small and technically a bug?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I missed this for beta3 but I have a pull-request up for this.
