### ISSUE TITLE
Clarification and mechanism for renaming metadata fields

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#171]
Right now it's not obvious how to rename a metadata fields. One might expect that changing the "label" in the _prose.yml file would rename the field on the platform. But that's not the case -- the labels on the platform come from sdg-translations. We should figure out a way to make it more obvious and/or easy to change these.

A quick idea might be:
1. Add "translation_key" to every item in the _prose.yml file (in open-sdg-data-starter)
2. Update the metadata.html include to use the translation_key if present.

Just need to figure out a way to make that backwards compatible, since existing sites will not have "translation_key" in their _prose.yml file.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I was just about to send some info to Moldova on how to edit/add metadata fields. I wasn't aware that the labels came from sdg-translations.
Is this the same for [us](https://github.com/ONSdigital/sdg-data/blob/f30b64dfcf8ef15495366fe6e2a7fcebcde5a8ae/_prose.yml)?
Where does the process happen e.g. where is the site told to use the sdg-translation value?
How would this work for countries who don't use one of the current languages? (For example, Moldova are using Romanian as a second language on their site)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Open SDG is hardcoded right now to first check for a "translation key" of `metadata_fields.` plus the field name. So for example, if the field name is `description`, then Open SDG tries to look for a translation key of `metadata_fields.description`. This happens [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/metadata.html#L3). As you can see in the next lines, if it doesn't find a translation key there, it just uses the "label" of the field.

I don't believe this is documented anywhere, which is a problem. Also, I think it's unnecessarily restrictive. We should probably instead have a "translation_key" property in the schema, which Open SDG can use instead. That might be a good thing to do before version 1.0.0.

**Comment by LucyGwilliamAdmin** [comment]
Ah ok, I see how it works now.

So this `translation_key` property would be added in the prose file of open-sdg-data-starter?

Does this mean a "ro" folder would need to be added to sdg-translations so that Moldova could add any Romanian stuff in there?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning should I make a folder for Romanian translations in sdg-translations so that Moldova can add their metadata label translations in there?

Just want to double check if that's what needs to happen before I send any guidance to them?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin In order to have a Romanian version of Open SDG, Moldova will need to perform a full translation of the blank spreadsheet. To get that blank spreadsheet, see the link under "New languages" [here](https://open-sdg.github.io/sdg-translations/translators/). This includes the "metadata_fields" stuff, as well as all the other stuff (such as indicator titles, general terms, etc.)

If they can provide us with the completed spreadsheet, we can "import" that into SDG Translations.

But to be clear - having the translations in SDG Translations is not a requirement. They could place translation files directly in their data repository if they wanted more direct control over them. I could give more detail if they want to go that route.

Also remember that translated goal icons is necessary.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks for the info - I have just sent the spreadsheet to them. The goal icons are actually the one thing they've translated already - see [here](https://statisticamd.github.io/open-sdg-site-starter/ro/)

**Comment by brockfanning** [comment]
Estimate: I think this should be more than just documentation. I think we should do the steps 1 and 2 from the original post. I would estimate about 10 hours.
