### ISSUE TITLE
Tooltip content is overlaid by target lines

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1711]
Data repository URL:  [https://github.com/DnsUpgradeEnvironment/dns-data](https://github.com/DnsUpgradeEnvironment/dns-data)
Data or metadata issue: meta?
Input format: csv

**Describe the bug**
Not a major issue but since there are other tooltip-related issues at the moment: The content of the tooltips are overlaid by the annotation lines:
![grafik](https://user-images.githubusercontent.com/50657629/175480287-2ac59790-83d0-49f1-8a56-2c622fe564b7.png)

It's just a guess, but could it be related to the recently added [drawTime: 'afterDatasetsDraw'](https://github.com/open-sdg/open-sdg/blob/2.1.0-dev/_includes/assets/js/view/chartTypeBase.js#L186) ??

**Additional context**
I have not tested this in a "neutral" environment, so there is a chance that this is caused by some overridden files. If so, please give a short feedback and ignore this issue.

**Comment by christoph-LSN** [comment]
@brockfanning @MoBosse 

I also have a tooltip issue: In 2021 in Statistische Region Braunschweig in the table is shown: 172190 (https://christoph-lsn.github.io/MT_Site/1-2-1/) on the tooltip 92,172

![image](https://user-images.githubusercontent.com/94443931/175485693-40bef69a-89ac-46f2-a822-206e5fc6beed.png)

**Comment by brockfanning** [comment]
@MoBosse According to [the documentation on drawTime](https://www.chartjs.org/chartjs-plugin-annotation/latest/guide/options.html#draw-time) "afterDatasetsDraw" is supposed to still be before tooltips. Also when I test locally, with a blank site the tooltips do appear in front of the annotations.

@christoph-LSN I'm not seeing 92,172 anywhere on the tooltip.

**Comment by brockfanning** [comment]
I'm hoping this was caused by an override, because I wasn't able to replicate it. Please re-open if needed.

**Comment by MoBosse** [comment]
@brockfanning You were right. I had an extra `drawTime: 'afterDraw'`, in my annotation_presets.js file, which seemed to be causing this.
