### ISSUE TITLE
Empty data columns are not displayed correctly

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1712]
Data repository URL:  [https://github.com/DnsUpgradeEnvironment/dns-data](https://github.com/DnsUpgradeEnvironment/dns-data)
Data or metadata issue: data
Input format: csv

**Describe the bug**
I added some empty columns in the data csv for the target years to show those years on the x-axis.
There are two series [here](https://dnsupgradeenvironment.github.io/dns-indicators/en/7-1-ab/). The first series has only one target year. In this case the chart works as expected: 
![grafik](https://user-images.githubusercontent.com/50657629/175483736-34756709-60a0-4c3c-bec4-a8f0f1b917de.png)
The second series has two empty columns (for 2030 and 2050; data ends in 2021). In this case the data somehow gets messed up (the data for 2021 are shown at 2050 and 2030 is not on the axis at all):
![grafik](https://user-images.githubusercontent.com/50657629/175484300-29cb7b17-6195-4e96-865a-a1d6ee6a0128.png)

**Additional context**
I have not tested this in a "neutral" environment, so there is a chance that this is caused by some overridden files. If so, please give a short feedback and ignore this issue.

**Comment by MoBosse** [comment]
Somehow this does not happen with bar-charts:
![grafik](https://user-images.githubusercontent.com/50657629/175496099-d9b446de-433c-48aa-93c6-8627900fbe92.png)

**Comment by brockfanning** [comment]
Closing as fixed.

**Comment by MoBosse** [comment]
Sorry I'm late with testing, but I can confirm that [#1715](https://github.com/open-sdg/open-sdg/pull/1715) fixed this issue. Thank you @brockfanning
