### ISSUE TITLE
Map does not update when changing unit or series

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1713]
Data repository URL: [https://github.com/DnsUpgradeEnvironment/dns-data]( https://github.com/DnsUpgradeEnvironment/dns-data)
Data or metadata issue: 
Input format: csv

**Describe the bug**
[Here ](https://dnsupgradeenvironment.github.io/dns-indicators/7-2-b/) is an indicator with two units (same goes for one unit with two series). The map loads correctly and the "change breakdown" shows up. However, after selecting the other series/unit 

- clicking "OK" does not collapse the selection field, 
- the series in disaggregations-legend does not change, 
- the time slider does not move anymore 
- and the presented data are still those of the first series.

The error message I'm getting suggests it has something to do with this line [https://github.com/open-sdg/open-sdg/blob/2.0.0-beta2/_includes/assets/js/plugins/jquery.sdgMap.js#L237](https://github.com/open-sdg/open-sdg/blob/2.0.0-beta2/_includes/assets/js/plugins/jquery.sdgMap.js#L237)

**Comment by brockfanning** [comment]
Closing as fixed.

**Comment by MoBosse** [comment]
Yes,[ #1714](https://github.com/open-sdg/open-sdg/pull/1714) has fixed this. Thanks @brockfanning !
