### ISSUE TITLE
Series dependent content not represented in maps

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#1723]
### Discussed in https://github.com/open-sdg/open-sdg/discussions/1717

<div type='discussions-op-text'>

<sup>Originally posted by **MoBosse** June 27, 2022</sup>
I just noticed that some series and unit dependent items are not present in the map:

- Titles 
  - Title of map sticks to the title, set for the first series when using `graph_titles`
  - The `indicator_name` is shown above the map when having no `graph_titles` (although `graph_title_from_series` in the site config is set to true)

-  Footnotes
   - The content of the `footer_fields` disappears compleatly when changing to the map view
   - `data_footnote` is shown under the map but is obviously not series dependent 

- Units (when there is only one unit available)
  - The content of `computation_units` disappears completely from the footer when switching to map view
  - The only way to display the unit seems to be to have a Units column in the data. The downside here is that it looks like you have the option to change it, since it is displayed with a radio button when you click the "Change Brakedowns" button. 

- Precision
   - has no impact either. Actually I would rather not have decimal places in the maps legend, but a) I wonder how the legend would look for e.g. values within a range from 0 to 1 and b) I think the tooltip values cound get decimal places if they are defined for the selected series

There are probably other elements that are relevant to maps, but these are the ones I've noticed so far.</div>

**Comment by brockfanning** [comment]
@MoBosse I started this issue, since this is definitely a bug. I've got a PR up to address these, if you have time to try it out: https://github.com/open-sdg/open-sdg/pull/1724

**Comment by MoBosse** [comment]
@brockfanning Perfect!  #1724 works and covers all above mentioned points. Thanks!

**Comment by brockfanning** [comment]
@MoBosse Thanks for testing! I just made a change, FYI - the items did not update when the map tab was first clicked. For example, if you are on a unit of "Total" while on the chart, and then you go to the map, but the map starts with a unit of "Percent", then the footer field for computation units would still say "Total". With the latest change it should hopefully update immediately when you go to (and from) the map tab.
