### ISSUE TITLE
Change download button wording

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1727]
**To do:** Change the wording of the SDG download buttons.

From > To
- Download Chart Image > Download chart image (.png)
- Download Chart CSV > Download chart data (.csv)
- Download Source CSV > Download source data (.csv)
- Download all data > Download all data (.zip)

Additionally for .zip. The sentence immediately under the buttons ' ZIP file - 47.7 MB etc' is to be replaced with 'Size: 46.4 MB, Data last updated: 04 July 2022'

@brockfanning I understand there are also additional buttons not currently used in the UK such as CSVW. The same format should be used for these. If you can let me know what additional buttons exist I can advise.

**Comment by brockfanning** [comment]
@phillipgardiner Here are some translations we have that involve downloads: https://github.com/open-sdg/sdg-translations/blob/2.1.0-dev/translations/en/indicator.yml#L8-L22

General note: One question we will need to decide is whether we want to update the English of these existing translations, or whether we want to create new ones. The downside of changing the English of the existing ones is that it makes all of the non-English translations incorrect (until they are manually fixed). The downside of creating new ones is that we have very similar translations which seems duplicative.

**Comment by brockfanning** [comment]
Actually, I just tried running "example.csv" through Google translate for a few languages, and in each case the ".csv" was not affected. So, maybe we can do this change outside of the translation system.

**Comment by brockfanning** [comment]
@phillipgardiner I've got a pull-request to make these changes in the English versions. For the extra ones I used my best judgement but feel free to recommend any changes. Here are all the changes in that pull request:

Old|New
---|---
Download Headline CSV|Download headline data (.csv)
Download Source CSV|Download source data (.csv)
Download source CSV for disaggregations|Download source data for disaggregations (.csv)
Download Source SDMX|Download source SDMX (.xml)
Download Chart CSV|Download chart data (.csv)
Download Table CSV|Download table data (.csv)
Download CSV|Download data (.csv)
Download as CSV|Download data as CSV
Download Chart Image|Download chart image (.png)
Download chart as image|Download chart image as PNG
Download GeoJSON|Download map data (.geojson)
Download as GeoJSON|Download map data as GeoJSON

**Comment by phillipgardiner** [comment]
Thanks @brockfanning, couple of observations form me,

1) I think one is missing 'Download all data > Download all data (.zip)' this is the download button on the homepage
2) I'm not quite sure of the content of use between: Download CSV & Download as CSV, Download Chart Image & Download chart as image and Download GeoJSON & Download as GeoJSON. To me they seem like they are the same thing? Are both required? 

Thanks
