### ISSUE TITLE
Change tag wording 'exploring data sources'

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#1731]
**To do:**
Change the tag wording 'exploring data sources' to 'No data available'  The current term 'explore data sources' is not understood by users. 

The text on the FAQ's page also requires updating to reflect this change. I also note the FAQ's have not been updated from when we changed the 'reported online' tag to just 'reported'

**Comment by brockfanning** [comment]
The translation has been added and this will be changed in the site starter when 2.1.0 is released.
