### ISSUE TITLE
Add 'About' h2 to goal page content

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1746]

**Comment by LucyGwilliamAdmin** [comment]
So looks like this: 
![image](https://user-images.githubusercontent.com/43404358/179797265-8b84a01e-8c30-481a-aae1-887044007bb7.png)

**Comment by christoph-LSN** [comment]
@LucyGwilliamAdmin that looks great how do I use this "About" to my goalpage?

**Comment by otis-bath** [comment]
Hi @christoph-LSN - currently to add this to each goal page you need to add the content under the create_goals header as shown here: https://open-sdg.readthedocs.io/en/latest/configuration/#create_goals

We are planning on using descriptions from eurostat which can be found here:  https://ec.europa.eu/eurostat/documents/3217494/14665254/KS-09-22-019-EN-N.pdf/2edccd6a-c90d-e2ed-ccda-7e3419c7c271?t=1653042954499

If this is something other users are interested in however we can consider adding it to the Open SDG starter and updates

**Comment by otis-bath** [comment]
'About this goal' to be set as the default 
To be made a site-wide configuration option
