### ISSUE TITLE
(AA) Reflow magnification issue

### ISSUE THREAD

**Issue by otis-bath** [open-sdg/open-sdg#1761]
When the content on a page is magnified to 400% the content begins to overlap in a few instances.

1. This is occurring on the archived indicators page currently. This implies this is an issue only occurring with the standalone-indicators layout. 
https://sdgdata.gov.uk/archived-indicators/
![image](https://user-images.githubusercontent.com/90769108/182164770-e184909c-f793-429c-8c89-638edd908292.png)
![image](https://user-images.githubusercontent.com/90769108/182164950-55064f59-5ed1-4200-9b92-26585cec843c.png)

2. Secondly, this occurs on the indicator page when at 400% zoom. This can be seen here in the sources and metadata tabs where the text is overflowing the boxes:
https://sdgdata.gov.uk/15-2-1/
![image](https://user-images.githubusercontent.com/90769108/182168806-d1da97a3-9932-437c-894c-f5a8ac2c677c.png)
![image](https://user-images.githubusercontent.com/90769108/182168891-388b5c84-51ae-4ce9-bcf0-dae879247231.png)
![image](https://user-images.githubusercontent.com/90769108/182169029-43d34359-fe38-4443-9bd5-8c891f01ef17.png)
![image](https://user-images.githubusercontent.com/90769108/182169091-47e95eb6-1b1e-4ed5-a7a7-2629d798692c.png)

3. The final instance is on the user personas page 
![image](https://user-images.githubusercontent.com/90769108/182169577-2df66665-02e1-4fba-84a2-b8af1d89c160.png)
https://sdgdata.gov.uk/user-personas/

We need the page to be viewable as a single column at 320px without loss of content or functionality. 
"Please note that for content which requires a two-dimensional layout for usage or meaning including tabular information, horizontal scrolling may be necessary in order for the presentation and structure to be preserved."

**Comment by brockfanning** [comment]
@otis-bath Numbers 1 and 3 above may be UK-specific issues, since the standalone-indicators layout is being overridden, and since the user-personas page is custom content. Number 2 might be something we can fix in Open SDG, so I'll look into that.

**Comment by brockfanning** [comment]
Number 2 above is partially dependent on content. In the case of [15.2.1](https://sdgdata.gov.uk/15-2-1/), the national metadata contains H3's that include the words "management" and "independently". At 400% zoom, both of these words are wider than the maximum width of that column. This causes them to overflow from the table column, which then causes everything else in the column to overflow from the table column. (I believe if these two words were gone that problem would be fix in this particular case.)

I'm not sure that there is any way to avoid the possibility of particularly long words being too wide for the column.  The only solution I know is a CSS trick to force long words to wrap to the next line. This involves applying this CSS to the `<td>` elements:

```
word-wrap: break-word;
max-width: 1px;
```

(It seems weird but the `max-width: 1px` apparently is what makes this trick work.)

The upside of the trick is that no text will overflow, and the downside is that long words will break to the next line. For example "Independently" might render as:

```
Independ
ently
```

I'll put up a PR with this change so we can try it out.
