### ISSUE TITLE
Security report issue - source code leakage

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1768]
Site repository URL: https://sdgdata.gov.uk/
Open SDG version: Tested 11/03/2021

**Issue found in security check - medium vulnerablility.**
The scanner detected server-side source code within the server's response. There was one instance found at: https://sdgdata.gov.uk/search/?q=nessus_was_textx5jmy1kn 
**Solution:** Need to make sure that the server does not deliver server side code to the client, and the server misconfiguration or server code should be changed to prevent this.
Can provide HTTP info if helpful.

**More info from the report FYI:**
A modern web application will be reliant on several different programming languages. These languages can be broken up in two flavours. These are client-side languages (such as those that run in the browser -- like JavaScript) and server-side languages (which are executed by the server -- like ASP, PHP, JSP, etc.) to form the dynamic pages (client-side code) that are then sent to the client.

Because all server side code should be executed by the server, it should never be seen by the client, however in some scenarios it is possible that the server has a misconfiguration or the server side code has syntax errors, and therefore is not executed by the server but is instead sent to the client. As the server-side source code often contains sensitive information, such as database connection strings or details into the application workflow, this can be extremely risky.

Cyber-criminals will attempt to discover pages that either accidentally or forcefully allow the server-side source code to be disclosed, to assist in discovering further vulnerabilities or sensitive information.

**Comment by brockfanning** [comment]
@sarah-beasley Were there any more details in the scan? The Open SDG platform, when viewed in a browser, is 100% client-side, so there is no code executed on the server-side. So, we definitely don't have a server-side vulnerability (since there is no server-side to be vulnerable) but I would like to know what exactly it was that the scanner is complaining about.

**Comment by sarah-beasley** [comment]
Hi Brock, yes the below information was also provided, hope it helps!:

Plugin Details
PUBLICATION DATE 2019-12-19T00:00:00+00:00
MODIFICATION DATE 2021-09-07T00:00:00+00:00
FAMILY Data Exposure
SEVERITY Medium
PLUGIN ID 98779

Risk Information
CVSSV3 BASE SCORE 5.3
CVSSV3 VECTOR CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
CVSS BASE SCORE 5.0
CVSS VECTOR CVSS2#AV:N/AC:L/Au:N/C:P/I:N/A:N

Reference Information
CWE 540
WASC Information Leakage
OWASP 2013-A5, 2010-A6, 2021-A1, 2017-A6, 2019-API3
CVE -
BID -

Identification
PROOF
<%

OUTPUT
On https://sdgdata.gov.uk/search/?q=nessus_was_textx5jmy1kn source code leakage was detected. Please see the attached
response for full details.

HTTP Info

REQUEST MADE

GET https://sdgdata.gov.uk/search/?q=nessus_was_textx5jmy1kn

REQUEST HEADERS
Upgrade-Insecure-Requests=1
User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4158.0 Safari/537.36
Accept=*/*
Accept-Language=en-US,en;q=0.5
Referer=https://sdgdata.gov.uk/

RESPONSE HEADERS
HTTP/1.1 200 OK
Connection=keep-alive
Server=GitHub.com
Content-Type=text/html; charset=utf-8
Last-Modified=Fri, 29 Oct 2021 10:42:52 GMT
Access-Control-Allow-Origin=*
Strict-Transport-Security=max-age=31556952
Etag=W/"617bd02c-44d72"
Expires=Wed, 03 Nov 2021 09:16:26 GMT
Cache-Control=max-age=600
Content-Encoding=gzip
X-Proxy-Cache=MISS
X-Github-Request-Id=856A:87A3:57F487:5A71F7:61825112
Accept-Ranges=bytes
Date=Wed, 03 Nov 2021 09:06:27 GMT
Via=1.1 varnish
Age=0
X-Served-By=cache-lon4269-LON
X-Cache=MISS
X-Cache-Hits=0
X-Timer=S1635930387.940025,VS0,VE136
Vary=Accept-Encoding
X-Fastly-Request-Id=a9e4117d153ac90a4026263741d0d517d1b7907c
Content-Length=284013

**Comment by otis-bath** [comment]
Action: to go back and see what it is specifically

**Comment by LucyGwilliamAdmin** [comment]
Closing this one as found not to be an issue
