### ISSUE TITLE
Map error when there is only one layer

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#178]
It appears we have some javascript that only works when there are multiple layers. Here is an example line: https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/jquery.sdgMap.js#L277

When a site has only 1 map layer, that variable is not an array. So the `[0]` gets an undefined. More investigation and confirmation is needed.

**Comment by Norric1Admin** [comment]
@LucyGwilliamAdmin This would explain why Kyrgyzstan maps aren't working.

**Comment by brockfanning** [comment]
A PR has been submitted for this: #183
