### ISSUE TITLE
translations in leaflet.disaggregationControls

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1788]
**Please complete the following information** 
Site repository URL: [e.g. github.com/ONSdigital/sdg-data]
Open SDG version: 2.1.0-dev

**Describe the bug**
Some fields in the disaggregation lists in maps are not translated. This is true for the disaggregation heading (e.g., "Gender" or "Age") in the selection list and in the list on the left side of the map when a disaggregation is selected, and for the word "All" for selecting the headline data.

**Screenshots**
This screenshot shows the expected behavior:
![grafik](https://user-images.githubusercontent.com/50657629/186589587-689ca70a-79a6-41b6-ae95-2ed45723f228.png)

**Additional context**
[This file](https://github.com/MoBosse/open-sdg/blob/2.1.0-dev/_includes/assets/js/plugins/leaflet.disaggregationControls.js) contains some overwrites that solved the issue for me. If someone could take a look at it and confirm that it's generally useful, I'd be happy to make a pull request.

**Comment by brockfanning** [comment]
@MoBosse Thank you for catching this! Your fixes look great to me, except for one issue: we don't have an "indicator.total" translation yet in the [sdg-translations repo](https://github.com/open-sdg/sdg-translations). Let me add something first, before you do a pull-request. Do you feel it is better in English as "Total" or "All"? (Or something else?)

**Comment by MoBosse** [comment]
Hi @brockfanning ,
We always use "Total", but I'll leave that to you, because I'm not the expert on English vocabulary here. :)

**Comment by brockfanning** [comment]
That works - we don't actually have a precedent in Open SDG, since we usually hide the aggregate option. I've added the indicator.total translation key in sdg-translations, so I think you could submit the PR as-is.
