### ISSUE TITLE
alterDataDisplay gets confused with values > 1000

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#1796]
Site repository URL: [e.g. github.com/ONSdigital/sdg-data](https://github.com/DnsUpgradeEnvironment/dns-indicators)
Open SDG version: 2.1.0-dev

**Describe the bug**
In the chart tooltip, the displayed values are messed up for values bigger than 1000 (see screenshot) when a decimal separator is defined as ",". My guess is that the tooltip gets the data (say 2000), wants to display it as "2.000" with a dot as the thousands separator, then [this line](https://github.com/open-sdg/open-sdg/blob/2.1.0-dev/_includes/assets/js/view/dataHelpers.js#L32) in the alterDataDisplay function replaces the dot with a comma, thinking that the dot is a decimal separator.
Then (although I don't know why the function does this after replacing the dot) the value (now "2,000") is rounded to the defined number of decimal places (0 in this case) to "2" since the function interpretes the comma as decimal seperator.

**To Reproduce**
1. Go to [https://dnsupgradeenvironment.github.io/dns-indicators/12-2/](https://dnsupgradeenvironment.github.io/dns-indicators/12-2/)
2. Hover over any datapoints
3. See tooltip

**Screenshots**
To avoid misunderstandings: The number that should be shown here in the tooltip is one thousand nine hundred and eighty-five.
![grafik](https://user-images.githubusercontent.com/50657629/187615699-d7ec6870-e454-4f59-977d-f1350ac2983c.png)

**Additional context**
Note that on the screenshot and on the linked indicator page the "alterDataDisplay" function is disabled for the data on the y-axis. Therefore, the dots (which correctly display the thousands) are displayed.

**Comment by MoBosse** [comment]
It does not solve the issue but I found an approach to configure the thousands separators: [https://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript](https://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript)

It works quite well for me (though only on the table values so far) so I wonder if we could add a variable like thousands_separator to the site config when solving this issue?
And another thought: is it possible to make the decimal_separator (and if integrated the thousands-separator) language depending? So the values could be shown in the format "1.234,5" when on the German site and as "1,234.5" when English is selcted.

**Comment by christoph-LSN** [comment]
@MoBosse 

> And another thought: is it possible to make the decimal_separator (and if integrated the thousands-separator) language depending? So the values could be shown in the format "1.234,5" when on the German site and as "1,234.5" when English is selcted.

this would be great!

**Comment by brockfanning** [comment]
A quick note while testing - if I have my browser's language set to English, I don't see the problem. But if I have the browser's language set to Deutsch, I do see it. That tells me that there is some code -- either in Open SDG or in Chart.js -- probably converting a number using `toLocaleString` or something like that. This seems like a bug that needs addressing.

**Comment by christoph-LSN** [comment]
Yes, Using English everything is ok

Using French, the Percent values have two digits the Anzahl values are displayed right, but with a _blank as thousands seperator

![image](https://user-images.githubusercontent.com/94443931/189044030-12b668a9-d762-470b-9cc4-ee63efcbc25c.png)

![image](https://user-images.githubusercontent.com/94443931/189044166-c136f55a-1dae-47db-b25d-d30f96eabbbf.png)

**Comment by brockfanning** [comment]
@MoBosse Would you be able to try the change in #1810 to see if it has any effect on the problem?

**Comment by christoph-LSN** [comment]
@MoBosse @brockfanning 

it works more or less. Numbers without decimal are shown right: [1-1-1](https://christoph-lsn.github.io/MT_Site/1-1-1/)

Numbers with decimal still show 3 digits than one:  [1-1-2](https://christoph-lsn.github.io/MT_Site/1-1-2/)

**Comment by MoBosse** [comment]
@brockfanning Thanks for taking a look at it. I am afraid there is still something wrong though.
Here are some examples wich hopefully show the behaviour with this PR:

[16.1](https://dnsupgradeenvironment.github.io/dns-indicators/16-1/)
Values > 1000, precision = 0, input values have 3 decimal places
![grafik](https://user-images.githubusercontent.com/50657629/189580323-7594f75a-0d84-45d0-87aa-90813bbef7a4.png)
--> Value is correct, decimal separator is correct but number of decimal places are not
--> Same effect when precision = undefined

[17.2](https://dnsupgradeenvironment.github.io/dns-indicators/17-2/)
Values > 1000, precision = 0, input values have no decimal places
![grafik](https://user-images.githubusercontent.com/50657629/189590547-692dccbe-6e98-4fa3-baa2-332edea8182c.png)
--> Value is not correct

Same indicator but with precision undefined:
![grafik](https://user-images.githubusercontent.com/50657629/189598206-cb983fd8-ecd8-4995-9bc9-fb9fec406899.png)
--> Value still not correct

[3.2.b](https://dnsupgradeenvironment.github.io/dns-indicators/3-2-b/)
Values < 1000, precision = 2, input values have 3 decimal places
![grafik](https://user-images.githubusercontent.com/50657629/189591562-fe980499-0f11-4977-bd1f-6131c234e404.png)
--> Value is correct, decimal separator is correct and number of decimal places are correct

**Comment by brockfanning** [comment]
Thanks for the detail @MoBosse. I'm wondering if a simpler change might help. If possible can you try out the branch from #1813? It does not address the thousands separator yet, but hopefully can be a first step.

**Comment by christoph-LSN** [comment]
@MoBosse @brockfanning I have tried ist, and it seems to work correctly....

[https://christoph-lsn.github.io/MT_Site/2-1-5/](https://christoph-lsn.github.io/MT_Site/2-1-5/)
