### ISSUE TITLE
Remove play/pause button from maps

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#1807]
The play/pause button doesn't seem to have an obvious use case and is quite inaccessible - let's remove it

**Comment by otis-bath** [comment]
Hi @christoph-LSN we are not proposing removing the slider or the >> and << buttons, currently all the play button does is automatically advance through the data however we are proposing removing this as it is inaccessible and does not become a redundant button when we change it to starting with the most recent year in the data - hope this helps

**Comment by christoph-LSN** [comment]
@otis-bath OK, now I understand....

**Comment by brockfanning** [comment]
To see what this would be like, you can try out the branch from this PR: https://github.com/open-sdg/open-sdg/pull/1812
