### ISSUE TITLE
Support lists in site config form for map colorRange

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1823]
The UK site has updated the colour range of the map scale to be:   
colorRange: 
    -  '#c4e1c6'
    -  '#b0d1b3'
    -  '#9bc2a1'
    -  '#87b28f'
    -  '#74a37c'
    -  '#60946b'
    -  '#4d8559'
    -  '#3a7747'
    -  '#276836'
   
At the moment, this cannot be specified in Open SDG on the site configuration form since the map colourRange field can only contain a single text item. In order to be able to do this, the configuration form needs to allow the map colourRange field to have multiple text items - if this can be done, that would allow us to update the colours of the maps on Open SDG.

**Comment by otis-bath** [comment]
May need to develop a message/warning in the instructions regarding changing the colours and how this affects accessibility
