### ISSUE TITLE
double config of analytic cookies in _config.yml and site_config_prod.yml

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1826]
**Please complete the following information** 
Site repository URL: [https://github.com/christoph-LSN/MT_Site/](https://github.com/christoph-LSN/MT_Site)
Open SDG version: [e.g. 2.1.0-dev]

**Describe the bug**
double config of analytic cookies:

in this line of the site config https://github.com/christoph-LSN/MT_Site/blob/515ed753932972a8a559db2a1ea2ccf7c877d34f/_data/site_config.yml#L17
analytic coockies an be set true.
and in this lline of the site_config_prod_yml 
https://github.com/christoph-LSN/MT_Site/blob/515ed753932972a8a559db2a1ea2ccf7c877d34f/_data/site_config_prod.yml#L22
alanytic cookies can be set true also.

I have noticed this because, I set up my custom domain integrationsmonitoring.niedersachsen.de and it shows the analytic cookies, although I had turned off the analytic cookies in my   _config.yml

**Comment by brockfanning** [comment]
@christoph-LSN I am guessing your goal is to have analytics on production but not on staging - is that correct? To do this you would need to set the configuration in this file: https://github.com/christoph-LSN/MT_Site/blob/develop/_data/site_config_prod.yml

Is that not working? I might be misunderstanding the bug.

**Comment by christoph-LSN** [comment]
@brockfanning no, I (my customers) don't want to have google analytics at all. From the perspective to have ga on the production site and not in the staging site everything it makes sense. I was wondering why ga is shown in the cookie (poduction-site), even if I had turned it off in my site_config (staging site). The I saw that ga can be configured in the site_config_prof as well.
