### ISSUE TITLE
Precision: comma doesn't shown if no decimal are in the data

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1827]
@brockfanning @MoBosse I am not sure if this is to see together with #1813 and #1796

**Please complete the following information** 
Site repository URL: [https://github.com/christoph-LSN/MT_Site/](https://github.com/christoph-LSN/MT_Site/)
Open SDG version: [e.g. 2.1.0-dev]

**Describe the bug**
comma doesn't show if in the data there is no decimal

example indicator: https://christoph-lsn.github.io/MT_Site/4-2-2/
[meta 4-2-2.md](https://github.com/christoph-LSN/IM_Data/edit/develop/meta/4-2-2.md#L23)
[data 4-2-2.csv](https://github.com/christoph-LSN/IM_Data/edit/develop/data/indicator_4-2-2.csv#L74)

![image](https://user-images.githubusercontent.com/94443931/195026162-e809256b-b5d0-472a-9103-dd931cab1845.png)

**Comment by brockfanning** [comment]
@christoph-LSN I would have thought this was the expected behavior - but are you saying you would prefer to see "6,0"?

**Comment by christoph-LSN** [comment]
@brockfanning
yes I need to see "6,0"

@MoBosse in your sdg-indikatoren.de 

Indicator: https://sdg-indikatoren.de/1-2-2/

in year 2014 the table shows 5,0

![image](https://user-images.githubusercontent.com/94443931/195767367-ca2dd58c-cdc3-44aa-80ac-f9ca9ad6d7bc.png)

in the CSV-Data :https://sdg-indikatoren.de/65216efe-5b58-49a6-ae5e-1774ca8db75f
the value for 2015 is 5 (without .0)

what's the difference between yours an mine configuration?

**Comment by christoph-LSN** [comment]
@MoBosse and how did you make the " " used as a thousands seperator

**Comment by christoph4711** [comment]
@Lucy, yes!

Von meinem iPhone gesendet
