### ISSUE TITLE
Where to translate the date format of download_all_data

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1828]
@MoBosse @brockfanning 

**Please complete the following information** 
Site repository URL: https://github.com/christoph-LSN/MT_Site
Open SDG version: [e.g. 2.1.0-dev]

**Describe the bug**
https://christoph-lsn.github.io/MT_Site/)

The Donload_all_datta card shows the englis date format. 
Where can I translate this?

https://github.com/open-sdg/open-sdg/blob/e911685dc3a1e2a773c2756bf37a7b4432f9c9fb/_includes/components/download-all-data.html#L10

does 'standard' mean the english date format?

![image](https://user-images.githubusercontent.com/94443931/195387898-949d567f-091c-494e-ae3b-668d8fa3162f.png)

**Comment by brockfanning** [comment]
@christoph-LSN That date format can be controlled in the site configuration. There is more info and an example here: https://open-sdg.readthedocs.io/en/latest/configuration/#date_formats

**Comment by christoph-LSN** [comment]
Thank you @brockfanning ! It Works....

![image](https://user-images.githubusercontent.com/94443931/199181148-63712e6c-9bc5-4041-9ede-2dc94d490af8.png)


@MoBosse perhaps you can use this configuration to for your www.sdg-indikatoren.de too
https://github.com/christoph-LSN/MT_Site/blob/3db8e68bde9a3943520a6208677981efae972518/_data/site_config.yml#L82-L84

**Comment by christoph-LSN** [comment]
@MoBosse @brockfanning I close this to me it works fine....
