### ISSUE TITLE
Map Legend

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1829]
@brockfanning 

**Please complete the following information** 
Site repository URL: https://github.com/christoph-LSN/MT_Site
Open SDG version: [e.g. 2.1.0-dev]

**Describe the bug**
Something is wrong with the map legend

![image](https://user-images.githubusercontent.com/94443931/195670057-210786d7-b53f-47b2-a9bd-31da1a29bd5e.png)

example indicator: https://christoph-lsn.github.io/MT_Site/5-2-2/

**Comment by brockfanning** [comment]
@christoph-LSN Can you describe the steps to recreate the problem? At the link above the legend values seem normal at the moment.

**Comment by christoph-LSN** [comment]
@brockfanning thanks for lokking at it. Now the legend looks normal...
