### ISSUE TITLE
Add Functionality for Custom Meta Descriptions

### ISSUE THREAD

**Issue by Govej** [open-sdg/open-sdg#1860]
Looking to optimize the UK site for search engines, with an aim to increase the CTR (Click Through Rate) allowing for custom meta descriptions will allow us to entice more users to the site. Currently we don't have meta descriptions for the home page or any goal pages that we're looking to target with our SEO work

These would be just for the Homepage and Goal pages for now

May be scope to look at more pages in the future such as indicators

**Comment by christoph-LSN** [comment]
@Govej I am interested in SEO optimizing as well for my [Migration Report](https://christoph-lsn.github.io/MT_Site/) but I'm an bloody greenhorn in this SEO topics
