### ISSUE TITLE
Fix year slider for map disaggregations

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1890]
Germany have [a case on their platform](https://dns-indikatoren.de/en/8-5-ab/) where they have a series with two disaggregations (20-64 years and 60-64 years). For 20-64 years they have data up to 2021, for 60-64 years the series currently ends in 2019, but the time slider runs until 2021 no matter which disaggregation is chosen. Since the map initially shows the 60-64 years disaggregation and the most recent year, the user sees a blank map when the map is opened.

When integrating start values for maps, maybe it is possible to add a rule that makes the maps only show those years where there are values for the chosen series/unit/disaggregation - link in with issue #1889

**Comment by otis-bath** [comment]
May need to include a warning for years with no data
