### ISSUE TITLE
Production site not deployed following production deployment

### ISSUE THREAD

**Issue by antonymbrown** [open-sdg/open-sdg#1928]
**Please complete the following information** 
Site repository URL: https://github.com/antonymbrown/site
Data repository URL: https://github.com/antonymbrown/data

**Describe the bug**
I am trying to set up the production site following this tutorial https://open-sdg.readthedocs.io/en/latest/hosting/github-pages-production/.

However, when performing a production deployment using the master branch I get the following error messages in 'Deploy to production' :

In the site repo, the error message is in build > Build the site.

`Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Unable to read data from: https://production-site-test.github.io/test-production-data/en/meta/all.json
404 Not Found
Error: Process completed with exit code 1.`

In the data repo, the error message is in build > Deploy to GitHub Pages

`Switched to a new branch 'gh-pages'
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial gh-pages commit
[gh-pages (root-commit) 0a1485f] Initial gh-pages commit
/usr/bin/git push --force https://***@github.com/production-site-test/test-production-data.git gh-pages
remote: Permission to production-site-test/test-production-data.git denied to antonymbrown.
fatal: unable to access 'https://github.com/production-site-test/test-production-data.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
fatal: 'github-pages-deploy-action-temp-deployment-folder' is not a working tree
Error: The process '/usr/bin/git' failed with exit code 128
Deployment failed! ❌`

**To Reproduce**
On first production deployment (in either site or data repo):

1. Go to staging site repository.
2. Switch to the branch `develop`.
3. Type `master` and then click on `Create branch: master from 'develop'`.
4. Error and production site not built.

The same error occurs following tutorial instructions for subsequent production deployments after initial creation of the master branch:

1. Go to staging site repository.
2. Click on the `Pull requests `tab
3. Press the `New pull request `button
4. Press` base: develop` and choose `master`. You should see something like: base: master <- compare: develop
5. Enter title as "Production release"
6. Press the green "Create pull request" button.
7. Wait for any automated tests to complete. These all pass OK.
8. Press the green "Merge pull request" button.
9. Error and production site not built.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome

**Comment by christoph-LSN** [comment]
@antonymbrown could you post your organization as well?
I can't find your production data repo

**Comment by christoph-LSN** [comment]
@antonymbrown only an idea: Your Repos in the oprganization aren named "main" perhaps you can try to rename them into "master"

**Comment by brockfanning** [comment]
@antonymbrown The production deployment of the data repository is failing, which means that the production deployment of the site repository won't succeed either. As you point out the relevant error in the data build is the "Permission to production-site-test/test-production-data.git denied to antonymbrown".

I wonder if Github has changed some things since we last tried this. Can you check something for me: On https://github.com/production-site-test/test-production-data/settings/actions under "Workflow permissions" is it set to "Read and write"? If not, maybe try setting it to "Read and write". Also do the same on https://github.com/production-site-test/production-site-test.github.io/settings/actions. Then try triggering another production deployment on your data repository.

**Comment by antonymbrown** [comment]
Thanks both for your responses.
@christoph-LSN I have renamed branches to master and attempted deploying the site again but still have the same error
@brockfanning Workflow permissions on both organisation repos were set to "Read and write"

**Comment by antonymbrown** [comment]
Thanks for your help @brockfanning. I have changed the settings in my production site organization to allow access tokens and tried rebuilding the site (which didn't work). Now when I go to create a new token it allows me to select the organization as a resource owner. Originally I used a classic token which didn't allow me to select repositories. I've just had a look at creating a new fine-grained token which does allow me to select repositories, but I can only select either my GitHub account or the organization as a resource owner (not both), and so I can't select all the required repositories?

**Comment by brockfanning** [comment]
@antonymbrown To make sure I understand right - when you say "changed the settings in my production site organization to allow access tokens" - what exactly were your steps there?

**Comment by antonymbrown** [comment]
Sorry for the delay @brockfanning. I went to Your Organizations > selected my production site organization > Settings > Personal Access Tokens > Settings and selected both "Allow access via fine-grained personal access tokens" and "Allow access via personal access tokens (classic)"

**Comment by brockfanning** [comment]
@antonymbrown When you created the personal access tokens, do you remember whether you choose "fine-grained" or "classic"? My theory is that for now, it is necessary to choose "classic". If you think you might have chosen "fine-grained", would you please delete those tokens and recreate "classic" tokens to replace them?
