### ISSUE TITLE
SDMX input

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#193]
Most of this work will happen (and is already happening) in the [sdg-build](https://github.com/open-sdg/sdg-build) project. But we can track concerns here specific to Open SDG.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning the latest version of the xml2csv python script can be found [here](https://github.com/LucyGwilliamAdmin/SDMX/blob/master/xml2csv.py)

**Comment by brockfanning** [comment]
This has been merged into sdg-build, so I'll go ahead and close this.
