### ISSUE TITLE
I am trying to update my data repo by adding datasets for SDG indicator. When I add any csv file I am getting build issue. It says ImportError: cannot import name 'cached_property' from 'functools'. I am not sure what is wrong. When I googled it it said cache_property does not run below python 2.7 and my python is set to version 2.7. I am not sure how to change it. 

### ISSUE THREAD

**Issue by MeghaStha** [open-sdg/open-sdg#1934]
**Please complete the following information**
Data repository URL: https://github.com/MeghaStha/AuburnAldataRepo
Data or metadata issue: data issue
Input format: CSV

**Describe the bug**
The data repo is not building after committing changes

**Additional context**
This job shows the error I have.
https://github.com/MeghaStha/AuburnAldataRepo/actions/runs/4111039689/jobs/7094417158
![image](https://user-images.githubusercontent.com/9130639/217287320-5690b795-cc66-41e2-809d-de3a52e4dcf0.png)

**Comment by otis-bath** [comment]
Hi! The resolution for this is here in the discussions section: 
https://github.com/open-sdg/open-sdg/discussions/1923
