### ISSUE TITLE
SDMX output

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#194]
Most of this work will happen (and is already happening) in the [sdg-build](https://github.com/open-sdg/sdg-build) project. But we can track concerns here specific to Open SDG.

**Comment by brockfanning** [comment]
@AnnCorp Here's that ticket I had created for tracking SDMX export discussion.

**Comment by LucyGwilliamAdmin** [comment]
Requirements for SDMX output:

User story:
As a country reporting data for SDGs
I need to make our data available in SDMX format
So that it can be exchanged with the UN and other custodian agencies

No matter what format data is uploaded in, it is converted to JSON when the site it built so we need the SDMX export to be created from JSON with use of DSD and mapping.

**Comment by LucyGwilliamAdmin** [comment]
For example, data would be available at [ORG].github.io/[DATA REPO]/data/[INDICATOR CODE].xml
Mock up:
![image](https://user-images.githubusercontent.com/43404358/66899509-ff8c0000-eff2-11e9-9102-9c9a007574db.png)

**Comment by LucyGwilliamAdmin** [comment]
There's also an issue in SDG Build (https://github.com/open-sdg/sdg-build/issues/52) so just copying over some info from that:
@brockfanning:
Some general thoughts are:

1. In implementing this, we may discover new requirements in the internal structure for this library. For example, in the output we may need to distinguish between "dimensions" and "attributes", but right now our internal structure is has nothing that would indicate which columns are "dimensions" and which columns are "attributes". We could also consider, rather than changing our internal structure, having some sort of a mapping passed to the SDMX output class that conveys that info.
2. I strongly recommend that try our best to use an open-source library to produce the output. I wonder if something like pandaSDMX would work for us here. If we find ourselves writing code that outputs SDMX, that would be a shame. Then perhaps once we're familiar with whatever library we use, we can refactor the SDMX inputs to also leverage it.

**Comment by LucyGwilliamAdmin** [comment]
Lucy:
>As we have now got the functionality for a few different SDMX types to be imported to Open SDG platforms we are beginning to consider functionality for SDMX data to exported from Open SDG platforms e.g. have data available at URL and also available for download.

>When any data is uploaded to an Open SDG platform e.g. in CSV, SDMX, markdown, etc. it is converted to json, so hoping to be able to export in SDMX format from json.

>Are any of you aware of any tools available that would allow us to do this? Or aware of anyone who has created something similar?

Abdulla (UNSD):
>Thanks for the good news! It would indeed be very useful if Open SDG could be used to export SDMX data as this would simplify and facilitate data exchange.

>ILO SMART now supports SDMX-JSON as one of the formats, and you should be able to use it to convert SDMX-ML or SDMX-CSV to SDMX-JSON, although I have not tested it.
 
>If you need support at the library level, need to check whether JSON is supported by SDMX Source. I’m not sure though if you will find useful since SDMX Source is implemented in .Net and Java. Please let me know what exactly you need to achieve.

Lucy:
>That’s good to hear – can this tool be used as a web service?
 
>Here is an image of the data flow we are trying to achieve (final output doesn’t necessary have to ML): 
>>Data-flow image from above
 
>The thing we’re looking for is the Tool part, which can take in a normal JSON (not SDMX), a mapping and a DSD and then output SDMX-ML.

Abdulla:
>This is an interesting diagram, I am trying to understand how it works.
 
>On the extreme left, you seem to be taking in SDMX (whether JSON, CSV, or XML) and converting it to (non-SDMX) JSON. Then you map that JSON to a customized DSD and output SDMX-ML.
 
>The question I have is: how would the output SDMX-ML be different from incoming SDMX?
 
>It is important to understand the objective because that also determines the choice of software. SDMX Converter, for example, can be configured as a Web service and can take Excel, CSV, and other formats, a DSD, and mappings, and convert the data to SDMX-ML or SDMX-CSV. Unfortunately, SDMX Converter does not support SDMX-JSON (unless they are adding support to their test versions). ILO SMART can similarly convert between formats and does support SDMX-JSON but it’s a desktop application.

Lucy:
>Currently the NRP is built with json files, no matter what format the data/metadata was uploaded in. 
 
>While the JSON and XML on the left are SDMX, the CSV is not and while it may be possible to allow users to download/access the uploaded SDMX files directly, we would still need a tool to convert the CSV to SDMX using the mapping and DSD.
 
>Also, we would like to make the data available in SDMX for individual files as well in bulk for all indicators, I’m not sure this would be possible if the data is coming from one SDMX file (as with Cambodia) without a tool that can convert the individual non-SDMX JSON into SDMX.

Abdulla:
>Assuming my understanding is correct – by no means a certainty – I would propose the following diagram:
>![image](https://user-images.githubusercontent.com/43404358/67097747-a965bb00-f1b2-11e9-96f5-3699b32722e6.png)

>In this case, you bring incoming file to a uniform SDMX-ML format, then (a) feed it to SDG Build to convert to JSON and compile the NRP site; (b) publish as is at the site. You may also choose to feed the non-SDMX CSV directly to SDG Build, and separately convert it to SDMX-ML for publication at the site.
 
>All the mappings are done before you feed data to the site, which I think is much easier than converting the input to JSON and then mapping it back to SDMX. Note that you still have to process incoming SDMX-ML in case it’s different from your target SDMX-ML format (e.g. StructureSpecific).

Abdulla:
>Oops, I forgot that SDMX Converter has not supported SDMX-JSON, therefore bottom-left part needs to be modified. I can find out whether there is a plan for SDMX Converter to support SDMX-JSON, or perhaps there’s another way of getting SDMX-JSON.

Abdulla:
>SDMX Source now supports SDMX-JSON: https://www.nuget.org/packages/SdmxSource.NuGet/
>I will try and find out from Eurostat whether they are planning to include support for SDMX-JSON in SDMX Converter.

**Comment by LucyGwilliamAdmin** [comment]
Also been in contact with Edgardo Greising (ILO)
Lucy:
>I work on the Open SDG platform and I’m emailing as we are looking for some sort of tool which can be built into the platform to convert to SDMX formats.

>I have used the SMART tool in the past to convert CSV files to SDMX-ML format and was just wondering if there is/going to be a web service which does the same thing as the SMART tool, if a DSD and mapping was provided to it?

Edgardo:
>The “SMART-as-a-Service” version has been in our minds for a long time, and we are sure we will have it one day. The “only” problem is that it would require a quite big effort to re-develop the whole UI and afterwards maintaining two versions (desktop and web), and we don’t have the resources as to cope with all these requirements. I will let you know if we can finally have it.

>In the meantime, have you tried the “SMARTcmd” command line application? I think it can work for your purpose of converting files from within your platform, provided it is run in a windows server. You have to install SMARTcmd.exe from the “Tools” menu in any directory and when you run SMARTcmd.exe with a .smart project file you have previously generated, including the input file and DSD, as well as the mapping, it will reproduce the execution in batch mode.
>The command line interface allows to modify the parameters in the project file for this run:
>![image](https://user-images.githubusercontent.com/43404358/67762695-f876e000-fa3d-11e9-98d9-8c0342a0d560.png)

>I think that, from the SDG platform UI, you should be able to upload the input data to the windows server where SMARTcmd is installed and launch the batch conversion with proper parameterization.
The front-end application can monitor the log file to wait for the completion of the conversion and then return the output file(s).
Please let us know if it worked.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp @SavvasStephanides 
I wanted to sum up my thinking on SDMX output, and get your feedback.

1. The idea of a "push button" SDMX output feature for Open SDG, where countries could achieve SMDX output, from their current CSV data, without any extra work or SDMX expertise, seems to be infeasible. More investigation is needed, but all evidence points to it being either impractical or impossible.
2. But countries still need this feature, so can we support them in the short term? Maybe by doing any of the following?
    1. Produce a document describing in detail how to use the various tools (like SDMX Converter) to convert their CSV files from the data starter into SDMX.
    2. Create an open-sdg-data-sdmx-starter repository, that starts countries off with a working SDMX setup.
    3. Anything else?

**Comment by AnnCorp** [comment]
Re 2.i, as part of a UNECE task team on Data transmission  we're already working on some high-level guidance for wiki pages in the UNECE knowledge bank and putting stuff into the UNECE Roadmap for SDG statistics (Lucy has drafted some materials that are with me for review). 
With the work of the SDMX working group, it would be worth us exploring more about what already exists that we could point to. Think previously we did some high-level diagrams showing the conversion process too. 
At the next UNECE meeting in Budapest I'm co-chairing a session on regional reporting and data flows and hoping to do cover some country usage of SDMX there, potentially with an Open SDG country. Again we could hopefully reuse some of that material too.

**Comment by LucyGwilliamAdmin** [comment]
Re 1. It's not possible to export SDMX straight from CSV with no other expertise but I think it would be possible to export SDMX without having to input SDMX as long as the country has a DSD and mapping.

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning 
Just writing paper about Kyrgyzstan implementing SDMX for UNECE webinars.

One of the things I'm writing under next steps is that they want their SDG data to be available at SDMX-API endpoint e.g. .StatSuite.

But now I'm thinking couldn't Open SDG be the SDMX-API endpoint once we set SDMX output up (cuts out the middle man)?

Obviously this wouldn't make sense for countries who are already using .StatSuite or something, or if they wanted other data to be available at SDMX-API endpoint, mainly thinking about teams are using SDMX just for SDGs

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp 
We might be cautious about promising anything like an "API", as that can imply more of a dynamic system where you can get different data by changing some URL parameters. At the moment I believe the most likely plan is that SDMX files are generated from the CSV files, via an external tool, and then linked from Open SDG. So, the SDMX files will be available for download, but that's not quite the same as an API.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning 
That's ok, wasn't going to mention anything about it - just a thought I had whilst writing the paper.

Do you think we should consider having an API?

Although I guess we could come to that later, once we have implemented the initial SDMX output but I guess it's a possibility we could keep in mind when making choices regarding the SDMX output?
