### ISSUE TITLE
Change build failure when no geodata

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#1952]
As with the issue that has just arisen for Ghana, whereby the build failed where there was no geodata but the map layers code was still in the config_data.yml file. This needed to be commented out in order for the build to run. Instead of a fail, could change so that it just gives a warning instead for the future.

**Comment by brockfanning** [comment]
@sarah-beasley I think this may be fixed. When I test it out locally by removing the GeoCode column from my only mapped indicator (1.3.1), the build still completes, and I see this in the logs:

```
00:00:00 - No indicators have data under "GeoCode".
Indicator 1-3-1 should not have "data_show_map" set to true, because it does not contain GeoCode data.
```
