### ISSUE TITLE
merging into master fails (site and data repo)

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#1956]
Hello @brockfanning @MoBosse @LucyGwilliamAdmin 

Do you have any ideas what's going on here?

**Please complete the following information**
Data repository URL: https://github.com/christoph-LSN/IM_Data
Site repository URL:  https://github.com/christoph-LSN/MT_Site

Production Organization: https://github.com/MT-production

Failed PR Data: https://github.com/christoph-LSN/IM_Data/actions/runs/4436809891
Failed PR Site: https://github.com/christoph-LSN/MT_Site/actions/runs/4436890800

I tried to merge small changes into my master repo (site and data)

Merging fails with the following error:

Data repo error Message:

/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/iukx6zb3c
Switched to a new branch 'github-pages-deploy-action/iukx6zb3c'
/usr/bin/git commit -m Deploying to gh-pages from  @ d02a62db626679ad75ea0d04c518ef97fa4141e0 🚀 --quiet --no-verify
/usr/bin/git push --force https://***@github.com/MT-production/IM_production_data.git github-pages-deploy-action/iukx6zb3c:gh-pages
fatal: could not read Password for 'https://***@github.com': No such device or address
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌

Site repo Error message:

/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/nd2xesg5z
Switched to a new branch 'github-pages-deploy-action/nd2xesg5z'
/usr/bin/git commit -m Deploying to master from  @ 4acacab03618e12e8eb02c6b9d85d24df0916f44 🚀 --quiet --no-verify
/usr/bin/git push --force https://***@github.com/MT-production/MT-production.github.io.git github-pages-deploy-action/nd2xesg5z:master
fatal: could not read Password for 'https://***@github.com': No such device or address
Running post deployment cleanup jobs… 🗑️
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Deployment failed! ❌

**Comment by MoBosse** [comment]
@christoph-LSN [This](https://github.com/actions/checkout/issues/417#issuecomment-1123595641) seems to have worked for some users with similar issues. Maybe you could give it a try.

**Comment by christoph-LSN** [comment]
@MoBosse  I have tried it but i get the same errors

![image](https://user-images.githubusercontent.com/94443931/225751355-39b89a3c-8a63-4a13-9e04-d831bfd9843e.png)

@brockfanning I choose the classic token, I am wondering why there is a hint that this token is used within the last 4 month 

![image](https://user-images.githubusercontent.com/94443931/225752242-47e1139d-dced-449c-a63b-79c97ee37dc2.png)

**Comment by christoph-LSN** [comment]
@brockfanning @MoBosse @LucyGwilliamAdmin 

Sometimes the problem sits right in front of the screen: i had to regenerate my access token because it expired last week.
But I didn't put the new access token into the repo secrets....

Thank you so much for lokking in my problem.....
