### ISSUE TITLE
Automated quick-start with Docker

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#197]
We may be able to make the quick-start easier with more automation. I'm not sure if we could get it to a one-command setup (the dream!) but we should try to get as close to that as possible.

**Comment by brockfanning** [comment]
Related discussion about Docker in #138

**Comment by brockfanning** [comment]
I wonder if a Docker setup could serve two purposes: local development, and also self-hosting in production? Maybe a bit ambitious...

**Comment by brockfanning** [comment]
@SavvasStephanides I tried it out and it seemed to be working great, but I get an error on the site build. It seems like it's having a problem with the bundle install:

```
# Build the Jekyll site.
cd site-starter && bundle install
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Makefile:12: recipe for target 'build' failed
make: *** [build] Error 1
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Makefile:45: recipe for target 'serve.docker' failed
make: *** [serve.docker] Error 1
```

Not sure if it's relevant but:
```
brockfanning@brockX1:~/repos/github/open-sdg/open-sdg$ docker --version
Docker version 18.09.7, build 2d0083d
```

**Comment by SavvasStephanides** [comment]
@brockfanning Rather strange. Can you try updating Docker in case you have an easier version?

**Comment by SavvasStephanides** [comment]
@brockfanning I made a few updates. The Docker image is now at [Docker Hub](https://hub.docker.com/r/opensdg/make) so no files are required to be stored in the repo. Just checkout `serve_docker` repo and use `make docker.serve` or `make docker` to access the container instance and run anything.

**Comment by brockfanning** [comment]
I'm not sure why but it's still unable find the 'bundler' gem - same error message as before. I did a general software update (I'm using Ubuntu) but the version of Docker stayed the same: 18.09.7.

**Comment by SavvasStephanides** [comment]
@brockfanning Have you tried the command above (`docker run -it --rm -p 4000:4000 -v ${PWD}:/repo opensdg/make:0.1 bash`)? This should create a new container but not run any `make` commands yet. Make sure the terminal is pointing at the root of the Open SDG repo. Then try running `make serve` within the container.

**Comment by brockfanning** [comment]
@SavvasStephanides That helped. Inside the container I got the same error during `make serve`, but after doing a `gem update --system` the `make serve` is able to complete. Only issue now is viewing the site in the browser. The expected http://127.0.0.1:4000/ is not working for me. Should I be trying a different URL?

**Comment by SavvasStephanides** [comment]
@brockfanning OK great! I'll probably need to update the image then to include the `gem update` command.

To view the site in the browser now is the weird part. Docker containers tend to expose the `0.0.0.0` IP address instead of `127.0.0.1` for some reason. So you'll need to do the same as before but instead of `make serve`, try running the following in the container:

```bash
make build && cd site-starter && bundle exec jekyll serve --skip-initial-build --host 0.0.0.0
```

You should be able then to view the site on http://localhost:4000. Let me know if it works.

**Comment by SavvasStephanides** [comment]
As mentioned in the call:

If you pull the latest changes for the `serve_docker` branch in `open-sdg` you should be able to run these on the terminal

- `make docker.setup` will create a new container with everything installed
- `make docker.run` will let you access the container. To serve the site, just run `serve` within the container
