### ISSUE TITLE
Indicator data not showing on site

### ISSUE THREAD

**Issue by Jonkat323** [open-sdg/open-sdg#1971]
**Please complete the following information**
Data repository URL: https://github.com/COJ-SDG/data
Data or metadata issue: Data (potentially both)
Input format: CSV and YAML

**Describe the bug**
I have followed the getting started tutorials and have uploaded the csv data and metadata for a test indicator (7-1-1) with all checks passed. My site shows that the indicator is being reported, but no data is not available when viewing. Downloading the source data results in an empty file.

**Comment by MoBosse** [comment]
@Jonkat323 You have a csv file in you [data folder](https://github.com/COJ-SDG/data/tree/develop/data) for indicator 17.1.1. Is there a typo and you meant to name the file indicator_7-1-1.csv?

**Comment by sarah-beasley** [comment]
Hi @Jonkat323 , have you done the [triggered builds tutorial](https://open-sdg.readthedocs.io/en/latest/automation/triggered-site-builds/)? This will set up the infrastructure to automatically rebuild your site so you should see the changes you make to the data repository. For a quick fix, you could try manually triggering the site rebuild by refreshing the site repository - just add a line to the readme file.

**Comment by Jonkat323** [comment]
@MoBosse Oh wow, thanks for spotting that! Thought I was going crazy. It is working correctly now.
