### ISSUE TITLE
all checks have failed

### ISSUE THREAD

**Issue by city-of-cape-town** [open-sdg/open-sdg#1987]
**Please complete the following information**
Data repository URL: [[e.g. github.com/ONSdigital/sdg-data]](https://github.com/city-of-cape-town/data-2-0-0/upload/develop/data)
Data or metadata issue:
Input format: CSV

**Describe the bug**
 When uploading the CSV file on data repository, a syntax error comes up and all checks fail.

**Additional context**
as per the open-sdg user guide, we can do steps 1-6 for "steps to upload the CSV file" but we experience problems with steps 7-8

**Comment by christoph-LSN** [comment]
@city-of-cape-town In your Action log the following Error is schown:

ImportError: cannot import name 'cached_property' from 'functools' (/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/functools.py)

Have your tried this: https://github.com/open-sdg/open-sdg/discussions/1923

**Comment by christoph-LSN** [comment]
@city-of-cape-town doe ist work again? Can we close this issue?
