### ISSUE TITLE
Data rounding changes non-decimal numbers

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#199]
The [data rounding function](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js#L19) actually changes non-decimal numbers. For example, it changes 171615 to 172000. I don't believe this is desired behavior. Or at least, if it is, it should be easier to override. (Right now, the only way to override the function is to override the entire indicatorModel.js file, or the scripts.html file.)

So I think we should either change this function as needed, or make it easier to override.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I'll just add this here: if the data rounding function is going to be looked at, we've come across another problem:

![image](https://user-images.githubusercontent.com/43404358/59357836-6d61ab80-8d23-11e9-93b4-88b5e797fa92.png)

![image](https://user-images.githubusercontent.com/43404358/59357915-8d916a80-8d23-11e9-9876-41d247b442ad.png)

**Comment by brockfanning** [comment]
Thanks @LucyGwilliamAdmin. It does look like clearly the default rounding function needs changing. We'll need to decide what the rounding function should do. The [existing function](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js#L19) is pretty hard to understand. Questions:

1. Do we want the default rounding function to affect non-decimal numbers? For example, should it affect the number 8628623?
2. For decimal numbers, do we want to have a maximum number of decimal places? If so, what would that be?
3. If we have a maximum number of decimal places, could it be site-wide? Or would it need to be configurable per indicator?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just spoken with our data team and the main message was that maybe it would be best to not have a rounding function at all. That way it would be up to the data provider, etc. to put what they want to show into the data file.

I've just done a quick test on a branch of the UK site with removing the rounding function.

This isn't something that has to be taken through to Open SDG as other countries may have different thoughts.

**Comment by brockfanning** [comment]
That sounds good to me - I'll work up a PR for this. Maybe we can make it more easily controlled at the same time.
