### ISSUE TITLE
Charts wont load on production site

### ISSUE THREAD

**Issue by Jonkat323** [open-sdg/open-sdg#2006]
Hi,

Yesterday I deployed a production environment following [this guide](https://open-sdg.readthedocs.io/en/latest/hosting/github-pages-production/). I then added a custom domain via the production site repository. At first glance everything seems to be working correctly, but I have noticed that none of the indicator graphs are loading (see screenshot below). However, the metadata in the table below the graph is correct.

Staging site repo - https://github.com/COJ-SDG/site
Staging data repo - https://github.com/COJ-SDG/data
Production site repo -  https://github.com/COJ-SDG-LIVE/COJ-SDG-LIVE.github.io
Production data repo -  https://github.com/COJ-SDG-LIVE/data

URL - https://sdg.urbanearth.co.za/

![image](https://github.com/open-sdg/open-sdg/assets/31311959/5340d836-5445-47c5-b217-9fc0c131802a)

**Comment by MoBosse** [comment]
@Jonkat323 I think the problem might be that you are using a custom domain for your production site.

Could you try replacing the _remote_data_prefix_ in [here](https://github.com/COJ-SDG/site/blob/develop/_data/site_config_prod.yml#L19)
by `https://sdg.urbanearth.co.za/data/`?

**Comment by christoph-LSN** [comment]
@Jonkat323 take a look here: https://github.com/open-sdg/open-sdg/issues/1824
I had the same issue after adding a custom domain

**Comment by sarah-beasley** [comment]
@Jonkat323 there is also some guidance on readthedocs about changing the remote_data_prefix when you use a custom domain [here](https://open-sdg.readthedocs.io/en/latest/hosting/github-pages-production/#custom-domain).

**Comment by Jonkat323** [comment]
> @Jonkat323 I think the problem might be that you are using a custom domain for your production site.
> 
> Could you try replacing the _remote_data_prefix_ in [here](https://github.com/COJ-SDG/site/blob/develop/_data/site_config_prod.yml#L19) by `https://sdg.urbanearth.co.za/data/`?

Thanks, that worked!



> @Jonkat323 take a look here: #1824 I had the same issue after adding a custom domain

Thanks I should have searched for this before I created a new issue. 



> @Jonkat323 there is also some guidance on readthedocs about changing the remote_data_prefix when you use a custom domain [here](https://open-sdg.readthedocs.io/en/latest/hosting/github-pages-production/#custom-domain) just FYI!

Thanks, somehow I missed that.
