### ISSUE TITLE
cannot import name 'make_generic_validator' from 'pydantic.class_validators'

### ISSUE THREAD

**Issue by pixerize** [open-sdg/open-sdg#2017]
**Please complete the following information**
Data repository URL: https://github.com/sdgbih/sdg-data-bosnia/actions/runs/5426347774/jobs/9868277525
Data or metadata issue:

**Describe the bug**
We are still with SDG version 1.5.0 version for now. I also override requirements to hit the "1.5.0-dev" branch, but cannot resolve this problem (on testing instance) . If anyone has idea, please help :)

Build cannot deploy, we get this error:
ImportError: cannot import name 'make_generic_validator' from 'pydantic.class_validators' (/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pydantic/class_validators.py)

**Additional context**

**Comment by christoph-LSN** [comment]
@brockfanning 

I have the same problem here...

opdensdg version: 2-1-1

Data repo: https://github.com/christoph-LSN/IM_Data/
Site repo: https://github.com/christoph-LSN/MT_Site/

Build error:
https://github.com/christoph-LSN/IM_Data/actions/runs/5443541788/jobs/9900186266

**Comment by christoph-LSN** [comment]
@pixerize @brockfanning 

I seems there has been an update of pydantic: https://pypi.org/project/pydantic/

Looking at the migration guide here: https://docs.pydantic.dev/latest/migration/ it seems there are alo of major changes.

As shown in the migration guide I added the line: pydantic==1.* in my [requirements.txt](https://github.com/christoph-LSN/IM_Data/blob/develop/scripts/requirements.txt) to use the V1 of padentic

The error was not shown anymore the question is if there are any other consequences...

**Comment by sarah-beasley** [comment]
Looks like this is a problem we are having on our site too when our team are trying to upload data - https://github.com/ONSdigital/sdg-data/actions/runs/5445957750/jobs/9905983795 . 
@brockfanning would you be able to provide a fix please? Thanks

**Comment by pixerize** [comment]
@christoph-LSN thank you very much, it solved the data build!

**Comment by christoph-LSN** [comment]
@sarah-beasley changing the requirements.txt as described above solves the problem. In the long run I think opensdg-build ahs to be updatet to pydantic V2

**Comment by brockfanning** [comment]
The suggestion by @christoph-LSN works for me as well. I've just made that change in our data starter: https://github.com/open-sdg/open-sdg-data-starter/pull/65/commits/d27c8dc41e64ea019cb6a81c1cd961d7d8867748

**Comment by christoph-LSN** [comment]
@brockfanning we can close this?
