### ISSUE TITLE
Embed indicators onto other indicator pages

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#2023]
Allow embedding indicators on other pages (discussions/2013) embedded using an iframe. Should be able to generate pages for every indicator, generate a second page and the header and footer would be hidden - so could be used to embed on other sites. Think about removing the scroll, metadata tabs, etc from the embedded indicator?

**Comment by christoph-LSN** [comment]
@sarah-beasley you can close this.....

**Comment by sarah-beasley** [comment]
Hi @christoph-LSN , we were wondering if you had any additional feedback from when you previously tested [#2025](https://github.com/open-sdg/open-sdg/pull/2025) as we'd still like to add this to the 2.3.0 release if it's working! Please let us know if you think it worked well enough to include in the release. Thanks
