### ISSUE TITLE
Search result structure markup (for voice control)

### ISSUE THREAD

**Issue by AaronONS** [open-sdg/open-sdg#2030]
Brock to estimate time. 

DAC Usability issue
Where there is structure within text, it may assist users if mark-up were introduced to ensure this structure is programmatically determinable.

There is a path provided for each result to show its location within the site. A ‘double angle bracket’ is used to indicate the flow of information, but the purpose of this icon may not be clear to screen reader users and which in turn may make the purpose of the information more difficult to determine.

URL
https://sdgdata.gov.uk/search/?q=

Solution:
The structure of this information is similar to a breadcrumb trail; consider marking it up as an ordered list.

Example:
```
<div class="url"> <ol> <li>general.posts</li> <li><span aria-hidden=true>»</span> /updates/2019/11/04/APIs.html</li> </ol> </div> 

```
Note: Additional information can be found in: Accessibility Audit Report for ONS SDG, 21/04/2021, ref-000699 page 52

**Comment by sarah-beasley** [comment]
![Image](https://github.com/open-sdg/open-sdg/assets/106670682/b80dff2e-b618-40a3-8335-d9d89d381b74)
