### ISSUE TITLE
Country to be able to select max number of lines on chart

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#207]
Currently the charts are allowed more that 10 lines to be on a chart before the following message is displayed: "There are too many datasets to show on the chart. Not all will be shown until you remove some selections."

This can be way too messy, it might be good for countries to be able to configure the maximum number of lines allowed on a chart.

**Comment by brockfanning** [comment]
Just to confirm - is the idea here to be able to configure the maximum per indicator? Or to configure the maximum site-wide?

**Comment by LucyGwilliamAdmin** [comment]
Site-wide

**Comment by brockfanning** [comment]
Since the number of chart colors is now configurable site-wide, this is effectively done. The number of colors (doubled) is what determines the maximum number of lines. I'll go ahead and close, but @LucyGwilliamAdmin please re-open if there is more to be done.
