### ISSUE TITLE
Series not appearing 

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#2071]
**Please complete the following information** 
Site repository URL: [https://github.com/ONSdigital/sdg-indicators/tree/develop]
Open SDG version: [2.2.0]

**Describe the bug**
on [3.b.1](http://uk-sdg-feature-branches.s3-website.eu-west-2.amazonaws.com/feature-site-keep-user-selections-on-unit-change/3-b-1/), the Proportion of girls vaccinated against HPV (%) series only appears when you have selected a vaccine, country and age category. The default is just to say that there is no data available which isn't true. Not sure if this is a setting we just need to change, or if this is another issue?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by brockfanning** [comment]
Possible approach: When switching to another series, Open SDG should treat it like it is loading a new page - in other words, if any disaggregations are needed in order to display data, they should be automatically selected.
