### ISSUE TITLE
Ruby gems error

### ISSUE THREAD

**Issue by sarah-beasley** [open-sdg/open-sdg#2079]
**Please complete the following information** 
Site repository URL: [e.g. github.com/ONSdigital/sdg-indicators]
Open SDG version: [e.g. 1.0.0]

**Describe the bug**
Trying to upgrade to beta1 in a feature branch and an error is coming up in the site repo. It also came up when trying to create Senegal's site (updating site_config step) the other day so i dont think it's an isolated issue.

Link to error - https://github.com/ONSdigital/sdg-indicators/actions/runs/7273620349/job/19817937839

![image](https://github.com/open-sdg/open-sdg/assets/106670682/e65c7c5e-558f-49b2-9f2c-81660242fdc2)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by beyersar** [comment]
Hi everyone! Have you found a solution for this issue? We are having a similar issue. https://github.com/StabsstelleNachhaltigkeit/sdg-in-staging-site/actions/runs/7872920892/job/21479173872 Thanks a lot for your help!

**Comment by sarah-beasley** [comment]
Hi, yes the issue is fixed by actioning this simple change - https://github.com/open-sdg/open-sdg/discussions/2080 please let us know if you have any further problems

**Comment by beyersar** [comment]
Dear Sarah, thanks for you help! Unfortunately it did not work out.
I changed the bundler version as suggested. And I changed the ruby version in automated tests (as suggested here: https://github.com/open-sdg/open-sdg/pull/2038). 
But now I get another error: https://github.com/DrJannisHoek/sdg-enz-staging-site/actions/runs/7929512104/job/21649889293 
The changes I made are here: https://github.com/DrJannisHoek/sdg-enz-staging-site/compare/develop...beyersar-bundler-2.
