### ISSUE TITLE
Some metadata fields from UN metadata template are missing

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#208]
** Update 12/02/2020 **
May need to also add fields re proxy status - to be discussed further **

**Update 05/02/2020**

The below fields are to be added under national metadata
- Quality assurance - quality_assurance?
- Comparability with international data/standards - international_comparability?
- Comments and limitations - Other information is currently comments_limitations so it may be other changing Other information to other_info so this can be comments_limitations
- Rational and interpretation - rational_interpretation?

Will discuss "Data collection methods" with Kyrgyzstan and may add to site starter later

------------------------------------------------------

This is the template that is recommended for use by countries i.e. this is filled in for each indicator:
[Metadata Template_V1.docx](https://github.com/open-sdg/open-sdg/files/3314671/Metadata.Template_V1.docx)

However, we don't display some of these fields on Open SDG platforms.

After speaking with Vibeke at UNSD, we think some work needs to be done to make sure that each of the metadata fields can be taken in and displayed on an Open SDG platform.

I have done a comparison of what's in the metadata template and what we currently have on Open SDG platforms. Below is a table showing the findings

| Template section | Template field | Open SDG metadata section | Open SDG metadata field|
|--------------------|-----------------|--------------------------------|-----------------------------|
|Indicator information|Goal| Not shown in Global Metadata Section but this info can be deducted|None|
|Indicator information|Target|Global Metadata| 'Target number' and 'Target name'|
|Indicator information|Indicator|Global Metadata|'Indicator number', 'Indicator name', 'Indicator display order (within Goal page)'|
|Data reporter|Organisation|Sources|'Organisation'|
|Data reporter|Contact person(s)/Focal point|Sources|None|
|Data reporter|Contact person's email|Sources|We have one field where contact details can be displayed: 'Contact details'|
|Data reporter|Contact person's phone|Sources|We have one field where contact details can be displayed: 'Contact details'|
|Definitions and concepts| Definition (asks for definition of indicator and unit of measurement) | National Metadata| ‘Definitions’ and ‘Unit of measurement’ |
|Definitions and concepts| Concepts (asks for definitions of all different concepts, variables and terms) | National metadata | We (UK) normally include this info under 'Definitions'|
|Definitions and concepts|Rationale and interpretation (asks to Explain how this indicator is related to the target, and any specific way it should be interpreted for example specific thresholds)| No field but would come under National Metadata section| None|
|Data sources and collection methods|Data Sources (asks for Description of sources of data to calculate this indicator, as well of the methods used for data collection. This description should include, when applicable, the sample frame used, the questions used to collect the data, the type of interview, the dates/duration of fieldwork, the sample size, the response rate, and any changes of the data source over time, details of denominator (if from a different source) and any other relevant information related to the origin of the source or indicator.)| Sources | We have 'Other information' field|
|Data sources and collection methods|Data collection methods|Sources|'Periodicity', 'Release date' and 'Next release date' but template also asks for collection dates)|
|Method of computation and other methodological considerations|Method of computation|National Metadata|'Calculations'|
|Method of computation and other methodological considerations|Comments and limitations|National Metadata|We have comments_limitations in .md files which converts to ‘Other information’ field in National Metadata section. Maybe this field name could just be changed?|
|Method of computation and other methodological considerations|Quality assurance (asks for information on steps taken for quality assurance)|None|None|
|Data availability and disaggregation|Data availability and gaps (asks for description of the availability of data, including the time periods for which data is (un)available)|None|None|
|Data availability and disaggregation|Disaggregation|No field but can see what disaggregations are available in filtering section|None|
|Comparability with international data/standards|Asks for discussions on this data’s comparability, and if the data deviates from internationally estimated data, explanation on the sources of discrepancy, highlighting and summarizing the main sources of differences. |None|None|
|References and documentation|Asks for any references and documentation that helps with understanding of how the data for this|None|None|

**Comment by LucyGwilliamAdmin** [comment]
From Vibeke:
Hi Lucy,

Thanks for going through our template and comparing it with what you currently have. I have now had a more thorough look too and here are some thoughts from me:
At the general level, I find it confusing that there is a split between national metadata and sources as the source is linked to the national metadata. This is particularly the case as you also have the Global metadata specified between, and for most of the countries the global data are not provided. For external users, that may be confusing as they do not know which metadata are the ones that are relevant for the data which are specified. I further have some thoughts on how it could be restructured, but am of course also open to alternative approaches:
a.	We could have the national metadata only, potentially with source information separately and with a link to the global metadata at the bottom – or at the top with a specification saying, please look here for a specification of the globally specified metadata. Further explaining that the platform only provides national data and that the national metadata will showcase potential differences from the global, some differences will be minor, while others will be more extensive, for example in the cases where national indicators are proxies/differing from the global ones.
b.	Alternatively, to more easily highlight similarities and differences, would it be possible to display the national and global metadata next to each other so that the user can see where there is a divergence in the metadata? (also highlighting that global metadata are only showed for comparison purposes)

For the concrete fields, I do not have a strong opinion on the use of grouping and naming of the fields, but for comparison with the global metadata it may be good to use a similar language. I also agree that there is no need to specify disaggregation for the national metadata as that is in the scroll down of the data. It would be good to add missing elements though. 

Please let us know what you think.

**Comment by LucyGwilliamAdmin** [comment]
From Chris:
* Having a separate Source tab makes it easier for users to find the report / data provider.
* It’s useful having the National and Global metadata all in one place, so users don’t have use external (potentially unaccessible) sites to get the information. I prefer option b.

**Comment by Norric1Admin** [comment]
**LINKS**
[Word](https://github.com/open-sdg/open-sdg/files/3314671/Metadata.Template_V1.docx)
[Excel](https://share.sp.ons.statistics.gov.uk/sites/SusIneq/SDG/_layouts/15/WopiFrame.aspx?sourcedoc=/sites/SusIneq/SDG/Sample/NRP/International-Development/Other/UNSD_metadata_template.xlsx&action=default)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp There are a lot of ideas discussed in this thread. What should our first step be?

One option could be to **add** all of the fields from the table above with "None" in the "Open SDG metadata field" column. But, there is still the question of whether they should appear in the "National" or "Global" tabs. That needs to be decided before they can be added.

**Comment by AnnCorp** [comment]
@brockfanning Lucy and I will discuss this early tomorrow and add further comments.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've edited the description with what Ann and I discussed

**Comment by brockfanning** [comment]
I opened up a couple of PRs to address this:
* https://github.com/open-sdg/open-sdg-data-starter/pull/23
* https://github.com/open-sdg/translations-open-sdg/pull/8
