### ISSUE TITLE
Allow reporting status to be viewed by other things than just by Goal

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#209]
When in Kyrgyzstan we were asked if it would be possible to display reporting status by ministry (so that they can hold them accountable) I have mocked this up here (only visually, not code):
[reportingstatus.docx](https://github.com/open-sdg/open-sdg/files/3314833/reportingstatus.docx)

Could we implement this? Or something similar which would allow countries to configure they're own reporting status by X page e.g. by Tier

**Comment by brockfanning** [comment]
Just a note that this was requested for the Kazakhstan platform as well.

**Comment by brockfanning** [comment]
Estimate: This should definitely be possible, but needs more investigation. I would give a rough estimate of about 10 hours.
