### ISSUE TITLE
Problem with translation in Klaro consent form

### ISSUE THREAD

**Issue by vmartin8888** [open-sdg/open-sdg#2126]
**Please complete the following information** 
Site repository URL: [e.g. github.com/ONSdigital/sdg-data]
Open SDG version: [e.g. 1.0.0]
2.3.0
**Describe the bug**
consent form dont support translates

**To Reproduce**
1. Go to 'https://vmartin8888.github.io/site'

**Expected behavior**
The klaro consent form not see boton label at spanish

**Screenshots**

<img width="383" alt="image" src="https://github.com/user-attachments/assets/ad80496c-57b4-4543-97ed-f36729a2643c">

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari] all browsers
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by christoph-LSN** [comment]
@vmartin8888 could you provide your site and data repo?

**Comment by christoph-LSN** [comment]
@vmartin8888 
@brockfanning 

I have created a coockies.yml for es. (using chatgtp, so maybe some es native speakers should have a look at it) I noticed that only the en folder has an coockies.yml

Create cookies.yml #459

**Comment by vmartin8888** [comment]
it works fine!. Thanx

**Comment by christoph-LSN** [comment]
@vmartin8888 @brockfanning can we close this?

**Comment by vmartin8888** [comment]
yes, you can
