### ISSUE TITLE
Zoom out the map is too small

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#2130]
**Please complete the following information** 
Site repository URL: https://github.com/christoph-LSN/MT_Site
Open SDG version: [e.g. 2.2.1]

Data Repo: https://github.com/christoph-LSN/IM_Data

Geojson: https://github.com/christoph-LSN/IM_Data/blob/develop/world2.geojson

_data Site config.yml: https://github.com/christoph-LSN/MT_Site/blob/develop/_data/site_config.yml

https://github.com/christoph-LSN/IM_Data/blob/develop/config_data.yml

Example indicator: https://christoph-lsn.github.io/MT_Site/1-2-5/

**Describe the bug**

Looking at the indicator 1-2-5 the map is loading properly, but I can't zoom out, to see the whole world. Where I have to adjust the Zoom?

any ideas @brockfanning @sarah-beasley @MoBosse

**Comment by MoBosse** [comment]
@christoph-LSN Isn't it just changing the value of the [min_zoom](https://github.com/christoph-LSN/MT_Site/blob/develop/_data/site_config.yml#L210)?

**Comment by christoph-LSN** [comment]
Thank you @MoBosse it works...
