### ISSUE TITLE
After Updating to 2.3.1 no Data is shown (urgend help needed)

### ISSUE THREAD

**Issue by christoph-LSN** [open-sdg/open-sdg#2147]
@brockfanning 
@MoBosse 
@sarah-beasley 

It's a little urgent. I'll need to fix ist until Monday or go back to 2.2.1... Any Ideas?

**Please complete the following information** 
Site repository URL: https://github.com/christoph-LSN/MT_Site
Open SDG version: [e.g. 2.3.2]

Example Indicator: https://christoph-lsn.github.io/MT_Site/1-1-1/

**Describe the bug**
After updating to 2.3.2 no data is shown. Inspecting the site the following error is shown:

sdg.js?v=20241011085522:4866 Uncaught ReferenceError: updateIndicatorDataUnitStatus is not defined
    at sdg.js?v=20241011085522:4866:36
    at new indicatorView (sdg.js?v=20241011085522:4894:3)
    at Object.success (sdg.js?v=20241011085522:5218:32)
    at c (jquery-3.6.1.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.1.min.js:2:29072)
    at l (jquery-3.6.1.min.js:2:80045)
    at XMLHttpRequest.<anonymous> (jquery-3.6.1.min.js:2:82499)

![image](https://github.com/user-attachments/assets/350c7347-dd3e-428a-a4d3-a19d08c095b2)

The files I have for updating to changed:
https://github.com/christoph-LSN/MT_Site/blob/develop/_config.yml

`remote_theme: open-sdg/open-sdg@2.3.2`

https://github.com/christoph-LSN/MT_Site/blob/develop/Gemfile

```
`source "https://rubygems.org"

gem "jekyll", "3.8.4"
gem "html-proofer", "3.19.4"
gem "jekyll-remote-theme"
gem "deep_merge"
gem "jekyll-open-sdg-plugins", "2.3.0"`
```

https://github.com/christoph-LSN/IM_Data/blob/develop/scripts/requirements.txt

`git+https://github.com/dougmet/yamlmd
git+https://github.com/open-sdg/sdg-build@2.3.1
frictionless==4.40.8
pydantic==1.*`

**Comment by MoBosse** [comment]
I don't know what's causing your error but I've seen that you have overwritten the [chartHelpers.js](https://github.com/christoph-LSN/MT_Site/blob/develop/_includes/assets/js/view/chartHelpers.js) file and last updated it 2 years ago. So maybe it doesn't fit with the rest of the open-sdg code anymore. 
I would copy the original form open-sdg version 2.3.2, paste it into your file and than readd whatever changes you have made there...

**Comment by christoph-LSN** [comment]
@MoBosse Thank you... I'll try it.
May be it's good to know, that I want to use the comment_obs in indicator 6-3-2:
files changed:

https://github.com/christoph-LSN/MT_Site/blob/develop/_data/site_config.yml

 `##Qualitätskennzeichen
observation_attributes:
  - field: COMMENT_OBS
    label: ''
`
https://github.com/christoph-LSN/IM_Data/blob/develop/data/indicator_6-3-2.csv

Example Indicator: https://christoph-lsn.github.io/MT_Site/6-3-2/

**Comment by christoph-LSN** [comment]
@MoBosse Thank you! It's working again but as you can see in 6-3-2 https://christoph-lsn.github.io/MT_Site/6-3-2/ the Comment_OBS is shown with: [note 1],  [note 2]. Do I have to change it in my translations?

**Comment by christoph-LSN** [comment]
@MoBosse it's working! Thank you for immediate help!
