### ISSUE TITLE
Graph title becomes very unclear if long

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#215]
If you look [here](https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-site-starter/en/2-2-1/), the graph title is very unclear as it is long.

I have suggested to Kyrgyzstan that they could edit the graph title so that it is more clear (maybe by making it more concise) in the short term.

As a longer term fix maybe the graph title could wrap over two lines if it is over a certain length?

**Comment by brockfanning** [comment]
Agreed, this would be a great improvement.

**Comment by brockfanning** [comment]
This was resolved by #315
