### ISSUE TITLE
PDF output

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#216]
Kyrgyzstan have mentioned they would like the function to be able to download data in PDF.

**Comment by brockfanning** [comment]
Let's describe this in user-story format:
```
As a [type of user]
I need to [description of feature]
So that I [purpose of feature]
```
In my experience, PDFs are actually a hindrance to interoperability. Maybe this is geared towards the policy-maker audience?

I would also wonder - is the request to have just tabular data in the PDF, or also to have the graph?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think we could close this - Kyrgyzstan brought this up quite a while ago and hasn't been brought up since by them or anyone. And your definitely right about it not be machine friendly

**Comment by brockfanning** [comment]
Ok cool, closing now.
