### ISSUE TITLE
Feature to compare data between two different indicators

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#217]
Request from Kyrgyzstan: "Can we in future include function «comparison or comparison of data» on two indicators from different goals (which, for example, are interrelated)."

**Comment by brockfanning** [comment]
This is an interesting idea. I think that to make sure we're meeting the needs of the users, it would be nice to detail this request in "user story" format:
```
As a [type of user]
I need to [description of feature]
So that I [purpose of feature]
```
And maybe a mockup would be helpful to see exactly what the comparison would look like.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning again I think this is possibly another one that could be closed as not brought up in since originally.

**Comment by brockfanning** [comment]
Sounds good, closing now.
