### ISSUE TITLE
Different lay-out to goal page

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#219]
Kyrgyzstan are wondering if it is possible to design their goal page like this:
![image](https://user-images.githubusercontent.com/43404358/60346619-65f10200-99b3-11e9-95b1-7e30ca2b2fb9.png)

**Comment by brockfanning** [comment]
Sure, I don't see why not. The main question to answer is, should this go into Open SDG, or be done custom per country. To help answer that, could you give a short description of the three tabs in the screenshot?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @AnnCorp @SavvasStephanides 
This was something Kyrgyzstan requested so more of a customisation but just thinking that maybe the goal orientation bar at the top might be useful for Open SDG- what are your thoughts?

**Comment by AnnCorp** [comment]
@phillipgardiner  just saw this issue and thought of you. Something to discuss with @LucyGwilliamAdmin  and tech team?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning goal page text is not currently customisable right? I think maybe this ticket could be closed but maybe a nice to have would be the customisable intro text that's been added to most/all other pages?

I think maybe the rest is quite specific

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin No I think the configurable goal page text is not done yet - see #631.

**Comment by LucyGwilliamAdmin** [comment]
Ah yes, you're right, so think we can close this one then?

**Comment by brockfanning** [comment]
I would be fine with closing it - I agree the other parts may be too country-specific to change in Open SDG.
