### ISSUE TITLE
Link to stats office on platform

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#221]
Suggestion from Kyrgyzstan:
Icon on top-left of homepage which is also link to country's stats office website
![image](https://user-images.githubusercontent.com/43404358/60651053-4b001100-9e3d-11e9-8faa-1a770982fb90.png)

**Comment by brockfanning** [comment]
Was the screenshot above intended to have a mockup of the feature? I'm not seeing it if so. I think that a mockup would help us decide whether this is something that should go into Open SDG, or should be custom per country.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning apologies, I've updated the image

**Comment by brockfanning** [comment]
Just speaking from a technical standpoint, it might be a little problematic to have the logo in the "gutter" on the left. It would definitely disappear on mobile.

Personally I feel like the most appropriate place for a link to the stats office is in the footer. Typically the footer is the place to link to related but separate stakeholders, contributors, etc. And that would also solve the mobile problem.

**Comment by LucyGwilliamAdmin** [comment]
Let's close this as 1. Brock pointed out why this wouldn't be suitable, and 2. Kyrgyzstan have gone ahead and done it themselves (https://sustainabledevelopment-kyrgyzstan.github.io/)
