### ISSUE TITLE
'Contacts' tab

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#222]
Suggestion from Kyrgyzstan:
Tab where we could display telephone numbers/email addresses

**Comment by brockfanning** [comment]
I would be interested to hear more details about the proposal. If by "tab" it is meant, another item in the navigation menu for a contact page, then this can be easily done by creating a page, and then updating the [menu config](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml#L83). But if it's something else then I would like to hear more about it.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning this is exactly what I meant - thanks for providing the info to add this
