### ISSUE TITLE
Search functionality refactor using Lunr.js?

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#226]
This may be a good opportunity to standardize around a third-party open-source library, remove custom code from the platform, and improve functionality: use [Lunr.js](https://lunrjs.com/) for the search functionality. Is it feasible to refactor the search functionality so that it uses Lunr.js instead of custom javascript?

**Comment by brockfanning** [comment]
@SavvasStephanides Here's that ticket I mentioned - this is a possible way for an incremental improvement to the search functionality. Lunr.js has some of the same natural-language features that back-end search software (like Solr) has. Its big downside is that, being client-side, it is not feasible beyond a certain amount of content. In other words, as content is added, Lunr.js will eventually affect performance negatively. So it's not useful for blogs, which will gradually accumulate more and more content. But, since Open SDG is pretty much "capped" at ~150 indicators, it might actually be a feasible long-term solution.

**Comment by AnnCorp** [comment]
@brockfanning for info, have pulled out some of the user needs we already have documented relating to improved search:
- I want to search for content using terms familiar to me so that I don't have to guess what it is called
- I want search to suggest alternative searches so that I can see if I used the wrong term
- I want to be able to search by indicator id so that I can quickly find the indicator I am interested in
- I want to be able to search for terms used in the source data so that I don't have to know the UN terminology

**Comment by brockfanning** [comment]
@AnnCorp Thanks for listing those. Here are some questions/comments: 

1.  _I want to search for content using terms familiar to me so that I don't have to guess what it is called_
    * We may be able to do this, but I'm not sure. Do you think you could give some examples of a search query, and what results it should find?
2.  _I want search to suggest alternative searches so that I can see if I used the wrong term_
    * I did just add some basic "did you mean" functionality to #427 .
3. _I want to be able to search by indicator id so that I can quickly find the indicator I am interested in_
    * This is in #427  - whether they use dots or dashes - indicators are searchable by id
4. _I want to be able to search for terms used in the source data so that I don't have to know the UN terminology_
    * To make sure I understand it right - the words in each indicator's **disaggregation** should be searchable too? Eg if an indicator is disaggregated by female/male then searching for "female" should include that indicator in the results?

**Comment by AnnCorp** [comment]
@brockfanning  re (1) things like emissions and climate change or mortality and deaths might be worth testing.

**Comment by brockfanning** [comment]
To fix:
* High contrast
* Links not including base folder
