### ISSUE TITLE
Properly translate the result count in search results

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#236]
The result count (eg, "26 indicators found") on the search page is not being translated. Example: [here](https://kazstat.github.io/sdg-site-kazstat/search/?q=%20%D0%BF%D0%B0%D0%B9%D1%8B%D0%B7)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you think this is a translation we could get in at the same time as the accessibility translations?

Although I think I remember you saying before it might require some more work on this side due to ordering of the sentence for diff langs?

**Comment by brockfanning** [comment]
In #1071 I've slightly shifted the phrasing from "X results found" to "Results found: X" which should make it more sensible in multiple languages.
