### ISSUE TITLE
Allow multiple links per data source

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#248]
As you can see [here](https://g205sdgs.github.io/sdg-indicators/2-2-1/) there are sometimes several source documents are available from the same organization. It would be good if in such cases several links could be named under one data source.

**Comment by brockfanning** [comment]
@MoBosse I was having difficulty coming up with a general way of achieving this, so tried a country-specific approach. Please take a look at [this PR](https://github.com/G205SDGs/sdg-data/pull/17) and let me know what you think.

**Comment by MoBosse** [comment]
@brockfanning  Works well. Thank you.
