### ISSUE TITLE
typo in quick start guide

### ISSUE THREAD

**Issue by angelamhkim** [open-sdg/open-sdg#267]
in the quick start guide under View the Site, I believe the url https://my-github-org/github.io/open-sdg-site-starter/ should be https://my-github-org.github.io/open-sdg-site-starter/ instead replace the / with a .

**Comment by brockfanning** [comment]
Great catch, thanks @angelamhkim.

**Comment by brockfanning** [comment]
If it's OK, let's keep this open until the typo is fixed.
