### ISSUE TITLE
incorporating R code for customized visualization

### ISSUE THREAD

**Issue by angelamhkim** [open-sdg/open-sdg#268]
is there a way to incorporate customized code in another language for visualizing specific indicators that may not fit the current viz options? 

example plot: http://rpubs.com/angelamhkim/LA511viz
example code: https://github.com/angelamhkim/open-sdg-data-starter/blob/develop/testing/5.1.1viz

similar issue: https://github.com/dawncomer/open-sdg-site-starter/issues/16

**Comment by brockfanning** [comment]
@angelamhkim There are a few approaches you could take in customizing the visualizations. I'm ordering these by (what I imagine to be) easiest to hardest:

1. If the visualization is available at a URL somewhere, it might be suitable for display in an iframe. You can see some examples [here](https://open-sdg.readthedocs.io/en/latest/faq/#can-content-from-other-websites-be-embedded-in-open-sdg).
2. You could implement any javascript-based visualization by digging into the code and wiring it up with the data. The existing options (bar, line, binary) can be seen [here](https://github.com/open-sdg/open-sdg/tree/master/_includes/components/charts) and all use the [Chart.js](https://www.chartjs.org/) library. But in theory you could use any other JS framework, like D3. Javascript is not R, of course, but this leads into a third possibility:
3. It may be possible to write R visualizations, and through a build-step compile them into the HTML/CSS/Javascript needed to display it on a website. I don't have any experience with this, but a quick Google shows some potential libraries like [this](https://rstudio.github.io/r2d3/index.html) and [this](http://tutuchan.github.io/chartjs/). I believe this is also basically what [Shiny](https://shiny.rstudio.com/) does.
4. Possibly a combination of 3 and 1 above? Ie, have a build step that converts the R code to HTML/CSS/Javascript pages, and then display it on the indicators using the iframe approach.

**Comment by brockfanning** [comment]
Cleaning up the queue a bit - please re-open if needed.
