### ISSUE TITLE
Negative values are displaying as missing values

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#279]
Looks this problem is caused by something in the 0.7.0 update:

https://sdg.mango-solutions.com/0-6-0/8-1-1/

https://sdg.mango-solutions.com/0-7-0/8-1-1/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It looks like this is caused by [this commit](https://github.com/ONSdigital/sdg-indicators/commit/058b1f42027106838957d27f46c1faf54136d46c). I don't totally understand the math, but I can see that if I revert that commit, the problem goes away.

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning, we want to display figures to 3 significant figures rather than to 2 decimal places so I changed the custom JS. I will see if there's a different formula I can use so that this doesn't happen

**Comment by LucyGwilliamAdmin** [comment]
Great, I have fixed this now - Thanks for your help
