### ISSUE TITLE
Using Open SDG for non-SDG metrics

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#293]
Continuing the discussion from [here](https://github.com/open-sdg/open-sdg-site-starter/issues/39#issuecomment-520206696). @christoph4711 wrote:

> I’m thinking about to develop such a reporting system for migration issues in Lower Saxony, based on the SDG repositories. It will be much smaller than SDG only 50 Indicators in three or four areas. (Population, education, labor market and social aspects of migration)
> Each indicator should be available on different regional structures (eg. Lower Syxony on the whole, large and small cities etc..), the data should be displayed in some graphics and maps, and also should be available as csv….
> What do you think, is this possible with the SDG repositories or do you have other repositories in mind that suit better to my ideas of an migration reporting system than the SDG repositories?

The functionality of graphs, maps, and CSV has already been implemented. And being essentially just a Jekyll site, Open SDG is quite flexible. There doesn't need to be any mention of the SDGs, for example. And there can be any number of "goals" (as many as the default 17, or as few as just 3 or 4).

The only part that may be less flexible at the moment is the word "Goal". Right now this word is hardcoded into Open SDG. If you wanted to use a different term for the concept (like maybe "Area") then you would need to override some files. However we could work on a feature for customizing that word, probably the `_config.yml` file, if it is a common need.

You might also want to hide the "Global Metadata" tab. It's another thing that's possible with overrides, but which could also be a config setting if it was a common need.

Other than those I can't think of any other "gotchas". I think this use-case is certainly worth a shot.

**Comment by christoph4711** [comment]
For a deeper understanding I provide two screenshopts from the current xls report...
The tables are more or less complex, I chose two less coplex ones ;-)


![Indicator_A1](https://user-images.githubusercontent.com/53389268/62937562-45e39980-bdcd-11e9-90e9-cb38a31f0179.PNG)

![Indicator_B5](https://user-images.githubusercontent.com/53389268/62937565-4aa84d80-bdcd-11e9-81c8-e303fb2cf78b.PNG)

**Comment by brockfanning** [comment]
@christoph4711 I don't have much time to analyze the source data, but my gut feeling says this would be possible, and I'm happy to provide any guidance along the way.

To kick things off, my first questions for you are the following: Out of the box, Open SDG is structured like this:

```
Homepage with lots of "Goals"
--> "Goal" pages with lots of "Indicators"
------> "Indicator" pages with data/metadata
```

* For your use-case, how would this need to differ?
* For example, would you need a different word instead of "Goals"?
* Also would you need any other types of pages?

**Comment by christoph4711** [comment]
@brockfanning 
i think the structure of 
---->"Goal" pages with
--------> "Indicator" pages with data /metadata

suits very well to my use case.

But the word "Goal" should be changened in "Themenbereich" or "topic"

A couple of questions are in my mind:
1) How can I reduce the number of  "Goals" ? I only have 4 Goals with lots of Indicators. I developed 4 graphics for my topics and put them [here](https://github.com/christoph4711/open-sdg-site-starter/tree/develop/assets/img) but its hs no effect to my "Goal" page....

Goal / Themenbereich: **Bevölkerung**:
---> 22 Indicators

Goal / Themenbereich: **Bildung und Qualifikation**:
---> 13 Indicators

Goal / Themenbereich: **Erwerbstätigkeit und Arbeitsmarkt**:
---> 9 Indicators

Goal / Themenbereich: **Soziales**:
---> 7 Indicators

2) How do I provide data into the Indicators. I tried to add data in [Indicator 1.2.1](http://prose.io/#christoph4711/open-sdg-data-starter/edit/develop/data/indicator_1-2-1.csv) but it has no effect. I can't see any data...

3) Ho can I change the Indexpage an the indicator pages? 
![grafik](https://user-images.githubusercontent.com/53389268/63406693-ec8df280-c3ea-11e9-963d-e48632d162d9.png)

**Comment by brockfanning** [comment]
To get the goal images to work, I think you'll need to update your `goal_image_base` in _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#goal_image_base) for documentation. I believe yours should be `https://christoph4711.github.io/open-sdg-site-starter/assets/img/goals`.

A quick and dirty way to override the word "Goal" which might work: In your site repository, create a file at the path `data/translations/en/general.yml` and `data/translations/de/general.yml`. Inside the English one, add something like this:
```
goal: Topic
goals: Topics
```
And then something similar for the German one.

As to why 1.2.1 is not showing data, I believe you need to update the `reporting_status` to `complete` in the `meta` folder of your data repository. See [here](https://open-sdg.readthedocs.io/en/latest/metadata-format/#data-info) for documentation.

To change the frontpage heading and/or instructions, you can set `frontpage_heading` and `frontpage_instructions` in _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#frontpage_heading) and [here](https://open-sdg.readthedocs.io/en/latest/configuration/#frontpage_instructions) for documentation.

As for how to control the number of goals and indicators, there is a way where you can control this entirely in the data repository. This is the approach I would recommend. The steps to do this would be:
1. In your data repository, delete all the files under `data` and `meta` that you won't be using. For example, if you won't need indicator 1.3.1, then delete [this file](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/meta/1-3-1.md) and [this file](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-3-1.csv).
2. Delete [this folder](https://github.com/christoph4711/open-sdg-site-starter/tree/develop/_goals) completely (and all the files in it)
3. Delete [this folder](https://github.com/christoph4711/open-sdg-site-starter/tree/develop/_indicators) completely (and all the files in it)
4. Add `create_goals` to your _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#create_goals) for documentation.
5. Add `create_indicators` to your _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#create_indicators) for documentation.

After these steps, your site should only display those indicators that exist in your data repository, and only those goals (topics) that the indicators belong to.

**Comment by christoph4711** [comment]
@brockfanning 

i have changed the reporting_status to complete [here](https://github.com/christoph4711/open-sdg-data-starter/edit/develop/meta/1-1-1.md)   Now the graph is shown but not the table.

I have also tried to add some data, but after updating the data/indicator_1-2-1.csv something went wrong: 

Checking 244 metadata files...
data/indicator_1-2-1.csv : First column not called "Year"
data/indicator_1-2-1.csv : Last column not called "Value", instead got  Weiblich
'Value'
Checking 244 metadata files...
Traceback (most recent call last):
  File "scripts/check_data.py", line 24, in <module>
    raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

**Comment by christoph4711** [comment]
@brockfanning 

after adding the columns Year and Value [here](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-2-2.csv) CircleCi  won't produce errors any more, but the table isn't shown as well.....

**Comment by MoBosse** [comment]
I´m not sure if that´s the reason for the table not to be shown, but your data should look like 
Year,AGS,Gebietseinheit,sex,Value
2018,xxx,yyy,male,123
2018,xxx,yyy,female,234
2018,xxx,yyy,total,357

**Comment by christoph4711** [comment]
@MoBosse 
obviously not, I have changed the data [here](data/indicator_1-3-1.csv). The graph is schown but not the table.... https://christoph4711.github.io/open-sdg-site-starter/1-3-1/

**Comment by MoBosse** [comment]
@christoph4711 
The graph is shown but doesn´t display any data right? 
And without data the table would not show anything.

**Comment by christoph4711** [comment]
@MoBosse 
yep, that's right....
The question is, why the data isn't shown in the table.....

**Comment by LucyGwilliamAdmin** [comment]
When I use ctrl+shift+i to inspect the page, this error comes up:
![image](https://user-images.githubusercontent.com/43404358/63507642-1705ab80-c4d0-11e9-8040-58ed0476451c.png)

One comment is (not sure if this will fix this) but in the metadata, try changing the graph_type to `bar` since there is only one Year of data.

**Comment by christoph4711** [comment]
@LucyGwilliamAdmin 
I have changed the graph_type to bar. But there is no effect.

Another may be error occurs: Since lunch CirecleCi do not work automatically,... Before Lunch it starts working immediatly if I editetd a file, now i have to start it by hand. I'm sorry but i am not familiar with CircleCi so the question is, when I choose "Restart from beginning" are my current changes took into account?

**Comment by LucyGwilliamAdmin** [comment]
I would try rebuilding both open-sdg-data-starter and open-sdg-site-starter from the beginning in CircleCi. A data build should be triggered if any changes are made to any files though so not sure why that's not working

**Comment by christoph4711** [comment]
@MoBosse 
In the documentaion is stated [here](https://open-sdg.readthedocs.io/en/latest/making-updates/#editing-data): 

> Note that your change will not immediately appear on your staging site - the change will need to be approved by a platform administrator on your team. <

May be because of this theres no table visible. But where do I approve the change?

**Comment by LucyGwilliamAdmin** [comment]
Since you are make commits directly I don't think you will need to get approval.

I don't think that's causing the table not displaying. I think the table isn't displaying since the data isn't being read - similarly to how even though graph is displaying, there's no data showing on it.

**Comment by brockfanning** [comment]
There may be a few issues:
1. I think maybe the "AGS" column is causing problems, probably because it's numerical. This should be reported as a bug in Open SDG, if I'm not mistaken. A quick fix might be to remove the "AGS" column, but eventually we'll want to get that fixed properly.
2. Try also upgrading to Open SDG 0.7.1 (you can do this [here](https://github.com/christoph4711/open-sdg-site-starter/blob/develop/_config.yml#L132))

**Comment by christoph4711** [comment]
Upgrading to SDG 0.7.1 solves some of the problems.... The tables are visible now, but only the "year" column ist shown in the table. Selecting things on the left side don't work. 

I try to provide a smaller datasset for testing....

**Comment by christoph4711** [comment]
@brockfanning

removing the column AGS solves the problem with selecting things on the left side, as you can see [here](https://christoph4711.github.io/open-sdg-site-starter/1-2-2/). 
So maybe it's a bug, but im to much a greenhorn in the whole thing to say that.....

And Immedieatly the next question comes up:
Hiow can I display the cities in the table in lines an not in columns?

Like:
**Year ---- City ---- ------------female ---- male --- total**
2018 ----Braunschweig-------85145 -----73030----158180
2018-----Salzgitter-Stadt-----10805------9045-----19850
2018-----Wolfsburg-Stadt----10555------8770-----19235

**Comment by brockfanning** [comment]
@christoph4711 Right now the way the table works is to have one row per year, and to keep adding new columns based on what the user has selected from those disaggregation widgets on the left. So, as the user selects more disaggregations on the left, more columns will be added to the table.

If you'd like a different format for the table, that could be a good thing to discuss in a separate issue, so we can hammer out the details, the use-case, etc.

One tip: Instead of putting "total" in your data, you should just leave those cells blank. There is more detail about that [here](https://open-sdg.readthedocs.io/en/latest/data-format/#fields).

**Comment by christoph4711** [comment]
@bockfanning

> If you'd like a different format for the table, that could be a good thing to discuss in a separate issue, so we can hammer out the details, the use-case, etc.

ok, if you think that's woth a discussion, you can open an issue ( I'm not sure, if hit the correct words describing the problem)

Thank you for the tip with the totals.

Another question comes up: In Germany we use "," as seperator for decimal numbers. That don't work because the "," is used as sperator in .csv files. My MS Excel produces csv files with ";" as seperator. I have tried to upload such a cvs table but that doesn't work.... Replacing ";" with "," and "," with "." makes it work.

**Comment by brockfanning** [comment]
That's a really interesting issue with the commas/separators, and I am curious if it is causing any problems in the sdg-build project. Apparently not, if you have not noticed any errors. But maybe something to keep an eye on. Long term though, we should figure something out so that you can use "," instead of ".", since that is what your audience expects.

**Comment by christoph4711** [comment]
I hace changed the data of [indicator 1.2.1](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-2-1.csv) (replacing "," with ";")

The result:
#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 219 metadata files...
data/indicator_1-2-1.csv Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

Checking 219 metadata files...
Traceback (most recent call last):
  File "scripts/check_data.py", line 24, in <module>
    raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

**Comment by christoph4711** [comment]
@brockfanning

**Goal images**
changing
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals/
to 
goal_image_base: https://christoph4711.github.io/open-sdg-site-starter/assets/img/goals/
results in no images at the index page.

**override the word Goal**
As you said I have added two gerneal.yml files [here](https://github.com/christoph4711/open-sdg-data-starter/tree/develop/data/translations)

but nothing happens. Not even an error occurs

Last question for this thread: Where do I change the goal names like: 

Ziel1:  Armut in allen ihren Formen und überall beenden
into 
eg. Ziel1: Bevölkerung

**Comment by brockfanning** [comment]
Overriding the word "Goal": Note that these translations need to go into your site repository, as opposed to your data repository. Same path (eg, `data/translations/de/general.yml`) but different repository.

Goal images: I am curious what's going on here. The images are definitely available, so I'm not sure why they would be broken. (eg, https://christoph4711.github.io/open-sdg-site-starter/assets/img/goals/de/1.png is available)

Goal names: Quick way would be to copy [this file](https://github.com/open-sdg/sdg-translations/blob/master/translations/de/global_goals.yml) into your site repository, as `data/translations/de/global_goals.yml` and then edit it as needed.

**Comment by christoph4711** [comment]
Both, overriding the word goal and change the names of the goals work fine! 
Thank you!

Can I change the Indicator names in the same way as the goal names?

**Comment by christoph4711** [comment]
@brockfanning

changing goal_image_base  ist now working. i hae not changed anything else ....

Where do I change the Indicator numbering? I only need 1.1 to 1.22, 2.1 to 2.13. and so on....

**Comment by brockfanning** [comment]
Ah, that may be a "pain point" for this approach, but first let's try it out: put those in the data repository in the "indicator" field. For example line 6 of [this file](https://raw.githubusercontent.com/open-sdg/open-sdg-data-starter/develop/meta/1-1-1.md). I'm not sure offhand whether the filenames matter, but you may also need to change the names of the files. Eg, `meta/1-1.md` instead of `meta/1-1-1.md`.

**Comment by christoph4711** [comment]
Changing indicator: 1.1.1 to indicator: 1.1
produces an error:

 Liquid Exception: undefined method `gsub' for 1.1:Float in /_layouts/indicator-json.html
jekyll 3.8.4 | Error:  undefined method `gsub' for 1.1:Float
Exited with code 1

renaming indicator_1.1.1.md to indicator_1.1.md
produces the following error

#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 90 metadata files...
data/indicator_1-1.csv [Errno 2] File b'data/indicator_1-1.csv' does not exist: b'data/indicator_1-1.csv'
Checking 90 metadata files...
Traceback (most recent call last):
  File "scripts/check_data.py", line 24, in <module>
    raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

creating an new csv file indicator_1-1.csv produces the same Error

#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 90 metadata files...
data/indicator_1-1.csv [Errno 2] File b'data/indicator_1-1.csv' does not exist: b'data/indicator_1-1.csv'
Checking 90 metadata files...
Traceback (most recent call last):
  File "scripts/check_data.py", line 24, in <module>
    raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

**Comment by brockfanning** [comment]
Ok, so it sounds like this is the first real obstacle to what you're trying to do. I would suggest starting a separate issue called "Support indicators without targets". There is some code in Open SDG will need to be adjusted in order to support 2-part indicator ids (eg 1-1, 1-2, etc.) in addition to 3-part indicator ids (eg 1-1-1, 1-2-1, etc.).

**Comment by christoph4711** [comment]
ok, i have started another Issue...

Another more complex question about maps:

I tried to use the maps option followingt the instructions [here](https://open-sdg.readthedocs.io/en/latest/maps/)

I have a geojson file saved in my data repository  and updated my config.yml
Everything works fine, but I donn't know what's the ID mentioned [here](https://open-sdg.readthedocs.io/en/latest/maps/#boundary-data-geojson) and where in the csv file have to add it.


I think the nameProperty is correct.

the unique ID in the geojson ist the AGS.  To my mind I have to add the values of AGS into the "Geocode" Column into my CSV file. Right?

snippet from my config.yml:
```

map_layers:
  -
    # [REQUIRED] The URL to the GeoJSON file for this layer:
    serviceUrl: https://github.com/christoph4711/open-sdg-data-starter/blob/develop/NI_GJ.geojson
    # [REQUIRED] The property in `properties` for each boundary's human-readable name
    nameProperty: NI_GJ
    # [REQUIRED] The property in `properties` for each boundary's unique ID (GeoCode). 
   idProperty: AGS
```


A _small_ snippet of my gejson file:

`{
"type": "FeatureCollection",
"name": "NI_GJ",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "ADE": 4, "GF": 4, "BSG": 1, "RS": "03101", "AGS": "03101", "SDV_RS": "031010000000", "GEN": "Braunschweig", "BEZ": "Kreisfreie Stadt", "IBZ": 40, "BEM": "--", "NBD": "ja", "SN_L": "03", "SN_R": "1", "SN_K": "01", "SN_V1": "00", "SN_V2": "00", "SN_G": "000", "FK_S3": "K", "NUTS": "DE911", "RS_0": "031010000000", "AGS_0": "03101000", "WSK": "1974\/03\/01", "DEBKG_ID": "DEBKGDL1000055XP" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 10.541354223536898, 52.347251399215594 ], [ 10.539209020792526, 52.345957050761037 ], [ 10.53420810532012, 52.342955163219997 ], [ 10.532007011228012, 52.337028588963307 ], [ 10.531811212023143, 52.331723524192043 ], [ 10.5316926939451, 52.32851173913221 ], [ 10.535274402962317, 52.328447784550157 ], [ 10.538591982348512, 52.328509718896392 ], [ 10.542189421955602, 52.329578747988606 ], [ 10.546375029832877, 52.331420892732083 ], [ 10.552020754442228, 52.338775330371448 ], [ 10.551960447905126, 52.340416799553012 ], [ 10.551928926980899, 52.341274716698308 ], [ 10.551849915105022, 52.343425072679288 ], [ ...},`

**Comment by brockfanning** [comment]
Referencing another issue which is a blocker for this one: #335

**Comment by brockfanning** [comment]
This issue is also needed for this one: #339

**Comment by Nachhaltige-Entwicklung-Deutschland** [comment]
@brockfanning I'm just trying to change the number of indicators and goals. I followed these instructions but unfortunately get an [error message](https://circleci.com/gh/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/62) from CircleCi. 

> As for how to control the number of goals and indicators, there is a way where you can control this entirely in the data repository. This is the approach I would recommend. The steps to do this would be:
> 
>     1. In your data repository, delete all the files under `data` and `meta` that you won't be using. For example, if you won't need indicator 1.3.1, then delete [this file](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/meta/1-3-1.md) and [this file](https://github.com/christoph4711/open-sdg-data-starter/blob/develop/data/indicator_1-3-1.csv).
> 
>     2. Delete [this folder](https://github.com/christoph4711/open-sdg-site-starter/tree/develop/_goals) completely (and all the files in it)
> 
>     3. Delete [this folder](https://github.com/christoph4711/open-sdg-site-starter/tree/develop/_indicators) completely (and all the files in it)
> 
>     4. Add `create_goals` to your _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#create_goals) for documentation.
> 
>     5. Add `create_indicators` to your _config.yml. See [here](https://open-sdg.readthedocs.io/en/latest/configuration/#create_indicators) for documentation.
> 
> 
> After these steps, your site should only display those indicators that exist in your data repository, and only those goals (topics) that the indicators belong to.

See my [data](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-data-starter) and [site](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter) repository. Have I made any mistakes?

By the way, this is MoBosse. I had to change my account.

**Comment by brockfanning** [comment]
@Nachhaltige-Entwicklung-Deutschland I think this is happening because of some incorrect metadata. For example see how the `indicator` field [here](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-data-starter/blob/develop/meta/11-1-2.md) says `11-5-2`, but should actually say `11-1-2`.

I suspect you'll need to go through each error in that CircleCI output (for example, `internally linking to /open-sdg-site-starter/4-c-1`) and figure out which indicator is incorrectly referring to that id (`4-c-1` in that example) and correct it.

**Comment by Nachhaltige-Entwicklung-Deutschland** [comment]
Yeah, pretty obvious, actually. I kind of missed it. sorry. 
It works now. thank you.

**Comment by angelamhkim** [comment]
@brockfanning I tried to follow these steps as well as the ones outlined [here](https://github.com/dawncomer/open-sdg-site-starter/issues/12) and got [this error](https://circleci.com/gh/dawncomer/open-sdg-site-starter/673) in Circle CI. It seems like it's a similar error to what @Nachhaltige-Entwicklung-Deutschland got but I can't seem to find the source of the error. All the 3.4.3 files I created refer to 3-4-3... Any ideas? This is the error text:

internally linking to /open-sdg-site-starter/3-4-3, which does not exist

**Comment by brockfanning** [comment]
@angelamhkim It looks like you fixed it - let me know if you are still having trouble.

**Comment by christoph4711** [comment]
I try to setup an new respository for another non SDG Metrics project.
two problems cam up:
1) the site respository has no workflow in circleCI, but the page will be build: [My site repository](https://github.com/christoph4711/WK-Site) an the [build page](https://christoph4711.github.io/WK-Site/) and last my [data repo](https://github.com/christoph4711/WK-Data)

2) After buildiing the site no goals or indicators will be shown. In my last [setup](https://github.com/christoph4711/open-sdg-site-starter)  [here](https://christoph4711.github.io/open-sdg-site-starter/) all Indicators have been shown after the first deployment. Is there anything new in the etarter repo I have missed?

**Comment by brockfanning** [comment]
@christoph4711 I haven't had time to look in detail, but I see that a lot of the activity in CircleCI is around the master branch. Out of the box, the staging deployment scripts assume you'll be working with a "develop" branch. Could that be the problem?

**Comment by brockfanning** [comment]
We'll close this for now and re-open individual tickets for specific issues that come up.
