### ISSUE TITLE
Can we add Markdown features to Metadata fields?

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#294]
E.g. can we use  ** ** to make text bold?

**Comment by brockfanning** [comment]
Markdown will only get converted into HTML if the Jekyll layout/include that renders it uses the `markdownify` filter. An example of where this is already being used is [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/indicator-content.html#L2). Right now, the metadata fields are not using that filter, as you can see [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/metadata.html#L32). But it should be fine to add the `markdownify` filter after the `t` filter, eg: `{{ meta[indicator_metadata.name] | t | markdownify }}`
