### ISSUE TITLE
Customise data notice which US site has

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#295]
Can we do this:
![image](https://user-images.githubusercontent.com/43404358/63017019-0bd9cc80-be8d-11e9-8320-824f8b7ffc83.png) (https://sdg.data.gov/17-3-2/)

But customise it e.g. have fields in metadata which provides text and colour?

**Comment by brockfanning** [comment]
The US site uses a [custom data file](https://github.com/GSA/sdg-indicators-usa/blob/develop/data/sdg_data_notices.csv) to manage those data notices. The "notice" column corresponds to a translation key in their [fork of sdg-translations](https://github.com/GSA/sdg-translations/blob/develop/translations/en/data_notice.yml). The template that renders it is [here](https://github.com/GSA/sdg-indicators-usa/blob/develop/_includes/components/indicator-content.html).

Controlling it in the metadata would also be a fine approach. 

The only worry I would have with giving control of the colour to data managers, is that some colours may result in insufficient contrast.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning on the test branch I have used the warning, danger and success styles that already exist so when high contrast mode is activated the colour of the box and the text changes to the correct colour. Maybe we could keep those and then add three more neutral colours (so we aren't using RAG) and then the data managers have a range of colours to choose from, which will also be accessible in both default-contrast and high-contrast?

**Comment by brockfanning** [comment]
I'll go ahead and close this, since the feature made it in.
