### ISSUE TITLE
Unit of measurement in map view

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#297]
The unit is currently not displayed anywhere in the map view. Is it possible to show the translated content of the csv-"Unit"-field somewhere in or above the map?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse @brockfanning Would we want to just add the same footers that the graph and table view have e.g.
![image](https://user-images.githubusercontent.com/43404358/63307767-810f2c80-c2e7-11e9-863c-1c7e432d3ad4.png)

**Comment by MoBosse** [comment]
It would be good if the name of the time series were also displayed. 
Nevertheless displaying the footers would be great as well.

However, this would create a new issue for us, as we currently use the footer-unit filed as a way to display a 'copyright' in a workaround (by using the translation).

blob:null/6bf8a4ee-3fdc-44e6-b378-c1c0d23c3995

Maybe it is possible to create a new footer field for that?

**Comment by brockfanning** [comment]
Yes it would be great to remove the need for that workaround. @MoBosse Do you think you could start a separate issue for that? My only question is: Would it be better to add a new "Copyright" field? Or would it be better to make the list of "footer fields" arbitrary/configurable?

In the meantime here we could brainstorm how these fields should appear on the map. Should it be another icon on the left side, which expands when clicked to reveal the fields? Or should it be only the unit of measurement, maybe displayed down near the "scale" in the lower right.

The upside of an icon on the left is that it will be the most unobtrusive approach. The downside is that users need to click on it to know what it is.

We'll want to keep in mind mobile. Though it might be fine on desktop to list a lot of fields, on mobile they might take up too much space.

**Comment by MoBosse** [comment]
![grafik](https://user-images.githubusercontent.com/50657629/63594618-3592a200-c5b7-11e9-92cd-40d0f900bb7b.png)

What actually has to be displayed is the name of the time series, its units (in the in the example of indicator 8.5.1 we show the values of time sieres "gender pay gap", (2-27%) but all you see in the map-view is the indicator title that says something of "average hourly earnings" what is kind of irritating) and the footer.
My suggestion is to place the footer fields underneath the map as in the picture of GB above and the name plus unit maybe above the bar in the upper right corner that shows the range of data.
