### ISSUE TITLE
ColorRange of maps depending on Goal-number

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#299]
Is there a possibility that the colorRange of the maps may vary from goal to goal? For example by giving the colorRange variable in _config something like a dictionary with lists of hex colors as values and the goal numbers as keys?

**Comment by MoBosse** [comment]
I tried to solve that for [this](https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-site-starter/) page by giving the 'colorRange' [here](https://nachhaltige-entwicklung-deutschland.github.io/open-sdg-site-starter/) a list of 17 lists of colorCodes and adress them [here](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/blob/develop/_includes/assets/js/plugins/leaflet.selectionLegend.js#L45-L46) and [here](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/blob/develop/_includes/assets/js/plugins/jquery.sdgMap.js#L78-L80) with the Goal-number. 
Although the code is not very nice, it works quite well. But, when I try to do the same for [this](https://g205sdgs.github.io/sdg-indicators/) page, it doesn´t work. When I want to change the color range as described, the maps are always displayed with the colors of chroma.brewer.BuGn.

Does anyone have any idea why??

**Comment by brockfanning** [comment]
We do have the map_options.colorRange for controlling the overall color range, but it's not per goal. This seemed to be difficult to implement. We've also found that the goal colors tend to fail accessibility color-contrast checks. We'll close this for now but please re-open if this is still an issue.
