### ISSUE TITLE
New row in Source

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#304]
How to add a very new field in Source as a "DATA SOURCE" row and  in which files should we add?

**Comment by LucyGwilliamAdmin** [comment]
@SDGArmenia if you add `source_url_1` and `source_url_text_1` to your metadata files, this should fix your problem. 
For example in the UK's metadata file for 1.1.1 we have:
source_url_1: https://data.worldbank.org/indicator/SI.POV.DDAY?locations=GB
source_url_text_1: Poverty headcount ratio at $1.90 a day (2011 PPP) (% of population)
This looks like this on the UK platform:
![image](https://user-images.githubusercontent.com/43404358/63172964-c48f3f80-c036-11e9-9b2c-eb42f7c632e8.png)

If you want to do this for source 2, 3, etc. just change the number at the end of the field name.

**Comment by brockfanning** [comment]
@SDGArmenia Did this resolve your question?

**Comment by brockfanning** [comment]
Cleaning up the queue a bit - please re-open if needed.
