### ISSUE TITLE
0.8.0 release

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#316]
Lots of new features including accessibility updates - time for 0.8.0?

**Comment by brockfanning** [comment]
Yes I think that would make sense, once we get in the accessibility fixes.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've put this together ready for the release once the two open PRs are closed. Do you think I've missed anything?

Changes:

* Translate regions on maps
* Translate each part of the combined disaggregation labels
* Set a body class for each layout
* Force a specific unit if needed when no headline data
* Use page.url instead of page.permalink
* Increase consistency by removing slashes before comparison
* Fixed typo in quickstart
* Fix search bar styling for IE and mobile
* Screen reader to read out disaggregation is expandable/collapsible and what state it is in
* Prefix social media platform links with platform name
* Clean up embed code and make more configurable
* Make search bar obvious to screen readers
* Give goal page title in format `Goal # - Goal title`
* Screen reader to indicate when check boxes are selected
* Add configurable data notice to indicator pages
* Stop disclaimer from overhanging if text is long
* Have list of sources in graph footer rather than just one
* Mobile menu fix
* Allow markdown in all visible metadata fields
* Added documentation for configurations

Open PRs
Optional alternative contrast button
Chart attributes changes from canvas to html

Breaking changes:
* You should be using SDG Translations 0.7.0 or higher before upgrading to this release
* Embedded feature configuration has changed. If you are using the embedded option you need to alter the metadata tags to account for these changes.
* In addition, if you have overridden any of the following files, check [this diff](link to comparison between 0.7.0 and 0.8.0) to see if you need to make any updates to your overriddes:
   * _includes/assets/js/indicatorModel.js
   * _includes/assets/js/indicatorView.js
   * _includes/assets/js/menu.js
   * _includes/assets/js/plugins/jquery.sdgMap.js
   * _includes/components/data-notice.html
   * _includes/components/metadata.html
   * _includes/footer.html
   * _includes/head.html
   * _includes/header.html
   * _includes/search.html
   * _layouts/indicator.html
   * assets/css/default.scss

**Comment by brockfanning** [comment]
I haven't gone over in detail, but this seems good to me. I usually try to put the PR numbers in parenthesis behind each item. Ie, `Translate map regions (#255)`.

Also we generally don't mention documentation changes in the changelog.

So I think if you could put this together as a PR to update [this file](https://github.com/open-sdg/open-sdg/blob/master/docs/changelog.md), that will be the last thing needed for 0.8.0!
