### ISSUE TITLE
More colors for bar charts

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#326]
If there are more than 6 time series, the colours are repeated in the bar chart.

![grafik](https://user-images.githubusercontent.com/50657629/63497010-3e09b080-c4c3-11e9-878e-dc5ba7a78e01.png)

Is it possible to provide more colours?

**Comment by MoBosse** [comment]
> I wonder if it's as easy as changing this line

Yes it is (doesn´t solve the problem with the not-dashed bars but you can easily add as many colors as you want). 
..which also gives you the opportunity to
a) use the sdg-colors:
![grafik](https://user-images.githubusercontent.com/50657629/65125503-c06b8e80-d9f5-11e9-8e4b-e7aef860888d.png)


or b) use shades of the current sdg-goal:
![grafik](https://user-images.githubusercontent.com/50657629/65125452-aa5dce00-d9f5-11e9-8bea-90476f64fcac.png)

see if-condition for approach b) [here](https://github.com/G205SDGs/sdg-indicators/blob/develop/_includes/assets/js/indicatorModel.js#L192)

**Comment by LucyGwilliamAdmin** [comment]
Should there be a way of customising this? At site level at least so countries can provide a long enough list of colours to make sure they aren't repeated in bar charts?

**Comment by brockfanning** [comment]
It does seem like this should be configurable. At least, there should be a way to do this without overriding the whole file. @MoBosse do you have any ideas on a way we could change the core code so that this could be done without overrides?

**Comment by MoBosse** [comment]
@brockfanning. How about this approach: The configurable part is in config.yml. Here you could be asked which colorset should be used. A possible selection would be 

1. The 6 default colors
2. The 17 SDG colors for every Indicator
3. A number of shades of the color of the current sdg goal
4. Passing a list with custom colors

The code for this could look like [this](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/blob/develop/_config.yml#L148-L159)

The necessary change of the core code would be in indicatorModel.js. Example [here](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/blob/develop/_includes/assets/js/indicatorModel.js#L194-L222)

**Comment by brockfanning** [comment]
@MoBosse This seems awesome to me. Just a couple of considerations about the config:
1. Since our chart-specific metadata fields start with `graph_` (like `graph_title` and `graph_type`) I was thinking maybe the site config could be `graph_color_set`, `graph_color_list`, etc? Or maybe if you wanted a more nested approach, something like:
    ```
    graph_colors:
        set: custom
        list: ['red','pink',etc..]
        number: 5
    ```
2. Maybe the values for the set could be simpler, like `default`, `sdg`, `goal`, etc?
3. Not a dealbreaker, but I wonder if the different set types (sdg, goal, etc.) could be done as Jekyll "includes", which maybe add some JSON to the global `opensdg` object. That way you wouldn't need to put all the options in indicatorModel.js - you could just check the `opensdg` object and use whatever is there. But again, not a dealbreaker, just a thought.

Lastly it would be great if you could start a PR for this. Looks promising!

**Comment by MoBosse** [comment]
Thank you for the suggestions @brockfanning. About Nr 3: I get the point of it but I don´t realy know of how to do that. I made a new js file in the includes folder containing all the set types etc (correct so far?), but I did not know how to adress that file from indicatorModel.js. Could you give me some more hints on how to do that? Otherwise I would start a PR for the code as it is now.

**Comment by brockfanning** [comment]
@MoBosse At the moment we have a very low-tech way to pass things around between javascript files: a global object called `opensdg`. So basically you can have:
```
<script>
opensdg.foo = 'bar';
</script>
```
And then later you can do:
```
<script>
console.log(opensdg.foo);
</script>
```

In the next major version (Open SDG 2.0) I think we'll have something a lot more sophisticated, but that's further down the line.

**Comment by MoBosse** [comment]
@brockfanning I placed all the stuff in [here ](https://github.com/Nachhaltige-Entwicklung-Deutschland/open-sdg-site-starter/blob/develop/assets/js/custom.js#L1) for testing but when I try to call opensdg.chartColors in indicatorModel.js it keeps saying "opensdg.chartColors is not a function". Do I have to activate/include it somewhere else?

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse yes, you need to point to the custom js file in the config.yml file using this:

```
custom_js:
  - /assets/js/custom.js
```

**Comment by MoBosse** [comment]
Thanks @LucyGwilliamAdmin! That worked.

**Comment by MoBosse** [comment]
Sorry @brockfanning and @LucyGwilliamAdmin but I have to ask again: It works to save my custom.js file in the "assets"-folder in the site-starter repo and point to it in config.yml, but actually I wanted to place the custom.js file in the "_includes"-folder in open-sdg. How can I point to it there?

custom_js:
  - /_includes/assets/js/custom.js

does not work.

**Comment by brockfanning** [comment]
@MoBosse The files in `_includes/assets/js` are where we put the platform's core code, so I agree that would make sense if you would like to get this feature into Open SDG. You'd probably want to name it something more specific, like `chartColors.js` or something.

But anyway, the steps would be:
1. Put the file where you would like, in that `_includes/assets/js` folder.
2. Update [this file](https://github.com/open-sdg/open-sdg/blob/master/assets/js/sdg.js) to "include" your new file

You have to be careful with placement, if your code needs to be available to another script. For example, if you need your code to be available in `indicatorModel.js`, then make sure you put it before [this line](https://github.com/open-sdg/open-sdg/blob/master/assets/js/sdg.js#L9).
