### ISSUE TITLE
Maps: enhancements and refactoring

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#33]
Right now there are 2 ways to get a "Map" tab to appear on an indicator page:

1. The integrated map can be shown by meeting these criteria:
    * The CSV data for the indicator includes a column called `GeoCode`
    * The indicator's metadata field `data_show_map` must be set to `true`
2. The indicator's metadata field `embedded_map_html` can include any arbitrary HTML (such as an iframe and/or some javascript)

A benefit of the integrated map is that it doesn't need to look elsewhere for statistical data. It re-uses all the statistics already in the CSV data being used for the charts and tables in the platform.

That said, there have been requests for enhancements on the integrated map, and some great work has been done to implement these features in a separate project, using the iframe approach mentioned above.

Let's try to re-visit the integrated map with a focus on leveraging third-party code as much as possible. A key goal is to maintain the integration with the CSV data, while also making it easier to add/change features. Focusing on a popular open-source mapping library would be a good way to meet that goal.

We may need to create separate tickets for each feature needed, but to get the conversation started, here is a list of requests for enhancements to the integrated map:

* More detailed legend
* Scale and compass
* Search function to find locations by name
* Disaggregation
* Nested zoom (showing more detailed subdivisions as zoom increases)
* Year slider with a "play" button
* Configurable base maps
* Full screen button
* Downloadable GIS data (including the SDG statistics)
* Mobile-friendly performance and interface

**Comment by brockfanning** [comment]
I'm working on a Leaflet-based implementation that I'll try to keep updated at [this demo site](http://brock.tips/sdg-site-maptest/4-2-1/), and in this PR: #34 

Here is some info on the features implemented so far:

* Full-screen button: provided by [this Leaflet plugin](http://leaflet.github.io/Leaflet.fullscreen/)
* Year slider with a "play" button: provided by [this Leaflet plugin](https://github.com/socib/Leaflet.TimeDimension)
* Configurable base maps: provided by core Leaflet
* Nested zoom: provided by [this Leaflet plugin](https://github.com/auto-mat/leaflet-zoom-show-hide)
* More detailed legend: A very [custom approach](https://github.com/brockfanning/open-sdg/blob/leaflet-map/_includes/assets/js/plugins/leaflet.selectionLegend.js) at the moment
* Download button: Using a [simple but custom approach](https://github.com/brockfanning/open-sdg/blob/leaflet-map/_includes/assets/js/plugins/leaflet.downloadGeoJson.js)
* Scale: provided by core Leaflet

**Comment by brockfanning** [comment]
Just compiling some the feedback given so far:
* It would be ideal for higher geography boundary (eg region) to continue to show (as a dashed
line for example) when you drill down to lower geography. This allows one to visually
identify areas within a higher geography.
* Needs compass/north sign
* The ability to select areas on the map and see the results next to the map is a good idea. However, there as to be care when showing stats for higher geographies in cases where some of
the lower geographies within the higher geography have no data.
* Selecting a region on the left does not seem to make the map zoom to/focus on that area and it
does not make the filter only the results for that region.

Did I miss any?

**Comment by brockfanning** [comment]
Documenting some notes/issues with the Leaflet demo above:

1. To make sure it stays mobile-friendly, I have tried to make sure that any "hover" functionality is unnecessary. Right now it does show the region names/values on hover, but mobile users can also get this info from tapping.
2. A possible problem with the nested zoom feature is that users may not even realize it exists. If a user never zooms in, they will never see that there is more granular data. Possible fixes for that:
    * Some help/instruction text
        * Fine, but does add some clutter
    * Automatically zoom in when clicking the top layer
        * Would be a bit confusing to see the higher boundary disappear when clicked (since the more lower geography does not include the boundaries of the higher geography). This would not be a problem if the above feedback were implemented (having the higher geography boundaries continue to show).

**Comment by Norric1Admin** [comment]
Excellent work ____
FYI all of the original 'Doug/Shane' maps are now removed from the UK NRP.
https://trello.com/c/7gZ5Yxh1/386-remove-in-progress-from-reporting-status-update-colour-scheme

**Comment by brockfanning** [comment]
Couple of updates:
* This feedback has been implemented: 
    > It would be ideal for higher geography boundary (eg region) to continue to show (as a dashed line for example) when you drill down to lower geography. This allows one to visually
    > identify areas within a higher geography.
* Improved the search functionality so you can search for regions that are not yet shown (because of the nested zoom)

**Comment by brockfanning** [comment]
Also changed the click behavior to auto-zoom, which avoids the problem where a user may not realize there is a nested zoom feature.

**Comment by brockfanning** [comment]
Added a couple of developer-oriented changes:
* Moved the configuration to the `_config.yml` file, so that no javascript needs to be overridden.
* Added documentation: https://github.com/open-sdg/open-sdg/blob/2f0f202b5e1e32f85a38979173a34b6b248ce5ef/docs/maps.md

**Comment by brockfanning** [comment]
There is a feature from MapTemplates that I haven't implemented in the Leaflet approach yet:  the line chart that appears when you hover over a region. Here's a screenshot of that in MapTemplates:

![maptemplates-timeline](https://user-images.githubusercontent.com/1319083/50601987-f8d93580-0e83-11e9-8b19-2fda28acfefd.png)

In MapTemplates the feature displays a line-graph showing the national average, with a point plotted to show the currently selected year/region combination. In other words it is designed to make it easy to compare/contrast a selected year+region with national average.

Since that will likely be a custom plugin, and will take up a decent chunk of screen space, I'll hold off until we discuss further how that should look/behave, if it's something we'd like to add at this time. Any thoughts?

**Comment by brockfanning** [comment]
I'll close this issue for now and we can open a new one for the next phase of mapping updates.
