### ISSUE TITLE
Sidebar is no longer hidden when map tab is selected

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#332]
![image](https://user-images.githubusercontent.com/43404358/63613177-0a6c7a80-c5d8-11e9-8cd6-f7eb604586db.png)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you have any idea what might have caused this to break?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'm having trouble recreating. I do notice that [this page](https://sdg.mango-solutions.com/0-8-0/4-2-1/) now has a series performance problem, and the javascript freezes up for a few seconds. We'll definitely want to take a look at that. But are you still seeing the problem from this issue?

**Comment by LucyGwilliamAdmin** [comment]
Ok, so not getting the issue with staging site but still getting it with live site even though there's no diff. I'll try rebuilding the live site to see if that fixes it

**Comment by LucyGwilliamAdmin** [comment]
Rebuilding the live site didn't work. Another thing that works on the staging site and not on the live site is the new high contrast button. I get this error in the console on the live site:
![image](https://user-images.githubusercontent.com/43404358/63637228-2886b900-c672-11e9-9536-ddc8cfa40dcd.png)
![image](https://user-images.githubusercontent.com/43404358/63637233-3a685c00-c672-11e9-945c-ea402997691a.png)

Are you getting something similar where it's working on the staging site but not on the live site?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It might be because the production config is pointing to an older version of sdg-translations. See here: https://github.com/ONSdigital/sdg-indicators/blob/develop/_config_prod.yml#L29

**Comment by LucyGwilliamAdmin** [comment]
Great, I've just upgraded and both things are working now. Thanks for your help!
