### ISSUE TITLE
Support indicators without targets / Changing Indicator numbering

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg#335]
.There is some code in Open SDG will need to be adjusted in order to support 2-part indicator ids (eg 1-1, 1-2, etc.) in addition to 3-part indicator ids (eg 1-1-1, 1-2-1, etc.).

continuing discussion from here: #293

Where do I change the Indicator numbering? I only need 1.1 to 1.22, 2.1 to 2.13. and so on....
I tried: 

Changing indicator: 1.1.1 to indicator: 1.1
produces an error:

Liquid Exception: undefined method gsub' for 1.1:Float in /_layouts/indicator-json.html jekyll 3.8.4 | Error: undefined method gsub' for 1.1:Float
Exited with code 1

renaming indicator_1.1.1.md to indicator_1.1.md
produces the following error

#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 90 metadata files...
data/indicator_1-1.csv [Errno 2] File b'data/indicator_1-1.csv' does not exist: b'data/indicator_1-1.csv'
Checking 90 metadata files...
Traceback (most recent call last):
File "scripts/check_data.py", line 24, in
raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

creating an new csv file indicator_1-1.csv produces the same Error

#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 90 metadata files...
data/indicator_1-1.csv [Errno 2] File b'data/indicator_1-1.csv' does not exist: b'data/indicator_1-1.csv'
Checking 90 metadata files...
Traceback (most recent call last):
File "scripts/check_data.py", line 24, in
raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

**Comment by christoph4711** [comment]
any new ideas here?

**Comment by brockfanning** [comment]
Overriding the indicator.html layout certainly works, though I agree it would be better if we could do this in a different way. The problem with overriding things is that they have to be considered when upgrading to a new version of Open SDG. This is not a big deal for small components, but would be a headache for something as large as the indicator.html layout.

Maybe a way to build on that `indicator_display` approach would be to create a new component called `indicator_id_display.html` which is purely to display indicator ids. Overriding that component would be easier (maintenance-wise) than overriding the entire indicator.html layout.

**Comment by christoph4711** [comment]
@brockfanning 
to build the new component indicator_id_display.html may be a way, but why I can't use the (existing) filenames instead e.g 
Indikactor 1 with 1.csv as data and 1.md as meta 
Indikactor 1.1 with 1-1.csv as data and 1-1.md as meta 
Isn't that easier than adding an new component or where do the numbers come from?

**Comment by brockfanning** [comment]
I think the challenge is that open-sdg is already hardwired to expect the three-part goal-target-indicator id numbers. But I don't know exactly where in the code, and to what extent. It might be very easy to change that hardwiring, or it might be a heavy lift.

So our options are:
1. Investigate the code, experiment a bit, and decide how difficult it will be to change the hardwiring to support indicators without targets, OR
2. Go ahead with something more like the indicator_id_display.html component idea.

**Comment by brockfanning** [comment]
@christoph4711 I did a quick test and made an indicator with a two-tier number, like "9.9". It seems to work fine, out of the box. This is using the latest code. Maybe some recent change has made this possible?

**Comment by brockfanning** [comment]
As far as I can tell, this is fixed. So I'll go ahead and close. But please re-open if you think that more is needed.
