### ISSUE TITLE
Case sensitive csv "value" and "Value"

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg#336]
May be an Error:

Using the word "value" in the csv file produceses following Error

#!/bin/bash -eo pipefail
. venv/bin/activate
python3 scripts/check_data.py

Checking 90 metadata files...
data/indicator_1-5-1.csv : Last column not called "Value", instead got  value
'Value'
Checking 90 metadata files...
Traceback (most recent call last):
  File "scripts/check_data.py", line 24, in <module>
    raise RuntimeError("Failed checks")
RuntimeError: Failed checks
Exited with code 1

Using "Value" instead and everything is working fine.

**Comment by christoph4711** [comment]
I saw it, but obvisioly i haven't read it exactly.

**Comment by brockfanning** [comment]
Cleaning up the queue a bit - please reopen if needed.
