### ISSUE TITLE
Branches not building

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#345]
Branches made from master don't seem to be building e.g. [scaled-graph](https://circleci.com/gh/open-sdg/open-sdg/1011) even though the [last build of the master branch](https://circleci.com/gh/open-sdg/open-sdg/1005) passed

**Comment by LucyGwilliamAdmin** [comment]
I've just rebuilt master to see if that still passed and it didn't.
@brockfanning does this mean it's something to do with something open-sdg is pointing at? e.g. sdg-build or sdg-translations?

**Comment by LucyGwilliamAdmin** [comment]
Will merging in #344 fix this?

**Comment by brockfanning** [comment]
I suspect you're right, yes. I've just merged it. Though, existing branches won't automatically get fixed - they'll need to have the latest master merged (or rebased) into them. Or if it's easier, close the failing branches and recreate new ones.

**Comment by LucyGwilliamAdmin** [comment]
This has been fixed now #344 has been merged in to master.
