### ISSUE TITLE
Not showing data

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#350]
Why is this indicator not showing data?
https://armstat.github.io/sdg-site-armenia/1-5-1/

**Comment by MoBosse** [comment]
You have to change reporting_status [here](https://raw.githubusercontent.com/armstat/sdg-data-armenia/develop/meta/1-5-1.md) from "notstarted" to "complete"

**Comment by LucyGwilliamAdmin** [comment]
Hi @SDGArmenia following changing the reporting status you will also need to rebuild sdg-site-armenia on Circle CI by going to the latest build of sdg-site-armenia (which I think is [this](https://circleci.com/gh/armstat/sdg-site-armenia/420) at the moment) in order for the changes to the metadata file to take affect.

**Comment by brockfanning** [comment]
Cleaning up the queue a bit - the question was answered so I will close. Please re-open if needed.
