### ISSUE TITLE
min max value in maps

### ISSUE THREAD

**Issue by christoph4711** [open-sdg/open-sdg#356]
In my map [here](https://christoph4711.github.io/open-sdg-site-starter/1-2-1/) in the map legend the max vaule is displayed with 268505 which is not displayed on the map, because this value is a aggeregation of a couple of cities, what I need to have in the table an the graph view, but can't (yet)  display on the map. In the following the classses displayed on the map are too large...

![grafik](https://user-images.githubusercontent.com/53389268/64840361-7b151e80-d5fb-11e9-9b8c-8998b5fd42d3.png)

It is possible to set a min and max vaule for the map? Or may be the min and max vaule can be caluclated for each year from the data that has a GeoCode, data without GeoCode should be ignored.

**Comment by brockfanning** [comment]
@christoph4711 I'm not sure, but the problem may be related to #109. If so, a quick fix would be to remove the GeoCode from all rows that are maennlich or weiblich. In theory this might fix the problem.

Though of course a better fix would be if we could resolve #109, and an even *better* fix would be if we could come up with a way to work disaggregation into the maps.

**Comment by brockfanning** [comment]
The map functionality had somewhat of a rewrite in version 1.0.0, so I'm curious to know if this is still an issue. Any updates would be appreciated.

**Comment by LucyGwilliamAdmin** [comment]
I didn't create this issue but here are my comments from looking at this UK feature branch:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/map-tooltip-fix/3-a-1/

Looks like min and max values on legend aren't min and max of what is currently shown on map e.g.
Table:
![image](https://user-images.githubusercontent.com/43404358/86583489-48b62280-bf7b-11ea-9db6-939ac5b17d76.png)

Map:
![image](https://user-images.githubusercontent.com/43404358/86583529-59669880-bf7b-11ea-8c3f-9d60b7900a9b.png)

Max value is fine (23.3578 (23.4 to 1d.p) is Scotland 2011 value) but 12.9203.. (12.9 to 1d.p) isn't a minimum - min value for 2011 is Northern Ireland (18.9) and min value overall is England 2018: 14.4

However when zoom in to lower level of map, 12.9203.. is min value for South East in 2018

**Comment by WohnungNDS** [comment]
@brockfanning 
@LucyGwilliamAdmin 

In my [map](https://wohnungnds.github.io/WK_Site/1-1-1/), the min an max values are not right. It looks like the min an max values are from the whole dataset except the percent values of Neubau_Anteil

![grafik](https://user-images.githubusercontent.com/67795376/87336925-e775ec80-c542-11ea-8863-68d535266091.png)

Especially when changing the category to "Neubau_Anteil" which is the percentage of new build houses (0% to 100%) the min and max values remain between 25540 and 596488

![grafik](https://user-images.githubusercontent.com/67795376/87337123-3f145800-c543-11ea-8753-dffce8cb808c.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Looking at the code, I think your suspicion is correct that it is looking through all available layers for the absolute minimum and maximum, and keeping those constant even as the user zooms in/out. A different approach might be to only look at the visible layer for the min/max, and then to re-calculate this whenever the user zooms in/out. To me this makes sense - the different layers are really like completely different maps, so it seems correct to re-calculate whenever that changes. What do you think?

**Comment by WohnungNDS** [comment]
Min mx values in my map is wrong as you can see here [indicator 4.1.2](https://wohnungnds.github.io/IM_Site/4-1-2/)
the min value is greater than the mx value

[data repo](https://github.com/WohnungNDS/IM_Data)
[site repo](https://github.com/WohnungNDS/IM_Site)

![image](https://user-images.githubusercontent.com/67795376/137262565-ab7b6738-6b17-4e56-9bb6-022b7b0ee18f.png)

**Comment by brockfanning** [comment]
@WohnungNDS The reason that is happening is that you have some dashes in your data under the "Value" column. This is causing the code to interpret all the values as text (strings) and that means that the min/max behavior is looking at alphabetical order - eg, "84" is considered greater than "105", because "8" is after "1". The fix here would be to remove the rows that have dashes as values. Here is an example: https://github.com/WohnungNDS/IM_Data/blob/develop/data/indicator_4-1-2.csv#L277

If it is important that they be in the CSV files, you could maybe get around the problem by just removing the dashes themselves, but leaving the rows.

**Comment by brockfanning** [comment]
I believe that the questions remaining in this issue are:

1. Should the color legend (for want of a better term) be dynamic based on the current year?
2. Should the color legend be dynamic based on the visible zoom layer?

I feel like this is a design question that might need user research. One nagging question I have is - is that color legend even useful at all? Maybe this could be a "discussion" or we could talk at the next tech call.

**Comment by brockfanning** [comment]
We'll limit this to the bug reported in the first post here.

**Comment by LucyGwilliamAdmin** [comment]
I have created a discussion for the remaining questions: https://github.com/open-sdg/open-sdg/discussions/1501

**Comment by brockfanning** [comment]
Regarding the original bug reported here - I believe it has been fixed since the time of posting. I just tried locally and can't recreate the issue (rows of data affecting the min/max that don't have geocodes). So I'll go ahead and close this, but please re-open if needed!
