### ISSUE TITLE
Title tags on goal pages lack the short name

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#359]
The `<title>` tag in the `<head>` on goal pages is missing the short name. Ie, instead of `Goal 1 - End poverty in all its forms everywhere` it just has `Goal 1 -`.

**Comment by LucyGwilliamAdmin** [comment]
Started taking a look at this. Changed `page.short` to `goal_short` [here](https://github.com/open-sdg/open-sdg/blob/tab-title-fix/_includes/head.html#L23) but for some reason I am getting [this Circle error](https://circleci.com/gh/open-sdg/open-sdg/1091)

**Comment by LucyGwilliamAdmin** [comment]
[This](https://github.com/open-sdg/open-sdg/blob/tab-title-fix/_includes/head.html) seems to work now. Will make new branch and create PR.
