### ISSUE TITLE
min_ /max_value with multiple units

### ISSUE THREAD

**Issue by JustusCas** [open-sdg/open-sdg#361]
I just tried the min_ /max_values (very cool) and noticed that they are fixed when changing the unit see [here](https://g205sdgs.github.io/sdg-indicators/12-2-1/).
Is there a possibility to define min_/ max_values, which are connected to the respective unit?

**Comment by brockfanning** [comment]
Ah, I don't think we considered that - but that's a great point.

@JustusCas @LucyGwilliamAdmin 
Can I step back a bit and ask - what is the behavior without defined min/max values? I'm just wondering if maybe we can make the default behavior good enough that defining min/max might be unnecessary.

**Comment by LucyGwilliamAdmin** [comment]
Not entirely sure what the default behaviour is for max - sometimes the max value on the axis is the max value in the data, sometimes it isn't. Min value is always zero by default

**Comment by brockfanning** [comment]
I'm thinking we should do this for 1.0.0, because it will likely involve some changes in API.

**Comment by brockfanning** [comment]
I'm looking at a couple of ways of controlling this in the indicator metadata.

Approach 1: one list of objects
```
graph_limits:
  - unit: tons
    minimum: 0
    maximum: 4
  - unit: passengers
    minimum: 50
    maximum: 450
```

Approach 2: three separate lists of values
```
graph_limit_units:
  - tons
  - passengers
graph_limit_minimums:
  - 0
  - 50
graph_limit_maximums:
  - 4
  - 450
```

Approach 1 seems more easy to understand quickly, but it requires more finesse with the YAML syntax. Also it could not be done in the Prose.io interface.

Approach 2 is a little harder to understand, but it is simpler, YAML-wise. And it could be done in the Prose.io interface.

**Comment by brockfanning** [comment]
This can be tested in #497, though it depends on another PR in sdg-build.
