### ISSUE TITLE
Selection of categories is reset when the unit is changed

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#366]
A little hard to explain, but I do my best:

In [this example](https://g205sdgs.github.io/sdg-indicators/en/2-5-2/) there are three time series. Two of them have the unit % and one have the unit "Number".

First issue is, that you have the possibility to select the third time series even though unit % is selected.

The second issue is that if % is selected and you select the third time series (no data is shown) and you now change the unit to "Number" the selection of the third time series gets lost and changes to the default selection.

**Comment by brockfanning** [comment]
This indeed a thorny problem, and the code related to it (mostly [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js#L584) and [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorView.js#L78)) is kind of "best guess". So I'm not surprised there are bugs still.

It'd probably be obvious if I thought about it, but just to avoid confusion, @MoBosse can you describe the expected (ideal) behavior in both of these situations?

**Comment by MoBosse** [comment]
@brockfanning 
Perhaps it would be best if the possible choice of time series were dependent on the selected unit.
For example: Suppose there are three time series A (%), B (Number) and C (% and Number). 
If % is selected, only A and B should be selectable.
![grafik](https://user-images.githubusercontent.com/50657629/65421664-94407b00-de04-11e9-8995-e8e75bbd4cd8.png)

If you change the unit only B and C should be selectable.
![grafik](https://user-images.githubusercontent.com/50657629/65421834-0fa22c80-de05-11e9-948a-d580457dadaf.png)

If C is selected, when the unit is changed, this selection should be retained.
It would also be good if the dropdown menu didn't close every time the unit was changed.

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse is this still an issue? - I'm looking at your original example (https://g205sdgs.github.io/sdg-indicators/en/2-5-2/) and looks like they're no longer resetting

**Comment by MoBosse** [comment]
@LucyGwilliamAdmin You are right. This seems to be solved.
