### ISSUE TITLE
Change Global Title

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#375]
How to change global title in Armenian and in Russian?
![Title](https://user-images.githubusercontent.com/46884106/66122920-f6159780-e5f1-11e9-95aa-cba098a6feff.jpg)

**Comment by brockfanning** [comment]
@SDGArmenia This can be controlled in the `_config.yml` file with the [frontpage_heading](https://open-sdg.readthedocs.io/en/latest/configuration/#frontpage_heading) setting.

Another alternative way is to override the default "frontpage.heading" translations.

To do that, you could copy three files ([ru](https://github.com/open-sdg/sdg-translations/blob/master/translations/ru/frontpage.yml#L1), [am](https://github.com/open-sdg/sdg-translations/blob/master/translations/am/frontpage.yml#L1), and [en](https://github.com/open-sdg/sdg-translations/blob/master/translations/en/frontpage.yml#L4)) into your `data/translations/*` folders. So you would have these files:
* data/translations/ru/frontpage.yml
* data/translations/am/frontpage.yml
* data/translations/en/frontpage.yml

Then you could edit those files and control the "heading" as needed.
