### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by TenZeroOne** [open-sdg/open-sdg#376]
Nice project but not everyone is keen or willing to use either GitHub, CircleCI or furthermore Travis . . . lots of reasons behind this choice

There was a nice question: "Guides on hosting and automation #15" that has been closed without any answer.

Why don't you put together a simple guide in how to Self-Host SDG? Or at least the steps required, like OS (can I run it on CentOS?); Python version? Jekyll version? Ruby version? Space required?  ???

Thank you for your answer

**Comment by brockfanning** [comment]
Hi @TenZeroOne, thanks for the question. We can use this thread to figure out what needs to be added to our [documentation](https://open-sdg.readthedocs.io/en/latest/).

Usage of this platform requires three parts:
1. Version control
2. Automation
3. Hosting

I know it's not what you're asking, but just for explanatory purposes, that most commonly-used cloud-based approach uses the following free services:
1. Version control - Github.com
2. Automation - CircleCI.com
3. Hosting - Github.com (Github Pages)

I've recently been [experimenting with GitLab.com](https://github.com/open-sdg/open-sdg/issues/362), and will be putting up documentation soon on using that approach:
1. Version control - GitLab.com
2. Automation - GitLab.com
3. Hosting - GitLab.com

If you'd like to completely avoid all cloud services, there are limitless options. I have never tried it, but if I were to, I'd probably start with self-hosted [GitLab Community Edition](https://about.gitlab.com/install/?version=ce). I believe this would cover all three:
1. Version control - GitLab
2. Automation - GitLab
3. Hosting - GitLab

Or you could mix-and-match based on what you are comfortable with. For example:
1. Version control - Gogs
2. Automation - Jenkins
3. Hosting - Nginx

If you are not completely opposed to using cloud services, you could self-host some parts but not others. For example:
1. Version control - Github.com
2. Automation - CircleCI.com
3. Hosting - Apache

Lastly - note that your choice for the "Hosting" part can differ for staging vs. production. In other words, you might use Github.com for hosting your staging site, and self-hosted Apache for hosting your production site.

Also to address some of your specific questions:
* OS (can I run it on CentOS?): It would depend on which part you're talking about, but in general I would expect any flavor of Linux to be fine.
* Python version: Python would only be needed for the "automation" part, and the [sdg-build](https://github.com/open-sdg/sdg-build/) library sets the requirement there - Python 3.5 or higher.
* Jekyll version: I don't believe we've got that documented/tested, and would welcome any feedback if you find a version of Jekyll that doesn't work. I know that Jekyll 3.8.4 works.
* Ruby version: This would depend on whatever Jekyll needs. I've been using Ruby 2.5.1 locally.
* Space required: I assuming you're asking about the "hosting" part mainly? This would depend on how many indicators/pages/uploads/etc you've got, and how many languages the site is translated into. On average I would expect the built site to take up roughly 25MB - multiplied by the number of languages you're using. (Ie, English only - 25MB, English + Spanish - 50MB, etc.)

**Comment by brockfanning** [comment]
A bit of an update here:

With the launch of "Github Actions", Github can handle all three aspects:
1. Version control - github.com
2. Automation - github.com
3. Hosting - github.com

And as mentioned above, all of this can be done with Gitlab as well:
1. Version control - gitlab.com (or self-hosted Gitlab)
2. Automation - gitlab.com (or self-hosted Gitlab)
3. Hosting - gitlab.com (or self-hosted Gitlab)

The only downside of Gitlab, at this time, is that you lose the Prose.io data management tool. But this is not a huge loss.

**Comment by brockfanning** [comment]
I hope this answered the original question, so I'll close the issue. Feel free to re-open if needed.
