### ISSUE TITLE
Can't hide metadata fields

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#379]
I'm trying to hide the indicator sort order field as the main reason that exists is to tell the site how to behave so I've changed the prose file so that 

`- name: "indicator_sort_order"`
        `field:`
            `element: text`
            `label: "Indicator display order (within Goal page)"`
            `scope: global`

becomes

`- name: "indicator_sort_order"`
        `field:`
            `element: hidden`
            `label: "Indicator display order (within Goal page)"`
            `scope: global`

However this doesn't seem to hide the field.

**Comment by LucyGwilliamAdmin** [comment]
If I change `element` to `hidden` and `scope` to `data`, this removes the field but is this the correct behaviour or should the field be hidden just by changing `element` to `hidden`?

**Comment by brockfanning** [comment]
The best way to prevent a field from displaying would be to give it a "scope" of "data". Eg:

```
scope: data
```

**Comment by LucyGwilliamAdmin** [comment]
Ok, thanks - this worked!
