### ISSUE TITLE
Overwriting of files not working properly

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#382]
So when I try to overwrite a file in uk sdg-indicators repo, I get this Travis error:

![image](https://user-images.githubusercontent.com/43404358/67017642-f6ce2380-f0f1-11e9-9f0a-bf38e5cf7dae.png)

When I also overwrite the file mentioned in the error, the error goes away.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Is it possible that the tag number in remote_theme was pointing to a version of Open SDG that didn't include the [edit-buttons.html file](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/edit-buttons.html). I think that file only exists in the very latest tag, 0.9.4.

**Comment by brockfanning** [comment]
I think this was resolved, but please re-open if needed.
