### ISSUE TITLE
adding horizontal line to charts for target metric

### ISSUE THREAD

**Issue by angelamhkim** [open-sdg/open-sdg#384]
is there a way to add horizontal lines to the charts to show what the target metric is? 
http://rpubs.com/angelamhkim/test
![image](https://user-images.githubusercontent.com/31169340/67034622-da6bc000-f0cc-11e9-837f-f8921554ec68.png)

**Comment by LucyGwilliamAdmin** [comment]
The top answer on this question explains how it could be done:
https://stackoverflow.com/questions/42691873/draw-horizontal-line-on-chart-in-chart-js-on-v2?rq=1

**Comment by brockfanning** [comment]
As for how it would be controlled, I would guess a special metadata field. And it would need to have multiple values, one for each unit of measurement.

**Comment by LucyGwilliamAdmin** [comment]
Fixed in #912
