### ISSUE TITLE
Values on the labels in maps do not get updated

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#385]
When changing the year, the map-color and the bar chart are getting updated, but the value on the label is not.

![grafik](https://user-images.githubusercontent.com/50657629/67193094-02bd2c80-f3f5-11e9-8866-73d63ef6f6d7.png)

![grafik](https://user-images.githubusercontent.com/50657629/67193179-2b452680-f3f5-11e9-82fd-034bf42e9417.png)

**Comment by brockfanning** [comment]
Sounds like our "tooltips" are not getting updated by the year change. This may take some fiddling, but here are some relevant lines of code:
* The callback function that fires when the year is changed: https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/jquery.sdgMap.js#L240
* The code where the tooltips are originally added: https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/plugins/jquery.sdgMap.js#L130
