### ISSUE TITLE
Bump nokogiri from 1.10.3 to 1.10.4

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#386]
Have had a few security issue emails re bumping nokogiri from 1.10.3 to 1.10.4 so using most recent. Are we alright to upgrade or is there is reason why we're using 1.10.3?

@brockfanning

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I don't know of any reason not to upgrade, so my guess is that it would be fine.
