### ISSUE TITLE
How to add and translate National Metadata?

### ISSUE THREAD

**Issue by SDGArmenia** [open-sdg/open-sdg#387]
I want to fill in the empty fields for the National metadata and translate it into Armenian and Russian.
(https://armstat.github.io/sdg-site-armenia/8-4-2/)

**Comment by brockfanning** [comment]
@SDGArmenia The first step would be the translations. You will decide:

1. **What translation file to put them in?** Perhaps it makes sense to put all metadata translations in your "meta.yml" files ([Armenian](https://github.com/armstat/sdg-site-armenia/blob/develop/data/translations/am/meta.yml), [Russian](https://github.com/armstat/sdg-site-armenia/blob/develop/data/translations/ru/meta.yml), [English](https://github.com/armstat/sdg-site-armenia/blob/develop/data/translations/am/meta.yml)).
2. **What to call them?** This "key" is arbitrary. For example, if you are translating an indicator description for 8.4.2, you might call it `description-8-4-2`.

So, in the example above, you might add the following to `data/translations/en/meta.yml`:
```
description-8-4-2: This is my description for indicator 8.4.2
```

Next you would do the same for the other languages (adding to `data/translations/am/meta.yml` and `data/translations/ru/meta.yml`).

Finally you would reference these translations in the metadata file. To follow the example above, you would edit the [metadata file for 8.4.2](https://github.com/armstat/sdg-data-armenia/blob/develop/meta/8-4-2.md) and add the following:
```
national_indicator_description: meta.description-8-4-2
```

The value "**meta.description-8-4-2**" is called a "translation key", and it comes from a combination of the filename ("meta.yml" in the example above) and the "key" you chose ("description-8-4-2"), joined by a dot: `meta.description-8-4-2`

**Comment by SDGArmenia** [comment]
I did it but I have a problem with the Unit of measurement: it is not shown on the site.  I added a translation (unit-8-4-2: mln. drams, drams, %)In meta.yml  file and a referance (national_unit_of_measurement: meta.unit-8-4-2) in 8-4-2.md file.

**Comment by brockfanning** [comment]
@SDGArmenia Sorry for the delay. It looks like you got it working - at least I'm seeing that field (unit of measurement) on your site. Let me know if there are any remaining issues.
