### ISSUE TITLE
Edges issue

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#390]
Looking at this [feature branch](https://sdg.mango-solutions.com/3-3-2-deploy/3-3-2/), you can see that there's still a problem with the edges.

First of all it says Ethnic Group is 'Available when 'Country' is selected' but looks as if it actually dependent on 'Country of birth'

![image](https://user-images.githubusercontent.com/43404358/68482490-9eda9680-0231-11ea-9edd-ff210aaa9b0f.png)

![image](https://user-images.githubusercontent.com/43404358/68482569-c893bd80-0231-11ea-9ca3-0ae7321ea3ed.png)

![image](https://user-images.githubusercontent.com/43404358/68482608-da756080-0231-11ea-81bf-c2a8c9cc3553.png)

![image](https://user-images.githubusercontent.com/43404358/68482849-540d4e80-0232-11ea-8a0f-4e139b5ad9b4.png)

**Comment by brockfanning** [comment]
Estimate: This has the potential to be tricky and possibly involve changes in sdg-build, so I would estimate between 5-15 hours.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Unfortunately the feature branch isn't there anymore. Do you have any ideas on how to recreate this problem?

**Comment by LucyGwilliamAdmin** [comment]
This particular indicator actually seems to be fine on [live site](https://sustainabledevelopment-uk.github.io/3-3-2/), maybe it was fixed with data layout. I will see if I can find another example.

**Comment by brockfanning** [comment]
I haven't been able to find any examples of this, though I strongly suspect there is some combination of data that could still trigger this. Do you think we should close for now?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning found example on Kyrgyzstan site:
https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/en/4-3-1-1a/

**Comment by LucyGwilliamAdmin** [comment]
Although this looks like it's because each of the Age breakdowns is connected to one of the Education level breakdowns

**Comment by McCraeJames** [comment]
Hi all, we're getting this issue with 4.2.1 feature branch - http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_4-2-1/4-2-1/

Ethnic group isn't appearing under ethnicity and learning sub category (lower) doesn't appear under learning sub category (higher); all of them are currently appearing under region.

**Comment by denzil86** [comment]
Hi, I am getting the same problem as James with the following feature branch. Also data is able to be selected without selecting a mandatoryfield. For example you can select an English Region when Wales is selected 

http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/datapreview_2-2-2/2-2-2/

**Comment by brockfanning** [comment]
At the moment, I can't view the 4.2.1 example - in my browser (Firefox) I keep getting the "A web page is slowing down your browser" message. I think that some javascript is interacting with the data in a bad way. I'll have to look more into that.

By contrast the 2.2.2 example loads quickly for me. One clear bug is that sorting of the subcategories alphabetically, even when there is supposed to be a hierarchy. I think we could maybe tackle that separately, so I'm opened a separate issue about it: #817

**Comment by brockfanning** [comment]
Also a note that I created #818 as a separate issue to investigate how we can better support large datasets (like the 4.2.1 example above).
