### ISSUE TITLE
Download chart CSV not including added series

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#392]
This needs confirmation but there does seem to be a problem related to headlines and the "Download chart CSV" button. For demonstration, try the button here: https://kazstat.github.io/sdg-site-kazstat/en/1-2-1/

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning It seems to work for me - although I know there was a problem with the button on IE

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I was vague before, sorry. For me it's downloading ok, but the file only has one column: Year. Are you seeing the same?

**Comment by LucyGwilliamAdmin** [comment]
Ah right, yes just opened it and get the same tging

**Comment by LucyGwilliamAdmin** [comment]
Yeah and when an indicator does have headline data and more time series are added, the downloaded csv only has the year and headline data

**Comment by brockfanning** [comment]
Estimate: This has the potential to be a thorny problem, but to start I would estimate about 5-10 hours.
