### ISSUE TITLE
Planning for version 1.0.0

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#393]
In order to get ready for version 1.0.0, we need to make sure we are happy with the "API" - aka, the way this platform responds to the various inputs, configurations, data, and content that site builders feed it. Releasing 1.0.0 is kind of like setting that API in stone. Once we release 1.0.0, any changes to that API would likely require a jump to 2.0.0. So we should go through the platform and confirm that we're happy with things.

Here are some ideas of things we might want to look for:

1. What site configuration settings are required? (By "required" I mean that without them the build will fail, or some necessary content will be missing.) Are there any that we could make optional or remove altogether? Are the required configuration settings named in a logical way?
2. What indicator metadata fields are required? (By "required" I mean that without them the build will fail, or some necessary content will be missing.) Are there any that we could make optional or remove altogether? Are the required fields named in a logical way?
3. What backwards-compatibility code do we still have in the platform? Releasing 1.0.0 is our chance to remove that excess code, thereby making the platform more consistent and clear.
4. In looking through the issue queue, or there any features/fixes still to do which might affect the API? If so, we might consider completing those before releasing 1.0.0. (I'll create an issue tag called "1.0.0 blocker").

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @SavvasStephanides @AnnCorp FYI I've just merged #394 which contains several breaking changes. Most/all countries should be "pinned" to a particular version of Open SDG, but it's something to keep in mind. If any countries have trouble, they can try pinning to the most recent tag, 0.10.0.

This is a step towards releasing 1.0.0. I've also started a PR for documenting the changes: #403 

Let's continue to think about other changes we need/want to make before 1.0.0 is release.

On a related note - this platform relies heavily on three other projects:
1. [sdg-translations](https://github.com/open-sdg/sdg-translations)
    I don't have a problem with going ahead and releasing 1.0.0 of that project. It would be nice to make sure there are no empty translations.
2. [sdg-build](https://github.com/open-sdg/sdg-build)
    This is probably close to being ready for 1.0.0. I've submitted an experimental PR along these lines, [here](https://github.com/open-sdg/sdg-build/pull/77). There may be other issues that should be done too, like [this one](https://github.com/open-sdg/sdg-build/issues/24).
3. [jekyll-open-sdg-plugins](https://github.com/open-sdg/jekyll-open-sdg-plugins)
    This is basically an extension of open-sdg, and so should go to 1.0.0 at the same time that open-sdg goes to 1.0.0.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning thanks for the info.

Just want to double check if we are happy for translations to come from Google Translate? If so, I can fill in the empty translations.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Sorry I didn't reply to this. I'm fine with Google Translate as a first step, to get things moving.

**Comment by brockfanning** [comment]
We've been doing this planning through that "project", so I'll close this.
