### ISSUE TITLE
Error when creating a branch

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#395]
I just created a branch from develop and got [this error](https://circleci.com/gh/open-sdg/open-sdg/1132) (even before I made any changes):

![image](https://user-images.githubusercontent.com/43404358/69241328-7c803b80-0b96-11ea-8ea5-76378fdcf890.png)

**Comment by LucyGwilliamAdmin** [comment]
Maybe something to do with this line:

https://github.com/open-sdg/open-sdg/blob/17e837f8db45f263cbf2ba123df457debbeae57f/_layouts/indicator.html#L24

@brockfanning I can see you've made the indicator names translatable on the data testing repo - could this be something to do with that?

**Comment by brockfanning** [comment]
Sorry, yes probably something I did recently. I'm looking into it now.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin PR up at #397
