### ISSUE TITLE
Page title not showing correctly on Kyrgyzstan site

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#396]
![image](https://user-images.githubusercontent.com/43404358/69257789-87959480-0bb3-11ea-813f-73f0c4689145.png)

Tab title just shows "Goal -" instead of "Goal 1 - No poverty" - not sure why since it's using open-sdg 0.9.3 so should have the feature and its working for UK and Kazakhstan..

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe there was a goal-related fix in 0.9.4.

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning 

Upgrading to 0.9.4 fixed this so closing
