### ISSUE TITLE
Investigate using Github Actions for automation

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#398]
Github has rolled out a new CI/CD service called [Github Actions](https://github.com/features/actions). It's apparently free for public repositories, similar to TravisCI and CircleCI. We should give it a try and see if it could be supported easily. It could potentially simplify the getting started process just like [using Gitlab can](#362), particularly with regards to SSH keys.

**Comment by brockfanning** [comment]
Estimate: The investigation should only take about 5 hours. If this looks like it's worth doing, I would estimate another 5-10 hours to test it out and get it working. After that, probably another 3-4 hours to update all the docs. So altogether 13-19 hours if all goes well.

**Comment by brockfanning** [comment]
This investigation went well, and the results are that GitHub Actions would be an improvement by removing the SSH key stuff from the quick start. It also allows for a simpler quick start, because of fewer steps. Making this change would involve three PRs:
1. A documentation PR here (#420)
2. An update of open-sdg-data-starter (https://github.com/open-sdg/open-sdg-data-starter/pull/20)
3. An update of open-sdg-site-starter (https://github.com/open-sdg/open-sdg-site-starter/pull/45)

A few notes:
1. There's a bug being discussed [here](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true) that, if resolved, will actually make our Quick Start even easier. There's a section involving "Access Tokens" that is only necessary because of that bug.
2. This change does remove the need for SSH keys, which is great. Triggering the site repo from the data repo should be possible, but will require the aforementioned "Access Tokens". So I think it could be separate from the quick start. Maybe in a separate ticket?
3. I was able to get the setup of the automated testing worked into the quick start as well, which is nice because after people are done with the quick-start, they should have working automated tests.

This one is a big tricky to test. The obvious options are:
1. Look at the "files changed" of the 3 PRs and try to go through them as a new user.
2. Go ahead and merge the 3 PRs, then try to go through them as a new user. (Reverting them afterwards if they didn't work.)

I'm fairly confident in the PRs (did plenty of testing myself) so I would feel comfortable with the second option.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning This sounds good.

Agree that we should have data repo triggering site repo as a separate ticket.

Also happy for option 2 for testing.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Cool - if you could approve the 3 PRs I'll merge, and we can start testing it out.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @SavvasStephanides @AnnCorp We've not got an updated Quick Start, which uses GitHub Actions. I'll be going through it as a new user, to make sure it works. I'll report any issues.

Note that it no longer requires "forking". GitHub also introduced a new feature called "template" repositories, and I've made the starter repos both "templates".

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I've just tried to follow the quick start instructions to create a repo and it's definitely a lot easier but I seem to have come across an issue:

I've got to point 8 on _Update the site Jekyll configuration_ but it's not passing the checks: https://github.com/LucyGwilliamAdmin/sdg-site-lucy/pull/1/checks
```
Unable to fetch remote data from: https://LucyGwilliamAdmin.github.io/sdg-data-lucy/en/meta/all.json
404 Not Found
##[error]Process completed with exit code 1.
```
Looks like it's expecting the metadata to be within an 'en' folder but this isn't the case.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning also quick question, will GitHub Actions also be used for deployment?

**Comment by brockfanning** [comment]
Thanks for the feedback @LucyGwilliamAdmin I'll look into it. Yes, GitHub Actions will be used for deployment (assuming we resolve the issue you noticed).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think I might have found the issue. I recreated my tokens in GitHub and re-ran the checks and they've passed now.

When I was creating the tokens the first time I only selected the first section (repo I think?) as wasn't sure but when I recreated them, I selected all sections.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning also the reason I asked about deployment as seen Moritz from Germany team has emailed again as he still hasn't been able to deploy. Is it going to be a big job to set up deploying with GitHub Actions?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning something else.. in the _Turn on automated testing_ section of the quick start guide, point 8 is _Under "Status checks found in the last week for this repository" check the box for "test"._ However I've just gone to do that and "test" isn't one of the options:

![image](https://user-images.githubusercontent.com/43404358/71833662-51e63580-30a5-11ea-9758-673fb72dae1b.png)

**Comment by LucyGwilliamAdmin** [comment]
I've finished the quick start guide and have a site up and running [here](https://lucygwilliamadmin.github.io/sdg-site-lucy) - a couple of issues: indicator names aren't showing on goal pages, only indicator id e.g. [goal 1](https://lucygwilliamadmin.github.io/sdg-site-lucy/1/) nor on indicator pages e.g. [1.1.1](https://lucygwilliamadmin.github.io/sdg-site-lucy/1-1-1/)

**Comment by brockfanning** [comment]
Thanks again for all the feedback @LucyGwilliamAdmin, I will try to resolve these issues as soon as possible, so that we (hopefully) don't have to revert the changes.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin This is ready to try again, when you have time. Some comments on your findings:
* "Unable to fetch remote data" error: I think this was due to the first deployment of the data repository failing. This was due to an issue in [another project](https://github.com/JamesIves/github-pages-deploy-action/), which should now be fixed. (If curious, you can see the failure happening [here](https://github.com/LucyGwilliamAdmin/sdg-data-lucy/commit/ebde0af40c2964ccfaa1c2ecf8fdf8b727138b90/checks?check_suite_id=386411319#step:6:55).) So in theory that won't happen again.
* Personal access token and permissions: You mentioned you had to select all the permissions, but you should be able to do it with only the "repo" permission. The next time you try, you might try again with only the "repo" permissions.
* "build" vs "test" in the status checks: This should be resolved now (I tweaked open-sdg-data-starter)
* missing indicator names in the built site: Apparently the 0.10.0 release of open-sdg is not compatible with the 1.0.0-rc9 release of jekyll-open-sdg-plugins. I've tweaked open-sdg-site-starter to [point to the latest open-sdg code](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml#L13).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning great thanks!

I've just tried this again (https://github.com/LucyGwilliamAdmin/sdg-data-quick-start and https://github.com/LucyGwilliamAdmin/sdg-site-quick-start) and got all the way through without any issues.

I think maybe one thing we could add to the docs is about what permissions need to selected when creating a token just to avoid confusion.

**Comment by brockfanning** [comment]
I think we can close this, since all the starters (in this repo itself) have been switched over.
