### ISSUE TITLE
Configurable goal page layout

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#404]
So UK site has different goal page layout to everyone else (I think), as we have a grid rather than a list - is this configurable somewhere? which layout is default?

Should we make showing targets on goal page more easily configurable?

**Comment by LucyGwilliamAdmin** [comment]
I actually did some more digging and can see that if using `create_goals` in the config file, turning targets on and off is very easy - should we recommend that all countries use this method? Are there instructions anywhere on how to move to using `create_goals`.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I do think that the create_indicators, create_goals, and create_pages options should be used, for most sites. In fact the open-sdg-site-starter ships with this approach. So new implementations will tend to use the create_* approach.

The only possible negative is if you wanted to use some other Jekyll feature/plugin and needed control over the "front matter" of each page. For example, if using the create_* approach, it's impossible to use jekyll_redirect_from to add a redirect (I mentioned that difficulty [here](https://github.com/ONSdigital/sdg-indicators/issues/3285)).

The benefit of the create_* approach is more dramatic for implementations using multiple languages. For a site using only one language, the create_* approach saves you from needing about 150 files or so in your site repo (the indicators, goals, and 4 other pages). But for a site using three languages, it saves you from needing 450 (150 * 3) files in your site repo.

I think the only place we documentation of these in [here](https://open-sdg.readthedocs.io/en/latest/configuration/).

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Also by the way, the create_* approach is not technically required, to use different goal layouts. You can also update the `layout` setting in the front matter of each goal file, if not using the create_* approach.

**Comment by brockfanning** [comment]
I think we can close this - as the create_* approach is now part of the site starter. Please re-open if needed.
