### ISSUE TITLE
Documentation for how to configure reporting status options

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#405]
By default, the reporting status options are:

* Complete
* In progress
* Exploring data sources

However, Not applicable is now also allowed as an option and a few countries have decided to stop using In progress.

Thought it might be useful to have some documentation on how to change what options a site uses.

**Comment by brockfanning** [comment]
That's a good point.

I was also wondering if we could truly make it configurable. Right now, it's sort of configurable, in that you don't technically have to use all four options. But it's not possible to use other alternative options. This may be tied in with #209.

**Comment by brockfanning** [comment]
Actually looking at the reportingstatus.html code, it does seem like alternative options are already supported.

But there are a couple of places in the platform that rely on particular status options:
* https://github.com/open-sdg/open-sdg/blob/master/_layouts/search.html#L27
* https://github.com/open-sdg/open-sdg/blob/master/_layouts/goal.html#L32
* https://github.com/open-sdg/open-sdg/blob/master/_layouts/goal-by-target.html#L51
* https://github.com/open-sdg/open-sdg/blob/master/_layouts/indicator.html#L60

Anyway, I am getting away from the point of this issue. We definitely do need documentation on how to control the available reporting status options.

**Comment by brockfanning** [comment]
This is a documentation issue, so should only take 2-3 hours.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Do you think [this](https://open-sdg.readthedocs.io/en/latest/reporting-status/) is enough documentation on the subject? Or do you see anything that could be changed or added?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning would the country also need to do something with the colours? Is that something that would need to be included?

**Comment by brockfanning** [comment]
I think this has been fixed by #432 so I'll go ahead and close.
