### ISSUE TITLE
Page to showcase features on read the docs

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#406]
A page on Read The Docs which existing or potential Open SDG users can look at to see customisations in use.

Have started page [here](https://github.com/open-sdg/open-sdg/blob/platform-features/docs/open-sdg-features.md)

So far there's examples for the following features:

* Multilingual
* Maps
* Embedded content
* Targets on goal pages
* Reporting status options
* Contrast button
* Add pages

Are there any other features that we can give examples of?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning do you think there's anything else we want to show examples of?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'll think more, but one that comes to mind is the disaggregation feature (the drop-downs on the left).

**Comment by LucyGwilliamAdmin** [comment]
Thanks @brockfanning - just added disaggregations

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin  the only other thing I can think of is to show can have global and national indicators. Once add in any of the missing links (Rwanda map etc) I think it would be great to get this live on the Readthedocs (up near the top next to FAQ) so we can start sharing it. Thank you!

**Comment by LucyGwilliamAdmin** [comment]
Some guidance needs to be created and added

Under add pages:
For guidance on how to create new pages, see [XX]().

Under reporting status options:
For guidance on how to change what reporting status options your site uses, see the [XX page]().

Under national and global indicators:
Adding national indicators

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Was there more to do here, or can this be closed?

**Comment by LucyGwilliamAdmin** [comment]
This can be closed
