### ISSUE TITLE
Automated selecting still not quite right

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#426]
Some work has been done previously to ensure that some data is shown even if no headline data is provided (#186).

However it looks like there are still some cases when this isn't working correctly e.g. [2.3.1 on UK site](https://sustainabledevelopment-uk.github.io/2-3-1/)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I believe #441 should fix this.
