### ISSUE TITLE
Revisit the category display on the News listing

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#434]
Do we like the way categories look on the News listing page?

**Comment by brockfanning** [comment]
This may be resolved by #457. In that PR, the categories have been styled like the indicator tags.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning The category display can now be removed if not wanted - is there anything else we want to do with it?

**Comment by brockfanning** [comment]
Ok, I think that covers us here, I'll close now.
