### ISSUE TITLE
alternative to mapbox

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#437]
Since the use of mapbox is not completely free of charge (with costs from 50.000 calls per month) we are thinking about whether we can still use mapbox or not. 
Does anybody know an alternative provider of maps? And how easy/difficult would it be to integrate these maps (does leaflet only work with Mapbox?).

The chance that we get more than 50.000 hits is relatively low, but the people responsible for this site here are worried that someone might want to harm us and call the page with a small script every second. Or that the code of our site including the mapbox token is forked and the token is used elsewhere.

I would really like to use the map function, so if someone has an idea how to close these security holes I would be very grateful for suggestions.

**Comment by christoph4711** [comment]
I am interessted in this map stuff also. Especially I would think about having different layewrs in one map. So we can show diassagregated data on the map.

Have a look here: https://github.com/open-sdg/open-sdg/issues/374#issuecomment-546880441

**Comment by MoBosse** [comment]
Just realized that using the openStreetMaps tile ( https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png) is working, altough it is not very pretty.

**Comment by MoBosse** [comment]
I withdraw the part of the question about an alternative to Mapbox. The tiles based on osm (see list here https://wiki.openstreetmap.org/wiki/Tiles ) all seem to work.

However, I would be interested in your thoughts on the potential misuse of the Mapbox token.

**Comment by brockfanning** [comment]
> Since the use of mapbox is not completely free of charge (with costs from 50.000 calls per month) we are thinking about whether we can still use mapbox or not.
> Does anybody know an alternative provider of maps? And how easy/difficult would it be to integrate these maps (does leaflet only work with Mapbox?).

Leaflet is definitely not associated with Mapbox, and yes you can use any other tile provider. You've already found that you can use Open Street Map. However a caution there, you should read [this document](https://operations.osmfoundation.org/policies/tiles/). That document also has some helpful links at the bottom to alternative tile providers, both free and paid-for.

> The chance that we get more than 50.000 hits is relatively low, but the people responsible for this site here are worried that someone might want to harm us and call the page with a small script every second. Or that the code of our site including the mapbox token is forked and the token is used elsewhere.

I think that Mapbox's "URL restrictions" may help with this. See their docs [here](https://docs.mapbox.com/accounts/overview/tokens/#url-restrictions).

**Comment by brockfanning** [comment]
I'll go ahead and close this. Feel free to reopen if there are any more questions.
