### ISSUE TITLE
Configurable main logos (flag image)

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#470]
Can we make the main logo image more configurable, so that it can include multiple images, displayed horizontally in a row?

**Comment by phillipgardiner** [comment]
@AnnCorp @brockfanning I was not sure if we were doing this anymore? I thought we had decided we would rely on a countries photoshop skills to adapt.
If this is the case we will need a card for the UK only to add the Union Jack.

**Comment by brockfanning** [comment]
@phillipgardiner That's what I remember also - I think we can close this one.
