### ISSUE TITLE
Smaller goal icons in goal/indicator page banners

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#477]
This is a follow-up on the discussion in #474 

I believe the consensus was to limit the goal icons in goal page banners and indicator page banners to 80% instead of 100%. But @SavvasStephanides @LucyGwilliamAdmin @phillipgardiner correct me if I'm wrong.

**Comment by phillipgardiner** [comment]
80% :)

**Comment by brockfanning** [comment]
A note that this has been postponed because the grid system causes unwanted whitespace between the icon and the H1.

**Comment by phillipgardiner** [comment]
No longer required due to changes to the indicator banner made within 'Adjust heading structure across site #651'
