### ISSUE TITLE
Vertically center H1 in indicator page banners

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#478]
This is a follow-up from discussion in #474

**Comment by brockfanning** [comment]
In addition to the markup change, @phillipgardiner suggests making the banner text vertically centered.

Tech note - what that require "flex" display maybe? I feel like vertical alignment is always tricky.

**Comment by phillipgardiner** [comment]
I also believe the text in the banner may look better as a 'h1' rather than a 'h2'. (separate note: not sure why 'h1' is smaller than 'h2'??)

**Comment by brockfanning** [comment]
Renaming this, since the other part has already been done.

**Comment by phillipgardiner** [comment]
No longer required due to changes to the indicator banner made within 'Adjust heading structure across site #651'
