### ISSUE TITLE
Indicator page accessibility issues

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#488]
Here are the 3 things that pa11y is complaining about, on our indicator pages:

```
 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 2.79:1.
   Recommendation:  change text colour to #565656.

   (#clear)

   <button id="clear" class="disabled">Clear selections <i class="fa f...</button>
```
The above seems valid - the "Clear selections" button in the left sidebar does not have enough contrast when disabled. Of course, it's meant to be disabled, so maybe we can add an aria property to show that it's disabled?

```
 • This table appears to be used for layout, but contains a caption element. Layout tables
   must not contain captions.

   (#datatables > table)

   <table class="table-responsive table table-hover dataTable no-footer" role="grid">
   <caption>Proportion of p...</table>
```

The above seems clearly invalid. That table is a regular table, and not being used for layout. So we just need to tell pa11y not to complain about that.

```
 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(2) > a)

   <a class="nav-link" data-toggle="tab" href="#global" aria-controls="global" role="tab"
   data-on="click" data-event-category="Tab change" data-event-action="Change metadata view"
   data-event-label="Change to My global metadata title tab">My global metad...

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(3) > a)

   <a class="nav-link" data-toggle="tab" href="#sources" aria-controls="sources" role="tab"
   data-on="click" data-event-category="Tab change" data-event-action="Change metadata view"
   data-event-label="Change to My sources title tab">My sources title</a>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > ul > li:nth-child(4) > a)

   <a class="nav-link" data-toggle="tab" href="#edit" aria-controls="edit" role="tab">Edit</a>

 • This element has insufficient contrast at this conformance level. Expected a contrast
   ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.93:1.
   Recommendation:  change background to #fefefe.

   (#indicator-main > section > div:nth-child(1) > ul > li:nth-child(2) > a)

   <a class="nav-link" data-toggle="tab" href="#tableview" aria-controls="tableview"
   role="tab" data-on="click" data-event-category="Tab change" data-event-action="Change data
   view" data-event-label="Change to Table tab">Table</a>
```

All of the above seem related to the new tab styles. Apparently pa11y thinks the non-active tabs need more contrast between the link and the tab background.

@SavvasStephanides @phillipgardiner Any ideas?

**Comment by phillipgardiner** [comment]
@brockfanning @SavvasStephanides In regard to the tabs I think there are a couple of options:

1) For the tabs, turn all text to black (still keeping the underline). They use this approach on gov.uk (https://design-system.service.gov.uk/components/tabs/default/index.html)

2) Consider changing the blue link colour to something with sufficient contrast. For example #155084, obviously this would change across the whole site

I believe option 1 is probably the way to go first, as tabs are essentially there own widget so the tab text does not have to look like links. Links usually take you to another place.

In regard to the clear all button, agree with brock, needs a disabled state applied :)

**Comment by brockfanning** [comment]
Ok, I've got PRs opened for all these issues:
* #490 
* #491 
* #492 

It turned out that the complaint about "Layout tables must not contain captions" actually clued me in to a bug in the Jekyll code. Fixing the bug satisfied that complaint. :)

**Comment by brockfanning** [comment]
These are all fixed now.
