### ISSUE TITLE
Feedback on "Sources" functionality?

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#504]
This is a call for any feedback on the Sources functionality, as described [here](https://open-sdg.readthedocs.io/en/latest/metadata-format/#data-sources-metadata). Since we're getting close to release version 1, this would be the time to make any architectural changes related to sources. So:
1. Any annoyances or limitations with the current system?
2. Any source-related features you would like added?
3. Any source-related bugs you've noticed?
4. Other thoughts?

**Comment by MoBosse** [comment]
Hi @brockfanning, here are a few things that come to my mind about sources:

- The placement of the third (fifth, seventh...) source depends on the length of the value in the last tablerow of source 1 and 2 (3 and 4,...). See screenshot:
![grafik](https://user-images.githubusercontent.com/50657629/74925842-3b860600-53d5-11ea-9b7d-bc0f9be0c24c.png)

- It looks strange when two sources are side by side, but have table rows with different heights:
![grafik](https://user-images.githubusercontent.com/50657629/74926503-44c3a280-53d6-11ea-9715-667f8722427b.png)

- Not sure if it's of any interest for anyone but us, but sometimes the source_organisation contains additional information beside the Organistaion name, so I added a **source_organisation_#_short** that is shown in the sources tab beside the original **source_organisation_#** that is shown in the footer. 


![grafik](https://user-images.githubusercontent.com/50657629/74927422-d849a300-53d7-11ea-87f8-7031183da860.png)

**Comment by brockfanning** [comment]
Thanks for the feedback @MoBosse, very helpful.

**Comment by ONSBen** [comment]
Hello @brockfanning 

I agree with the Source 3 / 5 / ... position and row alignment issue raised above.

Looking specifically at the 'Data last updated' and 'Metadata last updated' field, would it be possible for that to link to several of the most recent changes, rather than just one? Or to link to a GitHub page of all changes to that indicator? The intent is to make it easier to check older versions of the data / metadata.

While I think that the metadata tabs in general are a little too discrete, I don't know much about user-friendly design or what other user experiences are, so take that with a pinch of salt.

Many thanks

**Comment by brockfanning** [comment]
@MoBosse @ONSBen In regards to the position/alignment issue, do you think it would be preferable to have them in a single column? To see what it would look like, I've got a pull-request up with a screenshot here: #591

**Comment by MoBosse** [comment]
@brockfanning Actually I like the approach that the sources are listed side by side in two columns. Especially if there are a lot of sources, you can still see them at one glance. But if it is too complicated to solve the described problems in a two-column design, the single column would certainly be a good compromise.

**Comment by brockfanning** [comment]
Thanks for the feedback @MoBosse. Let's try to keep the 2-column layout then. As I understand the main goals are:
1. The extra source, in the case of an odd number of sources, should always appear in the left column, regardless of the heights of the columns.
2. Remove the lines beneath the metadata fields, since they look bad when side-by-side.

@ONSBen I like the idea of a link to history of changes for that indicator. It actually seems like that would be easier than going to a specific commit. Would it be better to link to, for example, here? https://github.com/ONSdigital/sdg-data/commits/develop/data/indicator_1-1-1.csv

Also about the tabs, we've been revamping them in preparation for version 1.0.0. You can see a sneak preview here: https://open-sdg.github.io/open-sdg-site-starter/1-1-1

**Comment by ONSBen** [comment]
@brockfanning I realised after the fact that I had rather strayed outside the bounds of the issue - apologies, and thanks for addressing the points raised anyway. Apologies for my delayed response as well - I haven't been using GitHub recently.

I think that history page is definitely better. It might be a bit of a struggle for users unfamiliar with GitHub, but that is probably unavoidable given that we use its commit history to track changes to the data and metadata. Is that history page available as an API endpoint, out of curiosity? Being able to pull all the update dates of every indicator at once (or a subset thereof) might be handy.

I like the new tabs - they entirely cover the issue raised.

**Comment by brockfanning** [comment]
Let's use this ticket to solve the row alignment problem.

**Comment by phillipgardiner** [comment]
@brockfanning Following Slack conversation, lets try making a change to the gutter size at some point and see what effect that has, we can then take it from there.

**Comment by brockfanning** [comment]
@phillipgardiner It turned out to be a really easy code change to add the gutter - I've got a PR with a screenshot here: #1096

**Comment by phillipgardiner** [comment]
@brockfanning thanks for the screenshot. I definitely think that helps :). I believe it is probably now a decision for @AnnCorp on weather any further time is spent addressing this (as per the slack conversation).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @phillipgardiner is there more to do here? I'm also starting to wonder what will happen with the sources tab when a country is using SDMX metadata fields

**Comment by phillipgardiner** [comment]
@LucyGwilliamAdmin I believe this one is done, and was signed off by Ann in the PR #1096. The SDMX metadata fields is not something i'm up-to speed with but I'm guessing it definitely needs consideration etc, so maybe a ticket somewhere?

**Comment by brockfanning** [comment]
The functionality for displaying multiple distinct sources, each with their own set of fields, has been a feature of Open SDG for a while. In fact it was one of the features added when the UK forked the US code, if I remember right. The point of the functionality is to allow these multiple sources to be displayed in a grid in the "Sources" tab, with each item having their own set of fields.

One alternative to this approach is a single metadata field called "Sources" (for example) with free-form text describing all of the sources. This is basically what a country would be doing if they were using the SDMX metadata fields.

I think that countries that are using the SDMX metadata fields will probably not want the Sources tab, and would want to remove it by omitting it from the `metadata_tabs` site config.

**Comment by LucyGwilliamAdmin** [comment]
Closing this and opening new ticket specifically re. displaying source info when using SDMX
