### ISSUE TITLE
Graph not showing same values as table when rounded

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#516]
I've just added some rounding functionality for Kyrgyzstan but the rounded values aren't showing on the graph, only on the table.

For example, see [1.2.1](https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/1-2-1/)
Table:
![image](https://user-images.githubusercontent.com/43404358/75332620-9e1b4e00-587c-11ea-8e54-013c436d9556.png)

Graph:
![image](https://user-images.githubusercontent.com/43404358/75332746-ce62ec80-587c-11ea-870f-1e5056c23be2.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin From what I can tell: It looks like the Chart.js library does its own conversion, at least to remove unneeded trailing zeroes in the decimal place. Your rounding function is having the effect of adding trailing zeroes in the decimal place. The table is showing them faithfully, but Chart.js is chopping them off.

**Comment by brockfanning** [comment]
Possibly the same issue as #341

**Comment by brockfanning** [comment]
I believe this will be fixed by #1073.
