### ISSUE TITLE
Support using as a local reporting platform

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#52]
As far as I know there is only one piece of this platform that hinders usage as a local reporting platform: the metadata tab on indicator pages that says "National Metadata". Let's make this text more easily customized, so that it can instead say "Local Metadata".

**Comment by AnnCorp** [comment]
Would this be set by some sort of variable in config file default to 'National' but can be changed to 'Local' or specific area name as required?. Should we give some kind of guidance re max text length as while OK on desktops, would be an issue on mobiles?

**Comment by brockfanning** [comment]
That sounds like a great approach to me.
