### ISSUE TITLE
Create/translate defaults for homepage introduction banner

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#528]
We need to decide on default text for the homepage introduction banner, title and description. Then we need to translate it and add to [translations-open-sdg](https://github.com/open-sdg/translations-open-sdg).

**Comment by brockfanning** [comment]
@AnnCorp Could you suggest copy to use for the default homepage introduction banner title and description?

**Comment by AnnCorp** [comment]
@SavvasStephanides pls could you add comment here with link or visual of the latest mockup for this, so i can see what quantity of text you've allowed space for? Thank you.

**Comment by SavvasStephanides** [comment]
@AnnCorp Technically there's no limit on the amount of text you're allowed to add.

**Comment by SavvasStephanides** [comment]
@AnnCorp as requested, [UK site feature branch](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1/)

**Comment by AnnCorp** [comment]
@SavvasStephanides could you see how the following fits please?
The Sustainable Development Goals (SDGs)[https://www.un.org/sustainabledevelopment/sustainable-development-goals/] are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the 2030 Agenda for Sustainable Development [http://www.un.org/ga/search/view_doc.asp?symbol=A/RES/70/1&Lang=E].
In the UK, the Office for National Statistics (ONS) are responsible for monitoring and reporting on SDG indicators.
@brockfanning in the site starters do you substitute country/organisation names somehow?

**Comment by SavvasStephanides** [comment]
@AnnCorp Should I leave the same title?

![image](https://user-images.githubusercontent.com/478770/76436508-3d2d6300-63b0-11ea-925d-a45fdda1eb7f.png)

**Comment by brockfanning** [comment]
This text will be translated:

## 17 goals to transform our world

The [Sustainable Development Goals (SDGs)](https://www.un.org/sustainabledevelopment/sustainable-development-goals/) are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the [2030 Agenda for Sustainable Development](http://www.un.org/ga/search/view_doc.asp?symbol=A/RES/70/1&Lang=E).

Then the translation keys will be added to the site starter config file.

**Comment by brockfanning** [comment]
Closing, this has been translated and added to the starter repos: https://open-sdg.github.io/open-sdg-site-starter/
