### ISSUE TITLE
Multiple graph titles - one per unit of measurement

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#531]
In many cases I've seen the `graph_title` used to describe only one of multiple available units of measurement. Would it be helpful if the `graph_title` field could have multiple values - one for each unit of measurement?

**Comment by brockfanning** [comment]
@AnnCorp @LucyGwilliamAdmin I was hoping to get your thoughts on this. Changing the graph title in this way should probably be done before 1.0.0, if it's going to be done. But I'm not sure if this is needed.

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning I think we've had a couple of requests from our data team re. the graph title changing when the units are changed

**Comment by brockfanning** [comment]
So it sounds like this is a feature worth adding. I think if we change the way `graph_title` works, then we should do this before 1.0.0. However we could also instead add a _new_ metadata field, like `graph_title_per_unit` or something, and try to continue supporting `graph_title`. It's a little cumbersome to try to support two approaches, but if we can't get this done by 1.0.0, that might be an option to get it done soon after.
