### ISSUE TITLE
Review all ReadTheDocs content.

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#535]
- [ ] Non-technical sections
  - [x] Home - Ann edited for review by Brock
  - [x] About 
  - [x] Open SDG features 
  - [x] FAQ
  - [x] List of users 
  - [x] Case studies
  - [x] Support (updated to inc issue templates)
  - [x] Contribution guidelines 
  - [x] Code of conduct
  - [x] Glossary of terms

- [x] Technical sections
  - [x] Change log
  - [x] Architecture diagram
  - [x] Requirements
  - [x] Quick start
  - [x] Making updates
  - [x] Metadata format
  - [x] Metadata file formats
  - [x] Data format
  - [x] Data sources
  - [x] Chart types
  - [x] Upgrading
  - [x] Local development
  - [x] Deployment
  - [x] Configuration
  - [x] Customisation
  - [x] Translation
  - [x] Maps
  - [x] Analytics
  - [x] Reporting status
  - [x] GitHub Actions
  - [x] CircleCI
  - [x] TravisCI
  - [x] Jenkins
  - [x] GitHub integration
  - [x] GitHub pages
  - [x] AWS S3
  - [x] Linux server

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp @brockfanning @SavvasStephanides 

I've added a checklist to the comment - I've put each page where I thought it would go but might not be right

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is `indicator_number` still a required field?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes, that's actually the latest recommendation. It used to be `indicator`, and there is actually [backwards-compatibility code](https://github.com/open-sdg/jekyll-open-sdg-plugins/blob/master/lib/jekyll-open-sdg-plugins/create_indicators.rb#L64) to continue to support `indicator`, but the docs recommend `indicator_number`.

In fact, I think we ought to try updating the starter repo to `indicator_number` instead of `indicator`. I can try that out locally.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin @AnnCorp @SavvasStephanides For the configuration page (https://open-sdg.readthedocs.io/en/latest/configuration/) what do you think about making the whole list alphabetical? Right now it's kind of a jumble, roughly separated between required and optional. But I was thinking maybe just alphabetical, with required/optional indicated for each one.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning think that makes sense

**Comment by brockfanning** [comment]
Some TODOs as I'm going through the technical docs:
* Update changelog.md with the latest changes
* Update requirements.md to highlight GitHub Actions instead of CircleCI

**Comment by brockfanning** [comment]
I've got PRs open for the todos above, and have gone through all the technical docs.

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin could you review and update the 'Support' page please to add in info about using the Issues templates you've created. Cheers!

**Comment by AnnCorp** [comment]
All checkboxes completed!
