### ISSUE TITLE
Stop chart colors from changing

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#559]
We have received feedback from some users that the legend entries are confusing. An often repeated statement is that it is confusing that the colors in the charts and legends change when you select or deselect time series. 
As far as I know the color is determined by a "datasetIndex" (that changes, everytime the selection changes) and the corresponding position in the given list of colors. Based on this approach, I can't think of a way to fix a color to a time series, but maybe someone else has an idea about it?

**Comment by brockfanning** [comment]
@MoBosse I've never noticed that before, but I agree it would be nice if each series had its own color. As is, we have to re-interpret the legend every time we add/remove a series.

**Comment by brockfanning** [comment]
Just a thought: one approach might be to have a javascript object "seriesColors" (or something) which starts empty, and gets bigger every time a series is added. The trick I think will be to make Chart.js use these colors.

**Comment by brockfanning** [comment]
There is a pull request opened for this, but it could use testing: #815

**Comment by brockfanning** [comment]
@MoBosse I've finally got a potential fix ready for testing, if you are interested: #1011

**Comment by brockfanning** [comment]
This will be in 1.3.0.
