### ISSUE TITLE
Banner body difficult to read in high-contrast mode

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#564]
The text created by frontpage_introduction_banner.description is hard to read on high-contrast mode:

<img width="885" alt="frontpage-banner-contrast-issue" src="https://user-images.githubusercontent.com/1319083/77192520-160f1980-6ab3-11ea-8198-d0007b72e526.png">

**Comment by brockfanning** [comment]
@SavvasStephanides Can you take a look at this? I think we need automated tests for the frontpage_introduction_banner stuff as well - I only happened to notice this from manual testing.

**Comment by brockfanning** [comment]
I see @phillipgardiner already noticed this.

**Comment by SavvasStephanides** [comment]
@brockfanning Yes, we've been talking about this last week.
