### ISSUE TITLE
Disaggregations not resetting when unit type is changed

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#577]
Currently disaggregations aren't resetting when unit type is changed. For example, see 3.3.3 on UK site.

By default looks like this:
![image](https://user-images.githubusercontent.com/43404358/77561174-46412880-6eb6-11ea-9aa7-bc7a721bcad0.png)

Then when other units type is selected (Percentage of total cases):
![image](https://user-images.githubusercontent.com/43404358/77561273-6244ca00-6eb6-11ea-8d48-e90ba7b92483.png)

Then back to default units type:
![image](https://user-images.githubusercontent.com/43404358/77561472-a59f3880-6eb6-11ea-8549-aa90ef4dab6c.png)

Note: I haven't selected/unselected any disaggregation options

**Comment by LucyGwilliamAdmin** [comment]
I think I would expect the first and third graph to look the same, especially the fact that the UK would still show as headline (grey bar).

Do we want the automated disaggregation selection process to be restarted whenever a new units type is selected?

**Comment by LucyGwilliamAdmin** [comment]
Another example on Kyrgyzstan site: [7.3.1.2](https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/en/7-3-1-2/)

When first land on page there are no disaggregation options available with default unit type, but then when you click on other unit type and back on default, disaggregation options from other unit type still display, making it look to the user like they have options.

**Comment by brockfanning** [comment]
This seems like a tricky question - do you know if there is any upcoming user testing that might inform how it should work?

The first thought that occurs to me is that, under normal circumstances, changing the Unit doesn't reset anything. But if the other Unit doesn't have the same disaggregations available, then the Unit radio button includes some sort of message like "(selected disaggregations will be reset)" or something to that effect. Or maybe a popup. I'm not sure how technically feasible that is, just brainstorming.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning don't think there's anything coming up which could help with this..
@AnnCorp what are your thoughts?
Phill (not sure why I can't tag you) - have you come across anything like this before?

**Comment by phillipgardiner** [comment]
Hi @LucyGwilliamAdmin @AnnCorp  . I'm trying to get my head round how this actually works. Like @brockfanning my thought is that changing the Unit doesn't reset anything - So yes I would expect the first and third graph to look the same. However, I'm not 100% sure why it changes in graph 1 (UK) to graph 2 (Africa)? my assumption would be that the graph would continue to show the UK but as a percentage rather than a number. I would think you would then be given the option to select 'country of birth' if you so wished when displayed as a percentage? To be honest I think this is an area that in time will require some re-work, I guess it's a case of what is good enough for now?

**Comment by brockfanning** [comment]
At least part of this was fixed by #604. That PR addressed one issue [mentioned above](https://github.com/open-sdg/open-sdg/issues/577#issuecomment-604524327).

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning can this be closed due to #781 ?

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning do you know if/what is remaining on this?

**Comment by brockfanning** [comment]
I feel like #781 did fix this completely - I could be wrong but I guess we can close now and open a new ticket if needed.
