### ISSUE TITLE
In high contrast version, the graph text is grey and hard to see.

### ISSUE THREAD

**Issue by SavvasStephanides** [open-sdg/open-sdg#579]
Change axis text to white in high contrast

![image](https://user-images.githubusercontent.com/478770/77570448-b99d6700-6ec3-11ea-96db-39e4092958e1.png)

**Comment by SavvasStephanides** [comment]
@brockfanning I'm not too sure how possible this is to do. As in, have different colours displaying depending on whether the page is on default or high contrast.

**Comment by brockfanning** [comment]
Yep, I think this will need to be javascript instead of CSS. I'll take a closer look.

**Comment by brockfanning** [comment]
@SavvasStephanides A PR for this is ready to review: #593
