### ISSUE TITLE
UK open-sdg Pull Request

### ISSUE THREAD

**Issue by Norric1Admin** [open-sdg/open-sdg#59]
Amend the [sdg-indicators](https://github.com/ONSdigital/sdg-indicators) repo so that the UK site pulls its layout and build scripts from open-sdg.

**Comment by dougmet** [comment]
Reviewing now.

**Comment by dougmet** [comment]
apologies, assigned myself the wrong ticket

**Comment by Norric1Admin** [comment]
@AnnCorp This [submission](https://github.com/ONSdigital/sdg-indicators/pull/2881) has passed. I'll merge it now and test it on the UK platform. Any issues, it can be quickly reverted.

**Comment by Norric1Admin** [comment]
@dougmet @brockfanning It's all working as expected, except the that toolbar is missing (Goals, Reporting Status...). Can you advise on this please?

**Comment by brockfanning** [comment]
@Norric1Admin @dougmet The _config.yml and _config_prod.yml will need a `menu` entry. Here's an example: https://github.com/brockfanning/sdg-site-maptest/blob/develop/_config.yml#L78

Also to get the Twitter link back, the config files will need a `twitter` entry. Here's an example of that: https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml#L39

**Comment by brockfanning** [comment]
@Norric1Admin Also the value for the `twitter` entry would just be the Twitter username: 'StatsClaudie'

**Comment by Norric1Admin** [comment]
Got it – thanks 😊

**Comment by Norric1Admin** [comment]
The UK platform is now running from open-sdg, although I have disabled the map feature. Our team have decided to keep the changes, and there will be further user testing over the next week.

All open-sdg changes can be reversed by reverting the following:
https://github.com/ONSdigital/sdg-indicators/pull/2881
https://github.com/ONSdigital/sdg-indicators/pull/2884
https://github.com/ONSdigital/sdg-indicators/pull/2885

Apologies for the rather haphazard way this was achieved - in future I will try to keep these changes within a single pull request, to make the reversion easier.
