### ISSUE TITLE
Mapping query

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#606]
@brockfanning 
Just testing v1 mapping on UK site and getting this error:
https://travis-ci.org/github/ONSdigital/sdg-data/builds/670255089#L272
![image](https://user-images.githubusercontent.com/43404358/78283045-22648f00-7515-11ea-8cc6-19f070e360e4.png)

Our geocoding function that we run our data files through beforehand adds a geocode to every row which is possible, including disaggregation rows. Is this what would be causing that error?

Also isn't it possible to have data for different map levels e.g. originally map may show country level data and then if you zoom in it might show region level data - wouldn't that mean that years need to have more than one geocode - one for country and one for region

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides this is where I got to on the map thing

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I'll take a look, thanks for the info.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think we need to either:
1. Improve the error message there
2. Print a warning instead of throwing an exception
3. All of the above

But I do think there is an issue in the data. See these two lines as an example - they appear to be duplicates, but with different values:
* https://github.com/ONSdigital/sdg-data/blob/v1-test/data/indicator_16-1-3.csv#L262
* https://github.com/ONSdigital/sdg-data/blob/v1-test/data/indicator_16-1-3.csv#L276

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I just opened this PR for a better error message, and a warning instead of exception: https://github.com/open-sdg/sdg-build/pull/140

If you give it a try, it should give you a better idea of the data issues. And it should allow the build to complete, I think.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning @SavvasStephanides so my travis checks are passing now.

But I'm getting this error in the console:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-a-1/

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I need to fix that error message, I'll submit a PR shortly. But in the meantime, this is because you don't have a `map_layers` setting in the site config, I think. See here: https://open-sdg.readthedocs.io/en/latest/maps/#map_layers

**Comment by SavvasStephanides** [comment]
`options.mapLayers` returns `null` which gives you this error. Not sure if this was an issue before.

EDIT: Seems to be what Brock is suggesting

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I just pushed up a PR to give a console warning when this happens: https://github.com/open-sdg/open-sdg/pull/608

**Comment by LucyGwilliamAdmin** [comment]
I thought map_layers was going in the data config now?

**Comment by brockfanning** [comment]
Well... I guess it has to be in both the site config and the data config, but with different stuff. I think we need to spell that out in the docs, sorry about that.

**Comment by LucyGwilliamAdmin** [comment]
Ohh that's ok - sorry!

**Comment by LucyGwilliamAdmin** [comment]
I've just re-read it and think I've got it now!

**Comment by LucyGwilliamAdmin** [comment]
Got a map:
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-a-1/

Thanks so much for your help both!

**Comment by SavvasStephanides** [comment]
Nice!
