### ISSUE TITLE
Zooming maps on mobile

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#609]
It seems that maps can't be zoomed in on mobile. I believe this is due to the code that prevents the user from panning away from the starting view. (For example, if you're looking at a map of the UK, and try pan down to France, it will snap you back up to the UK.) Maybe when zooming in on mobile, the system interprets that as panning away? Or it could be some other issue.

Maps are not particular usable on mobile anyway, so I think this is a lower priority, but still something that we should be able to fix, in theory.

**Comment by SavvasStephanides** [comment]
Which browsers have you tested this on? I tried it on Safari on iOS and it seems to work fine with pinching the maps outwards or inwards. If all else fails we have the `+` and `-` buttons which seem to work fine, no?

![image](https://user-images.githubusercontent.com/478770/78371413-d91d4980-75bf-11ea-89e7-b8d83d066aa8.png)

**Comment by LucyGwilliamAdmin** [comment]
Just did a quick test on Chrome on my Android device and I can also zoom - I do have a different issue though.

The options on the left get covered when parts of the map are selected:
![image](https://user-images.githubusercontent.com/43404358/78372032-ad4e9380-75c0-11ea-9d42-8a701d902998.png)

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin Wondering what version of Chrome you have.

This is Chrome on Samsung S10 and it looks OK:

![image](https://user-images.githubusercontent.com/478770/78372875-b8ee8a00-75c1-11ea-8bc2-adf8e27da495.png)

**Comment by brockfanning** [comment]
I was testing on Android Firefox. I tried again, and I believe I was able to get all the way down to the local authority level, but it was pretty laggy. I guess we can close this, if you all agree.

For the legend problem, see this other issue about that: #482

**Comment by SavvasStephanides** [comment]
I agree
