### ISSUE TITLE
Long main nav causes hover underlining to shift page

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#610]
If a site has multiple languages, the underlining of the main nav items on hover is causing the rest of the page to shift down, ever-so-slightly. Not a huge problem, but a very visible and slightly annoying bug. I believe this only happens when the main nav is so wide that it bumps down below the main logo.

It's not the kind of thing I can show in a screenshot, but you can see it in action here: https://sdg-kyrgyzstan.github.io/open-sdg-site-starter/

**Comment by SavvasStephanides** [comment]
Yes this might be a problem but it's an inevitable part of internationalising websites.

![ezgif-6-bad9263e5b9f](https://user-images.githubusercontent.com/478770/78557655-16c0e300-7809-11ea-87e4-84a9f71e7002.gif)

**Comment by brockfanning** [comment]
@SavvasStephanides I don't have a problem with the navigation wrapping itself, it's the jumping down of the rest of the page on hover, caused by the underlining. I'm hoping there is some CSS tweak we can do to prevent that. See this demo:
![captured](https://user-images.githubusercontent.com/1319083/78564915-1fa2bc00-77eb-11ea-8798-59093c544dae.gif)

**Comment by brockfanning** [comment]
Tweaked the title - I guess it's not really related to the language toggle.

**Comment by SavvasStephanides** [comment]
Ah that makes sense. I think if we set a border for the neutral (ie. not-hovered) state and set it to transparent somehow, it will stop the jumping effect.

**Comment by brockfanning** [comment]
Sounds good to me!
