### ISSUE TITLE
Reduce over-reliance on remote sources when running locally

### ISSUE THREAD

**Issue by SavvasStephanides** [open-sdg/open-sdg#623]
Current when testing changes locally for SDG repos (including OpenSDG, UK platform etc) we seem to rely heavily on remote sources. Usually it's not that much of a problem, but if something happens, like for example the Internet connection is lost, or Github Pages goes down ([as it happened recently](https://www.githubstatus.com/incidents/f3xzj5fgfq5b)), development is pretty much crippled. 

Obviously this is a huge change and not something to happen soon. This is issue is mostly for discussion. I think it'd improve the developer experience immensely, not just for Open SDG, but for individual sites which use Open SDG globally.

Testing Open SDG relies on these Github repos, which are cloned for each test, or serve:

* `open-sdg/open-sdg-site-starter`
* `open-sdg/open-sdg-data-starter`

After that, the starter repos and UK site rely on remote sources:

* Remote data source - _this is a quite a bit of an issue since when testing locally (`http://localhost`), as the data cannot be displayed due to Github's CORS policy. The page is stuck on a loading animation_
* Translations from `sdg-translations`
* Images for goal tiles from `sdg-translations`
* Quite a few Javascript libraries that are currently loaded from remote CDNs (Bootstrap, jQuery, Leaflet, Font Awesome...)

It would be nice if we could reduce this over-reliance on remote sources as much as we can (I understand that some need to stay remote). I'm open to suggestions on how to do achieve this but here are a few of mine:

* Clone, build and run everything locally for testing. This could either mean building each and every repository on its own port (or directory) manually, or create a project which does this for you using `docker-compose`. Automatically set all files to point to the correct links when testing locally and deploying.
* Create a guide on how to prepare everything locally and set all links to point to localhost.
* Add JS libraries as part of the repos. Usually JS libraries come with a "minified" version, which is a lot smaller than the normal version.

**Comment by brockfanning** [comment]
I agree this is a really good idea, even if it is done one bit at a time. I've been in spots where I wanted to do some development while on a hotspot, but I knew that just one `make serve` would max out my cell's data plan... Some thoughts on each item:

1. Local cloning of starter repos: I'm sure we can remove the need for the `make serve` to clone the starter repositories. I can look into that.
2.  Data source: I have been using the npm package "live-server" to do this. This is a bit manual, unfortunately, but is working in a pinch. The steps are:
    * Build the data locally (eg, `python scripts/build_data.py`)
    * Go into the built folder (eg, `cd _site`)
    * Launch the server (with a flag to avoid CORS issues): `live-server --cors`
    * Copy/paste the local URL to the site config's `remote_data_prefix`
3. Translations: A possible fix is to have a local copy of the sdg-translations repo and copy the `translations` folder into your data repo, before building it. That's kind of manual though, so something more automated would be preferred.
4. Goal images: Along the same lines, a possible fix is to have a local copy of sdg-translations, and copy the `www/assets/img/goals` and www/assets/img/high-contrast` folders into the site repo under `assets/img`, and then set the site config's `goal_image_base` to somethiing like `/assets/img/goals`. (That's off the top of my head, so there may be some tweaks needed.) But again that's very manual and something automated would be better.
5. Third-party javascript libraries: This is tough one - I don't think we want to start a practice of committing all dependencies to the project. I would hope that maybe we could come up with some script and/or config to download them all and then use local versions.
6. The open-sdg theme itself: The downloading of the open-sdg theme (via the `remote_theme` setting) can also be avoided by using it as a Ruby Gem. I haven't tried that out recently though.

**Comment by SavvasStephanides** [comment]
Thanks @brockfanning 

> Local cloning of starter repos: I'm sure we can remove the need for the make serve to clone the starter repositories. I can look into that.

Great. I was thinking we could have the starter repos already cloned and build from there somehow, instead of having to clone every time.

> Data source

Great if your steps result in the data being on localhost. If it is, we don't really need to set up CORS policies (I think) since both the site and data are (or should be) on localhost.

> Translations: A possible fix is to have a local copy of the sdg-translations repo and copy the translations folder into your data repo, before building it. That's kind of manual though, so something more automated would be preferred.

That's what I was thinking. Having the translations build locally and use them from there. As it's manual, that's why I proposed `docker-compose`. Each repo will be its own service with its own port (eg. `http://localhost:5000` for site, `http://localhost:5001` for data etc), or directory with a bit of reverse proxy magic (`http://localhost/site` for site, `http://localhost/data` for data etc).

> Goal images

I assume having a local copy of translations would also localise the goal images as well, as they are stored as part of `sdg-translations`.

> Third-party javascript libraries

Yes I completely understand your hesitance to store dependencies on the repo. Maybe we can come up with something similar to what `npm install` does. It looks through `package.json` and installs all the dependencies on `node_modules` which isn't pushed to Git. Something similar would be nice, for example `make install-dependencies` which would run a `curl` or `wget` from a list of URLs and store them on an ignored folder. This could also be implemented on deployment.

> The open-sdg theme itself

Great that the remote theme can be a Ruby gem!

**Comment by brockfanning** [comment]
A few of these issues should be fixed in #624.

**Comment by brockfanning** [comment]
One other thing we could do is try to get sdg-build and yamlmd into PyPI. I don't much experience with that, but my hope is that it would prevent those projects from needing to be cloned during the local builds each time.

**Comment by SavvasStephanides** [comment]
Good idea @brockfanning. I don't have any experience with this either, but [this could help](https://packaging.python.org/tutorials/packaging-projects/).

**Comment by SavvasStephanides** [comment]
@AnnCorp I'm not sure if we should expect this to be completed by version 1.1.0. This is a huge change and quick a big chunk of work. We are still mostly at conception stage at this point.

**Comment by AnnCorp** [comment]
@SavvasStephanides  no probs (sorry, think may have tagged by accident!). We can go through at Tech call what we think could stay in or be removed.

**Comment by SavvasStephanides** [comment]
I have another idea regarding this isssue:

We should have a `make` command which will install all relevant packages once. Something like `make install`. This will run commands like `pip install`,  `npm install`, or `bundle install`. Remove them from `make serve` so that they don't get installed every time a serve is requested.

**Comment by brockfanning** [comment]
One remaining thing - do not install NPM when serving locally.
