### ISSUE TITLE
Moved coloured bar to top of page

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#627]
Flagged in Phill's expert review - reposition or remove coloured bar to very top of page, above disclaimer banner

**Comment by phillipgardiner** [comment]
It may be that it ends up better removed OR some other design element needs to be added just to split up the top section from the bottom section slightly

**Comment by SavvasStephanides** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/478770/79986525-16307980-84a4-11ea-9da7-ed2deaf26114.png)

**Comment by phillipgardiner** [comment]
Exactly like that :)
