### ISSUE TITLE
Change breadcrumbs to GDS standard 

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#629]
Follow GDS visual standard for breadcrumbs
(https://designsystem.service.gov.uk/components/breadcrumbs/)

**Comment by phillipgardiner** [comment]
https://design-system.service.gov.uk/components/breadcrumbs/

**Comment by phillipgardiner** [comment]
@brockfanning The main visual changes you have listed above are correct. Yes we would also need to take into account the optional pages that are now available to countries (including which page is the homepage etc). 
I think I had mock up somewhere but not able to find it at this time, however your last example above (indicator 2.3.1) is correct and the one we should implement. Breadcrumbs have been shown to work best when at the top of a page.
