### ISSUE TITLE
Documentation on how to add/remove indicators

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#63]
It's not obvious how to add a new indicator, and actually involves 4 steps:
1. Data repository: Create the new CSV file in data/
2. Data repository: Create the new .md file in meta/
3. Site repository: Create the new file in _indicators/
4. Site repository (or fork of sdg-translations): Add the new indicator to the global_indicators.yml translation files

This seems like something that should be documented.

**Comment by brockfanning** [comment]
We should also cover removing indicators. And mention any scripts available to help.

**Comment by brockfanning** [comment]
The new create_indicators feature of jekyll-open-sdg-plugins pretty much removes the need to document and/or script this. It just becomes automatic. So I will close this for now.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I was just about to create a new issue about adding new indicators e.g national indicators. 

Looking at this, the CSV and md just need to be named correctly and then the new indicator should be automatically created right?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Yes, if a country is using the [create_indicators](https://open-sdg.readthedocs.io/en/latest/configuration/#create_indicators) option then that's all they need to do. The starter repository already uses `create_indicators`, so all new countries will be automatically using it.

**Comment by LucyGwilliamAdmin** [comment]
Ok great. Doesn't look like Moldova are using `create_indicators` so to add this, does anything else need to be done other than adding it to the config file?
