### ISSUE TITLE
Review breadcrumb bar position

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#630]
Review position of breadcrumb bar on page

**Comment by phillipgardiner** [comment]
@SavvasStephanides mock up of new position for breadcrumbs. We can work together to ensure the spacing and look on pages is correct.

[Breadcrumbs_#630 - Copy.pdf](https://github.com/open-sdg/open-sdg/files/4508888/Breadcrumbs_.630.-.Copy.pdf)

**Comment by phillipgardiner** [comment]
Believe this has been done and can be closed
