### ISSUE TITLE
Add navigation between goal pages

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#632]

**Comment by phillipgardiner** [comment]
@SavvasStephanides a rough mock up of navigation between goal pages. Please take no notice of the rest of the page as just used it as an example. I have include under the mock up how it would appear on the different pages - including mobile where it would need to become vertically stacked.

I think the above will become more important when we implement the new goal page which will mean longer pages.

[Goal_Navigation_#632.pdf](https://github.com/open-sdg/open-sdg/files/4510278/Goal_Navigation_.632.pdf)

A references for you:
https://components.publishing.service.gov.uk/component-guide/previous_and_next_navigation

@AnnCorp I also need to have a little think about if a similar function will be required for the indicator pages and how they would all fit together.

**Comment by phillipgardiner** [comment]
Possibly leave this one until after upcoming usability testing to see how people move between goals.

**Comment by angelamhkim** [comment]
Jumping into this issue as we wanted to develop something similar to our Los Angeles platform. I saw Germany already deployed it in their platform (http://sdg-indikatoren.de/en/1-1-1/). It would be a useful feature for us to add.

**Comment by brockfanning** [comment]
@phillipgardiner Do we have any new insights regarding this? This functionality has been submitted as a PR. Here are some screenshots of that particular approach:

For goals:

![previous-next-1](https://user-images.githubusercontent.com/1319083/101851659-f67cbd00-3b29-11eb-9bc4-ec0f316d9ee1.png)

For indicators:

![previous-next-2](https://user-images.githubusercontent.com/1319083/101851666-fb417100-3b29-11eb-8378-bb5e18a39523.png)

**Comment by phillipgardiner** [comment]
@brockfanning During UK usability testing, this was shown to not be a major requirement. Primarily because users happily and easily moved between goals (and indicators) using either the breadcrumbs or via returning to the goals page. Therefore it was not deemed a priority for the UK (if required at all). Of course other countries may find different results?

**Comment by brockfanning** [comment]
@phillipgardiner Ok understood, thanks. In that case maybe we could move forward with this as an optional feature. @angelamhkim is interested in this for LA, and Bosnia and Germany both use this feature.

**Comment by phillipgardiner** [comment]
@brockfanning I guess that would be a call for @AnnCorp

**Comment by AnnCorp** [comment]
@brockfanning @phillipgardiner I think including as an optional feature sounds like a good approach.

**Comment by brockfanning** [comment]
Thanks @AnnCorp.

@phillipgardiner Given that, what do you think about styling of the previous/next links in the screenshot above. You'll notice they're styled like blue buttons. Some questions I'm wondering about:

1. Is the blue OK or should they be green to match our download buttons?
2. Is it correct to style them like buttons or should they be ordinary links?
3. Do you have any strong objections to placing them at the top of the page like that? This is how Germany has it. I'm guessing the rationale is that this makes it easy to click through several goals/indicators without having to move the mouse or do any scrolling.

**Comment by phillipgardiner** [comment]
@brockfanning @AnnCorp All good questions brock. To be totally honest the answer is 'I don't know'. I feel a little bit uncomfortable with this one anyway, as in the UK we did not find a need for it. I know this exists in other countries but is it based on a real user need or just a decision taken by a designer at some point to include them?

Are we looking at introducing this just for goals or indicators too? I think the interesting bit of the interaction is when a user moves from a goal to an indicator and visa versa - when they are scrolling through indicators and then wish to change the goal (would they go back to using the breadcrumbs to change goal or return to the goals page etc?

Without user testing any of this it is hard to tell how users would use this and what it should look like. However if it was me, the attached file is the design etc I would be taking into user testing to see how it stood up. This is based on GDS guidelines. 

[Goal_Navigation_#632_v2.pdf](https://github.com/open-sdg/open-sdg/files/5694601/Goal_Navigation_.632_v2.pdf)

A references for you:
https://components.publishing.service.gov.uk/component-guide/previous_and_next_navigation

So in answer to your questions above:
1) I'm not sure. I guess the best option is to make it configurable by the country (as I notice Germany set them the same colour as the goal on which they appear)
2) Don't know. I would have defaulted to links (see design above) and see how that performed in user testing
3) Again not sure. I think at the top is probably the obvious choice, but it depends on how the user uses the site. For example if they view a goal and then scroll the indicators to try and find the one they want and don't, they then might expect something to be at the bottom to save them scrolling back up to the top of the page to change goal. However if they are using them just to jump through the goals then at the top is best. 

Sorry these responses are not concrete, I just think unfortunately for something which appears on the face of it quite simple, it could have quite an impact on the overall navigation of the site.

I wonder if any of the countries could feed in, what they have observed from users using the site?

**Comment by phillipgardiner** [comment]
@brockfanning @AnnCorp Ps as a result perhaps back to top links should be considered for all goals pages? See: https://github.com/ONSdigital/sdg-indicators/issues/3393

**Comment by brockfanning** [comment]
Planning to revisit for 1.4.0.
