### ISSUE TITLE
Review position of download buttons

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#636]
Suggestion from Phill to position within chart/table tab

**Comment by phillipgardiner** [comment]
@SavvasStephanides a rough mock up of new position
[Chart_Buttons_#636.pdf](https://github.com/open-sdg/open-sdg/files/4508860/Chart_Buttons_.636.pdf)
. We can work together to ensure the correct amount of spacing etc.

**Comment by phillipgardiner** [comment]
@brockfanning thanks for the feedback very useful. This was one of those recommendations made of the back of an expert review sometime back. However we having now done the bench marking activity, we have evidence that shows users are able to see the buttons where they are currently placed. 

If @AnnCorp agrees I therefore think we can probably leave the buttons as is and just close this ticket.

**Comment by AnnCorp** [comment]
@phillipgardiner @brockfanning yes agree with closing ticket.
