### ISSUE TITLE
Vertical line on graphs

### ISSUE THREAD

**Issue by AnnCorp** [open-sdg/open-sdg#637]
Use a vertical line on graphs to allow users to see precisely where the cursor crosses the x-axis

**Comment by SavvasStephanides** [comment]
I found [this](https://stackoverflow.com/a/45172506) from a quick search. Probably what we're looking for.

**Comment by SavvasStephanides** [comment]
Example from ONS website referenced in Phill's document:

![ezgif-4-91ea3b28cb64](https://user-images.githubusercontent.com/478770/79486607-dc2c2700-800e-11ea-8ac4-1f241a6bad04.gif)
