### ISSUE TITLE
title text not finding goal info

### ISSUE THREAD

**Issue by dougmet** [open-sdg/open-sdg#64]
As shown in the UK version the title text is pulling through the wrong goal information:

![image](https://user-images.githubusercontent.com/5878305/51609591-6bcd4d80-1f12-11e9-8f5d-7f66c834abf0.png)

Here the short text is for goal 1 not goal 2.

The reason is that on line https://github.com/open-sdg/open-sdg/blob/2d04ac1dad5af4e2fd0925dc9259149e720d6169/_includes/head.html#L17 where we assign the goal information, it uses `page.sdg_goal` which no longer exists at the page level. The page only knows:

```yaml
indicator: 2.3.2
layout: indicator
permalink: /2-3-2/
```

And the rest comes from the meta data which first appears below the `head.html` include https://github.com/open-sdg/open-sdg/blob/2d04ac1dad5af4e2fd0925dc9259149e720d6169/_layouts/indicator.html#L8

So we either need to remove the goal info or pull in the meta data higher up so that the `head.html` include can use it too.

**Comment by dougmet** [comment]
I don't see the harm in pulling in data and meta data at the top. Not quite as pretty from an includes point of view but if they need access to those objects then they need access.

**Comment by brockfanning** [comment]
@dougmet That approach sounds great to me.

**Comment by dougmet** [comment]
Great. I'll put together a PR
