### ISSUE TITLE
1.0.0 remote theme not available

### ISSUE THREAD

**Issue by mgbernal** [open-sdg/open-sdg#643]
We are trying to create a new projecct from template, it looks like 1.0.0 build is not avaialable, only until 1.0.0-beta is it going to be realeased?
Config file:
remote_theme: open-sdg/open-sdg@1.0.0 <- not working displaying theme not found when building

Thanks

**Comment by brockfanning** [comment]
@mgbernal We are testing a bit longer with 1.0.0-beta. If the testing goes well, 1.0.0 will be identical to 1.0.0-beta, so it should be fine to go ahead and try out 1.0.0-beta.

**Comment by mgbernal** [comment]
Thanks. We will use beta :) So we are betatesters-ish.
Regards
