### ISSUE TITLE
Mobile: search toggle reverts to English

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#649]
When looking at a non-English implementation on a phone, when you touch the search toggle, it shows "Hide" (in English). And when you toggle back, it shows "Search" (in English).

**Comment by SavvasStephanides** [comment]
The search label is [hardcoded](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/menu.js#L43) in multiple occasions on `menu.js` which causes the bug. 

A refactor might be in order to make the search/extension of the search box more CSS-based.

**Comment by brockfanning** [comment]
That might be best. If we wanted a quicker fix, it is possible translate stuff in javascript (see [here](https://open-sdg.readthedocs.io/en/latest/translation/#translation-in-javascript)).

Regardless of the solution, I don't think we have "Hide" translated in sdg-translations.

**Comment by SavvasStephanides** [comment]
> I don't think we have "Hide" translated in sdg-translations.

That should be the first step.

I think we shouldn't rely on Javascript as much as we do for drop downs, especially when labels are involved ("Search" etc). CSS might be better, [see example](https://codepen.io/SavvStudio/pen/wvKgKBX).

**Comment by SavvasStephanides** [comment]
Also, on a slightly related note: I accidentally noticed that when the "Search" label is English when resizing the browser, even when the current language is non-English. Not sure if people will ever need to resize the browser other that testing it but it's worth noting:

![ezgif-3-79f664a70f4e](https://user-images.githubusercontent.com/478770/80099904-1e9db880-8567-11ea-8782-bdfd724f4684.gif)
