### ISSUE TITLE
Adjust heading structure across site

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#651]
The hierarchy of headings across the whole site needs to be
considered to ensure visual distinction and consistency

**Comment by phillipgardiner** [comment]
@SavvasStephanides how many H levels do we need? H1, H2, H3, H4????

From what I can work out based on GDS guidelines, https://design-system.service.gov.uk/styles/typography/

I would suggest:
H1 = 36px
H2 = 24px
H3 = 19px
Normal copy text 15px
We may also need to introduce a lead copy text size, something like 17 or 18px for text at the start of the goals pages or the intro text on the homepage.

To be honest need to see it all side by side to be able to be 100% confident.

**Comment by phillipgardiner** [comment]
@phillipgardiner The lowest I've seen is H5 on the Updates page, but I think these should change. It jumps from H2 straight to H5.

**Comment by phillipgardiner** [comment]
@SavvasStephanides let me know if you need any more information. I believe that the H5 on the Updates page would actually be a H3 = 19px in our new structure.

**Comment by SavvasStephanides** [comment]
Hi @phillipgardiner, I need your opinion on something:

On the indicator page the H1 heading is currently set at `24px`

![image](https://user-images.githubusercontent.com/478770/80395023-9262fc80-88aa-11ea-83a5-53af0b25f4d5.png)

If I change that to 36px as you suggested, it looks a little too large (especially is the indicator name is big, which often tends to be):

![image](https://user-images.githubusercontent.com/478770/80395236-d1914d80-88aa-11ea-8f30-dc204dfc21d8.png)

Thoughts?

**Comment by phillipgardiner** [comment]
@SavvasStephanides is the example above using our new font? It may be worth doing that card first so we can see it in context. I see what you mean above, lets discuss in our call later :)

**Comment by phillipgardiner** [comment]
@SavvasStephanides update the sizing in my original comment a bit but still need to discuss

**Comment by SavvasStephanides** [comment]
@phillipgardiner 

> is the example above using our new font? 

The screenshot uses the "Open Sans". Here's what it looks like with Helvetica:

![image](https://user-images.githubusercontent.com/478770/80486458-1cff3680-8953-11ea-8a52-b2ec4d127b81.png)

and Arial:

![image](https://user-images.githubusercontent.com/478770/80486529-3902d800-8953-11ea-950c-2b719f2f076b.png)

**Comment by phillipgardiner** [comment]
@SavvasStephanides Yes agreed it is too large. As discussed on our call one approach is to separate out the indicator number and the text. The indicator number can then become our H1 and the text can be sized as lead copy text 19px. We would need to ensure the H1 has appropriate arial tag? for accessibility purposes. 

To be discussed on team call tomorrow, if OK I believe we would no longfer need tickets #477 and #478 which could be closed.

Examples of proposal shown below:

![Screenshot (11)](https://user-images.githubusercontent.com/60919820/80495366-b9c7d100-895f-11ea-87b9-0b4df0594c82.png)
![Screenshot (12)](https://user-images.githubusercontent.com/60919820/80495376-baf8fe00-895f-11ea-9aab-f2f3ffc219c6.png)

**Comment by SavvasStephanides** [comment]
Thanks @phillipgardiner. Yes, I agree that it looks much better and it follows our "rule" of always starting a page with `H1`. 

Phill also made an excellent point regarding accessibility with screen readers. The user will click once to read the "Indicator X" label and then once more to read the indicator name. This can become cumbersome for screen reader users.  This can be fixed with some ARIA magic:

```html
<header aria-labelledby="indicatorId indicatorDescription">
    <h1 id="indicatorId" aria-hidden="true">Indicator 1.2.1</h1>
    <div id="indicatorDescription aria-hidden="true">Proportion of population living below the national poverty line, by sex and age</div>
</header>
```

With the above, the screen reader will read the header as "Indicator 1.2.1 Proportion of population living below the national poverty line, by sex and age" and then move to the next section on the next click.

**Comment by SavvasStephanides** [comment]
@phillipgardiner Another question for you:

Should the same font sizes apply for the mobile layout?

**Comment by phillipgardiner** [comment]
@SavvasStephanides very good question. There is the potential to adapt the font sizes for mobile. But I think (dependent on effort involved) we may be better to see what the current fonts look like on mobile before deciding where the changes need to be?

**Comment by SavvasStephanides** [comment]
@phillipgardiner Thanks! Sounds good.

**Comment by SavvasStephanides** [comment]
Just as a reference, this is how the indicator page with the changes we discussed would look like on mobile (iPhone 11):

<img width="489" alt="Screenshot 2020-04-29 at 16 19 50" src="https://user-images.githubusercontent.com/478770/80613527-50b28d00-8a35-11ea-9030-d4165de3fac6.png">

**Comment by SavvasStephanides** [comment]
@phillipgardiner @AnnCorp @LucyGwilliamAdmin @brockfanning An discussed in the call, this is what the banner looks like if we change the indicator name to an H2 heading:

## Short title

Desktop:

![image](https://user-images.githubusercontent.com/478770/80625228-d0942380-8a44-11ea-98fb-336417574334.png)

Mobile:

![image](https://user-images.githubusercontent.com/478770/80625314-edc8f200-8a44-11ea-99ae-98748d179ceb.png)

## Long title

Desktop:

![image](https://user-images.githubusercontent.com/478770/80625015-75fac780-8a44-11ea-8c37-bca6d88098f8.png)

Mobile:

![image](https://user-images.githubusercontent.com/478770/80625105-9b87d100-8a44-11ea-8ae0-773973549ecc.png)

**Comment by AnnCorp** [comment]
Thanks @SavvasStephanides. Think this looks better on desktop, the number and name look more connected as less difference in size. Mobile a bit more difficult though...

**Comment by brockfanning** [comment]
Maybe if they were closer together? Also I was wondering about having a line in between them, if that didn't make it look too busy. (not a designer though, so I defer to Phil's preference)

**Comment by phillipgardiner** [comment]
@SavvasStephanides. Thanks for this. My initial view is making the text that big it starts to become unreadable (not very easy to scan). Can we have a call this afternoon to discuss? I have had a play this morning and believe there may be something we can do if we use a 22px size font, 1.4 line spacing. I'd also like to discuss font weighting and the use of spans as per @brockfanning suggestion yesterday.

<h1 class="govuk-heading-xl">
  <span class="govuk-caption-xl">govuk-caption-xl</span>
  govuk-heading-xl
</h1>

**Comment by SavvasStephanides** [comment]
@phillipgardiner Happy to discuss over a call.

> I'd also like to discuss font weighting and the use of spans as per @brockfanning suggestion yesterday, as I have found examples of its use on GDS pages.

Can you please paste a few links of these examples? That'd give us an idea of what we're going after.

**Comment by SavvasStephanides** [comment]
Just had a discussion with @phillipgardiner regarding the styling of the header in the indicator page. We thought we'd set the "lead copy" paragraph font size to 22px (from 19px). Both me and Phill think it looks great and it works better at combining the title with the paragraph. A few screenshots below. Let me know what you think.

## Screenshots

### Desktop

![image](https://user-images.githubusercontent.com/478770/80720623-11e40c00-8af5-11ea-8435-220069b2dad9.png)

### Mobile

![image](https://user-images.githubusercontent.com/478770/80720808-5a032e80-8af5-11ea-91ab-afebd0c39df0.png)

**Comment by phillipgardiner** [comment]
@SavvasStephanides thank for this. I'd add to this. the balance here is making all H1 headers work across all pages and all lead text work across pages where it is appropriate (which we currently think 22px does). Part of the problem with making it larger is it actually become less readable.

**Comment by phillipgardiner** [comment]
Also for mobile we may look at making some slight changes such as moving the goal icon centre and then starting the indicator text underneath, to enable to the text to be full width rather than having all the white space down the left hand side.

**Comment by AnnCorp** [comment]
@SavvasStephanides is there a feature branch link you could post for this please, with the latest sizings you and Phill have agreed?? Like @phillipgardiner 's suggestion re trying different layout for mobile.

**Comment by SavvasStephanides** [comment]
@AnnCorp Hi Ann. I could create a feature branch with the font size changes. Phill's suggestion for a different layout will take a bit longer to complete.

**Comment by SavvasStephanides** [comment]
@AnnCorp Here's the feature branch: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/heading_styling/

Still a work in progress, but most of the heading styling is there.

**Comment by SavvasStephanides** [comment]
@AnnCorp @brockfanning 

According to a discussion with @phillipgardiner, his suggestion is that the mobile version of the indicator banner would look like this (if I'm not mistaken):

![image](https://user-images.githubusercontent.com/478770/80805299-8f6c5280-8baf-11ea-9dc5-5643c7ff6bf5.png)

**Comment by AnnCorp** [comment]
Thanks @SavvasStephanides . Def looks better with the text full width not wrapping round image. @phillipgardiner is it standard to have icons in middle like this, not to left?

**Comment by phillipgardiner** [comment]
@SavvasStephanides @AnnCorp Thanks for this Savvas looking good. Ann, no standard, this was just initial thoughts we had based on our conversations. Now having seen it, I believe like you it would probably look / work better on the left - sorry savvas!

**Comment by SavvasStephanides** [comment]
@phillipgardiner That's OK. That was just a quick mockup using the Devtools. You're actually making my life much easier 🙂

**Comment by phillipgardiner** [comment]
@brockfanning @SavvasStephanides A slight side but can we also check that the text that is displayed when you type a phrase into the search box is also displayed at 16px. Wasn't sure if this would automatically change due to changes being made or weather the settings for that sit separately somewhere. Thanks

![Screenshot (17)](https://user-images.githubusercontent.com/60919820/81295384-3ba6b100-9068-11ea-8423-4b7c98e44d8f.png)
