### ISSUE TITLE
Remove navigation search when on search results page

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#666]
When a user is on the search results page. The search box in the navigation bar should NOT be visible. This will stop confusion about which search box to use when they wish to undertake a second subsequent search. Therefore the top search is visible on all pages apart from search results.

**Comment by brockfanning** [comment]
@phillipgardiner Apologies if we already discussed this, but what would you think about removing the second search bar from the search results page? Ie, if the user wants to do another search, they would have to use the search bar in the navigation area (the same one they used to start with).

This came to mind as I'm looking at an older version of Open SDG, when it used to work this way. See [here](https://kazstat.github.io/sdg-site-kazstat/ru/search/?q=%D0%9A%D0%B0%D0%B7%D0%B0%D1%85%D1%81%D1%82%D0%B0%D0%BD) for an example.

At the moment I can't remember why/when we added the search bar on the search results page. It's possible that it was a developer decision and not in response to any user needs.

**Comment by phillipgardiner** [comment]
@brockfanning. No don't think we did discuss this option. I believe based on best practices that the better option is to remove the search in the navigation rather than the search results page. For an example of what I mean see https://ee.co.uk/. The main issue is having two places in which to type additional searches.

However, of course i'm open to discussing based on development effort etc. As an MVP could be to remove the one on the search results for the time being with the longer term aim to remove the navigation one? Additionally we may run into problems about how and where to display things such as the 'Search results term and the number of results. 

Like I say I think its a case of why we are considering the alternative, if it is effort / time before delivery than thats a call for @AnnCorp to make I guess? but if its just on experience alone then I would advocate removing the search from the navigation as the best way forward as this is common practice and matches users expectations.

**Comment by AnnCorp** [comment]
A few queries on this please:
1. @phillipgardiner is the best practice on this documented anywhere that can refer to. I noticed that GDS also remove the top search bar: https://www.gov.uk/service-manual/service-standard
2. @brockfanning & @SavvasStephanides did we end up with 2 search bars on search results page, because its automatically added by lunr in the search results section?
3. @phillipgardiner  @SavvasStephanides briefly what effort/action would be required to 
(a.) remove/hide the lower search box in search results and keep top navigation search bar
(b.)  remove/hide the top navigation search bar and keep the lower search box in search results

**Comment by phillipgardiner** [comment]
@AnnCorp 
1) Unfortunately it's not documented as a standard by GDS etc, it is more driven by the guideline to 'put the search box where users expect to find it'. The common pattern nowadays is to hide the top right and place a search box on the results page as that is where their attention is drawn.
2)  N/A
3) From a design perspective the effort / action required would be minimal either way

**Comment by SavvasStephanides** [comment]
> did we end up with 2 search bars on search results page, because its automatically added by lunr in the search results section?

I believe so.

> briefly what effort/action would be required to
> (a.) remove/hide the lower search box in search results and keep top navigation search bar
> (b.) remove/hide the top navigation search bar and keep the lower search box in search results

I'm not 100% sure, we'll have to mess about and see. If the bottom search bar is there due to Lunr, it might be a bit more tricky to remove. Might not be though, some investigation is required (except if @brockfanning has an answer)

**Comment by brockfanning** [comment]
I honestly can't remember why the search-results bar was added - but I think either it was discussed/decided, or I just threw it in during the Lunr change. But it certainly is not required by Lunr.

Regarding the effort needed, it's negligible either way.

**Comment by phillipgardiner** [comment]
The search box displayed on the search page should always match the styling of the search on all other pages
