### ISSUE TITLE
Allow for arbitrary "tags" per indicator

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#67]
There have been multiple requests for some way to identify indicators that are custom, such as country-specific or city-specific indicators. I was thinking that one way to allow this would be support for a "tags" metadata field, which served to add additional tags (next to "Reported online", etc.) and also add CSS classes which could be used for any styling tweaks. Other ideas/approaches are welcome too.

**Comment by dougmet** [comment]
Do we want to consider integrating with search?

**Comment by brockfanning** [comment]
Adding facets to the search page would be awesome. It could maybe be configurable to turn any metadata field into a facet, including this one. That might be a little tricky though because most other metadata fields are simple strings, whereas this Tags field is an array of strings.

But anyway yes I think it's a great idea. We might split that into a separate ticket, since it may involve a little revamping of the search functionality.

**Comment by dougmet** [comment]
yes separate ticket sounds sensible
