### ISSUE TITLE
Rename bulk download zip file

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#679]
Downloaded file is called all_indicators.zip – think this needs to be renamed – maybe to include sdg, country and date?

**Comment by SavvasStephanides** [comment]
I see your point. Fair to include SDG and the country if needed (`sdg_uk_all_indicators.zip`?). The date however might be a bit misleading as the file is created after a data build

**Comment by LucyGwilliamAdmin** [comment]
Good point about the date - think even having sdg and country is an improvement

**Comment by brockfanning** [comment]
Closed by https://github.com/open-sdg/sdg-build/pull/189
