### ISSUE TITLE
Part of footnote is cut off in downloaded images

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#680]
Part of footnote is cut off in downloaded image (see [3.4.2 on test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-4-2/)). Also looks like graph title and disaggregations aren’t central in downloaded image:
This is what’s shown on platform:
![image](https://user-images.githubusercontent.com/43404358/82199285-66f58f80-98f5-11ea-85b2-ea9c1d96a1b9.png)

This is what shows in downloaded image:
![image](https://user-images.githubusercontent.com/43404358/82199356-7ffe4080-98f5-11ea-813b-bb24c1363045.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Could you give #707 a try and see if it helps?

**Comment by brockfanning** [comment]
Fixed by #707
