### ISSUE TITLE
Metadata tab panel too far over when only headline data

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#681]
Metadata tab panel starts too far over when there is only headline data available i.e. there aren’t any disaggregations (see [1.1.1](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/1-1-1/) on test site):
![image](https://user-images.githubusercontent.com/43404358/82199542-ba67dd80-98f5-11ea-984b-c3287c968e2a.png)

**Comment by brockfanning** [comment]
Fixed by #695
