### ISSUE TITLE
Metadata tab panel pushed down by disaggregation section

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#682]
Metadata tab panels gets pushed down by disaggregation section when disaggregation dropdowns are expanded (see [5.2.2 on UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/5-2-2/) – expand some disaggregation dropdowns and then scroll down to metadata)
UK test site:
![image](https://user-images.githubusercontent.com/43404358/82199703-f733d480-98f5-11ea-8d36-c55ffb991375.png)

**Comment by brockfanning** [comment]
I'll look into this one - I think I caused this with the recent indicator refactor.

**Comment by brockfanning** [comment]
Fixed by #695
