### ISSUE TITLE
Sources tab looks strange when there's only one source

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#683]
See [1.1.1 on UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/1-1-1/):
![image](https://user-images.githubusercontent.com/43404358/82200002-5db8f280-98f6-11ea-81cf-7f9d879e6352.png)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin It doesn't look too bad to me - can you describe the issue?

**Comment by LucyGwilliamAdmin** [comment]
Not really an issue - maybe it's just me - happy to close though :)
