### ISSUE TITLE
Geojsons open in new tab instead of downloading

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#684]
Is there a way to force the file to download rather than opening in a new tab? This would be more consistent with the rest of the download buttons (see [3.4.2](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-4-2/) on test site)

**Comment by SavvasStephanides** [comment]
Do people actually _need_ to download the GeoJSON files? If yes, then the way to do this is simply to add a [`download` attribute to the `<a>` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download)

**Comment by LucyGwilliamAdmin** [comment]
I'm not really sure - just something I noticed. Do you know what the normal behaviour would be?

**Comment by brockfanning** [comment]
I think people who want a GeoJSON file would probably know what to do with the file, even if it loaded in the browser. But for consistency with the other download buttons I agree it would be nice. Plus it sounds like it's very easy, from what @SavvasStephanides says.

**Comment by brockfanning** [comment]
Fixed by #714
