### ISSUE TITLE
Default selection of disaggregations

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#688]
Most default selecting seems fine except for when a new units type is selected – see [3.3.3 on UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-3-3/) – nothing shows on graph when Percentage (%) of total cases is selected. Also generally for [4.1.1](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/4-1-1/), may also be fixed if first thing is fixed

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning Again, will this be fixed by fixing #781 ?

**Comment by LucyGwilliamAdmin** [comment]
I think this is fine now we have no data message:
https://sdgdata.gov.uk/3-3-3/

**Comment by brockfanning** [comment]
Agreed.
