### ISSUE TITLE
Bullet pointed text is yellow in high contrast

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#690]
Bullet pointed text is yellow in high contrast mode (see this [update on UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/updates/2020/03/06/IWD-2020.html)) – means links within text don’t appear clickable

**Comment by brockfanning** [comment]
Fixed by #708
