### ISSUE TITLE
Map controls are yellow on white background in high contrast mode

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#691]
See [3.4.2 on UK test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/3-4-2/):
![image](https://user-images.githubusercontent.com/43404358/82202012-2861d400-98f9-11ea-8397-d4ececf97ee2.png)

**Comment by brockfanning** [comment]
It's part of a larger change, but I included a fix for this in #700

**Comment by brockfanning** [comment]
Fixed by #700
