### ISSUE TITLE
Tab outline not working properly on extra reporting status tabs

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#693]
Tested reporting status by tier and tab outline isn’t working properly – see this [test site](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test-extras/reporting-status/)

**Comment by SavvasStephanides** [comment]
Thanks Lucy. Removing `float: left` from `#main-content .details` in CSS seems to fix this. Seems to be unneeded.

**Comment by brockfanning** [comment]
Fixed by #713
