### ISSUE TITLE
Create platform logo

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#7]
Should we create a logo for this platform as general branding? To start it could display on the (soon-to-be-implemented) docs site, and on the [Github page](https://github.com/open-sdg).

**Comment by brockfanning** [comment]
Here's something simple I made in Google Slides:
![open-sdg-logo-draft](https://user-images.githubusercontent.com/1319083/50861338-537fff00-1366-11e9-9c92-3f9fdb1727ac.png)

**Comment by brockfanning** [comment]
On further thought it doesn't do much good to have a logo with just text. The main point is to have a square-shaped logo for favicon-related usage. So, needs to be something square that's recognizable even when tiny.

**Comment by brockfanning** [comment]
@AnnCorp sure thing, actually here is the code if you'd like to play around with the variables. This one has the canopy a bit bigger and the blues for the handle: https://codepen.io/brockfanning/pen/KbGmxw?editors=0010

**Comment by brockfanning** [comment]
Just adding a note here after offline discussions: We're hoping now that we might be able to use the UN's color wheel that everyone is already familiar with. @AnnCorp do you have any updates on whether that's possible?

**Comment by AnnCorp** [comment]
One of our team re-checked the UN SDG branding guidelines and sent me the following:

III. USE OF THE SDG COLOUR WHEEL
The SDG colour wheel may be used by UN entities and non-UN entities as illustrated in these guidelines.
UN and non-UN entities wishing to integrate the SDG colour wheel into a separate logo design must provide the following information for advance written permission by the United Nations Department of Public Information:
1.	A short statement of identity (nature of the entity and its objectives);
2.	An explanation of how and where the SDG colour wheel will be used, including the names of countries/territories where the SDG colour wheel will be used, and duration of its use.
It goes on to show what you can’t do to the wheel – no stretching, re-colouring, putting in boxes, cropping, dis-jointing etc
Full guidelines are here: https://www.un.org/sustainabledevelopment/news/communications-material/

**Comment by brockfanning** [comment]
@AnnCorp Ok great, that sounds promising. What do you think about these responses?

1. A short statement of identity (nature of the entity and its objectives)

Open SDG is a reporting platform developed for managing and publishing data and statistics related to the UN Sustainable Development Goals (SDGs). It is built exclusively with open-source libraries and tools and can be hosted and maintained using free services.

2. An explanation of how and where the SDG colour wheel will be used, including the names of countries/territories where the SDG colour wheel will be used, and duration of its use.

The SDG colour wheel will be used in three ways:
1. The "favicon" that ships with the Open SDG platform will be the SDG colour wheel. As countries implement this Open SDG platform, most/all of them will override this favicon in favor of their national flag. But any country that does not override the favicon will display the SDG colour wheel. (A "favicon" displays as a small square logo in web browser tabs when displaying a site.)
2. The SDG colour wheel will display as a graphic on this GitHub page, to the left of the "Open SDG" title: https://github.com/open-sdg
3. The SDG colour wheel will be included as a graphic in any blog posts, emails, or other communications about the Open SDG platform.

Am I missing any other ways we'd need a logo?

**Comment by AnnCorp** [comment]
Thanks for starting off the response @brockfanning. As we're not integrating the wheel into a logo design (eg if we used the wheel in place of the 'O' in Open SDG) from re-reading the guidelines it seems we could be OK to proceed without permissions. Perhaps we could implement based on this assumption and then send examples of how using with statement of identity, uses etc and check branding people happy with it? Previously there's been quite a delay in us receiving a response to branding queries.
Would we want to include in the Open SDG documentation too?

Re the statement of identity, perhaps could add a little text to make something like the following:
Open SDG is a reporting platform developed for managing and publishing data and statistics related to the UN Sustainable Development Goals (SDGs). Built exclusively with open-source libraries and tools, it is freely available for any country or organisation to reuse and can be hosted and maintained using free services. Open SDG is the result of collaboration between the US government, UK Office for National Statistics and the Centre for Open Data Enterprise. 
Could tag on a line at the end 'UN Statistics Division are actively exploring reuse of Open SDG in their DfID-funded SDG Monitoring project.' or could put that in the covering email when we send it off.

**Comment by brockfanning** [comment]
Ah, I misread it. And yes, adding it to the documentation is a good idea. I will put together a PR!

**Comment by AnnCorp** [comment]
Wow, you’re working very early today! FYI I had some issues merging PRs yesterday although could approve. I’ll have another go today if anything goes through…

**Comment by brockfanning** [comment]
@AnnCorp I've got the PR up if you want to try again: #89. Let me know if you have trouble and I'll take a look at permissions.
