### ISSUE TITLE
Short instructional video for data providers

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#71]
To help train data providers, should we make a short instructional video on how to edit data and metadata? I'm thinking something short and scripted, to be easy to caption in different languages.

**Comment by brockfanning** [comment]
Here is a first attempt at a "script" for this video. I've divided it into "scenes", though it might be fine as just a continuous screen-capture.

[Scene 1 - Open SDG]
This video will demonstrate how to update data and metadata for the Open SDG platform. The process requires only an internet connection and a web browser.

[Scene 2 - Visiting GitHub]
The first step is to open your browser and visit Github.com.

[Scene 3 - Signing up for GitHub]
If you have not already signed up for a GitHub account, click “Sign up” to get your free account. 

[Scene 4 - Logging into GitHub]
When you have a GitHub account, click “Sign in” to log into Github.com.

[Scene 5 - Visiting your Open SDG site]
In the same web browser, visit the staging site for your Open SDG platform.

[Scene 6 - Find an indicator that you want to update]
Navigate to the goal and indicator that you would like to update.

[Scene 7 - Editing data]
First we will update data. Click on the “Edit” tab and then select “Edit Data”. This takes you to the Prose.io service.

[Scene 8 - Prose.io authorization]
If you have not already done so, you will need to authorize the Prose.io service. Click on the green icon in the lower right. Then click “Authorize on GitHub”. Finally, return to the staging site for your Open SDG platform, navigate again to the indicator, and once again click “Edit” and “Edit Data”. Since you have authorized Prose.io, you will no longer see a green icon in the lower right.

[Scene 9 - Prose.io - making a data update]
To update the data, simply select a cell and make your change. You can use your keyboard’s arrow keys to move around the table, and then type in your update.

[Scene 10 - Prose.io - committing the update]
Once you have made your updates, click the disk icon to save them. You may need to click twice. Enter a short description of your changes, and then click “Commit”. Note that your changes will not immediately appear on your platform - they will need to be approved by a platform administrator.

[Scene 11 - Editing metadata]
Next we will update metadata. Return to the indicator on the staging site for your platform, and again click the “Edit” tab. This time, click “Edit Metadata”.

[Scene 12 - Prose.io - making a metadata update]
On the Prose.io service, click the Metadata icon on the right. Locate the field you would like to change, and then make your update.

[Scene 13 - Prose.io - committing the update]
Once you have made your updates, click the disk icon to save them. You may need to click twice. Enter a short description of your changes, and then click “Commit”. Note that your changes will not immediately appear on your platform - they will need to be approved by a platform administrator.

[Scene 14 - Summary]
This video has demonstrated how to sign in to GitHub.com, and how to use Prose.io to update data and metadata for the Open SDG platform. Thank you for watching.

**Comment by brockfanning** [comment]
On a related note, I just submitted a more wordy text-only version of this as a PR, to go into the ReadTheDocs documentation. #87

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I think this might be covered by #805 ?
