### ISSUE TITLE
Starting unit can change depending on language

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#716]
Something is causing the starting unit to change depending on the language. For example see [links removed, they no longer illustrate this issue].

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning is the alphabetic ordering based on translation key or what that translation key translates to?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Right now, if a site is using "translated builds", I believe the alphabetical order is based on what the translation key translated to, unfortunately. I think it's the main issue behind #972 and #814.
