### ISSUE TITLE
status-backgroundColor-notstarted not working

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#724]
**Please complete the following information** 
github.com/MoBosse/testSite2
1.0.0-beta4

**Describe the bug**
Overwriting the sass variable "status-backgroundColor-notstarted" has no visible effect on the site.

**Expected behavior**
When overwriting the variable like [this](https://github.com/MoBosse/testSite2/blob/develop/_sass/variables.scss#L12) the labels on the goal-page should turn red.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50657629/83485894-4823fb00-a4a8-11ea-8ec9-11a4595b4c8c.png)

**Comment by brockfanning** [comment]
@MoBosse Thanks for finding this bug. The PR #723 should have resolved this. We'll be releasing a new tag soon.
