### ISSUE TITLE
Bulk download button appearance

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#736]
**Please complete the following information** 
Site repository URL: e.g. github.com/ONSdigital/sdg-site (feature branch)
Open SDG version: 1.0.0

**Describe the bug**

**To Reproduce**
1. Go to [http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/)
2. Scroll down to "Download all data" button
3. See error

**Expected behavior**
Text on button should be clear and meet contrast standards

**Screenshots**
http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/opensdg1-data-test/
![image](https://user-images.githubusercontent.com/43404358/83755396-6edb6080-a665-11ea-97ca-48e4ff97814e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81

**Comment by SavvasStephanides** [comment]
Thanks Lucy. It looks fine on my system (Mac, Chrome 83). I'll run some tests on BrowserStack. Thanks for pointing this out!

**Comment by brockfanning** [comment]
This bug is being discussed in #748 so I'll close this one.
