### ISSUE TITLE
Merge data with GeoJSON at build time

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#74]
Right now the mapping solution using Javascript to merge the CSV data with the GeoJSON boundary files at "run time". Can we instead do this at "build time", so that the merged file (a GeoJSON file with yearly data included) can be accessed programmatically like a web service?

A critical piece of this would be to find out the global standard for the format/schema of the GeoJSON data that needs to be generated.

**Comment by dougmet** [comment]
most likely this will be implemented at [sdg-build](https://github.com/open-sdg/sdg-build). The geojson would be linked to from the metadata.

It will be easier once proper class definitions are setup open-sdg/sdg-build#4 and we can have various write methods that combine data and metadata.

**Comment by brockfanning** [comment]
Closing this since it will be discussed in sdg-build.
