### ISSUE TITLE
Indicators out of order

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#745]
**Please complete the following information** 
Site repository URL:  github.com/ONSdigital/sdg-site
Open SDG version: 1.0.0

**Describe the bug**
Indicators out of order -  targets greater than 9 appearing after alphabet targets

**To Reproduce**
1. Go to [https://onsdigital.github.io/sdg-indicators/8/](https://onsdigital.github.io/sdg-indicators/8/)
2. Scroll down to target 8.a
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43404358/84694112-8e656980-af40-11ea-8285-063eac98ebdb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81

Using goal-by-target layout but issue also occurs with goal layout

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning, I've had a further look and looks like we're missing indicator_number in the metadata files. However it look like indicator is in the built metadata, so I'm trying to use the alter_meta function to do meta['indicator_number'] = meta['indicator'] but I'm getting an error:

https://travis-ci.org/github/ONSdigital/sdg-data/builds/698896942

**Comment by MoBosse** [comment]
Hi @LucyGwilliamAdmin,
I do not quite understand what you are describing, but I have already run into this problem as well. I solved it by changing the indicator_sort_order in the meta files from e.g. 08_0a_01 to 08_aa_01. It is not a very elegant solution, but I thought it might help you..

**Comment by LucyGwilliamAdmin** [comment]
@MoBosse thanks for letting me know :)

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think we could take the solution by @MoBosse and add it to the jekyll-open-sdg-plugins code. I put up this PR: https://github.com/open-sdg/jekyll-open-sdg-plugins/pull/37

If you're interested in testing it, pointing to a branch of a Ruby gem can be a little tricky, but it should work with this in the Gemfile:

`gem 'jekyll-open-sdg-plugins', git: 'https://github.com/brockfanning/jekyll-open-sdg-plugins.git', branch: 'sort-order-alpha'`

**Comment by MoBosse** [comment]
@brockfanning, @LucyGwilliamAdmin I don`t know why but right now the indicator order [here](https://g205sdgs.github.io/sdg-indicators/8/) is messed up again, despite using '08-aa-01' for indicator_sort_order. 

(I am pointing to open sdg master banch as remote theme)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning I missed your previous comment but just checked on UK live site and ordering is fine now. @MoBosse are you still having a problem with it?

**Comment by MoBosse** [comment]
@LucyGwilliamAdmin If I remember right I solved the problem by adding `| sort: 'indicator_sort_order'` [here](https://github.com/G205SDGs/sdg-indicators/blob/develop/_layouts/goal-by-target.html#L80). 
I did not suggest this as a solution here since I think `indicator_sort_order` is not included in the most data repositories. 
Anyway I do not have any trouble with it anymore.
