### ISSUE TITLE
Page becomes unresponsive when disagg selected out of order

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#747]
**Please complete the following information** 
Site repository URL: github.com/ONSdigital/sdg-site
Open SDG version: 1.0.0

**Describe the bug**

**To Reproduce**
1. Go to [https://onsdigital.github.io/sdg-indicators/9-3-1/](https://onsdigital.github.io/sdg-indicators/9-3-1/)
2. Click on 'Industry lower sub-category' dropdown
3. Click on any item in drop down list e.g. Alcoholic bevarages
4. See error (page freezes and becomes unresponsive for 3/4 minutes)

**Expected behavior**
Nothing should happen e.g. nothing is selected, nothing freezes

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 81

**Comment by SavvasStephanides** [comment]
Good catch Lucy. It seems to be stuck in an infinite loop which throws a `RangeError: Maximum call stack size exceeded` once clicked.

![image](https://user-images.githubusercontent.com/478770/84780870-0635a180-afde-11ea-86b7-a4966ac82e65.png)

**Comment by brockfanning** [comment]
I think this might be fixed by #761.
