### ISSUE TITLE
Wrong color of download btn text dependeing on browser and language

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#748]
**Please complete the following information** 
Site repository URL: https://g205sdgs.github.io/sdg-indicators/
Open SDG version: 1.0.0

**Describe the bug**
Text of download-all-button is dark blue on green background (when changing the language to english the text is white on green background).

**To Reproduce**
1. Go to 'frontpage'
2. Click on 'language --> German'
3. Scroll down to 'download all data button'

**Expected behavior**
Text should be white

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50657629/84997360-c7732900-b14e-11ea-919e-abc9681a9ef6.png)

**Desktop (please complete the following information):**

!! Issue seems to appear only using firefox. (Tested with version 68.9.0esr (32-Bit))
Chrome and internet explorer showed the expected behavior!!

**Smartphone (please complete the following information):**

Tested on mobile (Android): shows expected behavior even when using firefox

**Additional context**

**Comment by brockfanning** [comment]
Thanks @MoBosse. @LucyGwilliamAdmin noticed this in #736 and at the time I couldn't recreate it. I believe I see what's happening now - it only turns blue after the button has been used once, and the page is reloaded. I suspect if you clear your browser history and try again you can confirm this.

**Comment by MoBosse** [comment]
Thanks @brockfanning, you are right, clearing the browser history sets the color back to white. 
Sorry for opening an issue that was mentioned before. Shall I close this one?

**Comment by SavvasStephanides** [comment]
@MoBosse Thanks Moritz. I was now able to reproduce this on Firefox. No need to close this, it seems like this is something that needs to be fixed.

**Comment by brockfanning** [comment]
#759 is an attempt to resolve this.
