### ISSUE TITLE
Inconsistent order of sub-categories in table head

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#756]
When you have chosen a category (England and Wales in screenshot) and two options from different sub-categories (Birthweight: 1000-1499 and Age: 19 and under), the order of categories in the table header is differnt from each other.
In this example the birthweight is placed before "England and Wales" while the age is placed behind it.

See screen shot below or example [here](https://sdgdata.gov.uk/3-2-2/)
![grafik](https://user-images.githubusercontent.com/50657629/86372635-bb28b900-bc82-11ea-8a24-f7f9362b47ba.png)

Obviously it has nothing to do with alphabetical order since both sub-categories start with a number.

It does only occour since open-sdg 1.0.0

**Comment by brockfanning** [comment]
#760 adds some sorting that may resolve this.
