### ISSUE TITLE
Control text color of status labels in target page

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#770]
**Please complete the following information** 
Site repository URL: https://g205sdgs.github.io/sdg-indicators/1/
Open SDG version: 1.0.1

**Describe the bug**
The text color of the status labels on the target pages seem not be set by the same variables used e.g. on the reporting status page.

**To Reproduce**
Go to https://g205sdgs.github.io/sdg-indicators/en/1/
Recognize that the text in the green label (Reported online) is white
Go to https://g205sdgs.github.io/sdg-indicators/en//reporting-status/
Note that the text in the green label (showing the number of indicators) is black.

**Expected behavior**
Since $status-color-complete was set to black in [variables.scss](https://github.com/G205SDGs/sdg-indicators/blob/develop/_sass/variables.scss), the labels on goal-by-target page should be black aswell.

**Screenshots**
Target page: 
![grafik](https://user-images.githubusercontent.com/50657629/87031306-3a6a3f80-c1e3-11ea-922b-437361bc7173.png)

Reporting status:
![grafik](https://user-images.githubusercontent.com/50657629/87031348-4e15a600-c1e3-11ea-8dad-ef646e4fc12f.png)

**Additional context**
Probably the same issue: could anyone explain how to get rid of the border around the "inprogress" labels?

**Comment by brockfanning** [comment]
@MoBosse I've given this a try in #773 but could use some help in testing it out. I tried to address both the color and border issue.

**Comment by MoBosse** [comment]
@brockfanning looks good to me. An overwrite of the variables $status-color-... and $status-border-... has the expected effect on both the reporting-status page and the goal pages!

**Comment by brockfanning** [comment]
Great!

@LucyGwilliamAdmin this is ready for review. We should make sure that the reporting status and goal pages look the same as before.
