### ISSUE TITLE
Allow for a configurable header with the menu aligned left

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#782]
**Is your feature request related to a problem? Please describe.**

Some aspects of the current header are problematic and would benefit from changes. For example the menu items could be more clear if they were aligned to the left, separate from the language/contrast toggles.

However we do not want to change this for all existing implementations of Open SDG. So we would like to create this as a new optional header.

**Describe the solution that you need**

Solution to be discussed in this ticket, but mainly the goal is to get the menu items aligned to the left, and do something else with the language/contrast toggles.

**Why do you need this feature?**

To improve UX.

**Describe alternatives you've considered**

We'll discuss alternatives in this ticket.

**Comment by brockfanning** [comment]
@phillipgardiner I converted this to an issue, for when you're ready to add details.

**Comment by phillipgardiner** [comment]
@brockfanning The main driver of this ticket is to allow owners of the site (specifically the UK) to position the main navigation on the left hand side. For OpenSDG I imagine this means allows them to have the option of placing the main navigation, left, right or centre.

Find attached the mock-up showing the possible options for placement of the language selector and contrast options as a result of this change. 
[SDG_Left_hand_navigation.pdf](https://github.com/open-sdg/open-sdg/files/5000479/SDG_Left_hand_navigation.pdf)

**Comment by brockfanning** [comment]
@phillipgardiner I've gone back to this issue because in one of the accessibility issues (#922) our custom MENU/SEARCH mobile dropdowns are turning out to be problematic. I was wondering if we could at least consider a revamp of that, along with this new header. My first thought was the common "hamburger menu" that a lot of sites have, since Bootstrap has built-in support for this. I've put up a PR that could be made into a feature branch, but in the meantime here are some screenshots:

## Desktop

![alternate-header-desktop](https://user-images.githubusercontent.com/1319083/94859158-1a24d800-0402-11eb-944c-e13f76ca1212.png)

## Mobile with hamburger menu collapsed

![alternate-header-mobile-collapsed](https://user-images.githubusercontent.com/1319083/94859184-21e47c80-0402-11eb-80a3-890933080cb9.png)

## Mobile with hamburger menu expanded

![alternate-header-mobile-expanded](https://user-images.githubusercontent.com/1319083/94859215-2d37a800-0402-11eb-8baa-dff519b2ba0c.png)

I should mention that in normal Bootstrap the menu has a visual border/background that makes it easier to see what's going on. But I tried to keep the changes to a minimum, so I've just got a grey line underneath the expanded menu. You can demo the default Bootstrap style [here](https://getbootstrap.com/docs/3.3/components/#navbar-default) (scroll down a bit to the first example).

Also, no worries if you don't think we should switch to the hamburger menu. I was just trying to brainstorm fixes for #922.

**Comment by phillipgardiner** [comment]
@brockfanning What are the issues being caused, is it just the focus sequence?

**Comment by brockfanning** [comment]
@phillipgardiner That's right, it's the tab order. I've thought of one idea that might help resolve just that issue, so I'll follow up as soon as I have a chance to try that out.
