### ISSUE TITLE
Increase white space on 'Reporting Progress' page between goals

### ISSUE THREAD

**Issue by phillipgardiner** [open-sdg/open-sdg#796]
On the reporting progress page the goal rows are very tightly packed against the horizontal grey lines. Adding some additional white space will increase the comprehensibility of this page. I believe this would just be a case of changing the bottom margin from something like 4px to 20px. I have attached a screen shot showing the existing spacing and how it could look.

![Screenshot (36)](https://user-images.githubusercontent.com/60919820/89024743-8198ab80-d31d-11ea-9b8a-f4243e9847de.png)

**Comment by brockfanning** [comment]
@phillipgardiner Here's a screenshot of the fix in #824 (increasing margin from 4px to 20px):

![screenshot-127 0 0 1_4000-2020 08 24-09_30_11](https://user-images.githubusercontent.com/1319083/91050371-8edb4a00-e5ec-11ea-8c8d-8d9c1ae0dca2.png)

**Comment by phillipgardiner** [comment]
@brockfanning looks good to me, happy with that 👍
