### ISSUE TITLE
Geojson download button showing for layers that aren't available

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#798]
See map tab on [3.a.1](https://sdgdata.gov.uk/3-a-1/) and [16.6.2](https://sdgdata.gov.uk/16-6-2/) on UK platform.

On both, "Download GeoJSON - Local Authorities" button shows, even though there is no geo data available for that map layer on back-end. When GeoJSON is downloaded, there are no values in the file - it's just the boundaries.

Think it would make sense if GeoJSONs can only be downloaded where there are values

**Comment by brockfanning** [comment]
Besides the download button, another issue is the the zoom functionality, because it switches to this empty layer at the specified zoom level.
