### ISSUE TITLE
Language-related links to external pages in the footer

### ISSUE THREAD

**Issue by MoBosse** [open-sdg/open-sdg#799]
**Is your feature request related to a problem? Please describe.**
It would be good if the selected language would influence the external links in the footer (e.g. to an English/German contact form or social media accounts).

**Describe the solution that you need**
The links that are defined in the config file should be able to be defined for each of the selectable languages individually.
e.g. 
footer_menu:
 - path_de: https://twitter.comdestatis?lang=de
   path_en: https://twitter.comdestatis?lang=en
   translation_key: general.witter

**Why do you need this feature?**
Right now english speaking users are linked to german pages.

**Comment by brockfanning** [comment]
@MoBosse Great point, and I like the idea of the `path_*` configuration approach. Just to throw out an alternative, what if the paths were "translated" like other things? I'm not sure if this would be good or add confusion. An example would be:
```
- path: custom.twitter_url
  translation_key: general.twitter
```

And this assumes that `custom.twitter_url` refers to a translation key, which in this case is only meant to contain URLs, per language.

Again, not sure if that's more or less confusing than the `path_*` config approach.

**Comment by MoBosse** [comment]
@brockfanning I think the translation approach is even better. I tried this by adding the code below to footer.html but the content of "path" (menu.contactPath) does not get translated. Did I make a mistake there? 
```
{% if item.path contains ":" %}
   <a href="{{ item.path }}" target="_blank">{{ item.translation_key | t }}</a>
{% elsif item.path contains "menu." %}
   <a href="{{ item.path | t }}" target="_blank">{{ item.translation_key | t }}</a>
{% else %}...
```
One thought about this approach: Is there any other way than to catch the paths that are to be translated by an if clause? Because this way you have to limit yourself to single folders like "menu, custom, ...".

**Comment by brockfanning** [comment]
The `t` filter can be used freely, because it returns the original string if there was no translation found. So I think something like this might work (moving the assignment of `item_path` up to the top, and running it through `t`):
```
{% assign item_path = item.path | t %} 
{% if item_path contains ":" %}
  <a href="{{ item_path }}" target="_blank">{{ item.translation_key | t }}</a>
{% else %}
  {% assign item_path_first = item_path | slice: 0 %}
  etc...
```

**Comment by brockfanning** [comment]
@MoBosse #825 is intended to demonstrate and implement this approach.

**Comment by brockfanning** [comment]
@MoBosse Have you had a chance to test out that pull-request to see if it solves the problem for you?

**Comment by MoBosse** [comment]
@brockfanning Yes, works well.
For example, the link to our Twitter channel is automatically adjusted according to the chosen language:
![grafik](https://user-images.githubusercontent.com/50657629/96078941-de831700-0eb3-11eb-83b3-c18b1222ebe1.png)
![grafik](https://user-images.githubusercontent.com/50657629/96078954-e8a51580-0eb3-11eb-91ae-5413732e43e2.png)
Thanks!
