### ISSUE TITLE
Favicon cleanup

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#808]
Right now we have five favicons in the [assets/img/favicons folder](https://github.com/open-sdg/open-sdg/tree/master/assets/img/favicons), but we're only using 2 of them. We have [references to other favicons](https://github.com/open-sdg/open-sdg/blob/master/_includes/head.html#L55-L62) but that section is commented out.

I would propose a general clean-up including the following:

1. Create an include file for favicons (eg, `_includes/components/favicons.html`)
2. Pick a popular favicon generator tool (such as favicon.io).
3. Convert the SDG color wheel using this tool
4. Adapt the tool's suggested markup and copy to the new include file
5. Remove our existing favicons and replace with those generated by the tool

After using this approach, we can recommend that users use the same favicon generator tool for their own favicons, and the files should be named as expected, out of the box.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning where is this up to (if anywhere)?

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Nowhere yet, but it should be easy once I get to it.
