### ISSUE TITLE
Support larger datasets

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#818]
**Is your feature request related to a problem? Please describe.**

As the dataset gets larger, performance will get worse. This is unavoidable, but maybe there are some inefficiencies in our code, or architectural factors, that are limiting us too much. We should investigate what the "bottlenecks" are when Open SDG tries to load a very large dataset.

**Describe the solution that you need**

If possible, better performance with larger datasets.

**Why do you need this feature?**

When the platform struggles with larger datasets it appears to the user that the site is broken.

**Describe alternatives you've considered**

Alternatively we could recommend a maximum number of rows of data.

**Additional context**

Here's an example of a very large dataset to test against: https://onsdigital.github.io/sdg-indicators/4-2-1/

**Comment by jwestw** [comment]
I had a very brief look this issue on 4.2.1. 

Only 7 data points are being plotted, though there are >92,000 observations in the original dataset; big but not massive. 

I would be interested to look at the code here to see where the bottleneck may lie. Are 92k datapoints being handed to chart js, or are these being processed before being handed on? It would seem the latter would be the most efficient.

**Comment by brockfanning** [comment]
@jwestw We do a fair bit of data processing before it gets to Chart.js, so I suspect that the bottlenecks are in our own code. The main file where that processing happens is here: https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js

It is probably a good idea to try to do some benchmarking of the various bits of that file to see which parts are taking the most time. I haven't done that before with javascript but could look into it.

While I'm thinking about it, there is one section of that file that sorts the rows, [here](https://github.com/open-sdg/open-sdg/blob/master/_includes/assets/js/indicatorModel.js#L185-L188). I'm not totally sure that the sorting is necessary. (It might be needed for some reason, but offhand I'm not sure what that is. Maybe for the download buttons?) If that's not necessary we might be able to remove that sorting.

**Comment by jwestw** [comment]
Hi Brock, I've had a look a this but unfortunately I have not JS skills and can't really gather what's going on here. I wonder if it's worth running the data processing part in Python before handing it to chart.js. If so, I can probably write a script for that

**Comment by brockfanning** [comment]
I agree that we may be able to do more in Python, as part of the sdg-build library, that would make things easier when it gets to the javascript. I think once we know where the bottlenecks are in the javascript we'll have a better idea of what the next steps are.

**Comment by leeoniya** [comment]
all the time (~15,000ms) is spent in finding unique Year values using an inefficient linear `indexOf` search:

![uniques](https://user-images.githubusercontent.com/43234/92197373-2afc2100-ee37-11ea-86b8-c34e9ac3fdcb.png)

the following does the same job in ~5ms for the 92k element array:

```js
function fastGetUniqueValuesByProperty(prop, rows) {
  const uniques = new Set();
  rows.forEach(r => uniques.add(r[prop]));
  return [...uniques].sort();
}

fastGetUniqueValuesByProperty("Year", rows);
```

**Comment by brockfanning** [comment]
@leeoniya Brilliant! I put up a PR for this at #871. We don't have any transpilation and still try to support IE11 (sadly) but I believe it still works with some polyfills. Does that look OK to you?

I would love to learn how to do this in the future! How did you get those line-by-line benchmarks in your screenshot?

**Comment by leeoniya** [comment]
> and still try to support IE11 (sadly) 

:(

you should be able to do it without polyfills by using a plain object. something like (untested):

```js
function fastGetUniqueValuesByProperty(prop, rows) {
  var uniques = {};
  rows.forEach(function(r) {
    uniques[prop] = 1;
  });
  return Object.keys(uniques).sort();
}
```

(a plain `for` loop with cached array length might be a lot faster than forEach in IE11 (i forget) but you should test).

> I would love to learn how to do this in the future! How did you get those line-by-line benchmarks in your screenshot?

pop open Chrome's devtools and record a performance profile during page load:

https://developers.google.com/web/tools/chrome-devtools/evaluate-performance

**Comment by brockfanning** [comment]
Awesome, thank you for the Chrome tip; that is huge.

I hadn't considered the plain object - that makes sense, but the only issue there is that the years get cast to strings. I think I'm fine using the polyfills. In fact I like the idea that we can eventually just remove the polyfills when we drop IE support, and we'll already be using (at least some) modern code.

**Comment by leeoniya** [comment]
btw, if you do actually need to display 92k datapoints in a chart ;)

https://github.com/leeoniya/uPlot#performance

**Comment by brockfanning** [comment]
Nice! I will take a closer look. Right now some of our code is very specific to Chart.js, but I'm curious how easy it would be to abstract our code enough that the charting library were more swappable. That would be a huge improvement in flexibility if we could get there.
