### ISSUE TITLE
Make sure disaggregation percentage bar behaviour is described to screen readers

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#833]
**Issue from DAC report:**
There is a bar which demonstrates visually a proportion of filters selected. There is no text alternative for this information. In addition, this updates dynamically, and this behaviour is not described to screen reader users.

**Solution from DAC report:**
Implement description as status message.

Page 65 on DAC report

**Example from DAC report:**

```
<div class="bar">
    <div class="selected" style="width: 50%;" role="status">
        <span class="visuallyhidden">50 percent of age sub-categories 
          selected</span>
    </div>
</div>
```

![image](https://user-images.githubusercontent.com/43404358/91310473-d3601480-e7a9-11ea-80cc-fa90474cc765.png)

**Comment by brockfanning** [comment]
@AnnCorp @phillipgardiner Before I start on this one - I just wanted to throw out a potentially easier option: removing that percentage bar. I'm fine with keeping it and working on an accessible version, but just wanted to make sure that option was discussed.

**Comment by AnnCorp** [comment]
@brockfanning  Not sure how much effort is required to make this fix? I think the percentage bar is useful when data filter sections are collapsed to see which disaggregations have active selections but if there was a simpler way to just show yes/know if sub-categories are selected would be happy to consider that. @phillipgardiner what are your thoughts please - simplify? Leave as is and make changes required by DAC and explore how bar is used during future user research?

**Comment by phillipgardiner** [comment]
@brockfanning @AnnCorp Brock you actually beat me to this. I was going to raise is the simpler solution to remove the percentage bars. I guess the question is what is the user need for them? I have to admit from a personal perspective, firstly I did not notice them until I had been on the project sometime, and even when I did I wasn't totally sure of their purpose (but that is literally from my own view) not representing users. These are not something I have seen before. Do we have any feedback that these are used by anyone? I dont currently have anything. One option is to remove them and see if this has any impact during the upcoming usability testing etc - my gut says it wont have any impact.

Going forward I believe this whole area is something that could probably do with some thinking and a potential re-design.

**Comment by brockfanning** [comment]
In terms of level of effort - it is a moderate difficulty - not a super easy tweak, but also not something that requires much re-structuring. The task would involve writing the javascript that will update the new "status" element dynamically with the current percentage. I would guess 4 or 5 hours with testing.

I'm wondering if the drop-downs should always default to being opened when there are subcategories within them selected. That way, the only way they would be closed with selections is if the user had done that intentionally.

My personal opinion is an agreement with Phil's, that probably most new users of the platform do not notice or benefit from the feature.

**Comment by AnnCorp** [comment]
@brockfanning @phillipgardiner Lucy checked with Data team and their use of it is similar to mine - a quick way of seeing what sub-categories have selections when the sub-categories are collapsed, particularly useful when there are multiple sub-categories to navigate. 
Am happy to lose the functionality of showing what percentage of items are selected but if there a much simpler alternative to just show a more boolean used/not used kind of status for the sub-categories? 
Could try Brock's suggestion for defaulting to open if selections within it as an interim and ask Data team to test that via a feature branch, though where there are multiple sub-categories with long lists in them this may not fully meet the need (but we could explore that later if no obvious other solution at the moment).

**Comment by phillipgardiner** [comment]
@AnnCorp @brockfanning is there an example indicator where there are lots of sub categories? I could take a look then. I think also looking at this on mobile would be useful.

**Comment by AnnCorp** [comment]
@phillipgardiner 3.4.2 has a few but @LucyGwilliamAdmin or Data team may have some other suggestions too

**Comment by phillipgardiner** [comment]
@AnnCorp @brockfanning thanks for the link. Perhaps going forward we could consider using something like listboxes: https://www.nngroup.com/articles/listbox-dropdown/, but this is too big a change right now without user testing etc. 

GOV.UK are also working on something smilar which also indicates if you have an option selected: https://finder-frontend.herokuapp.com/component-guide/option-select/with_option_pre_checked and https://finder-frontend.herokuapp.com/component-guide/option-select.

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner [5.2.1](https://sdgdata.gov.uk/5-2-1/) has quite a few subcategories

**Comment by brockfanning** [comment]
@AnnCorp Do I remember right from the last call that we can close this one without any changes to the platform?

**Comment by AnnCorp** [comment]
@brockfanning I don't think we can close this yet. I think it would be one for @LucyGwilliamAdmin to discuss and confirm with DAC re if this can be regarded as a supplementary activity. If so, then I believe no action is required, but if not we may still need to do soemthing.

**Comment by LucyGwilliamAdmin** [comment]
Feedback from DAC consultancy:

> This is one we discussed on the call with Andrew who agreed that this is supplementary information, so no you do not need to implement this one. 

So closing this one
