### ISSUE TITLE
Goal URLs - should we switch to numbers?

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#84]
The tests are failing now, with htmlproofer errors: https://circleci.com/gh/open-sdg/open-sdg/165

I believe it's due to some [goal short titles changing](https://github.com/open-sdg/sdg-translations/commit/67a90d0a8960c9395cf3d27bb0eca5c423258a0a) in the sdg-translations project. Some ways to deal with it:

1. Update the goal paths in the [open-sdg-site-starter](https://github.com/open-sdg/open-sdg-site-starter/tree/develop/_goals) repo to match the new short titles. We would also want to contact implementing countries to make sure their paths get updated too.
2. Revert the changes referenced above that affected the URL slugs - namely goals [11](https://github.com/open-sdg/sdg-translations/commit/67a90d0a8960c9395cf3d27bb0eca5c423258a0a#diff-bd649b1a46574edaedde33a51f9541faL8) and [16](https://github.com/open-sdg/sdg-translations/commit/67a90d0a8960c9395cf3d27bb0eca5c423258a0a#diff-bd649b1a46574edaedde33a51f9541faL26)
3. Update open-sdg in some way to lock down the goal URLs so that they are not dependent on the sdg-translations project. One obvious way would be to change them to numbers. Eg: `example.com/1` instead of `example.com/no-poverty`. This would also involve contacting implementing countries to help them update.

The second option above is the quickest fix, so I'll go ahead and do a PR for that. But thinking longer-term this is worth discussing.

**Comment by brockfanning** [comment]
I've got that PR ready: https://github.com/open-sdg/sdg-translations/pull/51

**Comment by brockfanning** [comment]
Thanks @dougmet the tests are passing now (though the README badge hasn't updated yet for some reason).

I'll leave this issue open for discussion of any possible changes related to this, like maybe the third option mentioned above.

**Comment by dougmet** [comment]
I've always preferred simpler goal urls anyway. So `/3/` for goal three works for me. Might need some local redirects to maintain old links -- this should be possible on a site-by-site basis.

**Comment by brockfanning** [comment]
I'm in agreement there. I guess though if there is resistance to switching to numbers, a fourth option might  be to add a "slug" property in the sdg-translations project, which can be treated as permanent to allow for future changes to the "short" property.

But I do like the idea of numbers for Goals, and if in the future we have Target pages, numbers for them as well. It's a nice predictable approach that lets people easily type in URLs if they want to.

**Comment by brockfanning** [comment]
@AnnCorp Just trying to gauge the comfort level with this -- how would you feel about goal URLs with numbers instead of text? So `https://onsdigital.github.io/sdg-indicators/1/` instead of `https://onsdigital.github.io/sdg-indicators/no-poverty/`?

**Comment by Norric1Admin** [comment]
I've asked the Data team about this, and Ann will be back on Thursday. Will respond when I can, but I don't see why not if the team are happy with it.

**Comment by AnnCorp** [comment]
@brockfanning we're all in agreement here that doing the numbers things makes sense. Would welcome more discussion on impact on those already using Open SDG and how we'd move them across.

**Comment by brockfanning** [comment]
@AnnCorp 
Ok great. The only impact would be that if anyone has bookmarked goal pages, or has published links directly to goal pages (like in blog posts, or tweets, or the like) then they would probably want to implement redirects. There are ways to do redirects in Jekyll, I believe, so we'd want to investigate that and help them implement, if they decide it is worth that effort.

Otherwise it would be a normal update, where we include it in a release with instructions on what to do. Countries would need to update the "permalink" on all of the files in their `_goals` folder, at the same time that they upgrade to the version of Open SDG that has this change. We could help with PRs as needed.

@philipashlock What do you think about this change?
