### ISSUE TITLE
Make chart tooltips accessible to all users

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#843]
**Page 90 in DAC report**

**Issue from DAC report:**
Certain data points are interactive, producing a tooltip containing text details when hovered with the mouse. This functionality is not keyboard accessible. On mobile, when the content is zoomed, the tooltip is not fully displayed on the screen, but when a user scrolls it disappears.

**Solution from DAC report:**
Please ensure that any information and functionality which is available to sighted users navigating with a mouse is accessible to all users. A control could be provided which allows users to single out particular points on the graph and relay the corresponding percentage information. 

**Example from DAC report:**
No example provided

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Adding a keyboard-accessible control to highlight each data-point is going to be a very involved piece of development. I'd recommend stepping back first and considering a couple of things:
1. Does the presence of the table make up for the chart not being accessible? If so, can we settle for inaccessible tooltips?
2. Should we add a configuration option that prevents the tooltips from displaying?

Also here is some ongoing discussion about keyboard navigation and Chart.js: https://github.com/chartjs/Chart.js/issues/1976

**Comment by brockfanning** [comment]
Noting that in the Chartjs issue linked above there's a link to an example of adding event listeners to the left/right arrow keys, to activate tooltips. This may be feasible for us.

**Comment by brockfanning** [comment]
I've got a first draft of accessible tooltips ready, though it depends on another PR.

**Comment by LucyGwilliamAdmin** [comment]
> I've got a first draft of accessible tooltips ready, though it depends on another PR.

Sounds great! Which PR is it dependent on?

**Comment by brockfanning** [comment]
It changes a few of the same files as #894 so I figured I would wait until that's merged before putting up the CR.

**Comment by LucyGwilliamAdmin** [comment]
> It changes a few of the same files as #894 so I figured I would wait until that's merged before putting up the PR.

That makes sense 👍
