### ISSUE TITLE
Written guidance: How to change page titles

### ISSUE THREAD

**Issue by jwestw** [open-sdg/open-sdg#857]
Following the changes in #834 we should write up some instructions on how to change the page titles for each of the two methods (for automatically generated and non-automatically generated pages)

**Comment by brockfanning** [comment]
Let's make sure to add this to https://open-sdg.readthedocs.io/en/latest/configuration/#create_pages

**Comment by brockfanning** [comment]
We also need documentation on creating pages, and mention this title stuff there too.
