### ISSUE TITLE
Allow deeper nesting in fields selector

### ISSUE THREAD

**Issue by dougmet** [open-sdg/open-sdg#86]
Currently the menu can only support one level of nesting. Fields are either parents, or `child` (literally a css class) . In reality we sometimes get deeper nesting. It would nice to generalise the code so that it can nest more deeply. I'm fine if there's still a limit, but ideally it should allow for another couple of levels and then it's up to the site maintainers if they like it or not.

See ONSdigital/sdg-indicators#2916 for a longer discussion.

**Comment by Norric1Admin** [comment]
Thanks @dougmet - this will improve how complex indicators (5.2.2) are displayed, and just sounds like a useful feature to have in general, as lower-level geographies will need to be nested.

**Comment by brockfanning** [comment]
We'll revisit in future user experience review.
