### ISSUE TITLE
Add aria label to A A contrast buttons

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#866]
![image](https://user-images.githubusercontent.com/43404358/91979752-1f690700-ed1e-11ea-8171-4af80fd7b773.png)

Spoke with DAC team this morning. For the above buttons to be accessible, they need to be given aria labels e.g. "Enable high contrast" and "Enable default contrast" (already have translations [here](https://github.com/open-sdg/sdg-translations/blob/master/translations/en/header.yml#L10-L11)

**Comment by brockfanning** [comment]
To discuss with DAC - these links already have `title` attributes. Is `aria-label` necessary when it would only duplicate the `title` attribute?
