### ISSUE TITLE
Use native HTML component for the table sort button

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#869]
**Page 100 in DAC report**

**Issue from DAC report:**
Column headings within the tables are focusable and act as sort ascending/descending buttons upon activation. However, they have no semantic role to describe to expose this behaviour to assistive technology in order for screen reader users and voice activation users to engage with this functionality. Setting a table heading as focusable meant that screen reader users could not use the standard keyboard shortcuts to navigate the table.
These shortcuts ensure that the column heading information is relayed as users navigate the table data to ensure the information is understood.

**Solution from DAC report:**
Please use native HTML components wherever possible, for example, the button element.

**Example from DAC report:**

```
<div style="display: none;">
    <span id="ColumnSortInfo">Click to sort by this column</span>
</div>
…
<th scope="col" class="sorting_asc" rowspan="1" colspan="1" style="white- 
  space: nowrap;">
    <button aria-sort="ascending" aria-controls="DataTables_Table_0"
       aria-describedby="ColumnSortInfo">
        <span>Year</span>
    </button>
    <span class="sort" aria-hidden="true"></span>
</th>
```

**Comment by brockfanning** [comment]
I'm going to check with DAC on this one. The table headings do have `aria-label` attributes which does seem to be read aloud by screen-readers. And as I can tell, the keyboard navigation (CTRL + ALT + arrow keys) does still work.
