### ISSUE TITLE
Make this theme a Ruby gem

### ISSUE THREAD

**Issue by brockfanning** [open-sdg/open-sdg#92]
This repository is a Jekyll theme which, so far, is being used with the help of the `jekyll_remote_theme` plugin. But we could also make this theme a Ruby gem, and allow users to use it in the normal way, without using `jekyll_remote_theme`. Is there any reason we should not add the required .gemspec file and push this to rubygems.org?

**Comment by dougmet** [comment]
Assume `jekyll_remote_theme` would still work? I can imagine with high-speed dev at the moment we may be pointing at GitHub branches quite often. Otherwise, I think this absolutely makes sense.

**Comment by brockfanning** [comment]
Yep, there's no reason that countries would need to stop using `jekyll_remote_theme`. This would, I believe, just add a second option for how to use Open SDG.
