### ISSUE TITLE
Make map tab panel focusable instead of the element containing the map

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#923]
**URL:** http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-a-1/

The `<div>` is focusable and all content is relayed including ‘map loading’ message, even when the map is already loaded.

**Solution:**
Please ensure that the tab panel is focusable, but the div containing the graphic is not, unless it is assigned a label and role.

**Example:**

```
<div role="tabpanel" class="tabPanel" id="mapview" aria-hidden="false" aria-labelledby="tab-mapview" style="" tabindex="0">
  <div id="map" aria-describedby="table-alternative" class="leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch- drag leaflet-touch-zoom" style="position: relative; outline: none;">
    <img src="/dac2020/assets/img/loading.gif" alt="Loading map"> […]
  </div>
</div>
```

instead of:

```
<div role="tabpanel" class="tabPanel" id="mapview" aria-hidden="false" aria-labelledby="tab-mapview" style="">
  <div id="map" aria-describedby="table-alternative" class="leaflet-container leaflet-touch leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch- drag leaflet-touch-zoom" tabindex="0" style="position: relative; outline: none;">
    <img src="/dac2020/assets/img/loading.gif" alt="Loading map"> […]
  </div>
</div>
````

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin Would it be possible to add to the description what the problem is that we're trying to solve? The only issue I gather from the description is that screenreaders are reading a "map loading" message. Is that the only issue?

**Comment by LucyGwilliamAdmin** [comment]
That's all they've said about the issue - but I think it also related to the latest issue I added (#924) re. making tabs focusable
