### ISSUE TITLE
Mark slider year up as text instead of a link

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#939]
URL: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/3-a-1/

**Screen shot:**
![image](https://user-images.githubusercontent.com/43404358/94694908-3a369780-032d-11eb-969c-b52ebd614cee.png)

The year ‘2016’ is implemented as a link and the link text changes depending on the year selected, however it does not seem to perform any function upon activation.

Solution:
If a link has no purpose, please consider marking it up as text and not as a link.

**Comment by brockfanning** [comment]
As with others, this is a third-party library but I believe it can be overridden.
