### ISSUE TITLE
Tab panels are focusable but not on page load – tabs have to be switched before the tab panels are focusable

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [open-sdg/open-sdg#962]
From DAC:

> “The tab panels are focusable but not on page load – tabs have to be switched before the tab panels are focusable.” – here is what I mean:

> No tabindex attribute on page load:
> ![image](https://user-images.githubusercontent.com/43404358/96262241-70c11300-0fb9-11eb-8f4a-435b4d0286d0.png)
> 
> Once I click a tab panel, tabindex attributes appear:
> ![image](https://user-images.githubusercontent.com/43404358/96262296-820a1f80-0fb9-11eb-825f-5e56a66ecf5c.png)
> 
> The currently open tabpanel on pageload is not in focus sequence so users who are looking for the tab that is already open, and don’t need to select it won’t find the tabpanel in focus sequence. 
> 
> A good example is: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html.  Their tabs always have a tabindex of 0, and this works fine because the ones that aren’t open are hidden with display:none; anyway so they wont be focusable unless they are open.

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin If I understand right, the request here is for the Chart tab to have a tabindex of 0 when the page first loads. Do I have that right?

**Comment by LucyGwilliamAdmin** [comment]
DAC have just summarised the changes needed - for this one they said:
> Tabpanels should all always have a tabindex of 0. This should work fine as hidden tabpanels wont be focusable due to the display:none; specified in the CSS

**Comment by brockfanning** [comment]
@LucyGwilliamAdmin I think that conflicts with something that DAC recommended before. See here: https://github.com/open-sdg/open-sdg/issues/840#issuecomment-685690973

Is it worth double-checking to make sure that's what we should do? I believe we had it that way before, but then they made that objection linked above.

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning added you into email chain, but also adding the reply here:

>Apologies for that conflicting information. Just to make it clear – the tabs work perfectly, I am just talking about the tabpanels. The tabpanel should only be in focus sequence when it is active, and assigning a tabindex of 0 is how non-focusable components are placed in focus sequence, so this terminology can be used interchangeably. However, when content is hidden with display:none; even if it is focusable, content it will not be in focus sequence – it is hidden from all users. The tabindex is pointless when the content is hidden and it doesn’t matter really if it is there or not. But the easiest thing to do is give all the tab panels a tabindex=0 and let the display:none; do all the work. This means you never have to dynamically change the tabindex.
