### ISSUE TITLE
Loading map

### ISSUE THREAD

**Issue by WohnungNDS** [open-sdg/open-sdg#973]
**Please complete the following information**
Data repository URL: https://github.com/WohnungNDS/WK_Data

Data or metadata issue:
Loading map

**Describe the bug**
a wheel is turning while loading / watching the map.
My first thout was I have done something wrong with my repository but then I saw that also [here](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dac2020/) the map does not load correctly.

Tested in 

firefox:
![firefox](https://user-images.githubusercontent.com/67795376/97293840-805c1980-184d-11eb-8203-2f2ece47e6f2.PNG)

IE:
![IE](https://user-images.githubusercontent.com/67795376/97295746-04170580-1850-11eb-9e35-e5c0e87f9195.PNG)

chrome
![Chrome](https://user-images.githubusercontent.com/67795376/97295764-0aa57d00-1850-11eb-8c8a-0dac68c08efe.PNG)

**Comment by LucyGwilliamAdmin** [comment]
@brockfanning think this used to happen on UK site but isn't now since pointing at latest accessibility fix commit

**Comment by brockfanning** [comment]
This should be fixed in the latest version, so I'll go ahead and close. Please re-open if you have any questions.
