### ISSUE TITLE
Test fails after set the languages

### ISSUE THREAD

**Issue by arc17854** [open-sdg/open-sdg#984]
We've started the site in two languages as default configuration ('en' and 'es'). Now I'm trying set only Spanish, so I had changed the configuration files _config.yml and _config_data.yml with this:
```
languages:
  - es
```
As I'm executing the pull request's test, it fails in testing html:
```
Ran on 282 files!
- ./_test/ods-cantabria/about/cookies-and-privacy/index.html

  *  internally linking to /ods-cantabria/en/, which does not exist (line 0)

     <a class="navbar-brand" href="/ods-cantabria/en/" id="home">
      <img src="/ods-cantabria/assets/img/SDG_logo.png" alt=" - ">
    </a>
  *  internally linking to /ods-cantabria/en/about/cookies-and-privacy/, which does not exist (line 0)
     <a href="/ods-cantabria/en/about/cookies-and-privacy/">menu.cookies</a>
  *  internally linking to /ods-cantabria/en/goals, which does not exist (line 0)
     <a href="/ods-cantabria/en/goals">general.goals</a>
  *  internally linking to /ods-cantabria/en/reporting-status, which does not exist (line 0)
     <a href="/ods-cantabria/en/reporting-status">menu.reporting_status</a>
- ./_test/ods-cantabria/about/index.html
htmlproofer 3.17.2 | Error:  HTML-Proofer found 36 failures!
  *  internally linking to /ods-cantabria/en/, which does not exist (line 0)
     <a class="navbar-brand" href="/ods-cantabria/en/" id="home">
      <img src="/ods-cantabria/assets/img/SDG_logo.png" alt=" - ">
    </a>
...
```

**Comment by LucyGwilliamAdmin** [comment]
@arc17854 to fix this problem there are some extra steps required:

1. Go to the _pages folder and delete the `es` subfolder - this can be done by deleting all the files within the `es` folder
2. Then in each of the remaining files in the _pages folder, edit the file so the language is `es` and it contains the translated text you wish to display
3. Go to the _posts folder and delete the `es` subfolder
4. Go into the remaining post in the _posts folder and edit it so the language is `en`

Let me know if this works

**Comment by arc17854** [comment]
Thank you, I have just tried, but now it fails building the site:
```
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Unable to read data from: https://icane.github.io/ods-data-cantabria//en/meta/all.json
404 Not Found
```

**Comment by LucyGwilliamAdmin** [comment]
@arc17854 no problem if you go to https://github.com/icane/ods-data-cantabria/settings and scroll down to the GitHub Pages section is the source branch set to `gh-pages`? If not set that, and then try rebuilding ods-cantabria

**Comment by arc17854** [comment]
Sorry, I hadn't commited _config.yml
Now it runs perfectily.

Thank you!
