### ISSUE TITLE
Overriding layout

### ISSUE THREAD

**Issue by arc17854** [open-sdg/open-sdg#986]
Hello!

I'm trying to override _layouts/goal-by-target-vertical.html
But it doesn't pass the test, the error reported is:
```
      Remote Theme: Using theme open-sdg/open-sdg
  Liquid Exception: Could not locate the included file 'components/goal/breadcrumbs.html' in any of ["/home/runner/work/ods-cantabria/ods-cantabria/_includes", "/tmp/jekyll-remote-theme-20201127-15964-11brrk9/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/goal-by-target-vertical.html
jekyll 3.8.4 | Error:  Could not locate the included file 'components/goal/breadcrumbs.html' in any of ["/home/runner/work/ods-cantabria/ods-cantabria/_includes", "/tmp/jekyll-remote-theme-20201127-15964-11brrk9/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
Error: Process completed with exit code 1.
```
Is necessary copy that include to local?

**Comment by arc17854** [comment]
By the way, when I change the line from <h2>Targets and indicators</h2> to <h2>Metas e indicdores</h2> (in Spanish) The page doesn't display correctly.

How could I add that as a translation? 

Thank you in advance

**Comment by brockfanning** [comment]
@arc17854 We are just about to release version 1.2.0 of Open SDG, and it sounds like the code you started with for `goal-by-target-vertical.html` is more recent than the version of Open SDG you have specified in `remote_theme`. I would recommend that you point to "master" for now, like so:

```
remote_theme: open-sdg/open-sdg@master
```

I think this should allow it to build, and resolve your display issues. Then as soon as 1.2.0 is released (in the next few weeks), you can update it to:

```
remote_theme: open-sdg/open-sdg@1.2.0
```

You've also noticed a bug in Open SDG - that "Targets and indicators" is not getting translated in the goal-by-target-vertical layout. We'll make sure to get that resolved in the upcoming release.

**Comment by arc17854** [comment]
Thank you @brockfanning !
I was using  remote_theme: `open-sdg/open-sdg@1.1.0`

**Comment by brockfanning** [comment]
@arc17854 No problem, and thanks for pointing out the missing translation.

By the way, if you're able to help us out with that Spanish translation - it's now ready to be translated here: https://hosted.weblate.org/translate/sdg-translations/general/es/?checksum=569d15c49c9fcf95

**Comment by arc17854** [comment]
Hello!!
With the remote theme 1.1.0 it can't pass the test, so now I'm using remote theme 'master' but I have a problem with the background on the links, suddendly are yellow. As if were in high contrast.

**Comment by brockfanning** [comment]
@arc17854 In this upcoming release we're adding more obvious focus colors on links, which I think is the yellow color you're describing. This yellow should only be visible when the link has focus - ie, you've just clicked on it, or you're using TAB for keyboard navigation. Previously we were using dotted grey lines which were much harder to notice.

Let me know if you're seeing a place on the site where the yellow is causing a problem.

For your information, you can take control of the colors of this focus treatment using Sass variables. You would add your variable overrides to your version of [this file](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_sass/variables.scss). Here are [the default values for these focus colors](https://github.com/open-sdg/open-sdg/blob/master/_sass/variables/_colors.scss#L5-L10).

**Comment by arc17854** [comment]
Thank you very much @brockfanning !!

I'll take it in account.

I'll collaborate with the translation from my personal account.
