### ISSUE TITLE
Show data table instead of chart by default

### ISSUE THREAD

**Issue by arc17854** [open-sdg/open-sdg#994]
When we are in the indicator page, we want to show the data table tab instead of chart tab by default.

I changed the file data-tabs.html to indicate which is active, but it didn't work.

Now I'm trying a custom javascript to do this:
`$('[href="#tableview"]').tab('show');`

Is the correct way? 

Thank you in advance

**Comment by MoBosse** [comment]
Not entirely sure but I think you have to change `class="nav-item active"` to `class="nav-item"` in [this line](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/indicator/data-tabs.html#L5) and the other way round in this [line](https://github.com/open-sdg/open-sdg/blob/master/_includes/components/indicator/data-tabs.html#L8). I just tried this for [this page](https://sdgtestenvironment.github.io/sdg-indicators/) and it worked.

**Comment by MoBosse** [comment]
Sorry, just saw that table is selected but not shown. Plaese ignore my comment above.

**Comment by MoBosse** [comment]
Could you try changing `class="tab-pane active"` to `class="tab-pane"` in data-panes.html in line 2 and the other way round in line 5?

**Comment by arc17854** [comment]
Thank you very much @MoBosse !
It works perfectly
